# -*- coding: utf-8 -*-
"""Chapter-artifact source data, Book p10-14 (Boloor clubbing inserts; generalised lymphadenopathy; oedema; blood pressure)."""

# (page, fmt, sec, point, question, options, ans, explanation)
D = [
# ---------------------------------------------------------------- Book p10 (Boloor insert)
(10, "recall", "Neurological Causes of Clubbing (Boloor insert)",
 "Neurological causes of clubbing",
 "The inserted Boloor reference page on Book p10 lists which group of causes of clubbing?",
 ["Neurological causes - syringomyelia, median nerve injury and hemiplegia",
  "Cardiac causes - cyanotic heart disease, infective endocarditis and atrial myxoma",
  "Endocrine causes - thyroid acropachy and acromegaly",
  "Occupational causes - vinyl chloride and arsenic exposure"],
 0,
 "The Boloor insert supplies the neurological column of clubbing causes: syringomyelia, median nerve injury and hemiplegia. It complements the respiratory, cardiovascular and GI groups given in the main text. (Book p10)"),

(10, "oddoneout", "Neurological Causes of Clubbing (Boloor insert)",
 "Neurological clubbing list",
 "Which of the following is NOT listed among the neurological causes of clubbing in the inserted reference page?",
 ["Syringomyelia", "Median nerve injury", "Hemiplegia", "Myasthenia gravis"],
 3,
 "The three neurological causes given are syringomyelia, median nerve injury and hemiplegia. Myasthenia gravis is a disorder of the neuromuscular junction and is not a cause of clubbing. (Book p10)"),

# ---------------------------------------------------------------- Book p11 (Boloor figure)
(11, "recall", "Grade 4 Clubbing (Boloor figure)",
 "The grade demonstrated in Boloor Fig. 2C.18",
 "Boloor Fig. 2C.18, inserted on Book p11, demonstrates which grade of clubbing?",
 ["Grade 4", "Grade 1", "Grade 2", "Grade 3"],
 0,
 "The figure caption reads 'Demonstration of grade 4 clubbing'. Grade 4 is the grade at which hypertrophic osteoarthropathy is present, in contrast to grade 3's drumstick fingertip. (Book p11)"),

(11, "scenario", "Grade 4 Clubbing (Boloor figure)",
 "Interpretation of grade 4",
 "A patient whose hand is shown in the grade-4 clubbing figure of the insert is examined by you. Which additional finding would you specifically look for, since it defines this grade?",
 ["Periosteal reaction of the long bones with joint symptoms - hypertrophic osteoarthropathy",
  "A raised Lovibond angle alone",
  "Nail-bed fluctuation on pressure",
  "Subungual soft tissue proliferation with a parrot-beak fingertip"],
 0,
 "Grade 4 is defined by hypertrophic osteoarthropathy, so periosteal reaction and articular symptoms are the findings that upgrade the finger signs to grade 4. Nail-bed fluctuation is grade 1, a raised Lovibond angle grade 2, and the parrot-beak tip grade 3. (Book p11)"),

# ---------------------------------------------------------------- Book p12 (Boloor atypical clubbing table)
(12, "recall", "Atypical Presentations of Clubbing (Boloor table)",
 "Acute clubbing",
 "In the Boloor atypical clubbing table the causes of acute clubbing are:",
 ["Subacute bacterial endocarditis, lung abscess and empyema",
  "Bronchogenic carcinoma, mesothelioma and lymphoma",
  "Cirrhosis, inflammatory bowel disease and coeliac disease",
  "Leprosy, sclerodactyly and vinyl chloride exposure"],
 0,
 "Acute clubbing in the table belongs to subacute bacterial endocarditis, lung abscess and empyema - the same suppurative and endocardial group that produces clubbing over weeks rather than years. (Book p12)"),

(12, "match", "Atypical Presentations of Clubbing (Boloor table)",
 "Unilateral and unidigital clubbing in the table",
 "Match each atypical pattern to the causes given in the Boloor table \u2014 1) Unilateral clubbing 2) Unidigital clubbing 3) Reversible clubbing \u2026 A) Hemiplegia, aneurysm of the subclavian artery, Pancoast tumour B) Median nerve injury and trauma C) Lung abscess and empyema",
 ["1-A, 2-B, 3-C", "1-B, 2-A, 3-C", "1-C, 2-B, 3-A", "1-A, 2-C, 3-B"],
 0,
 "Unilateral clubbing is listed with hemiplegia, subclavian artery aneurysm and Pancoast tumour; unidigital clubbing with median nerve injury and trauma; reversible clubbing with lung abscess and empyema - clubbing that regresses once the pus is drained. (Book p12)"),

(12, "match", "Atypical Presentations of Clubbing (Boloor table)",
 "Painful and cyanotic clubbing in the table",
 "Match each pattern to its listed causes \u2014 1) Painful clubbing 2) Clubbing with cyanosis 3) Pseudoclubbing \u2026 A) Cyanotic congenital heart diseases and interstitial lung disease B) Bronchogenic carcinoma, subacute bacterial endocarditis and lung abscess C) Leprosy, leukaemic infiltration, hyperparathyroidism, thyroid acropachy, sclerodactyly, vinyl chloride exposure and subungual tumours",
 ["1-B, 2-A, 3-C", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-C, 3-A"],
 0,
 "Painful clubbing is listed with bronchogenic carcinoma, subacute bacterial endocarditis and lung abscess; clubbing with cyanosis with cyanotic congenital heart disease and interstitial lung disease; and pseudoclubbing with a long list including leprosy, leukaemic infiltration, hyperparathyroidism, thyroid acropachy, sclerodactyly, vinyl chloride exposure and subungual tumours or cysts. (Book p12)"),

(12, "scenario", "Atypical Presentations of Clubbing (Boloor table)",
 "Differential clubbing and its lesion",
 "A patient has clubbing of both lower limbs with normal upper limbs. The Boloor atypical clubbing table attributes differential clubbing (upper limb normal, lower limb clubbed) to:",
 ["Patent ductus arteriosus with reversal of shunt", "PDA with transposition of the great arteries and reversal of shunt", "Pancoast tumour of the lung", "Cyanotic congenital heart disease with ILD"],
 0,
 "Differential clubbing with a normal upper limb and clubbed lower limb is produced by a patent ductus arteriosus with reversal of shunt - the mirror image of the reverse pattern. Adding transposition of the great arteries reverses which limb is affected. (Book p12)"),

(12, "scenario", "Atypical Presentations of Clubbing (Boloor table)",
 "Reverse differential clubbing",
 "Clubbing confined to the upper limbs with normal lower limbs - reverse differential clubbing - is attributed in the table to:",
 ["PDA with transposition of the great arteries and reversal of shunt",
  "PDA with reversal of shunt alone",
  "Interstitial lung disease with cyanosis",
  "Subclavian artery aneurysm"],
 0,
 "Reverse differential clubbing (upper limb clubbed, lower limb normal) requires PDA plus transposition of the great arteries plus reversal of shunt. Compare with differential clubbing, which needs PDA with reversal alone. (Book p12)"),

(12, "oddoneout", "Atypical Presentations of Clubbing (Boloor table)",
 "Pseudoclubbing list in the table",
 "Which of the following is NOT listed under pseudoclubbing in the Boloor atypical clubbing table?",
 ["Leprosy", "Leukaemic infiltration", "Thyroid acropachy", "Bronchogenic carcinoma"],
 3,
 "The pseudoclubbing list is leprosy, leukaemic infiltration, hyperparathyroidism, thyroid acropachy, sclerodactyly, vinyl chloride exposure and subungual tumours or cysts. Bronchogenic carcinoma produces true - and painful - clubbing. (Book p12)"),

(12, "recall", "Atypical Presentations of Clubbing (Boloor table)",
 "Clubbing with cyanosis in the table",
 "In the Boloor table, clubbing with cyanosis is listed with:",
 ["Cyanotic congenital heart diseases and interstitial lung disease",
  "Chronic bronchitis and bronchiectasis",
  "Cirrhosis and inflammatory bowel disease",
  "Subacute bacterial endocarditis and empyema"],
 0,
 "Clubbing with cyanosis is paired with cyanotic congenital heart disease and interstitial lung disease. The pairing is useful because cyanosis plus clubbing without a shunt suggests ILD rather than heart disease. (Book p12)"),

(12, "scenario", "Atypical Presentations of Clubbing (Boloor table)",
 "Reversible clubbing",
 "A patient's clubbing regresses completely after drainage of a lung abscess. In the Boloor atypical clubbing table this pattern is called:",
 ["Reversible clubbing", "Acute clubbing", "Pseudoclubbing", "Differential clubbing"],
 0,
 "Reversible clubbing - listed with lung abscess and empyema - is the pattern that resolves when the underlying pus is evacuated. It is a reminder that clubbing is not always permanent. (Book p12)"),

# ---------------------------------------------------------------- Book p13
(13, "match", "Generalised Lymphadenopathy & Oedema",
 "Causes of generalised lymphadenopathy by group",
 "Match each group of causes of generalised lymphadenopathy to its examples \u2014 1) Infections 2) Malignancies 3) Autoimmune 4) Miscellaneous \u2026 A) HIV, infectious mononucleosis, tuberculosis B) Leukaemia, lymphoma, metastatic carcinoma C) SLE, Felty's syndrome, Still's disease D) Sarcoidosis",
 ["1-A, 2-B, 3-C, 4-D", "1-B, 2-A, 3-C, 4-D", "1-A, 2-C, 3-B, 4-D", "1-C, 2-B, 3-A, 4-D"],
 0,
 "Infections (HIV, infectious mononucleosis, tuberculosis), malignancies (leukaemia, lymphoma, metastatic carcinoma), autoimmune disease (SLE, Felty's syndrome, Still's disease) and miscellaneous (sarcoidosis) form the four groups. (Book p13)"),

(13, "match", "Generalised Lymphadenopathy & Oedema",
 "Pitting and non-pitting oedema",
 "Match each type of oedema to its causes \u2014 1) Non-pitting oedema 2) Pitting oedema \u2026 A) Myxoedema, lymphoedema in late-stage filariasis, scleroderma, angioneurotic oedema B) CCF, cirrhosis, nephrotic syndrome, hypoproteinaemia, pericardial effusion, constrictive pericarditis, amlodipine",
 ["1-A, 2-B", "1-B, 2-A", "1-A, 2-A", "1-B, 2-B"],
 0,
 "Non-pitting oedema is myxoedema, late-stage filarial lymphoedema, scleroderma and angioneurotic oedema. Pitting oedema is cardiac, hepatic, renal and hypoproteinaemic oedema plus drugs such as amlodipine. (Book p13)"),

(13, "scenario", "Generalised Lymphadenopathy & Oedema",
 "Amlodipine-induced oedema",
 "A hypertensive patient on amlodipine develops bilateral pitting pedal oedema with no cardiac, renal or hepatic abnormality. According to the book's list of pitting oedema causes:",
 ["Amlodipine is a listed drug cause of pitting oedema", "Drug-induced oedema is always non-pitting", "The oedema must be lymphatic because it is bilateral", "Amlodipine causes oedema only in nephrotic patients"],
 0,
 "Amlodipine appears explicitly in the pitting oedema list, along with CCF, cirrhosis, nephrotic syndrome, hypoproteinaemia, pericardial effusion and constrictive pericarditis. It is one of the commonest bedside causes of unexplained ankle swelling. (Book p13)"),

(13, "oddoneout", "Generalised Lymphadenopathy & Oedema",
 "Non-pitting oedema",
 "Which of the following causes non-pitting oedema?",
 ["Myxoedema", "Nephrotic syndrome", "Constrictive pericarditis", "Chronic liver disease with hypoproteinaemia"],
 0,
 "Myxoedema is non-pitting because mucopolysaccharide deposition, not free fluid, expands the tissue. Nephrotic syndrome, constrictive pericarditis and hypoproteinaemia all cause pitting oedema. (Book p13)"),

(13, "match", "Generalised Lymphadenopathy & Oedema",
 "Unilateral and bilateral leg swelling",
 "Match each distribution of leg swelling to its differential \u2014 1) Unilateral leg swelling 2) Bilateral leg swelling 3) Milroy's disease \u2026 A) DVT, soft tissue infection, trauma, lymphoedema, immobility such as hemiplegia B) Heart failure, chronic venous insufficiency, hypoproteinaemia, lymphatic obstruction, drugs C) Unexplained lymphoedema appearing at puberty, more common in females",
 ["1-A, 2-B, 3-C", "1-B, 2-A, 3-C", "1-A, 2-C, 3-B", "1-C, 2-B, 3-A"],
 0,
 "Unilateral swelling suggests local causes (DVT, infection, trauma, lymphoedema, immobility such as hemiplegia); bilateral swelling suggests systemic causes (heart failure, chronic venous insufficiency, hypoproteinaemia, lymphatic obstruction, drugs); Milroy's disease is unexplained lymphoedema appearing at puberty and is commoner in females. (Book p13)"),

(13, "scenario", "Generalised Lymphadenopathy & Oedema",
 "Milroy's disease",
 "A 14-year-old girl has painless, non-pitting swelling of both legs beginning at puberty, with no cardiac, renal or hepatic cause. The entity described in the book is:",
 ["Milroy's disease", "Filariasis with late-stage lymphoedema", "Angioneurotic oedema", "Lipodermatosclerosis from chronic venous insufficiency"],
 0,
 "Milroy's disease is unexplained lymphoedema that appears at puberty and is commoner in females - one of the bilateral leg swelling causes that has no systemic driver. (Book p13)"),

(13, "oddoneout", "Generalised Lymphadenopathy & Oedema",
 "Unilateral leg swelling list",
 "Which of the following is NOT listed as a cause of unilateral leg swelling?",
 ["Deep vein thrombosis", "Soft tissue infection", "Immobility such as hemiplegia", "Chronic venous insufficiency"],
 3,
 "Chronic venous insufficiency is a cause of bilateral leg swelling. The unilateral list is DVT, soft tissue infection, trauma, lymphoedema and immobility such as hemiplegia. (Book p13)"),

(13, "scenario", "Generalised Lymphadenopathy & Oedema",
 "Autoimmune causes of generalised lymphadenopathy",
 "A patient with rheumatoid arthritis develops generalised lymphadenopathy and splenomegaly with neutropenia. The eponymous syndrome named in the autoimmune group of generalised lymphadenopathy causes is:",
 ["Felty's syndrome", "Still's disease", "Sjogren's syndrome", "Caplan's syndrome"],
 0,
 "Felty's syndrome - rheumatoid arthritis with splenomegaly and neutropenia - is listed together with SLE and Still's disease among autoimmune causes of generalised lymphadenopathy. (Book p13)"),

(13, "recall", "Generalised Lymphadenopathy & Oedema",
 "Miscellaneous cause of generalised lymphadenopathy",
 "Which disease is listed as the 'miscellaneous' cause of generalised lymphadenopathy?",
 ["Sarcoidosis", "Amyloidosis", "Hypothyroidism", "Sickle cell disease"],
 0,
 "Sarcoidosis is the miscellaneous cause, standing alone after the infection, malignancy and autoimmune groups. Its bilateral hilar lymphadenopathy plus peripheral nodes is the classic clinical picture. (Book p13)"),

(13, "scenario", "Generalised Lymphadenopathy & Oedema",
 "Which oedema is non-pitting?",
 "An elderly man has firm, non-pitting swelling of both lower legs, dry skin, hoarse voice and a raised TSH. His oedema is best described as:",
 ["Non-pitting oedema of myxoedema", "Pitting oedema of hypoproteinaemia", "Lymphoedema of late-stage filariasis", "Angioneurotic oedema"],
 0,
 "Myxoedema causes non-pitting oedema through mucopolysaccharide deposition. The clue is the accompanying hypothyroid features and the failure to pit on pressure. (Book p13)"),

# ---------------------------------------------------------------- Book p14: BP definition and cuff
(14, "recall", "Blood Pressure Measurement",
 "Definition of blood pressure",
 "Blood pressure is defined in the book as:",
 ["The lateral force exerted by the blood column per unit area of vascular wall",
  "The product of cardiac output and systemic vascular resistance",
  "The force of ventricular contraction transmitted to the arterial wall during systole",
  "The pressure gradient between the aorta and the right atrium"],
 0,
 "The definition given is the lateral force exerted by the blood column per unit area of vascular wall - a physical rather than physiological definition, which is why measurement technique matters so much. (Book p14)"),

(14, "numeric", "Blood Pressure Measurement",
 "Dimensions of the BP cuff",
 "Regarding the standard BP cuff, the book states that the length is approximately ____ the width, the average length is ____, and the air bag should extend for at least ____ of the arm circumference.",
 ["Twice; 25 cm; two-thirds", "Three times; 30 cm; one-half", "Twice; 20 cm; three-quarters", "Three times; 25 cm; two-thirds"],
 0,
 "Cuff length is about twice its width, average length is 25 cm, and the bladder within the cuff should cover at least two-thirds of the arm circumference. A short or narrow cuff over-reads the pressure. (Book p14)"),

(14, "match", "Blood Pressure Measurement",
 "Phases of Korotkoff sounds",
 "Match each Korotkoff phase to its description \u2014 1) Phase 1 2) Phase 2 3) Phase 3 4) Phase 4 5) Phase 5 \u2026 A) Complete disappearance of sounds B) First appearance of low-frequency tapping sounds C) Softer and longer sounds D) Crisper and louder sounds E) Initial muffling of sounds, often absent",
 ["1-B, 2-C, 3-D, 4-E, 5-A", "1-B, 2-D, 3-C, 4-E, 5-A", "1-C, 2-B, 3-D, 4-E, 5-A", "1-B, 2-C, 3-E, 4-D, 5-A"],
 0,
 "Phase 1 is the first appearance of low-frequency tapping sounds (systolic), phase 2 softer and longer, phase 3 crisper and louder, phase 4 initial muffling (often absent), phase 5 complete disappearance (diastolic). (Book p14)"),

(14, "recall", "Blood Pressure Measurement",
 "Which Korotkoff phase is taken as DBP",
 "Normally, which Korotkoff phase is taken as the diastolic blood pressure, and when is the exception made?",
 ["Phase 5; in severe aortic regurgitation complete disappearance may not occur, so phase 4 is taken",
  "Phase 4; in severe aortic stenosis complete disappearance may not occur, so phase 5 is taken",
  "Phase 3; in atrial fibrillation the sounds never disappear, so phase 4 is taken",
  "Phase 5; in cardiac tamponade complete disappearance may not occur, so phase 4 is taken"],
 0,
 "Phase 5 (disappearance) is normally the diastolic pressure. In severe aortic regurgitation the sounds may never disappear completely, so phase 4 (muffling) is used instead - a classic examiner's trap. (Book p14)"),

(14, "scenario", "Blood Pressure Measurement",
 "Choosing the diastolic end point",
 "A patient with a wide pulse pressure and a blowing early diastolic murmur has Korotkoff sounds audible all the way down to 0 mmHg. The correct diastolic end point is:",
 ["Phase 4, because complete disappearance of sounds does not occur in severe aortic regurgitation",
  "Phase 5, because disappearance must always define the diastolic pressure",
  "Phase 1, because the true diastolic pressure equals the first sound in AR",
  "The midpoint between phase 4 and phase 5"],
 0,
 "When the sounds never disappear - the classic setting being severe aortic regurgitation - phase 4 (initial muffling) is taken as the DBP. (Book p14)"),

(14, "numeric", "Blood Pressure Measurement",
 "Normal variation between upper limbs",
 "Normal variation in blood pressure between the two upper limbs is:",
 ["10-15 mmHg", "5-8 mmHg", "15-25 mmHg", "Up to 30 mmHg"],
 0,
 "The book allows 10-15 mmHg between upper limbs; a difference above this must be explained, and if it is new it raises the possibility of aortic dissection or subclavian steal. (Book p14)"),

# ---------------------------------------------------------------- Book p14: auscultatory gap
(14, "recall", "Auscultatory Gap & Inter-limb BP Variation",
 "Definition and effect of the auscultatory gap",
 "The auscultatory gap is:",
 ["Temporary disappearance of Korotkoff sounds after the systolic reading with reappearance just above the diastolic value, which underestimates the systolic BP",
  "Permanent loss of Korotkoff sounds below systolic pressure, which overestimates the systolic BP",
  "A gap between the first and second Korotkoff sounds, which overestimates the diastolic pressure",
  "Absence of all Korotkoff sounds in the presence of a palpable pulse"],
 0,
 "In the auscultatory gap the sounds vanish after the systolic reading and return just above the diastolic value; it is seen in elderly hypertensives and causes the systolic pressure to be underestimated. (Book p14)"),

(14, "management", "Auscultatory Gap & Inter-limb BP Variation",
 "Avoiding the error of the auscultatory gap",
 "How is the error caused by an auscultatory gap avoided at the bedside?",
 ["By simultaneously palpating the radial pulse, which persists throughout the gap",
  "By inflating the cuff 20 mmHg above the estimated systolic pressure",
  "By using a larger cuff and recording both phases 4 and 5",
  "By taking the measurement in the standing position only"],
 0,
 "Palpating the radial pulse while auscultating solves it: the pulse continues through the gap, so the true systolic level is not lost - this is exactly why the palpatory method precedes auscultation in clinical practice. (Book p14)"),

(14, "oddoneout", "Auscultatory Gap & Inter-limb BP Variation",
 "Causes of increased inter-arm BP difference",
 "Which of the following is NOT one of the causes of increased BP variation between the upper limbs given in the book?",
 ["Aortic dissection, with occlusion of the subclavian artery by the haematoma", "Subclavian steal syndrome", "Elderly age with an auscultatory gap", "Coarctation of the aorta with unequal upper-limb pressures"],
 2,
 "The book lists aortic dissection (occlusion of the subclavian artery by the haematoma) and subclavian steal syndrome as causes of an increased inter-arm difference. An auscultatory gap affects the systolic reading of a single limb and is not the mechanism for inter-arm difference. (Book p14)"),

(14, "scenario", "Auscultatory Gap & Inter-limb BP Variation",
 "Subclavian steal syndrome",
 "A patient has a 25 mmHg difference in blood pressure between the arms; angiography shows reversed flow in the left vertebral artery feeding the left arm. The book's description of this situation is:",
 ["Subclavian steal syndrome - blood is stolen from the vertebral artery circulation to feed a hypoperfused arm",
  "Aortic dissection - the subclavian artery is occluded by haematoma",
  "Auscultatory gap - underestimation of systolic pressure",
  "Pulsus paradoxus - inspiratory fall in systolic pressure"],
 0,
 "Subclavian steal syndrome is exactly blood stolen from the vertebral circulation to feed a hypoperfused arm. Aortic dissection, by contrast, causes inter-arm difference from occlusion of the subclavian artery by the dissection haematoma. (Book p14)"),

# ---------------------------------------------------------------- Book p14: pulse pressure
(14, "numeric", "Pulse Pressure & Haemodynamics",
 "Normal pulse pressure",
 "Pulse pressure is the difference between systolic and diastolic pressure; the book gives a normal range of:",
 ["30-60 mmHg", "20-40 mmHg", "40-80 mmHg", "60-100 mmHg"],
 0,
 "Normal pulse pressure is 30-60 mmHg. Wider pressure means a large stroke volume or a leaky/rapid run-off circuit; narrower pressure means obstruction to outflow or to filling. (Book p14)"),

(14, "match", "Pulse Pressure & Haemodynamics",
 "Raised and narrow pulse pressure causes",
 "Match each pulse pressure abnormality to its listed causes \u2014 1) Raised pulse pressure 2) Narrow pulse pressure \u2026 A) Exercise, AR, PDA, fever, anaemia, AV fistulas, beriberi, Paget's disease, cirrhosis, pregnancy B) Aortic stenosis, constrictive pericarditis, cardiac tamponade",
 ["1-A, 2-B", "1-B, 2-A", "1-A, 2-A", "1-B, 2-B"],
 0,
 "Raised pulse pressure is seen with exercise, aortic regurgitation, PDA, fever, anaemia, AV fistulas, beriberi, Paget's disease, cirrhosis and pregnancy. Narrow pulse pressure is obstructive - aortic stenosis (outflow obstruction) and constrictive pericarditis or tamponade (filling obstruction), with MS and DSS queried in the book. (Book p14)"),

(14, "scenario", "Pulse Pressure & Haemodynamics",
 "Paget's disease and pulse pressure",
 "A patient with Paget's disease has a wide pulse pressure and bounding pulses. The mechanism given in the book is:",
 ["Arteriovenous fistulae within the bone", "Increased sympathetic drive with a large stroke volume", "Left ventricular hypertrophy from outflow obstruction", "Reduced arterial compliance with age alone"],
 0,
 "The book explains Paget's wide pulse pressure by fistulae in the bone - the same logic it applies to pregnancy (the whole placenta behaving as a big AV fistula) and to cirrhosis (intrahepatic and extrahepatic AV fistulae). (Book p14)"),

(14, "scenario", "Pulse Pressure & Haemodynamics",
 "Narrow pulse pressure in a young patient",
 "A young patient has exertional syncope, an ejection systolic murmur and a narrow pulse pressure with a slow-rising low-volume carotid pulse. Among the narrow pulse pressure causes this is:",
 ["Aortic stenosis - obstruction to ventricular outflow", "Constrictive pericarditis - obstruction to ventricular filling", "Cardiac tamponade - obstruction to ventricular filling", "Beriheri - high output state"],
 0,
 "The book separates the narrow pulse pressure causes into outflow obstruction (aortic stenosis) and filling obstruction (constrictive pericarditis, cardiac tamponade). An ejection murmur with a slowly rising pulse is outflow obstruction. (Book p14)"),

(14, "recall", "Pulse Pressure & Haemodynamics",
 "Adjuncts queried in narrow pulse pressure",
 "Besides aortic stenosis, constrictive pericarditis and cardiac tamponade, which two conditions does the book query as causes of a narrow pulse pressure?",
 ["Mitral stenosis and dextro-stenosis of the pulmonary artery?", "Mitral regurgitation and aortic regurgitation", "PDA and VSD", "Hypertrophic cardiomyopathy and coarctation"],
 0,
 "The book writes '? MS, ? DSS' - mitral stenosis and DSS are queried rather than asserted, and that query mark is part of the answer: they are possibilities, not established causes. (Book p14)"),

# ---------------------------------------------------------------- Book p15: AHA/ASA Blood Pressure Categories table
(15, "match", "AHA/ASA Blood Pressure Categories (Insert Table)",
 "Five AHA/ASA blood pressure categories and their systolic/diastolic cutoffs on Book p15",
 "Match each Blood Pressure Category in the AHA/ASA table on Book p15 to its exact systolic and diastolic mmHg definition and Boolean connector — 1) Normal vs Elevated 2) High Blood Pressure [Hypertension] Stage 1 3) High Blood Pressure [Hypertension] Stage 2 4) Hypertensive Crisis [consult your doctor immediately] … A) Systolic 130–139 OR Diastolic 80–89 mmHg B) Systolic >=140 OR Diastolic >=90 mmHg C) Systolic >180 and/or Diastolic >120 mmHg D) Normal = <120 AND <80 mmHg; Elevated = 120–129 AND <80 mmHg",
 ["1-D, 2-A, 3-B, 4-C", "1-A, 2-D, 3-B, 4-C", "1-D, 2-B, 3-A, 4-C", "1-D, 2-A, 3-C, 4-B"],
 0,
 "The AHA/ASA Blood Pressure Categories table on Book p15 defines: Normal (<120 AND <80 mmHg); Elevated (120–129 AND <80 mmHg); Hypertension Stage 1 (130–139 OR 80–89 mmHg); Hypertension Stage 2 (>=140 OR >=90 mmHg); and Hypertensive Crisis (>180 and/or >120 mmHg). (Book p15)"),

(15, "scenario", "AHA/ASA Blood Pressure Categories (Insert Table)",
 "Classifying Elevated BP vs Stage 1 Hypertension using the AND vs OR connectors on Book p15",
 "A patient's blood pressure is 126/84 mmHg on repeated clinic measurements. Using the AHA/ASA Blood Pressure Categories table on Book p15, which category applies and why?",
 ["High Blood Pressure (Hypertension) Stage 1, because Elevated BP requires BOTH systolic 120–129 AND diastolic <80 mmHg, whereas Stage 1 Hypertension requires systolic 130–139 OR diastolic 80–89 mmHg",
  "Elevated Blood Pressure, because the systolic reading lies between 120 and 129 mmHg regardless of the diastolic value",
  "High Blood Pressure (Hypertension) Stage 2, because any diastolic reading above 80 mmHg is classified as Stage 2",
  "Normal Blood Pressure, because both values are below 140/90 mmHg"],
 0,
 "In the AHA/ASA table on Book p15, Elevated BP uses 'and' (120–129 AND <80 mmHg), whereas Stage 1 Hypertension uses 'or' (130–139 OR 80–89 mmHg); a diastolic reading of 84 mmHg therefore places the patient in Stage 1 Hypertension. (Book p15)"),
]
