# -*- coding: utf-8 -*-
"""Chapter-artifact source data, Book p3-4 (General examination; Temperature; PUO)."""

# (page, fmt, sec, point, question, options, ans, explanation)
A = [
# ---------------------------------------------------------------- Book p3
(3, "recall", "General Examination: Overview & Vitals",
 "Opening sequence of general examination",
 "The book opens general examination with 'conscious, oriented, cooperative', then build and nutrition status, then vitals. Which of the following is NOT part of the vitals as listed there?",
 ["Pulse - rate, rhythm, volume, character, delay, vessel wall thickening and peripheral pulses",
  "Respiratory rate",
  "Blood pressure",
  "Levels of cervical lymph nodes Ia to VII"],
 3,
 "Vitals in the book's opening section are pulse, respiratory rate, blood pressure and temperature. Lymphadenopathy is a separate general-examination step, and the Ia-VII levels are described much later, under lymphadenopathy. (Book p3)"),

(3, "fillup", "General Examination: Overview & Vitals",
 "Temperature must always be measured with a thermometer",
 "Temperature must always be measured with a ____; the book warns you must not write 'afebrile' without one.",
 ["Thermometer", "Palpation of forehead and trunk", "Patient's own report of feeling hot", "Axillary tactile comparison with the examiner's hand"],
 0,
 "The instruction is categorical: always measure the temperature with a thermometer and never record 'afebrile' on the basis of feel alone - tactile assessment is unreliable. (Book p3)"),

(3, "oddoneout", "General Examination: Overview & Vitals",
 "Steps of general examination",
 "Which of the following is NOT one of the general-examination headings listed in the book's opening sequence?",
 ["Pallor", "Icterus", "Cyanosis", "Fundus examination"],
 3,
 "The listed sequence runs: conscious/oriented/cooperative, build and nutrition, vitals, pallor, icterus, cyanosis, clubbing, lymphadenopathy, oedema. Fundus examination is part of systemic examination, not this general survey. (Book p3)"),

(3, "match", "General Examination: Overview & Vitals",
 "Reporting lymphadenopathy: site, number, consistency, tenderness, shape, matted",
 "Match each feature of lymphadenopathy to the description the book wants reported \u2014 1) Site and number 2) Consistency 3) Tenderness 4) Shape and matting \u2026 A) Which node groups are enlarged and how many B) Soft, firm, hard or stony hard C) Painful or painless D) Whether nodes move together as a matted unit",
 ["1-A, 2-B, 3-C, 4-D", "1-B, 2-A, 3-D, 4-C", "1-A, 2-D, 3-C, 4-B", "1-C, 2-B, 3-A, 4-D"],
 0,
 "For every lymph node enlargement the book asks you to report site, number of nodes, consistency, tenderness, shape, and whether the nodes are matted; the matted quality is deliberately separated from simple shape because it carries malignancy and tuberculosis meaning. (Book p3)"),

# ---------------------------------------------------------------- Temperature (p3)
(3, "numeric", "Temperature & its Measurement",
 "Harrison's/19e definition of fever",
 "According to the Harrison's 19e definition quoted in the book, fever is defined by which pair of readings?",
 ["An AM temperature of >98.9\u00b0F (>37.2\u00b0C) or a PM temperature of >99.9\u00b0F (>37.7\u00b0C)",
  "An AM temperature of >99.9\u00b0F (>37.7\u00b0C) or a PM temperature of >98.9\u00b0F (>37.2\u00b0C)",
  "An AM temperature of >37.8\u00b0C or a PM temperature of >38.3\u00b0C",
  "Any temperature above 37.0\u00b0C at any time of the day"],
 0,
 "Fever is an AM temperature above 98.9\u00b0F (37.2\u00b0C) or a PM temperature above 99.9\u00b0F (37.7\u00b0C). The afternoon threshold is set higher precisely because normal temperature is higher later in the day. (Book p3)"),

(3, "numeric", "Temperature & its Measurement",
 "Normal body temperature range",
 "The normal body temperature range given in the book is:",
 ["36.0-37.0\u00b0C (96.8-98.6\u00b0F)", "36.5-37.5\u00b0C (97.7-99.5\u00b0F)", "37.0-38.0\u00b0C (98.6-100.4\u00b0F)", "35.5-36.5\u00b0C (95.9-97.7\u00b0F)"],
 1,
 "Normal body temperature is 36.5-37.5\u00b0C, that is 97.7-99.5\u00b0F. Any definition of fever has to be read against this range and against the normal daily variation. (Book p3)"),

(3, "recall", "Temperature & its Measurement",
 "Why temperature is higher in the evening",
 "Why is the body temperature higher in the evening?",
 ["Because the hypothalamic set point is normally reset upward at night",
  "Because of increased basal metabolic rate and skeletal muscle activity",
  "Because evaporative heat loss falls when the ambient temperature falls at night",
  "Because antipyretic tone from the circadian cortisol peak is lost in the evening"],
 1,
 "The book attributes the evening rise to increased basal metabolic rate and skeletal muscle activity; no set-point reset is involved, which is why the fever definition uses separate AM and PM thresholds. (Book p3)"),

(3, "match", "Temperature & its Measurement",
 "Alternative sites for temperature measurement",
 "Match each temperature-measurement site to the book's comment \u2014 1) Rectum 2) Lower oesophagus 3) Tympanic membrane 4) Oral cavity \u2026 A) Reading lower than rectal, attributed to mouth breathing B) Generally higher than oral readings C) Temperature closely reflects core temperature D) The third alternative site listed, with no further qualification",
 ["1-B, 2-C, 3-D, 4-A", "1-A, 2-C, 3-D, 4-B", "1-B, 2-D, 3-C, 4-A", "1-C, 2-B, 3-A, 4-D"],
 0,
 "Rectal temperatures are generally higher than oral readings; lower oesophageal temperatures closely reflect core temperature; the tympanic membrane is simply listed as another site; and the low oral reading is attributed to mouth breathing. (Book p3)"),

(3, "scenario", "Temperature & its Measurement",
 "Mouth breathing lowers oral reading",
 "A patient with severe pneumonia is breathing rapidly through the mouth. His oral temperature reads 37.6\u00b0C while the rectal temperature is 38.6\u00b0C. According to the book the discrepancy is best explained by:",
 ["Mouth breathing lowering the oral reading, an important factor in patients with respiratory infections and rapid breathing",
  "Rectal thermometry reading spuriously high in sepsis",
  "A normal circadian difference between core and oral sites",
  "Delayed equilibration of the rectal thermometer in tachypnoea"],
 0,
 "The lower oral readings are generally attributed to mouth breathing, which matters most in exactly this group - patients with respiratory infection and rapid breathing. This is why core sites (rectum, lower oesophagus) are preferred when accuracy matters. (Book p3)"),

# ---------------------------------------------------------------- Fever vs hyperthermia (p3)
(3, "recall", "Fever vs Hyperthermia",
 "Fever vs hyperthermia: the set-point distinction",
 "What single feature separates fever from hyperthermia in the book's definition?",
 ["Fever is an elevation of body temperature that exceeds the normal daily variation and occurs with a rise in the hypothalamic set point",
  "Fever is any temperature above 37.5\u00b0C while hyperthermia is any temperature above 41.5\u00b0C",
  "Fever is caused only by infection while hyperthermia is caused only by drugs",
  "Fever responds to cooling blankets while hyperthermia responds to antipyretics"],
 0,
 "Fever is a rise in temperature produced by a rise in the hypothalamic set point. Hyperthermia is an uncontrolled rise in body temperature that exceeds the body's ability to lose heat in the setting of an intact set point - hence antipyretics do not work. (Book p3)"),

(3, "scenario", "Fever vs Hyperthermia",
 "Antipyretics do not reduce hyperthermia",
 "A patient with heat stroke has a core temperature of 41.2\u00b0C. Antipyretics produce no fall in temperature. The best explanation is:",
 ["The hypothalamic set point is intact, so there is no new set point to lower - this is hyperthermia, not fever",
  "The dose of antipyretic was inadequate for a temperature above 41\u00b0C",
  "Antipyretics act only on peripheral heat loss and fail in humid environments",
  "Heat stroke always causes hypothalamic damage and therefore a permanently reset set point"],
 0,
 "In hyperthermia the set point is intact; the problem is heat production exceeding heat loss, so antipyretics have no target. Cooling, not antipyresis, is the treatment. (Book p3)"),

(3, "match", "Fever vs Hyperthermia",
 "Drugs and settings of the four hyperthermia causes",
 "Match each drug or setting to the hyperthermia syndrome the book attaches it to \u2014 1) Halothane 2) Haloperidol and fluphenazine 3) Interactions of two or more serotonergic drugs 4) Environmental heat load \u2026 A) Neuroleptic malignant syndrome B) Malignant hyperthermia C) Serotonin syndrome D) Heat stroke",
 ["1-B, 2-A, 3-C, 4-D", "1-A, 2-B, 3-C, 4-D", "1-B, 2-C, 3-A, 4-D", "1-D, 2-A, 3-C, 4-B"],
 0,
 "Anaesthetics such as halothane produce malignant hyperthermia by rapid uncoupling of oxidative phosphorylation in sensitive individuals; haloperidol and fluphenazine cause neuroleptic malignant syndrome; serotonin syndrome follows increased CNS serotonergic activity, typically with two or more serotonergic drugs; heat stroke is the environmental cause. (Book p3)"),

(3, "oddoneout", "Fever vs Hyperthermia",
 "Causes of hyperthermia",
 "Which of the following is NOT listed under causes of hyperthermia?",
 ["Neuroleptic malignant syndrome", "Serotonin syndrome", "Malignant hyperthermia", "Hypothyroidism"],
 3,
 "The hyperthermia causes listed are heat stroke, malignant hyperthermia, neuroleptic malignant syndrome and serotonin syndrome. Hypothyroidism belongs to the opposite end of the spectrum - it is one of the endocrine causes of hypothermia. (Book p3)"),

(3, "truefalse", "Fever vs Hyperthermia",
 "Statements on fever and hyperthermia",
 "Which statement about fever and hyperthermia is correct?",
 ["True: Fever is an elevation of body temperature that exceeds the normal daily variation and occurs in conjunction with a rise in the hypothalamic set point",
  "True: Antipyretics will not reduce the temperature in hyperthermia because the set point is intact",
  "False: In hyperthermia the hypothalamic set point is raised, so antipyretics work well",
  "False: Fever and hyperthermia are interchangeable terms for any temperature above 38\u00b0C"],
 0,
 "Fever = raised set point, so antipyretics work. Hyperthermia = intact set point, loss of heat exceeds the body's dissipating capacity, so antipyretics fail. The two are mechanistically different and are never interchangeable. (Book p3)"),

# ---------------------------------------------------------------- p4
(4, "numeric", "Hyperpyrexia, Hypothalamic Fever & Fever Mechanism",
 "Definition of hyperpyrexia",
 "Fever above which temperature is called hyperpyrexia, and which two causes are named?",
 ["Above 41.5\u00b0C (>106.7\u00b0F); CNS haemorrhage and severe infection",
  "Above 40.0\u00b0C (104\u00b0F); heat stroke and malignant hyperthermia",
  "Above 41.5\u00b0C (>106.7\u00b0F); heat stroke and neuroleptic malignant syndrome",
  "Above 39.5\u00b0C (103\u00b0F); severe infection and drug fever"],
 0,
 "Hyperpyrexia is fever above 41.5\u00b0C (>106.7\u00b0F) and the two causes the book names are CNS haemorrhage and severe infection. Note that heat stroke and NMS are causes of hyperthermia, a different category. (Book p4)"),

(4, "truefalse", "Hyperpyrexia, Hypothalamic Fever & Fever Mechanism",
 "Hypothalamic fever",
 "Which statement about hypothalamic fever is correct?",
 ["True: It is an elevated temperature caused by hypothalamic dysfunction",
  "True: Hypothalamic dysfunction usually causes subnormal, not supranormal, temperature",
  "False: Hypothalamic lesions characteristically produce sustained high fever above 41\u00b0C",
  "False: Hypothalamic fever is simply another name for hyperpyrexia"],
 0,
 "Hypothalamic dysfunction as a cause of raised temperature is a real but uncommon event - the book stresses the paradox that hypothalamic disease usually causes subnormal rather than supranormal temperature. Hyperpyrexia is a different, higher-threshold concept. (Book p4)"),

(4, "match", "Hyperpyrexia, Hypothalamic Fever & Fever Mechanism",
 "Mechanism of fever",
 "Match each step in the mechanism of fever \u2014 1) Pyrogenic cytokines 2) Cells they act on 3) Mediator produced 4) Final effect \u2026 A) IL-1, IL-6 and TNF\u03b1 B) Hypothalamic endothelial cells C) PGE2 D) Rise in the hypothalamic set point",
 ["1-A, 2-B, 3-C, 4-D", "1-B, 2-A, 3-D, 4-C", "1-A, 2-C, 3-B, 4-D", "1-C, 2-B, 3-A, 4-D"],
 0,
 "Infection or immune reactions release pyrogenic cytokines IL-1, IL-6 and TNF\u03b1; these induce hypothalamic endothelial cells to produce PGE2, which raises the hypothalamic set point and produces fever. This is the chain that antipyretics (COX inhibitors) interrupt. (Book p4)"),

(4, "fillup", "Hyperpyrexia, Hypothalamic Fever & Fever Mechanism",
 "Pyrogenic cytokines",
 "The pyrogenic cytokines released by infection or immune reactions, which induce hypothalamic endothelial cells to make PGE2, are IL-1, IL-6 and ____.",
 ["TNF\u03b1", "IL-4", "IL-10", "IFN-\u03b3"],
 0,
 "The trio is IL-1, IL-6 and TNF\u03b1. IL-4, IL-10 and IFN-\u03b3 are not listed as pyrogenic cytokines in this cascade. (Book p4)"),

(4, "oddoneout", "Hyperpyrexia, Hypothalamic Fever & Fever Mechanism",
 "Pyrogenic cytokine list",
 "Which of the following is NOT part of the book's pyrogenic cytokine cascade that raises the set point?",
 ["IL-1", "IL-6", "TNF\u03b1", "IL-4"],
 3,
 "The cascade is IL-1, IL-6 and TNF\u03b1 acting on hypothalamic endothelial cells to produce PGE2. IL-4 is a Th2 cytokine with no role in this chain. (Book p4)"),

# ---------------------------------------------------------------- AUFI & PUO (p4)
(4, "recall", "AUFI & PUO",
 "Definition of AUFI",
 "Acute undifferentiated febrile illness (AUFI) is defined in the book as:",
 ["Fever of <14 days without an organ-system-specific aetiology",
  "Fever of >3 weeks that remains undiagnosed after one week of inpatient evaluation",
  "Fever with a rash and no localising signs lasting more than 5 days",
  "Fever of <7 days with a proven bacterial isolate from blood culture"],
 0,
 "AUFI is a clinical term for fever of less than 14 days without an organ-system-specific aetiology. The 3-week definition belongs to PUO, and the two must not be mixed up. (Book p4)"),

(4, "match", "AUFI & PUO",
 "Order in which AUFI causes should be said",
 "Match each cause of AUFI to the position in which the book asks you to say it \u2014 1) First 2) Second 3) Third 4) Fourth 5) Fifth \u2026 A) Enteric fever B) Dengue C) Leptospirosis D) Scrub typhus E) Malaria",
 ["1-B, 2-D, 3-C, 4-E, 5-A", "1-B, 2-C, 3-D, 4-E, 5-A", "1-D, 2-B, 3-C, 4-A, 5-E", "1-B, 2-D, 3-E, 4-C, 5-A"],
 0,
 "The order to say in our setting is Dengue, Scrub typhus, Leptospirosis, Malaria, Enteric fever. The order itself is examinable because it encodes local epidemiology. (Book p4)"),

(4, "scenario", "AUFI & PUO",
 "Kala-azar and 'our setting'",
 "In a viva on AUFI the examiner asks for the important causes 'in our setting'. Which statement reflects the book's instruction?",
 ["Never say Leishmaniasis/Kala-azar unless probed - it is an important cause of AUFI but not in our setting",
  "Kala-azar should be named first because it is the commonest cause of AUFI",
  "Kala-azar should never be mentioned at all in any answer on fever",
  "Kala-azar is a cause of PUO only and never of AUFI"],
 0,
 "The book is explicit: say the local order (Dengue, Scrub typhus, Leptospirosis, Malaria, Enteric fever) and do not volunteer Kala-azar unless the examiner probes; it is an important cause of AUFI but not in our setting. (Book p4)"),

(4, "numeric", "AUFI & PUO",
 "Petersdorf and Beeson definition of PUO",
 "The Petersdorf and Beeson definition of PUO requires fever above 101 on at least two occasions, illness duration of more than ____, and uncertain diagnosis despite ____ of inpatient evaluation.",
 ["3 weeks; 1 week", "1 week; 3 days", "3 weeks; 3 days", "2 weeks; 1 week"],
 0,
 "Petersdorf and Beeson: illness of more than 3 weeks duration, fever above 101 on at least two occasions, and diagnosis still uncertain despite 1 week of inpatient evaluation. (Book p4)"),

(4, "truefalse", "AUFI & PUO",
 "Harrison's criteria for PUO",
 "Which statement about the criteria for PUO is correct?",
 ["True: Fever above 101 on at least two occasions and illness duration of more than 3 weeks",
  "True: No known immunocompromised state, and diagnosis uncertain after thorough history, examination and obligatory investigations",
  "False: A known immunocompromised state is part of the classical definition of PUO",
  "False: The obligatory investigation list for PUO includes bone marrow examination in every patient"],
 0,
 "Harrison's adds to the classical definition the absence of a known immunocompromised state and the requirement that diagnosis remains uncertain after thorough history, physical examination and a defined set of obligatory investigations - bone marrow is not among them. (Book p4)"),

(4, "oddoneout", "AUFI & PUO",
 "Obligatory investigations in PUO",
 "Which investigation is NOT part of the obligatory investigation list for PUO given in the book?",
 ["ESR and CRP", "Haemogram with peripheral smear", "USG abdomen and tuberculin skin test", "Bone marrow aspiration and trephine biopsy"],
 3,
 "The obligatory list is ESR, CRP, haemogram with PS, electrolytes, LFT, RFT, ANA, rheumatoid factor, urine analysis and culture, blood culture, CXR, USG abdomen and tuberculin skin test. Bone marrow is a second-line, cause-directed test. (Book p4)"),

(4, "fillup", "AUFI & PUO",
 "Types of PUO",
 "Besides the classical form, the book lists nosocomial PUO, neutropenic PUO and ____-associated PUO.",
 ["HIV", "TB", "Dialysis", "Transplant"],
 0,
 "The three variants named are nosocomial PUO, neutropenic PUO and HIV-associated PUO. Each has its own differential and its own obligatory work-up. (Book p4)"),

(4, "recall", "AUFI & PUO",
 "Key principle underlying PUO",
 "Which single statement best captures how PUO is usually caused?",
 ["PUO is usually caused by atypical presentations of common illnesses, not typical presentations of rare illnesses",
  "PUO is usually caused by typical presentations of rare illnesses, not atypical presentations of common illnesses",
  "PUO is usually caused by occult malignancy and should be investigated as such from the outset",
  "PUO is usually a manifestation of an undiagnosed connective tissue disease"],
 0,
 "This inversion of the two possibilities is the single most useful line in the section: common diseases presenting atypically far outnumber rare diseases presenting typically, so the work-up stays anchored on common illness. (Book p4)"),

(4, "match", "AUFI & PUO",
 "Aetiology of PUO by group",
 "Match each group of PUO causes to an example from the book's list \u2014 1) Infectious 2) Neoplastic 3) Connective tissue disorders 4) Drugs \u2026 A) Atrial myxoma B) Intra-abdominal abscess, including perinephric, perirenal, liver and subphrenic C) SLE, RA and vasculitides D) Drug fever",
 ["1-B, 2-A, 3-C, 4-D", "1-A, 2-B, 3-C, 4-D", "1-B, 2-C, 3-A, 4-D", "1-C, 2-A, 3-B, 4-D"],
 0,
 "Infectious causes include HIV, TB, malaria, enteric fever, infective endocarditis, UTI, intra-abdominal abscess (perinephric, perirenal, liver, subphrenic) and pelvic inflammatory disease; neoplastic causes include leukaemia, lymphoma, GI malignancies, secondaries and atrial myxoma; connective tissue disorders include SLE, RA and vasculitides; drug fever is its own group. (Book p4)"),

(4, "scenario", "AUFI & PUO",
 "Atrial myxoma as a neoplastic cause of PUO",
 "A patient with prolonged fever, a raised ESR and an early diastolic 'tumour plop' has a left atrial mass on echocardiography. Within the book's PUO framework this is an example of:",
 ["A neoplastic cause of PUO - atrial myxoma is listed with leukaemia, lymphoma and secondaries",
  "An infectious cause of PUO - the mass is a vegetation",
  "A connective tissue cause of PUO - the mass is a sterile thrombus of vasculitis",
  "A drug fever, since only drugs produce fever with a normal peripheral smear"],
 0,
 "Atrial myxoma is deliberately placed in the neoplastic list of PUO causes alongside leukaemia, lymphoma, GI malignancies and secondaries - a reminder that 'tumour' does not mean only solid organ malignancy or metastasis. (Book p4)"),

(4, "scenario", "AUFI & PUO",
 "Intra-abdominal abscess sites in PUO",
 "Which of the following abscess sites is NOT named in the book's list of intra-abdominal abscesses causing PUO?",
 ["Perinephric", "Perirenal", "Subphrenic", "Psoas"],
 3,
 "The named sites are perinephric, perirenal, liver and subphrenic, together with pelvic inflammatory disease as a separate infectious cause. Psoas abscess, though a real cause of occult fever, is not on this list and is not what the examiner is quoting. (Book p4)"),

# ---------------------------------------------------------------- Auto-inflammatory (p4)
(4, "oddoneout", "Auto-inflammatory Diseases of Fever",
 "Auto-inflammatory diseases with characteristic fever",
 "Which of the following is NOT one of the auto-inflammatory diseases in which fever is characteristic, as listed in the book?",
 ["Adult and juvenile onset Still's disease", "Familial Mediterranean fever", "Beh\u00e7et's syndrome", "Systemic lupus erythematosus"],
 3,
 "The list is adult and juvenile onset Still's disease, familial Mediterranean fever, Beh\u00e7et's syndrome, cryopyrin associated periodic syndromes (CAPS), PAPA syndrome and hyper-IgD syndrome. SLE appears in the PUO list as a connective tissue disorder, not as an auto-inflammatory periodic fever. (Book p4)"),

(4, "fillup", "Auto-inflammatory Diseases of Fever",
 "FMF pathogenesis reference and treatment",
 "Familial Mediterranean fever has its pathogenesis referenced to ____ in the book, and its treatment is colchicine.",
 ["Robbins", "Harrison's 19e", "Davidson", "Boloor"],
 0,
 "The pathogenesis of FMF is referenced to Robbins, and the treatment is colchicine - one of the only three diseases in which the book says colchicine is used. (Book p4)"),

(4, "numeric", "Auto-inflammatory Diseases of Fever",
 "The three diseases in which colchicine is used",
 "The book gives three diseases in which colchicine can be used. Which of the following is NOT one of them?",
 ["Gout", "Pericarditis", "Familial Mediterranean fever", "Beh\u00e7et's disease"],
 3,
 "The three uses are gout, pericarditis and familial Mediterranean fever. Beh\u00e7et's syndrome is an auto-inflammatory disease with characteristic fever, but colchicine is not one of the three listed indications. (Book p4)"),

(4, "fillup", "Auto-inflammatory Diseases of Fever",
 "PAPA syndrome",
 "PAPA syndrome stands for Pyogenic arthritis, Pyoderma gangrenosum and ____.",
 ["Acne", "Amyloidosis", "Adenopathy", "Alopecia"],
 0,
 "PAPA = Pyogenic arthritis, Pyoderma gangrenosum, Acne. It is one of the auto-inflammatory diseases listed in which fever is characteristic. (Book p4)"),

(4, "recall", "Auto-inflammatory Diseases of Fever",
 "CAPS expansion",
 "CAPS, listed under auto-inflammatory diseases with fever, stands for:",
 ["Cryopyrin associated periodic syndromes", "Cold agglutinin positive syndrome", "Chronic auto-inflammatory polyserositis syndrome", "Cytokine activation pyrexia syndrome"],
 0,
 "CAPS = cryopyrin associated periodic syndromes, grouped with Still's disease, FMF, Beh\u00e7et's, PAPA and hyper-IgD syndrome as auto-inflammatory causes of fever. (Book p4)"),

(4, "recall", "Auto-inflammatory Diseases of Fever",
 "Hyper-IgD syndrome",
 "Which statement about hyper-IgD syndrome in the book is correct?",
 ["It is listed among auto-inflammatory diseases in which fever is characteristic",
  "It is listed as a neoplastic cause of PUO",
  "It is listed as a variant of PUO seen in HIV infection",
  "It is listed as a drug fever caused by immunoglobulin therapy"],
 0,
 "Hyper-IgD syndrome appears in the auto-inflammatory fever list with Still's disease, FMF, Beh\u00e7et's, CAPS and PAPA - all characterised by recurrent fever without infection or malignancy. (Book p4)"),
]
