# -*- coding: utf-8 -*-
"""Chapter-artifact source data, Book p7-9 (cyanosis; clubbing basics, causes, theories; painful/unilateral clubbing; lymphadenopathy)."""

# (page, fmt, sec, point, question, options, ans, explanation)
C = [
# ---------------------------------------------------------------- Cyanosis (p7)
(7, "recall", "Cyanosis",
 "Definition of cyanosis",
 "Cyanosis is defined (Harrison's 19e) as bluish discolouration of skin and mucous membranes due to accumulation in small blood vessels of:",
 ["Reduced haemoglobin or haemoglobin derivatives such as methaemoglobin and sulphhaemoglobin",
  "Oxygenated haemoglobin within the capillaries",
  "Bilirubin and bile salts within the dermis",
  "Reduced albumin-bound free fatty acids in the dermal plexus"],
 0,
 "The pigment responsible is reduced haemoglobin or a haemoglobin derivative (metHb/sulfHb) accumulating in the small vessels of the skin and mucous membranes - never oxygenated haemoglobin, which is bright red. (Book p7)"),

(7, "numeric", "Cyanosis",
 "Reduced haemoglobin threshold for cyanosis",
 "Cyanosis becomes apparent when the quantity of reduced haemoglobin exceeds:",
 ["4 g/dL", "2 g/dL", "8 g/dL", "10 g/dL"],
 0,
 "Cyanosis appears when reduced haemoglobin exceeds 4 g/dL, which corresponds to an SpO2 of about 85% at least. Below that, the tissue appears normally coloured regardless of how the patient feels. (Book p7)"),

(7, "numeric", "Cyanosis",
 "SpO2 corresponding to cyanosis",
 "Cyanosis is indicative of an SpO2 of at least:",
 ["<85%", "<90%", "<80%", "<95%"],
 0,
 "Cyanosis indicates an SpO2 below about 85%. A patient breathing room air with an SpO2 of 90% may look perfectly pink - a clinical trap. (Book p7)"),

(7, "scenario", "Cyanosis",
 "Absolute quantity of reduced haemoglobin",
 "A woman with a haemoglobin of 4 g/dL is profoundly breathless but has no cyanosis. The best explanation according to the book is:",
 ["It is the absolute, not the relative, quantity of reduced Hb that causes cyanosis, and her total Hb is too low to reach 4 g/dL of reduced Hb",
  "Cyanosis is masked by anaemia-related pallor because conjunctival vessels are constricted",
  "Cyanosis requires an abnormal haemoglobin derivative, which she lacks",
  "Cyanosis cannot occur at any saturation above 70%, which she has not yet reached"],
 0,
 "Cyanosis needs an absolute quantity of more than 4 g/dL of reduced haemoglobin. In severe anaemia even a very low SpO2 may generate too little reduced Hb to produce the blue colour - so absence of cyanosis never excludes severe hypoxaemia. (Book p7)"),

(7, "match", "Cyanosis",
 "Central versus peripheral cyanosis",
 "Match each cyanosis concept to its description \u2014 1) Central cyanosis 2) Peripheral cyanosis 3) Spared site in peripheral cyanosis 4) Intermittent cyanosis \u2026 A) Ebstein's anomaly B) Arterial oxygen saturation reduced or an abnormal Hb derivative present, with both mucous membranes and skin affected C) Slowing of blood flow with increased oxygen extraction from saturated arterial blood D) Mucous membranes of the oral cavity and underside of the tongue",
 ["1-B, 2-C, 3-D, 4-A", "1-C, 2-B, 3-D, 4-A", "1-B, 2-D, 3-C, 4-A", "1-A, 2-C, 3-D, 4-B"],
 0,
 "Central cyanosis has a low arterial saturation or an abnormal derivative and involves both mucous membranes and skin; peripheral cyanosis reflects slow flow and increased extraction; in peripheral cyanosis the oral mucosa and underside of the tongue are often spared; intermittent cyanosis belongs to Ebstein's anomaly. (Book p7)"),

(7, "oddoneout", "Cyanosis",
 "Causes of central cyanosis",
 "Which of the following is NOT a listed cause of central cyanosis?",
 ["High altitude", "Congenital heart disease with an anatomical shunt", "V/Q mismatch from extensive pneumonia", "Cold exposure with vasoconstriction"],
 3,
 "Cold exposure produces peripheral cyanosis by vasoconstriction and diminished peripheral flow. Central cyanosis is listed as high altitude, anatomical shunts (congenital heart disease, pulmonary AV fistulas), haemoglobin anomalies and V/Q mismatch (extensive pneumonia, pulmonary oedema, COPD). (Book p7)"),

(7, "truefalse", "Cyanosis",
 "Iron-replete and iron-deplete cyanosis",
 "Which statement about hyperviscosity in cyanotic states is correct?",
 ["True: In iron-replete cyanosis, compensated erythrocytosis establishes equilibrium with the haematocrit, so hyperviscosity is rare",
  "True: In iron-deplete cyanosis, erythrocytosis fails to establish equilibrium with the haematocrit, so hyperviscosity occurs",
  "False: Hyperviscosity is commonest in iron-replete cyanosis because the haematocrit is highest",
  "False: Iron deficiency protects cyanotic patients from hyperviscosity"],
 0,
 "Iron-replete patients develop proportionate erythrocytosis that reaches equilibrium with the haematocrit and rarely becomes hyperviscous. Iron-deplete patients fail to reach that equilibrium, so viscosity rises disproportionately - an argument for treating iron deficiency in cyanotic heart disease. (Book p7)"),

(7, "match", "Cyanosis",
 "Differential cyanosis patterns",
 "Match each distribution of cyanosis to its lesion \u2014 1) Cyanosis of the lower limb only 2) Cyanosis of the upper limb only 3) Cyanosis that is intermittent \u2026 A) PDA with pulmonary hypertension and right-to-left shunt together with TGV B) Ebstein's anomaly C) PDA with pulmonary hypertension and right-to-left shunt",
 ["1-C, 2-A, 3-B", "1-A, 2-C, 3-B", "1-C, 2-B, 3-A", "1-B, 2-A, 3-C"],
 0,
 "Differential cyanosis (lower limb cyanosed, upper limb spared) means a PDA with Eisenmenger physiology and right-to-left shunt; if the upper limb is cyanosed instead, TGV is added (reverse differential pattern); intermittent cyanosis is a feature of Ebstein's anomaly. (Book p7)"),

(7, "scenario", "Cyanosis",
 "Differential cyanosis with lower-limb cyanosis",
 "A child with a large untreated ventricular septal defect has cyanosis and clubbing confined to both legs, with pink upper limbs. The most likely lesion is:",
 ["PDA with pulmonary hypertension and right-to-left shunt", "PDA with transposition of the great arteries", "Ebstein's anomaly", "Tetralogy of Fallot with pulmonary stenosis"],
 0,
 "Lower-limb-only cyanosis is the differential cyanosis of a ductus arteriosus with pulmonary hypertension and reversal of shunt, so desaturated blood enters the descending aorta beyond the origin of the upper-limb vessels. Ebstein's anomaly gives intermittent cyanosis. (Book p7)"),

# ---------------------------------------------------------------- Clubbing basics (p7-8)
(7, "recall", "Clubbing: Definition & Grades",
 "Definition of clubbing",
 "Clubbing is defined in the book as:",
 ["Selective bulbous enlargement of the distal portion of the digit due to deposition of subungual soft tissue",
  "Diffuse enlargement of the proximal phalanx due to periosteal new bone formation",
  "Bulbous enlargement of the digit with loss of the Lovibond angle caused by bony resorption",
  "Thickening of the nail plate itself with preservation of the nail-bed angle"],
 0,
 "The key words are selective, distal and subungual soft tissue deposition. Bony resorption with a preserved Lovibond angle describes pseudoclubbing, and periosteal new bone formation describes hypertrophic osteoarthropathy. (Book p7)"),

(7, "recall", "Clubbing: Definition & Grades",
 "The Lovibond angle",
 "The Lovibond angle is:",
 ["The normal angle between the nail and the nail bed", "The angle between the proximal and distal nail folds", "The angle subtended by the distal phalanx and the middle phalanx", "The angle between the nail plate and the terminal phalangeal joint line"],
 0,
 "The Lovibond angle is the normal angle between nail and nail-bed, measured at the profile of the finger. It increases in clubbing (grade 2) and is preserved in pseudoclubbing - which is exactly why the distinction matters. (Book p7)"),

(7, "numeric", "Clubbing: Definition & Grades",
 "Minimum duration for clubbing to appear",
 "The minimum duration required for clubbing to develop is:",
 ["2-3 weeks", "2-3 days", "2-3 months", "6 months"],
 0,
 "Clubbing develops over a minimum of 2-3 weeks - a useful negative point: a finger that becomes bulbous over 24-48 hours is not clubbing, and the book's figure of 2-3 weeks also explains reversible clubbing after empyema or lung abscess resolves. (Book p7)"),

(7, "recall", "Clubbing: Definition & Grades",
 "First finger to be affected",
 "The first finger in which clubbing appears is:",
 ["Index finger", "Thumb", "Little finger", "Middle finger"],
 0,
 "Clubbing first appears in the index finger. This is stated twice - once in the general clubbing section and once at the end of the section on patterns of clubbing. (Book p7)"),

(8, "match", "Clubbing: Definition & Grades",
 "Grades of clubbing",
 "Match each grade of clubbing to its clinical description \u2014 1) Grade 1 2) Grade 2 3) Grade 3 4) Grade 4 \u2026 A) Drumstick or parrot beak appearance B) Nail bed fluctuations C) Hypertrophic osteoarthropathy D) Increase in the Lovibond angle",
 ["1-B, 2-D, 3-A, 4-C", "1-B, 2-A, 3-D, 4-C", "1-D, 2-B, 3-A, 4-C", "1-A, 2-D, 3-B, 4-C"],
 0,
 "Grade 1 is nail bed fluctuation (bogginess), grade 2 an increase in the Lovibond angle, grade 3 the drumstick/parrot-beak fingertip, and grade 4 hypertrophic osteoarthropathy. The grade is quoted in the viva with the sign, not the disease. (Book p8)"),

(8, "scenario", "Clubbing: Definition & Grades",
 "Grade 4 clubbing and HOA",
 "A patient with bronchogenic carcinoma has bulbous fingertips with a swollen, tender wrist and periosteal reaction on radiography of the forearm. The grade of clubbing is:",
 ["Grade 4, because hypertrophic osteoarthropathy is present", "Grade 3, because the fingertip is drumstick shaped", "Grade 2, because the Lovibond angle is lost", "Not clubbing - this is pseudoclubbing"],
 0,
 "Grade 4 clubbing is defined by the presence of hypertrophic osteoarthropathy, which is what the periosteal reaction and joint symptoms represent. Grades 1 to 3 describe only the finger changes. (Book p8)"),

# ---------------------------------------------------------------- Causes of clubbing (p8)
(8, "match", "Causes of Clubbing",
 "Groups of causes of clubbing",
 "Match each group of causes to the examples given \u2014 1) Suppurative lung disease 2) Thoracic malignancy 3) Cardiovascular 4) Gastrointestinal \u2026 A) Cirrhosis (especially primary biliary cirrhosis) and inflammatory bowel disease B) Bronchiectasis, lung abscess and empyema C) Bronchogenic carcinoma, bronchial adenoma and mesothelioma D) Cyanotic heart disease, infective endocarditis and left atrial myxoma",
 ["1-B, 2-C, 3-D, 4-A", "1-C, 2-B, 3-D, 4-A", "1-B, 2-D, 3-C, 4-A", "1-A, 2-C, 3-D, 4-B"],
 0,
 "Suppurative lung disease (bronchiectasis, lung abscess, empyema), thoracic malignancy (bronchogenic carcinoma, bronchial adenoma, mesothelioma), cardiovascular causes (cyanotic heart disease, infective endocarditis, left atrial myxoma) and GI causes (cirrhosis - especially primary biliary cirrhosis - and inflammatory bowel disease) make up the list from Dr Vivekanandan. (Book p8)"),

(8, "truefalse", "Causes of Clubbing",
 "Diseases in which clubbing is rare",
 "Which statement about clubbing and chronic lung disease is correct?",
 ["True: Clubbing is rare in COPD and in tuberculosis",
  "True: Left atrial myxoma is listed among the cardiovascular causes of clubbing",
  "False: Bronchiectasis, lung abscess and empyema are diseases in which clubbing is rare",
  "False: Cirrhosis never causes clubbing"],
 0,
 "The book deliberately records that clubbing is rare in COPD and TB while it is common in suppurative lung disease, ILD and thoracic malignancy. Cardiac causes include cyanotic heart disease, infective endocarditis and left atrial myxoma. (Book p8)"),

(8, "oddoneout", "Causes of Clubbing",
 "Clubbing in suppurative and interstitial disease",
 "Which of the following is LEAST likely to cause clubbing?",
 ["Bronchiectasis", "Lung abscess", "Interstitial lung disease", "Chronic obstructive pulmonary disease"],
 3,
 "Clubbing is rare in COPD (and in TB); it is a feature of suppurative lung disease, malignancy and interstitial lung disease. This is one of the classic negative discriminations in a clubbing viva. (Book p8)"),

(8, "recall", "Causes of Clubbing",
 "Thyroid acropachy",
 "Thyroid acropachy, listed among other causes of clubbing, is:",
 ["A rare manifestation of Graves' disease with swelling of fingers and toes, clubbing and periosteal reaction of the extremity bones",
  "A rare manifestation of hypothyroidism with thickening of the skin of the fingers",
  "A paraneoplastic syndrome of thyroid carcinoma with clubbing and myxoedema",
  "An autoimmune overlap syndrome with clubbing and pretibial myxoedema only"],
 0,
 "Thyroid acropachy occurs in Graves' disease - swelling of fingers and toes, clubbing and periosteal reaction of extremity bones. It is the reason thyroid disease appears in the causes of clubbing at all. (Book p8)"),

(8, "fillup", "Causes of Clubbing",
 "POEMS syndrome",
 "POEMS syndrome, listed under other causes of clubbing, stands for Polyneuropathy, Organomegaly, Endocrinopathy, M protein and ____.",
 ["Skin changes", "Splenomegaly", "Serositis", "Skeletal lesions"],
 0,
 "POEMS = Polyneuropathy, Organomegaly, Endocrinopathy, M protein, Skin changes. It is worth remembering as a cause of clubbing that begins with a haematological plasma cell disorder, like the M protein itself. (Book p8)"),

(8, "scenario", "Causes of Clubbing",
 "Graves' disease with clubbing",
 "A patient with treated Graves' disease develops clubbing, swelling of the fingers and toes and periosteal reaction of the long bones. The correct label is:",
 ["Thyroid acropachy", "Hypertrophic osteoarthropathy", "Pseudoclubbing of acromegaly", "POEMS syndrome"],
 0,
 "Thyroid acropachy is a rare manifestation of Graves' disease presenting with swelling of fingers and toes, clubbing and periosteal reaction of extremity bones. HOA would imply an intrathoracic neoplasm, not thyroid disease. (Book p8)"),

# ---------------------------------------------------------------- Pseudoclubbing & theories (p8)
(8, "recall", "Pseudoclubbing & Theories of Clubbing",
 "Definition of pseudoclubbing",
 "Pseudoclubbing is:",
 ["Bulbous enlargement of fingers or toes with preservation of the Lovibond angle",
  "Bulbous enlargement of fingers or toes with loss of the Lovibond angle but no soft tissue proliferation",
  "Clubbing associated with an underlying neoplasm",
  "Clubbing that reverses completely after treatment of the primary disease"],
 0,
 "In pseudoclubbing the Lovibond angle is preserved. Per Kundu the mechanism is subperiosteal bone resorption in the phalanges without soft tissue proliferation - so the finger looks bulbous but the nail profile is unchanged. (Book p8)"),

(8, "match", "Pseudoclubbing & Theories of Clubbing",
 "Causes of pseudoclubbing",
 "Match each cause of pseudoclubbing \u2014 1) Infective 2) Connective tissue 3) Endocrine 4) Occupational \u2026 A) Acromegaly B) Leprosy C) Vinyl chloride workers with acro-osteolysis D) Scleroderma",
 ["1-B, 2-D, 3-A, 4-C", "1-A, 2-D, 3-B, 4-C", "1-B, 2-A, 3-D, 4-C", "1-C, 2-D, 3-A, 4-B"],
 0,
 "Pseudoclubbing is seen in leprosy, scleroderma, hyperparathyroidism, acromegaly and vinyl chloride workers with acro-osteolysis. All share bone resorption with a preserved Lovibond angle. (Book p8)"),

(8, "scenario", "Pseudoclubbing & Theories of Clubbing",
 "Bulbous fingers with a preserved angle",
 "A worker in a vinyl chloride plant has bulbous finger tips; the nail-bed angle is normal and radiographs show acro-osteolysis. This is:",
 ["Pseudoclubbing from acro-osteolysis", "True clubbing with early HOA", "Grade 3 clubbing", "Thyroid acropachy"],
 0,
 "Preservation of the Lovibond angle with bone resorption is the signature of pseudoclubbing; vinyl chloride exposure with acro-osteolysis is one of its listed causes, along with leprosy, scleroderma, hyperparathyroidism and acromegaly. (Book p8)"),

(8, "recall", "Pseudoclubbing & Theories of Clubbing",
 "Most accepted theory of clubbing",
 "The most accepted theory of clubbing in the book is:",
 ["Large megakaryocytes normally broken down in the pulmonary circulation reach the peripheral arterioles of the nail bed in lung disease and release PDGF, causing connective tissue proliferation",
  "Vagal stimulation causes vasodilation and connective tissue growth in the nail bed",
  "Growth hormone, PTH and oestrogen directly stimulate subungual fibroblasts",
  "Persistent hypoxia opens deep arteriovenous fistulae which enlarge the fingertip"],
 0,
 "The megakaryocyte/PDGF theory is the most accepted: megakaryocytes are normally fragmented in the pulmonary circulation; in lung disease they reach the nail-bed arterioles intact and release platelet-derived growth factor, driving connective tissue proliferation. (Book p8)"),

(8, "fillup", "Pseudoclubbing & Theories of Clubbing",
 "Growth factor released in the nail bed",
 "In the most accepted theory of clubbing, the megakaryocytes reaching the nail-bed arterioles release ____, which causes proliferation of connective tissue.",
 ["PDGF", "VEGF", "TGF-\u03b2", "EGF"],
 0,
 "The mediator is platelet-derived growth factor (PDGF). It explains why clubbing appears in conditions with right-to-left shunting and in suppurative lung disease, where megakaryocytes bypass the lung filter. (Book p8)"),

(8, "match", "Pseudoclubbing & Theories of Clubbing",
 "Theories of clubbing",
 "Match each theory of clubbing to its proposed mechanism \u2014 1) Neurogenic 2) Humoral 3) Hypoxic 4) Ferritin \u2026 A) Vagal stimulation causes vasodilation B) GH, PTH and oestrogen cause vasodilation C) Persistent hypoxia opens deep AV fistulae D) Decreased systemic ferritin causes dilation of AV anastomoses",
 ["1-A, 2-B, 3-C, 4-D", "1-B, 2-A, 3-C, 4-D", "1-A, 2-C, 3-B, 4-D", "1-D, 2-B, 3-C, 4-A"],
 0,
 "Neurogenic (vagal stimulation causing vasodilation), humoral (GH, PTH, oestrogen), hypoxic (persistent hypoxia opening deep AV fistulae) and ferritin (decreased systemic ferritin dilating AV anastomoses) theories are all listed in addition to the most-accepted megakaryocyte/PDGF mechanism. (Book p8)"),

# ---------------------------------------------------------------- Patterns of clubbing (p9)
(9, "recall", "Painful, Unilateral & Unidigital Clubbing",
 "Causes of painful clubbing",
 "Painful clubbing is listed in association with:",
 ["Bronchogenic carcinoma, lung abscess and infective endocarditis",
  "Cirrhosis, inflammatory bowel disease and coeliac disease",
  "Cyanotic heart disease and interstitial lung disease",
  "Acromegaly, leprosy and hyperparathyroidism"],
 0,
 "Painful clubbing belongs to bronchogenic carcinoma, lung abscess and infective endocarditis - three conditions in which the clubbing itself hurts, in contrast to the usual painless clubbing. (Book p9)"),

(9, "recall", "Painful, Unilateral & Unidigital Clubbing",
 "Unilateral clubbing",
 "Which of the following is a listed cause of unilateral clubbing?",
 ["Presubclavian coarctation of aorta, with only left-sided clubbing", "Presubclavian coarctation of aorta, with only right-sided clubbing", "Atrial septal defect with Eisenmenger syndrome", "Scleroderma of one hand"],
 0,
 "Unilateral clubbing is described in presubclavian coarctation of aorta with only left-sided clubbing, apical bronchogenic carcinoma, cervical rib and aneurysm of the subclavian or axillary artery. (Book p9)"),

(9, "scenario", "Painful, Unilateral & Unidigital Clubbing",
 "Left-sided clubbing only",
 "A young hypertensive patient has clubbing of the left hand only, with an absent left radial pulse. Among the listed causes of unilateral clubbing, the book's lesion here is:",
 ["Presubclavian coarctation of aorta", "Apical bronchogenic carcinoma", "Cervical rib", "Subclavian artery aneurysm"],
 0,
 "Presubclavian coarctation of the aorta is the cause given that produces clubbing confined to the left side. An apical bronchogenic carcinoma, cervical rib and subclavian/axillary aneurysm are the other unilateral causes - each with its own localising signs. (Book p9)"),

(9, "oddoneout", "Painful, Unilateral & Unidigital Clubbing",
 "Unidigital clubbing",
 "Which of the following is NOT a listed cause of unidigital clubbing?",
 ["Hereditary occurrence", "Repeated local trauma", "Median nerve injury", "Bronchiectasis"],
 3,
 "Unidigital clubbing is hereditary, follows repeated local trauma, and rarely follows median nerve injury. Bronchiectasis produces generalised clubbing, not single-digit clubbing. (Book p9)"),

(9, "recall", "Painful, Unilateral & Unidigital Clubbing",
 "First affected finger",
 "Which finger is the first to be affected by clubbing?",
 ["Index finger", "Thumb", "Ring finger", "Ring and little fingers together"],
 0,
 "The index finger is the first to be affected. Both the clubbing definition page and the closing line of the clubbing section state this, which is why it is a favourite one-line viva question. (Book p9)"),

# ---------------------------------------------------------------- Lymphadenopathy (p9)
(9, "numeric", "Lymphadenopathy: Significance & Character",
 "When lymphadenopathy is significant",
 "According to the book, which node size is significant in the inguinal region?",
 [">1.5 cm", ">1 cm", ">2 cm", ">3 cm"],
 0,
 "Inguinal nodes are significant when larger than 1.5 cm; any other node is significant when larger than 1 cm; and any supraclavicular or epitrochlear node is significant however small it is. (Book p9)"),

(9, "recall", "Lymphadenopathy: Significance & Character",
 "Nodes significant whatever their size",
 "Which nodes are significant whatever their size?",
 ["Supraclavicular and epitrochlear nodes", "Inguinal and axillary nodes", "Submental and submandibular nodes", "Anterior cervical and posterior triangle nodes"],
 0,
 "Any supraclavicular or epitrochlear node is significant at any size - these are the two sites where even a small node mandates explanation, and both are classic answers in a lymphadenopathy viva. (Book p9)"),

(9, "recall", "Lymphadenopathy: Significance & Character",
 "Definition of generalised lymphadenopathy",
 "Generalised lymphadenopathy is best defined as involvement of:",
 ["Two or more non-contiguous lymph node areas - though Harrison's says three or more, which is not practical",
  "All palpable node groups excluding the inguinal group",
  "Three or more contiguous node areas only",
  "Any two node areas including the two inguinal groups"],
 0,
 "The book prefers two or more non-contiguous areas and explicitly notes that Harrison's says three or more but that this is not practical. Persistent generalised lymphadenopathy means it lasts more than 3 months. (Book p9)"),

(9, "numeric", "Lymphadenopathy: Significance & Character",
 "Persistent generalised lymphadenopathy",
 "Persistent generalised lymphadenopathy is defined as lasting more than:",
 ["3 months", "2 weeks", "6 months", "1 year"],
 0,
 "More than 3 months defines persistence. The distinction matters because transient generalised lymphadenopathy accompanies most viral illness, whereas persistence raises HIV, tuberculosis, lymphoma and connective tissue disease. (Book p9)"),

(9, "match", "Lymphadenopathy: Significance & Character",
 "Character of lymph nodes",
 "Match each lymph node character to its meaning \u2014 1) Painful lymphadenopathy 2) Firm, rubbery nodes 3) Fluctuant nodes 4) Stony hard node \u2026 A) Suppurative nodes B) Metastasis C) Infectious aetiology or even acute leukaemia D) Lymphoma",
 ["1-C, 2-D, 3-A, 4-B", "1-A, 2-D, 3-C, 4-B", "1-C, 2-A, 3-D, 4-B", "1-D, 2-C, 3-A, 4-B"],
 0,
 "Painful nodes suggest infection but can occur in acute leukaemia; firm, rubbery nodes suggest lymphoma; fluctuant nodes are suppurative; a stony hard node means metastasis. (Book p9)"),

(9, "scenario", "Lymphadenopathy: Significance & Character",
 "Matted nodes",
 "Matted nodes - which feel connected and move together as a unit - are seen in:",
 ["Tuberculosis as the benign cause, and lymphoma or metastatic carcinoma as the malignant causes",
  "Infectious mononucleosis as the benign cause, and acute leukaemia as the malignant cause",
  "Sarcoidosis as the benign cause, and Hodgkin's lymphoma only",
  "Suppurative lymphadenitis as the benign cause, and secondaries as the malignant cause"],
 0,
 "Matted nodes are benign in tuberculosis and malignant in lymphoma or metastatic carcinoma. The clue is in the matting together with the consistency and the site, not in enlargement alone. (Book p9)"),

(9, "match", "Lymphadenopathy: Significance & Character",
 "Levels of cervical nodes",
 "Match each cervical node level to its region \u2014 1) Ia 2) Ib 3) II, III and IV 4) V 5) VI 6) VII \u2026 A) Submental B) Submandibular C) Upper, middle and lower jugular D) Posterior triangle E) Anterior triangle F) Superior mediastinal",
 ["1-A, 2-B, 3-C, 4-D, 5-E, 6-F", "1-B, 2-A, 3-C, 4-D, 5-E, 6-F", "1-A, 2-B, 3-D, 4-C, 5-F, 6-E", "1-A, 2-C, 3-B, 4-D, 5-E, 6-F"],
 0,
 "Ia submental, Ib submandibular, II-IV upper/middle/lower jugular, V posterior triangle, VI anterior triangle, VII superior mediastinal. The levels are used to describe neck nodes and to plan neck dissection. (Book p9)"),

(9, "scenario", "Lymphadenopathy: Significance & Character",
 "Node character in a young patient",
 "A 22-year-old has a 3 cm firm, rubbery, painless lower cervical node with no other nodes palpable. Among the listed characters, firm rubbery nodes are said to be suggestive of:",
 ["Lymphoma", "Suppuration", "Metastatic carcinoma from a head and neck primary", "Tubercular lymphadenitis"],
 0,
 "Firm and rubbery suggests lymphoma; fluctuant means suppurative; stony hard means metastatic deposit. Matted nodes would be more typical of tuberculosis. (Book p9)"),
]
