# -*- coding: utf-8 -*-
"""Chapter-artifact source data, Book p5-6 (pulse-temperature relation, fever patterns, hypothermia, pallor, icterus)."""

# (page, fmt, sec, point, question, options, ans, explanation)
B = [
# ---------------------------------------------------------------- p5
(5, "numeric", "Relative Bradycardia & Tachycardia",
 "Pulse response to fever",
 "For every 1\u00b0F rise in body temperature, the pulse rate should rise by about ____.",
 ["10/min", "5/min", "15/min", "20/min"],
 0,
 "The bedside rule is 10 beats per minute per 1\u00b0F (about 18 per 1\u00b0C) rise of temperature. A pulse that fails to rise this much is relative bradycardia; one that overshoots is relative tachycardia. (Book p5)"),

(5, "match", "Relative Bradycardia & Tachycardia",
 "Causes of relative bradycardia",
 "Match each cause of relative bradycardia to its identification \u2014 1) Enteric fever, first week 2) Yellow fever 3) Weil's disease 4) Brucellosis \u2026 A) The pulse-temperature dissociation here is called Faget's sign B) Mechanism is heart block C) A variety of leptospirosis D) A zoonosis that classically gives relative bradycardia",
 ["1-B, 2-A, 3-C, 4-D", "1-A, 2-B, 3-C, 4-D", "1-B, 2-C, 3-A, 4-D", "1-C, 2-A, 3-B, 4-D"],
 0,
 "Relative bradycardia in enteric fever (first week) is produced by heart block; in yellow fever the dissociation is called Faget's sign; Weil's disease is a variety of leptospirosis; and brucellosis is a classic cause. (Book p5)"),

(5, "scenario", "Relative Bradycardia & Tachycardia",
 "Faget's sign",
 "A traveller returns with jaundice, bleeding, and a temperature of 39.5\u00b0C with a pulse of 78/min. The eponym for this pulse-temperature dissociation, when seen in this illness, is:",
 ["Faget's sign", "Kussmaul's sign", "Osler's sign", "de Musset's sign"],
 0,
 "In yellow fever relative bradycardia is called Faget's sign. Kussmaul's sign is a paradoxical rise of JVP on inspiration; Osler's and de Musset's signs concern endocarditis and aortic regurgitation respectively. (Book p5)"),

(5, "recall", "Relative Bradycardia & Tachycardia",
 "Mechanism of relative bradycardia in enteric fever",
 "The relative bradycardia of enteric fever in the first week is attributed to:",
 ["Heart block", "Increased vagal tone from mesenteric lymphadenopathy", "Dehydration reducing stroke volume", "Direct Salmonella myocarditis"],
 0,
 "The book gives the mechanism as heart block, and flags it as a point to read in more detail. This is distinct from the relative tachycardia seen with myocarditis (diphtheritic, rheumatic). (Book p5)"),

(5, "oddoneout", "Relative Bradycardia & Tachycardia",
 "Separating causes of relative bradycardia from relative tachycardia",
 "Which of the following causes relative bradycardia and NOT relative tachycardia?",
 ["Acute rheumatic carditis", "Tuberculosis", "Polyarteritis nodosa", "Brucellosis"],
 3,
 "Relative tachycardia belongs to acute rheumatic carditis, tuberculosis, polyarteritis nodosa and diphtheritic myocarditis; brucellosis is a cause of relative bradycardia, along with enteric fever, viral fevers and Weil's disease. (Book p5)"),

(5, "recall", "Relative Bradycardia & Tachycardia",
 "Relative tachycardia list",
 "Which of the following is listed as a cause of relative tachycardia?",
 ["Diphtheritic myocarditis", "Brucellosis", "Yellow fever", "Enteric fever in the first week"],
 0,
 "Diphtheritic myocarditis joins acute rheumatic carditis, tuberculosis and polyarteritis nodosa in the relative tachycardia list. The other three options all cause relative bradycardia. (Book p5)"),

# ---------------------------------------------------------------- Patterns of fever
(5, "recall", "Patterns of Fever",
 "Definition of intermittent fever",
 "Intermittent fever is defined in the book as:",
 ["Fever present for several hours, which always touches the baseline sometime during the day",
  "Fever that never touches the baseline but fluctuates by more than 2\u00b0C",
  "Fever that does not fluctuate by more than 1\u00b0C during the day",
  "Fever that recurs in cycles of one to two weeks"],
 0,
 "Intermittent fever is present for several hours and always touches the baseline at some point in the day; quotidian, tertian and quartan are its subdivisions. Never touching the baseline defines remittent and continued fevers instead. (Book p5)"),

(5, "match", "Patterns of Fever",
 "Subdivisions of intermittent fever",
 "Match each intermittent pattern to its timing \u2014 1) Quotidian 2) Double quotidian 3) Tertian 4) Quartan \u2026 A) Paroxysm on alternate days B) Two-day interval between paroxysms C) Paroxysm of fever occurs daily D) Two spikes of fever in a single day",
 ["1-C, 2-D, 3-A, 4-B", "1-D, 2-C, 3-A, 4-B", "1-C, 2-D, 3-B, 4-A", "1-A, 2-D, 3-C, 4-B"],
 0,
 "Quotidian = daily paroxysm; double quotidian = two spikes in a day; tertian = alternate-day paroxysm; quartan = a two-day interval between paroxysms. (Book p5)"),

(5, "recall", "Patterns of Fever",
 "Causes of quotidian fever",
 "Which group of conditions is listed as producing quotidian fever?",
 ["Tuberculosis, UTI and septicaemia", "Kala-azar and gonococcal perihepatitis", "Borrelia infection", "Lobar pneumonia and meningococcaemia"],
 0,
 "Quotidian (daily) paroxysms are seen in tuberculosis, UTI and septicaemia. Kala-azar and gonococcal perihepatitis give the camel-hump (double quotidian) pattern, and Borrelia gives relapsing fever. (Book p5)"),

(5, "recall", "Patterns of Fever",
 "Double quotidian fever and its classic associations",
 "Double quotidian fever - two spikes of fever in one day - is most commonly of which aetiology, and was commonly seen in which condition?",
 ["Gonococcal; endocarditis", "Malarial; meningitis", "Tubercular; pericarditis", "Enteric; osteomyelitis"],
 0,
 "Double quotidian fever is commonly gonococcal in aetiology and used to be commonly seen in endocarditis - a historical association that still gets asked. (Book p5)"),

(5, "match", "Patterns of Fever",
 "Malarial fevers and their other names",
 "Match each fever to its organism or mechanism \u2014 1) Benign tertian malaria 2) Malignant tertian malaria 3) Quartan fever 4) Charcot's intermittent fever \u2026 A) P. malariae B) P. vivax or P. ovale C) P. falciparum, also called aestivo-autumnal or Roman fever D) Chills with RUQ pain and jaundice from a stone obstructing the CBD",
 ["1-B, 2-C, 3-A, 4-D", "1-C, 2-B, 3-A, 4-D", "1-B, 2-A, 3-C, 4-D", "1-D, 2-C, 3-A, 4-B"],
 0,
 "Benign tertian malaria is P. vivax/ovale; malignant tertian (falciparum, aestivo-autumnal, Roman) fever is P. falciparum; quartan fever with a two-day interval is P. malariae; and Charcot's intermittent fever is the cholangitic pattern of chills, RUQ pain and jaundice from a CBD stone. (Book p5)"),

(5, "recall", "Patterns of Fever",
 "Definition of remittent fever",
 "Remittent fever is characterised by:",
 ["A daily fluctuation of more than 2\u00b0C (3\u00b0F), and it never touches the baseline",
  "A daily fluctuation of less than 1\u00b0C, and it never touches the baseline",
  "Fever that touches the baseline once every day",
  "Fever with two spikes in a single day"],
 0,
 "Remittent fever swings by more than 2\u00b0C (3\u00b0F) a day and never touches the baseline. For contrast, remember that the normal fluctuation of temperature is 0.9\u00b0C. (Book p5)"),

(5, "numeric", "Patterns of Fever",
 "Normal daily temperature fluctuation",
 "For contrast with the definition of remittent fever, the book notes that normal daily fluctuation of temperature is:",
 ["0.9\u00b0C", "0.5\u00b0C", "1.5\u00b0C", "2.0\u00b0C"],
 0,
 "Normal fluctuation is 0.9\u00b0C, so a swing of more than 2\u00b0C is a large excursion indeed, and the definition of continued fever (no more than 1\u00b0C) sits far below it. (Book p5)"),

(5, "match", "Patterns of Fever",
 "Remittent and continued fever causes",
 "Match each fever pattern to its listed causes \u2014 1) Remittent 2) Continued \u2026 A) Lobar pneumonia, second week of enteric fever, gram negative sepsis, acute rheumatic fever, meningococcaemia B) Amoebic liver abscess, acute bronchopneumonia, third week of enteric fever",
 ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
 0,
 "Remittent fever is seen in amoebic liver abscess, acute bronchopneumonia and the third week of enteric fever; continued fever with minimal fluctuation is seen in lobar pneumonia (classically), the second week of enteric fever, gram negative sepsis, acute rheumatic fever and meningococcaemia. (Book p5)"),

(5, "oddoneout", "Patterns of Fever",
 "Which fever never touches the baseline",
 "Amoebic liver abscess, acute bronchopneumonia and the third week of enteric fever share which fever pattern?",
 ["Continued fever", "Remittent fever", "Quotidian fever", "Pel-Ebstein fever"],
 1,
 "All three are listed under remittent fever - a daily fluctuation of more than 2\u00b0C that never touches the baseline. Continued fever belongs to lobar pneumonia, gram negative sepsis, acute rheumatic fever and meningococcaemia. (Book p5)"),

(5, "recall", "Patterns of Fever",
 "Pel-Ebstein pattern",
 "The Pel-Ebstein (Ebstein-Cardarelli) pattern, in which fever cyclically increases and decreases in periods of one to two weeks, is called by that name:",
 ["Only when it is associated with Hodgkin's lymphoma - other cyclical fevers are simply called cyclical fevers",
  "Whenever it is associated with any lymphoma, Hodgkin's or non-Hodgkin's",
  "Only when it is associated with kala-azar",
  "Whenever the fever period lasts longer than two weeks"],
 0,
 "The eponym is used only for the cyclical fever of Hodgkin's lymphoma; identical-looking cyclical fevers in other diseases are called cyclical fevers and nothing more. (Book p5)"),

(5, "match", "Patterns of Fever",
 "Specific named fever patterns",
 "Match each named pattern to its disease \u2014 1) Camel hump pattern 2) Step-ladder pattern 3) Undulant fever 4) Relapsing fever \u2026 A) Brucellosis, with fever that rapidly rises and falls B) Kala-azar and gonococcal perihepatitis (Fitz-Hugh-Curtis syndrome) C) Enteric fever D) A cyclical fever caused by Borrelia infection",
 ["1-B, 2-C, 3-A, 4-D", "1-C, 2-B, 3-A, 4-D", "1-B, 2-A, 3-C, 4-D", "1-D, 2-C, 3-A, 4-B"],
 0,
 "Camel hump = double quotidian pattern of kala-azar and gonococcal perihepatitis; step-ladder = enteric fever; undulant = brucellosis; relapsing = Borrelia. (Book p5)"),

(5, "fillup", "Patterns of Fever",
 "Step-ladder fever",
 "The step-ladder pattern, in which fever stays at a baseline and then acutely rises to a new baseline, is characteristic of ____.",
 ["Enteric fever", "Brucellosis", "Hodgkin's lymphoma", "Kala-azar"],
 0,
 "Step-ladder fever is the enteric fever pattern; the baseline holds, then climbs acutely to a new level. Brucellosis gives undulant fever, Borrelia relapsing fever, kala-azar the camel hump. (Book p5)"),

(5, "truefalse", "Patterns of Fever",
 "Baseline behaviour across fever patterns",
 "Which statement about fever patterns is correct?",
 ["True: Remittent fever never touches the baseline and fluctuates by more than 2\u00b0C",
  "True: Continued fever does not fluctuate by more than 1\u00b0C and never touches the baseline",
  "False: Intermittent fever never touches the baseline at any time during the day",
  "False: The normal daily fluctuation of temperature is 2\u00b0C"],
 0,
 "Touching or not touching the baseline is the discriminator: intermittent fever always touches it, remittent and continued never do. Normal daily fluctuation is 0.9\u00b0C, not 2\u00b0C. (Book p5)"),

(5, "scenario", "Patterns of Fever",
 "Fever with splenomegaly and double spikes",
 "A patient from an endemic area has months of fever, massive splenomegaly and two temperature spikes each day. The camel hump (double quotidian) pattern here points to:",
 ["Kala-azar", "Enteric fever", "Brucellosis", "Hodgkin's lymphoma"],
 0,
 "Camel hump pattern (double quotidian fever) is listed for kala-azar and gonococcal perihepatitis. Step-ladder fever belongs to enteric fever, undulant fever to brucellosis, and Pel-Ebstein fever to Hodgkin's lymphoma. (Book p5)"),
(6, "scenario", "Patterns of Fever",
 "Hectic fever and pent-up pus",
 "A patient has daily fever with wide swings (39.5\u00b0C to 35.8\u00b0C) and imaging shows a liver abscess. The pattern is hectic fever, and the book associates hectic fever with:",
 ["Any pent-up pus in the body, such as liver abscess, lung abscess, empyema and subphrenic abscess",
  "Cyclical fevers of Hodgkin's lymphoma",
  "The second week of enteric fever",
  "Gonococcal perihepatitis only"],
 0,
 "Hectic fever is characterised by wide swings and is associated with any pent-up pus - liver abscess, lung abscess, empyema and subphrenic abscess. This is different from Pel-Ebstein fever of Hodgkin's lymphoma. (Book p6)"),


# ---------------------------------------------------------------- Hypothermia (p6)
(6, "recall", "Hypothermia",
 "Primary versus secondary hypothermia",
 "Which of the following is a primary cause of hypothermia as classified in the book?",
 ["Accidental exposure", "Cerebrovascular accident", "Overwhelming sepsis", "Adrenal insufficiency"],
 0,
 "Primary hypothermia is typically due to accidental exposure. Secondary hypothermia is failure of thermoregulation, and includes cerebrovascular accident, overwhelming sepsis, low cardiac output after acute MI, endocrine disease and intoxication. (Book p6)"),

(6, "oddoneout", "Hypothermia",
 "Secondary hypothermia",
 "Which of the following is NOT a secondary cause of hypothermia?",
 ["Panhypopituitarism", "Adrenal insufficiency", "Overwhelming sepsis", "Immersion in cold water"],
 3,
 "Immersion is a primary (accidental exposure) mechanism. The secondary list is failure of thermoregulation from CVA, overwhelming sepsis, low cardiac output following acute MI, endocrine disorders (hypothyroidism, panhypopituitarism, adrenal insufficiency) and intoxication with drugs or alcohol. (Book p6)"),

(6, "scenario", "Hypothermia",
 "Hypothermia in a myxoedematous patient",
 "An elderly woman is found drowsy with a temperature of 34.8\u00b0C, bradycardia and delayed reflexes; TSH is markedly raised. According to the book's classification her hypothermia is:",
 ["Secondary, from endocrine failure of thermoregulation",
  "Primary, from accidental cold exposure",
  "Not true hypothermia because her set point is intact",
  "A drug-induced hypothermia until proven otherwise"],
 0,
 "Hypothyroidism is one of the endocrine causes of secondary hypothermia - thermoregulation fails rather than the environment overcoming it. The book's secondary list also includes panhypopituitarism, adrenal insufficiency, CVA, sepsis, low cardiac output and intoxication. (Book p6)"),

(6, "recall", "Hypothermia",
 "Signs and symptoms of hypothermia",
 "Which set of findings does the book list as the signs and symptoms of hypothermia?",
 ["Altered sensorium (confusion to coma), tachypnoea, tachycardia, lethargy, shivering and pallor",
  "Altered sensorium, bradypnoea, bradycardia and absence of shivering",
  "Confusion, hypertension, flushing and sweating",
  "Coma, hyperreflexia, hyperthermia and rigors"],
 0,
 "The book lists altered sensorium (confusion to coma), tachypnoea, tachycardia, lethargy, shivering and pallor. Note that clinically severe hypothermia can cause bradycardia, but that is not the list this book gives - answer what the source says. (Book p6)"),

# ---------------------------------------------------------------- Pallor (p6)
(6, "recall", "Pallor",
 "Anaemia and pallor are not interchangeable",
 "Which statement about pallor and anaemia is correct according to the book?",
 ["Anaemia and pallor are not interchangeable terms - anaemia is only one of the causes of pallor",
  "Pallor and anaemia are interchangeable terms because pallor always indicates anaemia",
  "Pallor never occurs without anaemia",
  "Anaemia is a clinical diagnosis and pallor is its laboratory confirmation"],
 0,
 "The book is emphatic: pallor is a physical sign with many causes, and anaemia is just one of them. This is why the examiner expects you to name causes of pallor without anaemia. (Book p6)"),

(6, "match", "Pallor",
 "Sites to examine for pallor",
 "Match the instruction for examining pallor \u2014 1) Where to examine 2) Which conjunctiva 3) Which part of the tongue 4) Which surfaces \u2026 A) Lower palpebral conjunctiva B) In sunlight C) Tip and dorsum D) Palms and soles",
 ["1-B, 2-A, 3-C, 4-D", "1-A, 2-B, 3-C, 4-D", "1-B, 2-C, 3-A, 4-D", "1-D, 2-A, 3-C, 4-B"],
 0,
 "Examine in sunlight and look at the lower palpebral conjunctiva, the tip and dorsum of the tongue, the mucous membrane of the palate, the nail beds, and the palms and soles. (Book p6)"),

(6, "oddoneout", "Pallor",
 "Sites for pallor versus sites for icterus",
 "Which of the following is NOT one of the sites the book lists for examining pallor?",
 ["Lower palpebral conjunctiva", "Tip and dorsum of the tongue", "Mucous membrane of the palate", "Bulbar conjunctiva"],
 3,
 "The bulbar conjunctiva is deliberately avoided - for icterus the book says we do not check through the bulbar conjunctiva because mud or dust can get easily deposited there. It is not a pallor site either. (Book p6)"),

(6, "recall", "Pallor",
 "Pallor without anaemia",
 "Which of the following is listed as a cause of pallor without anaemia (Kundu)?",
 ["Shock and low cardiac output states", "Iron deficiency anaemia", "Thalassaemia trait", "Acute blood loss"],
 0,
 "Kundu's list of pallor without anaemia is shock, low cardiac output states, hypothyroidism and hypopituitarism. The other options are anaemias - they produce pallor precisely because haemoglobin is reduced. (Book p6)"),

(6, "match", "Pallor",
 "Aetiopathological classification of anaemia",
 "Match each arm of the aetiopathological classification of anaemia \u2014 1) Marrow production defect 2) Ineffective erythropoiesis - defective nuclear maturation 3) Ineffective erythropoiesis - cytoplasmic maturation 4) Blood loss/haemolysis \u2026 A) B12/folate deficiency and myelodysplasia B) Bone marrow disorders and decreased stimulation from inflammation or renal disease C) Defects in haeme or globin synthesis D) Loss of red cells or their destruction",
 ["1-B, 2-A, 3-C, 4-D", "1-A, 2-B, 3-C, 4-D", "1-B, 2-C, 3-A, 4-D", "1-C, 2-A, 3-B, 4-D"],
 0,
 "Marrow production defects include bone marrow disorders and decreased stimulation (inflammation, renal disease); ineffective erythropoiesis splits into defective nuclear maturation (B12/folate, myelodysplasia) and cytoplasmic maturation (haeme/globin synthesis); the last arm is blood loss and haemolysis. (Book p6)"),

# ---------------------------------------------------------------- Icterus (p6)
(6, "recall", "Icterus",
 "Where to look for icterus",
 "Icterus is best looked for in:",
 ["The sclera through the upper palpebral conjunctiva", "The sclera through the bulbar conjunctiva", "The lower palpebral conjunctiva", "The hard palate only"],
 0,
 "The site is the sclera, viewed through the upper palpebral conjunctiva. The bulbar conjunctiva is avoided because mud or dust deposits there and can be mistaken for icterus. (Book p6)"),

(6, "numeric", "Icterus",
 "Minimum bilirubin for clinical icterus",
 "The minimum serum bilirubin at which clinical icterus appears is:",
 ["2.5 mg/dL", "1.0 mg/dL", "1.5 mg/dL", "5.0 mg/dL"],
 0,
 "Icterus needs a bilirubin of at least 2.5 mg/dL to become clinically visible. This is why jaundice is a relatively late sign of hyperbilirubinaemia. (Book p6)"),

(6, "recall", "Icterus",
 "Why the sclera shows icterus early",
 "Why is icterus checked in the sclera?",
 ["The sclera is rich in elastic tissue, where bilirubin preferentially gets deposited",
  "The sclera has the highest blood flow per gram of tissue in the body",
  "The sclera lacks lymphatics, so bilirubin cannot be cleared",
  "The sclera has a thin epithelium that makes pigment visible earlier"],
 0,
 "Bilirubin preferentially deposits in elastic tissue, and the sclera is rich in it - which is also why the sclera is the classic first place that jaundice is noticed. (Book p6)"),

(6, "match", "Icterus",
 "Tints of icterus",
 "Match each tint of icterus to its severity and aetiology \u2014 1) Lemon yellow 2) Orange yellow 3) Greenish yellow \u2026 A) Severe jaundice, obstructive aetiology B) Mild jaundice, haemolytic aetiology C) Moderate jaundice, hepatocellular aetiology",
 ["1-B, 2-C, 3-A", "1-A, 2-C, 3-B", "1-C, 2-B, 3-A", "1-B, 2-A, 3-C"],
 0,
 "Lemon yellow = mild, haemolytic; orange yellow = moderate, hepatocellular; greenish yellow = severe, obstructive. The tint is a bedside clue to the underlying mechanism. (Book p6)"),

(6, "recall", "Icterus",
 "Why ask the patient to look down",
 "Why does the book ask the patient to look down while checking for icterus?",
 ["The perilimbal sclera is thinner than the posterior sclera, and looking down lets both perilimbal and posterior sclerae be compared",
  "Looking down exposes the lower palpebral conjunctiva, the richest site of bilirubin deposition",
  "Looking down relaxes the orbicularis oculi and prevents artefactual redness",
  "Looking down increases conjunctival blood flow and makes mild icterus obvious"],
 0,
 "Since the perilimbal sclera is thinner than the posterior part, mild icterus is easier to appreciate posteriorly; asking the patient to look down lines up both the perilimbal and posterior sclerae so they can be compared. (Book p6)"),

(6, "scenario", "Icterus",
 "Mild haemolytic jaundice",
 "A young man has mild jaundice, splenomegaly and anaemia with a raised reticulocyte count; his conjunctivae show a lemon-yellow tint. The book's tint for haemolytic jaundice is:",
 ["Lemon yellow", "Orange yellow", "Greenish yellow", "Greyish yellow"],
 0,
 "Lemon yellow is mild jaundice of haemolytic aetiology; orange yellow is moderate and hepatocellular; greenish yellow is severe and obstructive. (Book p6)"),
]
