# -*- coding: utf-8 -*-
"""Chapter 2 source data, Part A: Book p16-20 (Dyspnoea, Boloor Orthopnoea vs PND, Chest pain & Angina)."""

# (page, fmt, sec, point, question, options, ans, explanation)
A = [
# ---------------------------------------------------------------- Book p16
(16, "recall", "Cardinal Symptoms, Dyspnoea & NYHA Grading",
 "Five cardinal symptoms of CVS history and Dr. Hamide's substitution",
 "The book lists five cardinal symptoms in cardiovascular history — breathlessness, chest pain, palpitations, syncope and pedal oedema — and adds which specific modification by Dr. Hamide?",
 ["Replace syncope with haemoptysis as the fifth cardinal symptom",
  "Replace pedal oedema with cough as the fifth cardinal symptom",
  "Replace palpitations with easy fatigability as the fifth cardinal symptom",
  "Add right hypochondrial pain as a sixth cardinal symptom"],
 1,
 "The five cardinal symptoms are breathlessness, chest pain, palpitations, syncope and pedal oedema; Dr. Hamide's teaching replaces pedal oedema with cough in that cardinal five. (Book p16)"),

(16, "fillup", "Cardinal Symptoms, Dyspnoea & NYHA Grading",
 "Definition of dyspnoea (Dr. Hamide)",
 "Dr. Hamide defines dyspnoea as an abnormal awareness of one's own ____.",
 ["Respiration",
  "Heartbeat",
  "Effort tolerance",
  "Inspiratory reserve"],
 0,
 "Dr. Hamide uses parallel bedside definitions: dyspnoea is abnormal awareness of one's own respiration (p16), whereas palpitations are abnormal awareness of one's own heartbeat (p23). (Book p16)"),

(16, "scenario", "Cardinal Symptoms, Dyspnoea & NYHA Grading",
 "Quantifying progression of dyspnoea and associated symptoms",
 "When taking the history of progression of dyspnoea, how does the book specifically advise you to quantify the patient's functional decline, and what associated respiratory symptoms are listed at the end of the dyspnoea checklist?",
 ["Ask the exact number of pillows added per month; associated with epistaxis and stridor",
  "Ask how many minutes it takes for dyspnoea to settle upright; associated with hiccups and dysphonia",
  "Ask how many kilometres the patient could walk until fatigue initially versus now; associated with cough and wheeze with expectoration",
  "Ask the patient to grade breathlessness on a 1-to-10 scale; associated with pleuritic rub and hiccups"],
 2,
 "Under progression of dyspnoea, the parenthetical instruction is to ask how many kilometres the patient walked until fatigue initially versus now; at the end of the dyspnoea checklist, the associated symptoms are cough and wheeze with expectoration. (Book p16)"),

(16, "oddoneout", "Cardinal Symptoms, Dyspnoea & NYHA Grading",
 "Dyspnoea history checklist (What to ask)",
 "Which of the following is NOT one of the eight headings under 'Dyspnoea — What to ask' on Book p16?",
 ["Onset, progression and duration",
  "Orthopnoea and paroxysmal nocturnal dyspnoea (PND)",
  "NYHA grading, aggravating/relieving factors, and associated cough/wheeze with expectoration",
  "Post-dyspnoea polyuria and relationship to meal timing"],
 3,
 "The eight headings under Dyspnoea -> What to ask are: (a) onset, (b) progression, (c) duration, (d) orthopnoea, (e) PND, (f) NYHA, (g) aggravating and relieving factors, and (h) associated cough, wheeze with expectoration. Post-episode diuresis belongs to palpitations (p23), and meal timing belongs to chest pain (p20). (Book p16)"),

(16, "recall", "Cardinal Symptoms, Dyspnoea & NYHA Grading",
 "Harrison's mechanism of orthopnoea",
 "According to the Harrison explanation quoted on Book p16, orthopnoea results from:",
 ["Depression of the medullary respiratory centre during REM sleep with a sudden adrenergic surge",
  "Redistribution of fluid from the splanchnic circulation and lower extremities into the central circulation during recumbency, raising pulmonary capillary pressure",
  "Bronchospasm triggered by vagal tone when the patient assumes the supine posture",
  "Gravity-dependent collapse of the basal alveoli with right-to-left intrapulmonary shunting"],
 1,
 "During recumbency, fluid shifts from the splanchnic bed and lower extremities into the central circulation, increasing pulmonary capillary pressure and producing orthopnoea. (Book p16)"),

(16, "oddoneout", "Cardinal Symptoms, Dyspnoea & NYHA Grading",
 "Non-cardiac settings of orthopnoea (Harrison)",
 "Besides left heart failure, Harrison's notes that orthopnoea can also be seen in all of the following EXCEPT:",
 ["Abdominal obesity",
  "Ascites",
  "Pulmonary disease in which lung mechanics favour an upright posture",
  "Uncomplicated hepatopulmonary syndrome"],
 3,
 "Book p16 cites Harrison's three additional causes of orthopnoea: abdominal obesity, ascites, and pulmonary disease whose lung mechanics favour an upright posture. Hepatopulmonary syndrome causes platypnoea (dyspnoea upright, relieved supine), the exact opposite postural pattern. (Book p16)"),

(16, "truefalse", "Cardinal Symptoms, Dyspnoea & NYHA Grading",
 "Severity of orthopnoea vs PND and why PND is delayed",
 "Which of the following True/False statements accurately reflects the book's comparison between orthopnoea and PND on p16?",
 ["True: Orthopnoea represents a more severe stage than PND, and PND takes time after sleep because it is due to reabsorption of interstitial fluid",
  "True: PND represents a more severe stage than orthopnoea because it occurs immediately upon lying flat",
  "False: Orthopnoea is more severe than PND",
  "False: Interstitial fluid reabsorption explains why PND occurs after a delay during sleep"],
 0,
 "The notes explicitly state two rules on p16: orthopnoea is more severe than PND, and PND takes time after sleep because it is driven by interstitial fluid reabsorption. (Book p16)"),

(16, "fillup", "Cardinal Symptoms, Dyspnoea & NYHA Grading",
 "Other symptoms graded by NYHA (Dr. Hamide)",
 "According to Dr. Hamide's note on Book p16, in addition to dyspnoea, NYHA grading can also be used for ____ and ____.",
 ["Syncope and pedal oedema",
  "Chest pain and palpitations",
  "Cough and haemoptysis",
  "Fatigue and orthopnoea"],
 1,
 "Heading 2.f.i states: 'NYHA Grading (Dr. Hamide) — Can also be used for chest pain, palpitations'. (Book p16)"),

(16, "match", "Cardinal Symptoms, Dyspnoea & NYHA Grading",
 "NYHA functional classification (Dr. Hamide)",
 "Match each NYHA class in Dr. Hamide's simplified scheme (used for dyspnoea, chest pain and palpitations) to its trigger — 1) Class I 2) Class II 3) Class III 4) Class IV … A) Day-to-day activities B) Unaccustomed exercise C) At rest D) Accustomed exercise",
 ["1-D, 2-B, 3-A, 4-C",
  "1-B, 2-D, 3-A, 4-C",
  "1-B, 2-A, 3-D, 4-C",
  "1-A, 2-D, 3-B, 4-C"],
 1,
 "In Dr. Hamide's NYHA grading: Class I is symptoms with unaccustomed exercise, Class II with accustomed exercise, Class III with day-to-day activities, and Class IV at rest. (Book p16)"),

(16, "match", "Cardinal Symptoms, Dyspnoea & NYHA Grading",
 "NYHA functional classification (Dr. Vivekanandan)",
 "Match each NYHA class in Dr. Vivekanandan's formal definition to its clinical description — 1) Class I 2) Class II 3) Class III 4) Class IV … A) Less than ordinary physical activity produces dyspnoea (marked limitation; asymptomatic at rest) B) Ordinary physical activity does not produce dyspnoea (no symptoms, no limitation) C) Inability to carry out any physical activity without discomfort; symptoms at rest (severe limitation) D) Ordinary physical activity produces dyspnoea (mild symptoms, slight limitation)",
 ["1-D, 2-B, 3-A, 4-C",
  "1-B, 2-A, 3-D, 4-C",
  "1-B, 2-D, 3-A, 4-C",
  "1-B, 2-D, 3-C, 4-A"],
 2,
 "Dr. Vivekanandan's NYHA definitions: Class I = ordinary physical activity does not produce dyspnoea; Class II = ordinary activity produces dyspnoea (slight limitation); Class III = less than ordinary activity produces dyspnoea (marked limitation, comfortable at rest); Class IV = symptoms at rest / inability to carry out any physical activity without discomfort. (Book p16)"),

(16, "scenario", "Cardinal Symptoms, Dyspnoea & NYHA Grading",
 "Dr. Vivek's walking rule for NYHA Class III and the limitation of NYHA",
 "A patient has no breathlessness at rest, but ordinary level walking produces dyspnoea. According to Dr. Vivek's bedside rule on p16, how should this patient be classified, and what limitation of the NYHA system is noted right below it?",
 ["Classify as NYHA Class II; the limitation of NYHA is that it cannot be applied to patients with chest pain",
  "Classify as NYHA Class IV; the limitation of NYHA is that it ignores orthopnoea and PND",
  "Classify as NYHA Class I; the limitation of NYHA is that it requires treadmill MET testing",
  "Classify as NYHA Class III; the limitation of NYHA is that there is no universal definition of 'ordinary physical activity'"],
 3,
 "Dr. Vivek's rule states: if walking produces symptoms, consider it NYHA Class III. Immediately below, the book notes the core problem with the NYHA scale: there is no definition of 'ordinary physical activity'. (Book p16)"),

# ---------------------------------------------------------------- Book p17
(17, "numeric", "Trepopnea, Platypnea & Orthodeoxia",
 "Normal benchmark for daily physical activity",
 "To overcome the ambiguity of 'ordinary physical activity', the book advises asking everything the patient does daily and gives what benchmark as normal physical activity?",
 ["Climbing 1–2 flights of stairs",
  "Climbing 4–5 flights of stairs without stopping",
  "Walking 5 kilometres briskly on level ground",
  "Running 400 metres in under 3 minutes"],
 0,
 "Normally, climbing 1–2 flights of stairs is considered normal physical activity when benchmarking a patient's daily activity. (Book p17)"),

(17, "fillup", "Trepopnea, Platypnea & Orthodeoxia",
 "Trepopnea definition and disease association",
 "____ is dyspnoea occurring in the right or left lateral decubitus position and is classically seen in dilated cardiomyopathy.",
 ["Platypnea",
  "Trepopnea",
  "Orthodeoxia",
  "Bendopnea"],
 1,
 "Trepopnea is dyspnoea in the right or left decubitus position and is listed as being seen in dilated cardiomyopathy. (Book p17)"),

(17, "numeric", "Trepopnea, Platypnea & Orthodeoxia",
 "Definitions of platypnea and orthodeoxia",
 "Platypnea is breathlessness in the upright posture; the accompanying orthodeoxia is defined in the book as a drop in arterial oxygen saturation of at least ____ on assuming the upright position.",
 ["2%",
  "5%",
  "10%",
  "15%"],
 1,
 "Platypnea is breathlessness in the upright posture and orthodeoxia is defined parenthetically as at least a 5% drop in oxygen saturation upright. (Book p17)"),

(17, "match", "Trepopnea, Platypnea & Orthodeoxia",
 "Five causes of platypnea/orthodeoxia and their mechanisms",
 "Match each cause of platypnea/orthodeoxia on Book p17 to its stated mechanism — 1) Left atrial thrombus 2) Left atrial myxoma 3) Hepatopulmonary syndrome 4) Atrial septal defect … A) Gravity-driven prolapse of an intracardiac tumour across the mitral orifice B) Ball-valve obstruction of the mitral orifice due to gravity C) Increased right-to-left shunting while standing up (alongside pulmonary diseases with V/Q mismatch as the fifth cause) D) Reduced hepatic metabolism of nitric oxide (NO) in cirrhosis opens basal AV shunts on sitting; supine diaphragm elevation compresses the lung and reduces shunting",
 ["1-B, 2-A, 3-D, 4-C",
  "1-A, 2-B, 3-D, 4-C",
  "1-B, 2-D, 3-A, 4-C",
  "1-B, 2-A, 3-C, 4-D"],
 0,
 "The five listed causes of platypnea/orthodeoxia on p17 are: (i) LA thrombus (ball-valve due to gravity), (ii) LA myxoma (gravity), (iii) hepatopulmonary syndrome (reduced NO metabolism in cirrhotic liver -> AV shunts open on sitting; supine diaphragm pushes lung up -> reduced shunting), (iv) ASD (increased R-to-L shunting while standing up), and (v) pulmonary diseases with V/Q mismatch. (Book p17)"),

(17, "oddoneout", "Trepopnea, Platypnea & Orthodeoxia",
 "Five causes of platypnea/orthodeoxia",
 "Which of the following is NOT among the five causes of platypnea/orthodeoxia listed on Book p17?",
 ["Left atrial thrombus or left atrial myxoma acting via gravity",
  "Hepatopulmonary syndrome with nitric-oxide-mediated AV shunting",
  "Atrial septal defect with increased right-to-left shunting on standing",
  "Dilated cardiomyopathy with lateral decubitus airway compression"],
 3,
 "Dilated cardiomyopathy causes trepopnea (dyspnoea in right or left decubitus position), not platypnea/orthodeoxia. (Book p17)"),

(17, "match", "Chest Pain: Semiological Analysis",
 "Site and onset of chest pain",
 "Match each chest pain site or onset pattern on Book p17 to its clinical correlate — 1) Central chest pain building over minutes with activity 2) Retrosternal pain 3) Peak intensity reached immediately at onset 4) Onset in the morning … A) Acid reflux or myocardial infarction B) Angina / myocardial ischaemia C) Acute aortic dissection, pulmonary embolism or spontaneous pneumothorax D) Oesophageal pain",
 ["1-D, 2-B, 3-C, 4-A",
  "1-B, 2-D, 3-A, 4-C",
  "1-B, 2-D, 3-C, 4-A",
  "1-C, 2-D, 3-B, 4-A"],
 2,
 "Central pain that builds over minutes with activity and eases with rest points to angina/MI; retrosternal pain points to oesophageal pain; pain reaching peak intensity immediately points to aortic dissection, PE or spontaneous pneumothorax; morning onset is noted for acid reflux and MI. (Book p17)"),

(17, "scenario", "Chest Pain: Semiological Analysis",
 "Abdominal/epigastric pain radiating to the chest and stabbing vs heavy-pressure pain",
 "A patient complains of epigastric pain radiating to the chest. According to the 'site' and 'nature' sub-bullets on Book p17, which two aetiologies must be considered for epigastric pain radiating to the chest, and how does the note pair 'stabbing pain' versus 'steady heavy pressure'?",
 ["GI aetiology or angina for epigastric pain radiating to the chest; stabbing pain is paired with angina while steady heavy pressure is paired with MI",
  "Pericarditis or pleuritis for epigastric pain radiating to the chest; stabbing pain is paired with aortic dissection while steady heavy pressure is paired with GERD",
  "Costochondritis or pneumothorax for epigastric pain radiating to the chest; both stabbing pain and steady heavy pressure exclude ischaemia",
  "Cholecystitis alone for epigastric pain radiating to the chest; stabbing pain is paired with oesophageal spasm"],
 0,
 "Under 1.a.iii on Book p17, abdominal/epigastric pain with radiation to the chest is paired with 'GI / angina'; under 1.c.i and 1.c.ii, stabbing pain is listed with angina and steady heavy pressure with MI. (Book p17)"),

(17, "match", "Chest Pain: Semiological Analysis",
 "Nature/quality of chest pain",
 "Match each quality of chest pain to the condition the book pairs it with — 1) Steady heavy pressure 2) Pleuritic pain 3) Tearing or ripping pain 4) Spasmodic or squeezing pain … A) Pericarditis, pulmonary embolism or pulmonary parenchymal processes B) Oesophageal pain C) Myocardial infarction D) Acute aortic dissection",
 ["1-C, 2-A, 3-D, 4-B",
  "1-A, 2-C, 3-D, 4-B",
  "1-C, 2-D, 3-A, 4-B",
  "1-B, 2-A, 3-D, 4-C"],
 0,
 "Steady heavy pressure = MI; pleuritic pain = pericarditis, PE, pulmonary parenchymal processes; tearing/ripping pain = acute aortic dissection; spasmodic/squeezing = oesophageal pain. (Book p17)"),

(17, "truefalse", "Chest Pain: Semiological Analysis",
 "Burning chest pain caveat on Book p17",
 "Which of the following True/False statements accurately reflects the 'nature' of chest pain bullets on Book p17?",
 ["True: Burning chest pain excludes myocardial infarction and is diagnostic of peptic ulcer disease alone",
  "True: Burning pain is typical of acid reflux or peptic ulcer disease, however it can be seen even in myocardial infarction",
  "False: Tearing or ripping chest pain is characteristic of acute aortic dissection",
  "False: Pleuritic pain is seen in pericarditis, pulmonary embolism and pulmonary parenchymal processes"],
 1,
 "Book p17 explicitly warns under 1c.v: 'Burning pain — Acid reflux/Peptic ulcer disease however seen even in MI'. (Book p17)"),

(17, "match", "Chest Pain: Semiological Analysis",
 "Radiation of chest pain",
 "Match each radiation pattern of chest pain to its classical cause — 1) Substernal radiating to neck, jaw, shoulder and arms 2) Severe pain radiating to the back between the shoulder blades 3) Radiation to the trapezius ridge … A) Pericardial pain B) Myocardial infarction C) Acute aortic dissection",
 ["1-C, 2-B, 3-A",
  "1-B, 2-A, 3-C",
  "1-B, 2-C, 3-A",
  "1-A, 2-C, 3-B"],
 2,
 "Radiation to neck, jaw, shoulder and arms is classic for MI; radiation to the interscapular back is acute aortic dissection; radiation to the trapezius ridge (via the phrenic nerve) is classic for pericardial pain. (Book p17)"),

(17, "match", "Chest Pain: Semiological Analysis",
 "Aggravating and relieving factors of chest pain on Book p17",
 "Match each aggravating or relieving pattern on Book p17 to the condition it identifies — 1) Present at rest (vs lost at rest) 2) Alteration on change in position or movement 3) Worse supine, relieved by sitting upright and leaning forward 4) Exacerbated by alcohol, food or reclined position … A) Musculoskeletal chest pain B) Myocardial infarction (present at rest) vs angina (lost at rest) C) Gastro-oesophageal reflux disease (GERD) D) Pericarditis",
 ["1-B, 2-A, 3-D, 4-C",
  "1-A, 2-B, 3-D, 4-C",
  "1-B, 2-D, 3-A, 4-C",
  "1-B, 2-A, 3-C, 4-D"],
 0,
 "On Book p17: present at rest = MI (lost at rest = angina); alteration on change in position/movement = musculoskeletal; worse supine and relieved by sitting upright and leaning forward = pericarditis; exacerbated by alcohol, food or reclined position = GERD. (Book p17)"),

# ---------------------------------------------------------------- Book p18 (Boloor Table 3C.7, 1 of 2)
(18, "match", "Orthopnoea vs PND (Boloor Table 3C.7)",
 "Boloor Table 3C.7: Definition, timing and relief of PND vs Orthopnoea",
 "Match each feature from Boloor Table 3C.7 on Book p18 to the correct symptom column — 1) Sudden-onset dyspnoea 2–2.5 hours after sleep during REM sleep 2) Dyspnoea in recumbent posture occurring soon after lying down 3) Sits up with legs hanging down, stands up, air hunger, self-ventilates for comfort 4) Gets up, uses more pillows, sleeps in erect posture … A) PND — definition and timing B) Orthopnoea — definition and timing C) PND — method of relief D) Orthopnoea — method of relief",
 ["1-B, 2-A, 3-C, 4-D",
  "1-A, 2-B, 3-C, 4-D",
  "1-A, 2-B, 3-D, 4-C",
  "1-C, 2-D, 3-A, 4-B"],
 1,
 "In Boloor Table 3C.7 (p18), PND wakes the patient 2–2.5 hours after falling asleep during REM sleep and is relieved by sitting with legs dangling, standing and getting fresh air; orthopnoea occurs soon after lying down and is relieved by using extra pillows and sleeping erect. (Book p18)"),

(18, "scenario", "Orthopnoea vs PND (Boloor Table 3C.7)",
 "Boloor Table 3C.7: Mechanism of PND during REM sleep",
 "According to Boloor Table 3C.7 on Book p18, what sequence of events during rapid eye movement (REM) sleep precipitates an episode of paroxysmal nocturnal dyspnoea?",
 ["Shifting of >400 mL of venous blood from the lower limbs -> V/Q mismatch -> diaphragm compression -> postural diastolic dysfunction -> slow sustained rise in PCWP",
  "Nocturnal vagal surge -> bradycardia and coronary vasoconstriction -> acute mitral regurgitation -> alveolar flooding",
  "Depressed respiratory centre + sympathetic overactivity during REM -> catecholamine surge and tachycardia -> interstitial pulmonary congestion -> respiratory centre lags behind -> sudden transient rise in PCWP",
  "Upper airway collapse during REM sleep -> negative intrathoracic pressure swings -> right ventricular dilation without change in PCWP"],
 2,
 "Boloor Table 3C.7 contrasts the two mechanisms: PND is driven by a depressed respiratory centre plus REM-sleep sympathetic overactivity (catecholamine surge -> tachycardia -> interstitial pulmonary congestion -> sudden transient PCWP rise), whereas orthopnoea involves >400 mL venous shift, V/Q mismatch, diaphragm compression, postural diastolic dysfunction and a slow sustained rise in PCWP. (Book p18)"),

(18, "numeric", "Orthopnoea vs PND (Boloor Table 3C.7)",
 "Volume of venous blood shifted in orthopnoea and PCWP profile",
 "In Boloor Table 3C.7 on Book p18, orthopnoea is produced by the shifting of more than ____ of venous blood into the pulmonary circulation, producing a ____ rise in pulmonary capillary wedge pressure (PCWP).",
 ["400 mL; slow sustained",
  "150 mL; sudden transient",
  "400 mL; sudden transient",
  "1000 mL; slow sustained"],
 0,
 "Orthopnoea involves shifting of >400 mL of venous blood into the pulmonary circulation with a slow sustained rise in PCWP, whereas PND produces a sudden transient increase in PCWP. (Book p18)"),

(18, "truefalse", "Orthopnoea vs PND (Boloor Table 3C.7)",
 "Associated symptoms and oxygen saturation in PND vs Orthopnoea",
 "Which of the following True/False statements matches the 'Associated symptoms' and 'Oxygen saturation' rows of Boloor Table 3C.7 on Book p18?",
 ["True: Orthopnoea causes severe transient hypoxia while PND maintains normal oxygen saturation throughout the attack",
  "True: PND is associated with angina, perspiration, palpitations, rarely haemoptysis and transient hypoxia, whereas orthopnoea has all symptoms of CCF with normal oxygen saturation",
  "False: PND is associated with transient hypoxia",
  "False: Orthopnoea has normal oxygen saturation in Boloor Table 3C.7"],
 1,
 "In Boloor Table 3C.7, PND features angina, perspiration, palpitation, rarely haemoptysis, and transient hypoxia; orthopnoea features all the symptoms of CCF and normal oxygen saturation. (Book p18)"),

# ---------------------------------------------------------------- Book p19 (Boloor Table 3C.7, 2 of 2)
(19, "match", "Orthopnoea vs PND (Boloor Table 3C.7)",
 "Boloor Table 3C.7 (2 of 2): Differential diagnosis of PND vs Orthopnoea",
 "Match each differential diagnosis from the continuation of Boloor Table 3C.7 on Book p19 to the symptom it mimics — 1) Nightmares and panic attacks 2) Nocturnal hypoglycaemia and obstructive sleep apnoea 3) COPD and acute asthma 4) Gross obesity and gross ascites … A) PND — emotional and parasomnia mimics B) PND — metabolic and sleep-breathing mimics C) Orthopnoea — airway mimics D) Orthopnoea — mechanical and diaphragmatic mimics",
 ["1-A, 2-B, 3-C, 4-D",
  "1-C, 2-D, 3-A, 4-B",
  "1-A, 2-C, 3-B, 4-D",
  "1-B, 2-A, 3-D, 4-C"],
 0,
 "Book p19 lists the differential diagnosis row of Boloor Table 3C.7: PND is mimicked by nightmares, panic attacks, nocturnal hypoglycaemia and obstructive sleep apnoea (OSA); orthopnoea is mimicked by COPD, gross obesity, acute asthma and gross ascites. (Book p19)"),

(19, "oddoneout", "Orthopnoea vs PND (Boloor Table 3C.7)",
 "PND differential diagnosis list on Book p19",
 "Which of the following is listed under the differential diagnosis of orthopnoea rather than paroxysmal nocturnal dyspnoea on Book p19?",
 ["Nightmares",
  "Nocturnal hypoglycaemia",
  "Obstructive sleep apnoea (OSA)",
  "Gross ascites"],
 3,
 "Nightmares, panic attacks, nocturnal hypoglycaemia and OSA are the four differentials of PND; COPD, gross obesity, acute asthma and gross ascites are the four differentials of orthopnoea. (Book p19)"),

(19, "scenario", "Orthopnoea vs PND (Boloor Table 3C.7)",
 "Clinical application of Boloor Table 3C.7 differential diagnosis",
 "An insulin-treated patient wakes up suddenly 2 hours into sleep drenched in sweat and feeling acutely breathless, with a normal echocardiogram. Using the differential diagnosis row of Boloor Table 3C.7 on Book p19, which PND mimic must be excluded alongside panic attacks, nightmares and OSA?",
 ["Nocturnal hypoglycaemia",
  "Gross ascites",
  "Gross obesity",
  "Chronic obstructive pulmonary disease"],
 0,
 "Boloor Table 3C.7 (2 of 2) on Book p19 lists nocturnal hypoglycaemia alongside nightmares, panic attacks and obstructive sleep apnoea (OSA) as the four differential diagnoses of PND. (Book p19)"),

# ---------------------------------------------------------------- Book p20
(20, "numeric", "Chest Pain: Meals, Causes Table & Angina Variants",
 "Timing of post-meal GI pain, dual relief with NTG, and associated features of chest pain",
 "On Book p20, chest/epigastric pain exacerbated after a meal in peptic ulcer disease, pancreatitis or cholecystitis typically becomes symptomatic ____ after eating (alongside postprandial angina), and sublingual nitroglycerin (NTG) relieves both angina/MI and ____.",
 ["5–10 minutes; costochondritis",
  "60–90 minutes; oesophageal spasm",
  "60–90 minutes; acute pericarditis",
  "3–4 hours; gastro-oesophageal reflux"],
 1,
 "Postprandial GI pain (pancreatitis, cholecystitis, peptic ulcer disease) becomes symptomatic 60–90 minutes after eating (alongside postprandial angina), and NTG relieves both angina/MI and oesophageal spasm. (Book p20)"),

(20, "recall", "Chest Pain: Meals, Causes Table & Angina Variants",
 "Remaining items in the chest pain history checklist (f, g, h)",
 "After aggravating and relieving factors, the chest pain history checklist on Book p20 concludes with duration, number of episodes, and association with which two specific items?",
 ["Sweating/palpitations and food intake",
  "Haemoptysis and pedal oedema",
  "Nocturia and visual blurring",
  "Hoarseness and oliguria"],
 0,
 "Items 1.f, 1.g and 1.h on Book p20 are duration, number of episodes, and associated with (i) sweating, palpitations and (ii) food intake. (Book p20)"),

(20, "match", "Chest Pain: Meals, Causes Table & Angina Variants",
 "Mechanisms of non-ischaemic CVS chest pain in AS, AR and HOCM",
 "Match each valvular or myocardial lesion in the Book p20 chest-pain table to the exact mechanism of chest pain stated — 1) Aortic stenosis 2) Aortic regurgitation 3) HOCM 4) Non-valvular non-ischaemic CVS causes … A) Coronary arteries receive their blood supply in diastole, which is when regurgitation occurs B) LV hypertrophy raises myocardial oxygen demand beyond what can be met C) Same LV hypertrophy demand-supply mechanism as aortic stenosis D) Pericarditis, aortic dissection, pulmonary embolism and pulmonary hypertension",
 ["1-A, 2-B, 3-C, 4-D",
  "1-B, 2-C, 3-A, 4-D",
  "1-B, 2-A, 3-C, 4-D",
  "1-D, 2-A, 3-C, 4-B"],
 2,
 "The p20 table explains why non-CAD cardiac lesions cause angina: in AS (and HOCM), LV hypertrophy raises oxygen demand beyond supply; in AR, the coronaries fill during diastole, which is precisely when aortic regurgitation steals perfusion pressure. (Book p20)"),

(20, "oddoneout", "Chest Pain: Meals, Causes Table & Angina Variants",
 "Systemic classification of chest pain causes (p20 table)",
 "In the multi-system chest pain table on Book p20, which of the following is grouped under musculoskeletal causes?",
 ["Oesophageal spasm",
  "Pleuritis",
  "Pulmonary hypertension",
  "Cervical disk disease"],
 3,
 "The musculoskeletal column lists costochondritis, trauma and cervical disk disease; oesophageal spasm (with GERD and peptic ulcer) is under GIT, pleuritis (with pneumonia and pneumothorax) under RS, and pulmonary hypertension under non-ischaemic CVS. (Book p20)"),

(20, "numeric", "Chest Pain: Meals, Causes Table & Angina Variants",
 "Features and duration of classical anginal chest pain",
 "Classical anginal chest pain is described on Book p20 as a diffuse central anterior chest ache or dull discomfort that is unaffected by inspiration, relieved by rest and GTN, and lasts:",
 ["Less than 10 minutes",
  "Between 20 and 30 minutes",
  "Less than 60 seconds",
  "More than 30 minutes unless GTN is given"],
 0,
 "Typical anginal chest pain lasts <10 minutes, is felt diffusely in the centre of the anterior chest wall, is not affected by inspiration, and is relieved by rest and GTN. (Book p20)"),

(20, "match", "Chest Pain: Meals, Causes Table & Angina Variants",
 "Angina variants: unstable, crescendo, nocturnal/decubitus, walk-through, second-wind",
 "Match each angina variant on Book p20 to its defining clinical pattern — 1) Unstable angina 2) Crescendo angina 3) Walk-through (warm-up) angina 4) Second-wind angina … A) Increasing frequency at lower workloads, but NOT at rest B) Peripheral vasodilation during continued exercise decreases myocardial workload and relieves pain C) Abrupt onset or increasing severity, duration or frequency; may occur with minimal exertion or at rest D) Occurs on initial exertion, subsides, and then recurs on subsequent exertion",
 ["1-A, 2-C, 3-B, 4-D",
  "1-C, 2-A, 3-B, 4-D",
  "1-C, 2-A, 3-D, 4-B",
  "1-B, 2-A, 3-C, 4-D"],
 1,
 "Unstable angina may occur at rest or minimal exertion; crescendo angina increases in frequency at lower workloads but NOT at rest; walk-through/warm-up angina improves during continued exercise via peripheral vasodilation reducing workload; second-wind angina subsides after initial exertion only to recur on subsequent exertion. (Book p20)"),

(20, "truefalse", "Chest Pain: Meals, Causes Table & Angina Variants",
 "Crescendo angina vs unstable angina rest pain distinction",
 "Which of the following True/False statements accurately reflects the distinction between crescendo angina and unstable angina on Book p20?",
 ["True: Crescendo angina is defined by increasing frequency of angina at progressively lower workloads, but NOT at rest",
  "True: Crescendo angina requires chest pain at rest lasting more than 20 minutes",
  "False: Walk-through (warm-up) angina is relieved during exercise because peripheral vasodilation decreases myocardial workload",
  "False: Second-wind angina occurs on initial exertion, subsides, and recurs on subsequent exertion"],
 0,
 "Book p20 defines crescendo angina specifically as 'Increasing frequency at lower workloads, but not at rest', whereas unstable angina may occur with minimal exertion or at rest. (Book p20)"),

(20, "scenario", "Chest Pain: Meals, Causes Table & Angina Variants",
 "Nocturnal/decubitus angina and inferior wall MI autonomic features",
 "A patient experiences angina while lying flat at night (nocturnal/decubitus angina), and another presents with prolonged anginal pain accompanied by profuse sweating, nausea and bradycardia. According to Book p20, what do these two features respectively signify?",
 ["Nocturnal/decubitus angina indicates benign coronary vasospasm; autonomic symptoms are specific to anterior wall MI",
  "Nocturnal/decubitus angina indicates costochondritis; autonomic symptoms indicate walk-through angina",
  "Nocturnal/decubitus angina indicates severe coronary artery disease; prominent autonomic symptoms with prolonged pain are especially associated with inferior wall MI",
  "Both features indicate early Grade 1 stable angina with intact coronary reserve"],
 2,
 "Nocturnal/decubitus angina indicates severe coronary artery disease, and prolonged anginal pain (MI) is especially associated with autonomic symptoms in inferior wall MI. (Book p20)"),

(20, "numeric", "Chest Pain: Meals, Causes Table & Angina Variants",
 "Silent MI percentage and risk groups; angina equivalents",
 "According to Book p20, chest pain is absent in ____ of patients with myocardial infarction (silent MI) — especially in the elderly and diabetics — while dyspnoea, fatigue or syncope relieved by NTG are termed ____.",
 ["10%; crescendo angina",
  "50%; walk-through angina",
  "30%; second-wind angina",
  "30%; angina equivalents"],
 3,
 "Silent MI accounts for 30% of MIs (especially in the elderly and patients with DM), and non-pain symptoms of myocardial ischaemia such as dyspnoea, fatigue and syncope relieved by NTG are called angina equivalents. (Book p20)"),
]
