# -*- coding: utf-8 -*-
"""Chapter 2 source data, Part B: Book p21-25 (CCS Angina, Syncope, Palpitations, Oedema Box 6.8, Negative/Drug History, Pulse Basics)."""

# (page, fmt, sec, point, question, options, ans, explanation)
B = [
# ---------------------------------------------------------------- Book p21
(21, "match", "CCS Angina Grading & Syncope vs Seizure",
 "Canadian Cardiovascular Society (CCS) grading of stable angina",
 "Match each Canadian Cardiovascular Society (CCS) grade of stable angina on Book p21 to its exact definition — 1) Grade 1 2) Grade 2 3) Grade 3 4) Grade 4 … A) Marked limitation of ordinary activity: walking 1–2 blocks on the level or climbing <1 flight of stairs B) Angina with strenuous exercise only C) Inability to carry out any physical activity without discomfort; may be present at rest D) Slight limitation of ordinary activity",
 ["1-B, 2-D, 3-A, 4-C",
  "1-D, 2-B, 3-A, 4-C",
  "1-B, 2-A, 3-D, 4-C",
  "1-B, 2-D, 3-C, 4-A"],
 0,
 "CCS grading of stable angina: Grade 1 = strenuous exercise only; Grade 2 = slight limitation of ordinary activity; Grade 3 = marked limitation (walking 1–2 blocks on the level or climbing <1 flight of stairs); Grade 4 = inability to carry out any physical activity without discomfort, may be present at rest. (Book p21)"),

(21, "numeric", "CCS Angina Grading & Syncope vs Seizure",
 "Exact walking and stair thresholds for CCS Grade 3 stable angina",
 "In the Canadian Cardiovascular Society (CCS) grading of stable angina on Book p21, Grade 3 (marked limitation of ordinary activity) is defined by angina when walking ____ on the level or climbing ____.",
 ["1–2 blocks; <1 flight of stairs",
  "3–4 blocks; 1–2 flights of stairs",
  "50 metres; >2 flights of stairs",
  "<1 block; any single step at rest"],
 0,
 "CCS Grade 3 is explicitly defined on Book p21 as marked limitation of ordinary activity: walking 1–2 blocks on the level or climbing <1 flight of stairs. (Book p21)"),

(21, "scenario", "CCS Angina Grading & Syncope vs Seizure",
 "Exertional syncope, fixed cardiac output lesions and syncope history checklist",
 "While taking a history of syncope (Book p21), you ask about onset, duration, total vs partial loss of consciousness, recovery time, orientation before and after the episode, associated fits or bowel/bladder symptoms, and whether the episode is exertional. Exertional syncope points specifically toward:",
 ["Regurgitant volume-overload lesions such as chronic mitral regurgitation and tricuspid regurgitation",
  "Fixed cardiac output lesions such as aortic stenosis (AS) and hypertrophic obstructive cardiomyopathy (HOCM)",
  "Vasovagal neurocardiogenic syncope triggered by peripheral venodilation",
  "Left-to-right intracardiac shunts such as uncomplicated ostium secundum ASD"],
 1,
 "Under Syncope -> What to ask, 'Exertional?' is specifically annotated with fixed-output lesions like AS and HOCM. (Book p21)"),

(21, "match", "CCS Angina Grading & Syncope vs Seizure",
 "Vasovagal syncope vs seizure table (Part 1: trigger, prodrome, duration, convulsion)",
 "Match each row from the 'Seizure vs syncope' table on Book p21 to the correct pairing — 1) Trigger 2) Prodrome 3) Duration of unconsciousness 4) Convulsion … A) <60 seconds in vasovagal syncope vs 1–2 minutes in seizure B) Illness, pain or emotion in vasovagal syncope vs often none (or sleep deprivation, alcohol, drugs) in seizure C) Brief myoclonic jerks in vasovagal syncope vs usually 1–2 minutes tonic-clonic in seizure D) Feeling faint, tinnitus, nausea, dimming of vision in vasovagal syncope vs not always present in seizure",
 ["1-D, 2-B, 3-A, 4-C",
  "1-B, 2-D, 3-C, 4-A",
  "1-B, 2-D, 3-A, 4-C",
  "1-A, 2-D, 3-B, 4-C"],
 2,
 "The p21 comparison table contrasts vasovagal syncope with seizure across trigger (illness/pain/emotion vs often none or sleep deprivation/alcohol/drugs), prodrome (faintness/tinnitus/nausea/dimming of vision vs not always present), duration of unconsciousness (<60 s vs 1–2 min) and convulsion (brief myoclonic jerks vs 1–2 min tonic-clonic). (Book p21)"),

(21, "scenario", "CCS Angina Grading & Syncope vs Seizure",
 "Vasovagal syncope vs seizure table (Part 2: colour, lateral tongue biting, recovery)",
 "A patient collapses briefly after venepuncture, looks pale/grey, bites the tip (not the lateral border) of the tongue, and recovers rapidly without post-event confusion. How does the Book p21 table contrast these three signs with a true seizure?",
 ["In seizure the colour is red/blue (may be pale), lateral tongue biting is common, and recovery is gradual over 30 minutes with confusion and amnesia",
  "In seizure the colour is always cherry-red, tongue biting is absent, and recovery occurs within 60 seconds without amnesia",
  "In seizure lateral tongue biting is very rare while tip biting is pathognomonic, and recovery takes <5 minutes",
  "In seizure pallor is obligatory, myoclonic jerks last <10 seconds, and orientation returns immediately"],
 0,
 "In vasovagal syncope: colour is pale/grey, lateral tongue biting is very rare (may bite tip), and recovery is rapid with no confusion. In seizure: colour is red/blue (may be pale), lateral tongue biting is common, and recovery is gradual over 30 minutes with confusion and amnesia. (Book p21)"),

(21, "truefalse", "CCS Angina Grading & Syncope vs Seizure",
 "Lateral vs tip tongue biting in vasovagal syncope vs seizure",
 "Which of the following True/False statements accurately states the tongue-biting rule in the Book p21 'Seizure vs syncope' table?",
 ["True: Lateral tongue biting is common in vasovagal syncope and very rare in seizure",
  "True: Lateral tongue biting is very rare in vasovagal syncope (where the patient may bite the tip) and common in seizure",
  "False: Lateral tongue biting is common in seizure",
  "False: In vasovagal syncope the patient may bite the tip of the tongue"],
 1,
 "The 'Lateral tongue biting' row on Book p21 reads: Vasovagal Syncope = 'Very rare (may bite tip)'; Seizure = 'Common'. (Book p21)"),

(21, "oddoneout", "CCS Angina Grading & Syncope vs Seizure",
 "Differential diagnosis list for syncope on Book p21",
 "Which of the following is NOT listed under the differential diagnosis (Ddx) of syncope at the bottom of Book p21?",
 ["Seizure and TIA",
  "Hypoglycaemia",
  "Cataplexy? and postconcussive syndrome?",
  "Narcoleptic sleep paralysis"],
 3,
 "The five items listed under 3. Ddx on Book p21 are seizure, TIA, hypoglycaemia, cataplexy? and postconcussive syndrome?. (Book p21)"),

# ---------------------------------------------------------------- Book p22
(22, "numeric", "Syncope Classification: Pathophysiology & Causes",
 "Definition of orthostatic syncope in the p22 table",
 "In the syncope classification table on Book p22, orthostatic syncope is defined by a decrease in systolic BP by more than ____ or diastolic BP by more than ____ within ____ of standing from the sitting position.",
 ["10 mmHg; 5 mmHg; 1 minute",
  "20 mmHg; 10 mmHg; 3 minutes",
  "30 mmHg; 15 mmHg; 5 minutes",
  "20 mmHg; 20 mmHg; 10 minutes"],
 1,
 "The Orthostatic column of the p22 table specifies: decrease in SBP by >20 mmHg or DBP by >10 mmHg within 3 minutes of standing from the sitting position. (Book p22)"),

(22, "match", "Syncope Classification: Pathophysiology & Causes",
 "Pathophysiology and causes across the syncope table on Book p22",
 "Match each type of syncope in the Book p22 table to its listed pathophysiology or causes — 1) Vasovagal syncope 2) Orthostatic syncope 3) Post-tussive syncope 4) Hypovolaemic syncope … A) Violent coughing raises intrathoracic pressure and decreases venous return (caused by lung disease) B) Always preceded by warning symptoms (nausea, weakness, blurred vision, headache); triggered by fear, emotional stress, anxiety or anaemia C) Haemorrhage and fluid loss D) Antihypertensive drugs, diabetic autonomic neuropathy and anaemia",
 ["1-B, 2-D, 3-A, 4-C",
  "1-D, 2-B, 3-A, 4-C",
  "1-B, 2-D, 3-C, 4-A",
  "1-A, 2-D, 3-B, 4-C"],
 0,
 "The p22 table maps each column: Vasovagal (warning nausea/weakness/blurred vision/headache; fear, emotional stress, anxiety, anaemia), Orthostatic (antihypertensives, diabetic autonomic neuropathy, anaemia), Post-tussive (violent coughing -> raised intrathoracic pressure -> decreased venous return in lung disease), Hypovolaemic (haemorrhage, fluid loss), plus Micturition syncope as the sixth column. (Book p22)"),

(22, "match", "Syncope Classification: Pathophysiology & Causes",
 "CVS electrical vs mechanical causes of syncope",
 "Match each cardiovascular syncope subgroup in the Book p22 table to its listed causes — 1) Electrical anomalies 2) Left-sided outflow mechanical causes 3) Right-sided / pulmonary mechanical causes 4) Intracardiac mass mechanical cause … A) Left atrial myxoma (postural syncope) B) Bradycardia, heart block, ventricular or supraventricular tachycardias C) Aortic stenosis and HOCM D) Pulmonary stenosis, Tetralogy of Fallot (TOF) and pulmonary embolism",
 ["1-C, 2-B, 3-D, 4-A",
  "1-B, 2-D, 3-C, 4-A",
  "1-B, 2-C, 3-D, 4-A",
  "1-B, 2-C, 3-A, 4-D"],
 2,
 "Under CVS causes of syncope on p22: Electrical anomalies = bradycardia, heart block, VT or SVT; Mechanical causes = AS, HOCM, pulmonary stenosis, TOF, pulmonary embolism, and LA myxoma (specifically annotated as postural syncope). (Book p22)"),

(22, "scenario", "Syncope Classification: Pathophysiology & Causes",
 "Post-tussive syncope mechanism and LA myxoma postural syncope",
 "A patient with chronic lung disease loses consciousness after a paroxysm of violent coughing, while another patient experiences syncope triggered specifically by changes in posture due to an intracardiac mass. According to the Book p22 table:",
 ["Violent coughing raises intrathoracic pressure and decreases venous return (post-tussive syncope); left atrial myxoma causes postural mechanical syncope",
  "Violent coughing causes cerebral vasoconstriction via hypocapnia; right ventricular myxoma is the only listed mechanical cause of syncope",
  "Violent coughing triggers complete heart block; aortic stenosis causes syncope only on recumbency",
  "Both episodes represent orthostatic syncope from diabetic autonomic neuropathy"],
 0,
 "In the p22 table, Post-tussive syncope (caused by lung disease) has the pathophysiology 'Violent coughing -> decreased venous return due to raised intrathoracic pressure', and under CVS mechanical causes, LA myxoma is specifically annotated '(postural syncope)'. (Book p22)"),

(22, "recall", "Syncope Classification: Pathophysiology & Causes",
 "Shared systemic cause across Vasovagal and Orthostatic syncope columns and the 6th column on p22",
 "In the six-column syncope table on Book p22, which non-cardiac condition is explicitly listed as a cause under BOTH Vasovagal and Orthostatic syncope, and what is the sixth syncope column header after Post-Tussive?",
 ["Hypoglycaemia; Carotid sinus syncope",
  "Anaemia; Micturition",
  "Dehydration; Defaecation",
  "Thyrotoxicosis; Deglutition"],
 1,
 "Anaemia appears under the 'Cause' row of both Vasovagal syncope (fear, sudden emotional stress, anxiety, anaemia) and Orthostatic syncope (antihypertensive drugs, diabetic autonomic neuropathy, anaemia), and the sixth column header of the table is Micturition. (Book p22)"),

# ---------------------------------------------------------------- Book p23
(23, "fillup", "Palpitations, Pedal Oedema (Box 6.8) & Cough",
 "Definition of palpitations (Dr. Hamide) and post-palpitation symptom",
 "Dr. Hamide defines palpitations as an abnormal awareness of one's own ____, and the history checklist specifically asks about post-palpitation ____.",
 ["Heartbeat; diuresis",
  "Pulse pressure; syncope",
  "Heartbeat; orthopnoea",
  "Cardiac output; diaphoresis"],
 0,
 "Palpitations are defined as abnormal awareness of one's own heartbeat (Dr. Hamide), and item 2g in the checklist asks about post-palpitation diuresis (alongside regular/irregular, duration, paroxysmal or not, and NYHA class). (Book p23)"),

(23, "match", "Palpitations, Pedal Oedema (Box 6.8) & Cough",
 "Semiology of palpitations: exertional vs rest, fast vs slow vs forceful",
 "Match each palpitation characteristic on Book p23 to the underlying cardiac mechanism — 1) Exertional palpitations 2) Palpitations at rest 3) Fast palpitations 4) Slow or forceful palpitations … A) Arrhythmia (mainly atrial fibrillation) B) Regurgitant valvular lesion C) Slow = volume overload; increased force = ventricular hypertrophy D) Arrhythmia",
 ["1-D, 2-B, 3-A, 4-C",
  "1-B, 2-D, 3-A, 4-C",
  "1-B, 2-A, 3-D, 4-C",
  "1-C, 2-D, 3-A, 4-B"],
 1,
 "Book p23 correlates palpitation features with mechanism: exertional = regurgitant lesion; at rest = arrhythmia; fast = arrhythmia (mainly AF); slow = volume overload; increased force = hypertrophy. (Book p23)"),

(23, "truefalse", "Palpitations, Pedal Oedema (Box 6.8) & Cough",
 "Timing of dyspnoea vs palpitations in AR and MR",
 "Which of the following True/False statements accurately states the note on Book p23 comparing aortic regurgitation (AR) and mitral regurgitation (MR)?",
 ["True: Both AR and MR present with palpitations, but in AR dyspnoea occurs much later than palpitations, whereas in MR they can occur at almost the same time",
  "True: In AR dyspnoea precedes palpitations by several years, whereas in MR palpitations occur decades before dyspnoea",
  "False: In AR, dyspnoea occurs much later than palpitations",
  "False: Both AR and MR have palpitations as a presenting complaint"],
 0,
 "In AR, dyspnoea occurs much later than the palpitations, whereas in MR, dyspnoea and palpitations can occur at almost the same time. (Book p23)"),

(23, "recall", "Palpitations, Pedal Oedema (Box 6.8) & Cough",
 "Pedal oedema and cough history checklists on Book p23",
 "Under 'Pedal oedema — What to ask' on Book p23, which three points are listed?",
 ["Onset and progression from which location to which; Unilateral vs Bilateral; Relieving factors",
  "Pitting time in seconds; Response to spironolactone; Abdominal girth measurement",
  "Presence of varicose veins; Calf tenderness; Skin hyperpigmentation",
  "Morning facial puffiness; Frothy urine; Salt intake in grams per day"],
 0,
 "Under Pedal oedema -> 1. What to ask on Book p23, the three bullets are: (a) Onset, progression from which location to which, (b) Unilateral vs Bilateral, and (c) Relieving factors. (Book p23)"),

(23, "match", "Palpitations, Pedal Oedema (Box 6.8) & Cough",
 "Box 6.8 on Book p23: Causes of unilateral and bilateral leg oedema",
 "Match each category from Box 6.8 ('Causes of unilateral and bilateral leg oedema') embedded on Book p23 to its exact examples — 1) Unilateral leg oedema 2) Bilateral: drugs 3) Bilateral: nutritional and congenital/pubertal 4) Bilateral: venous, lymphatic and systemic … A) NSAIDs, nifedipine, amlodipine and fludrocortisone B) DVT, soft-tissue infection, trauma, immobility (e.g. hemiplegia) and lymphoedema C) Thiamine (vitamin B1) deficiency (wet beriberi), kwashiorkor and Milroy's disease (pubertal, females > males) D) Heart failure, chronic venous insufficiency, nephrotic syndrome, cirrhosis, pelvic tumour/filariasis and IVC obstruction",
 ["1-A, 2-B, 3-C, 4-D",
  "1-B, 2-C, 3-A, 4-D",
  "1-B, 2-A, 3-C, 4-D",
  "1-D, 2-A, 3-C, 4-B"],
 2,
 "Box 6.8 on Book p23 supplies the full drug list (NSAIDs, nifedipine, amlodipine, fludrocortisone) and adds IVC obstruction, wet beriberi (thiamine/vitamin B1 deficiency), kwashiorkor and pelvic tumour to the bilateral oedema causes alongside unilateral DVT, infection, trauma, immobility and lymphoedema. (Book p23)"),

(23, "oddoneout", "Palpitations, Pedal Oedema (Box 6.8) & Cough",
 "Drugs causing bilateral leg oedema in Box 6.8 on Book p23",
 "Which of the following drugs is NOT among the four drug examples of bilateral leg oedema listed in Box 6.8 on Book p23?",
 ["NSAIDs",
  "Nifedipine and amlodipine",
  "Fludrocortisone",
  "Spironolactone"],
 3,
 "Box 6.8 lists 'Drugs, e.g. NSAIDs, nifedipine, amlodipine, fludrocortisone' under bilateral leg oedema (resolving the p14 stub on drugs causing oedema). Spironolactone is an aldosterone antagonist diuretic used to treat oedema, not a cause. (Book p23)"),

(23, "scenario", "Palpitations, Pedal Oedema (Box 6.8) & Cough",
 "Cough history and distinguishing haemoptysis from haematemesis",
 "When a cardiac patient reports blood on coughing, which two specific questions does Book p23 instruct you to ask under 'Blood on coughing'?",
 ["Whether there is any melena and whether the bleeding is associated with food",
  "Whether the blood is mixed with frothy pink sputum and whether it occurs only in winter",
  "Whether the patient takes warfarin at 4 pm and whether epistaxis preceded the cough",
  "Whether the cough is relieved by leaning forward and whether the sputum has a foul odour"],
 0,
 "Under Cough -> 1e. Blood on coughing, the sub-bullet specifically asks: 'Any melena? Associated w food?' — alongside duration, mode of onset, quantity, colour/odour, and postural/relieving factors. (Book p23)"),

# ---------------------------------------------------------------- Book p24
(24, "match", "Negative, Past, Personal & Drug History",
 "Negative history: symptoms of RHF, RF, left-sided disease and congenital heart disease",
 "Match each negative-history heading on Book p24 to the symptoms you must ask for — 1) Symptoms of right heart failure (RHF) 2) Symptoms of rheumatic fever (RF) 3) Symptoms of left-sided disease 4) Symptoms of congenital heart disease … A) Voice change, dysphagia and oliguria B) Pedal oedema, abdominal distension, dyspepsia, right hypochondrial pain and facial puffiness C) Cyanotic episodes and squatting D) Fever with joint pain, sore throat, involuntary movements and skin rash/nodules",
 ["1-D, 2-B, 3-A, 4-C",
  "1-B, 2-D, 3-A, 4-C",
  "1-B, 2-A, 3-D, 4-C",
  "1-B, 2-D, 3-C, 4-A"],
 1,
 "Book p24 groups negative history into RHF (pedal oedema, abdominal distension, dyspepsia, RHC pain, facial puffiness), RF (fever with joint pain, sore throat, involuntary movements, skin rash/nodules), Left-sided disease (voice change, dysphagia, oliguria), and Congenital disease (cyanotic episodes, squatting). (Book p24)"),

(24, "oddoneout", "Negative, Past, Personal & Drug History",
 "Symptoms of left-sided vs right-sided disease in negative history",
 "On Book p24, which of the following is listed under 'Symptoms of Left sided disease' rather than 'Symptoms of RHF'?",
 ["Pedal oedema and abdominal distension",
  "Dyspepsia and right hypochondrial pain",
  "Puffiness of face",
  "Voice change, dysphagia and oliguria"],
 3,
 "Under Negative History on Book p24: RHF symptoms are pedal oedema, abdominal distension, dyspepsia, right hypochondrial pain and puffiness of face; Left-sided disease symptoms are voice change (LA compression of recurrent laryngeal nerve), dysphagia (LA compression of oesophagus) and oliguria (low forward renal perfusion). (Book p24)"),

(24, "scenario", "Negative, Past, Personal & Drug History",
 "Negative history: PHT symptoms, IE complications and causes of fever in RHD",
 "A patient with known rheumatic valvular disease develops fever and worsening breathlessness. According to Book p24, which three causes of fever must be considered, and what term is given to haemoptysis in pulmonary hypertension?",
 ["Drug fever from digoxin, pulmonary embolism, and Dressler's syndrome; haemoptysis in PHT is termed winter bronchitis",
  "Viral myocarditis, thyroid storm, and left atrial myxoma; haemoptysis in PHT is termed Ortner's syndrome",
  "Reactivation of RHD, intercurrent infection (pneumonia, UTI altering haemodynamics), and chronic SABE; haemoptysis in PHT is termed pulmonary apoplexy",
  "Tuberculosis, malaria, and SLE flare; haemoptysis in PHT is termed Eisenmenger haemorrhage"],
 2,
 "Book p24 lists PHT symptoms (recurrent respiratory infection, syncope, haemoptysis [pulmonary apoplexy], chest pain), IE symptoms/complications (fever, stroke/TIA, haematuria), and the three causes of fever in a cardiac patient: reactivation of RHD, pneumonia/UTI (which alter haemodynamics and worsen breathlessness), and chronic SABE. (Book p24)"),

(24, "recall", "Negative, Past, Personal & Drug History",
 "Past history of cardiac intervention: complication of BMV in MS and personal/family history",
 "In the past, personal and family history section on Book p24, balloon mitral valvotomy (BMV) for mitral stenosis is specifically noted as a cause of ____, suspected infective endocarditis requires asking about ____, and family history specifically queries comorbidities and ____.",
 ["Aortic regurgitation (AR); raw milk consumption; cardiomyopathies",
  "Tricuspid stenosis (TS); high-altitude travel; channelopathies",
  "Constrictive pericarditis; silica exposure; dyslipidaemia",
  "Mitral regurgitation (MR); intravenous drug abuse; connective tissue disorder (CTD)"],
 3,
 "Under Past history, heart surgeries are checked both as a risk for IE and because BMV in MS can lead to MR; under Personal history, IV drug abuse is specifically asked when suspecting IE; under Family history, the notes query 'Comorbidities, CTD?'. (Book p24)"),

(24, "management", "Negative, Past, Personal & Drug History",
 "Dosing schedules and timing rationale for digoxin, diuretics and nitroglycerin",
 "Why does the treatment history section on Book p24 specify giving diuretics and nitroglycerin tablets at 8 am and 4 pm rather than at night, and what is the weekly schedule for digoxin?",
 ["Diuretics cause nocturia and nitroglycerin causes nocturnal hypotension if given at night; digoxin is taken 5 days a week with 2 days off",
  "Both drugs lose bioavailability in the supine posture; digoxin is taken every alternate day (3 days a week)",
  "Diuretics cause nocturnal hypokalaemia and nitroglycerin causes morning headache; digoxin is taken 6 days a week with 1 day off",
  "Night dosing of diuretics precipitates PND and nitroglycerin causes reflex bradycardia; digoxin is taken daily without interruption"],
 0,
 "Digoxin is given as 5 days of intake with 2 days off; diuretics and nitroglycerin are given at 8 am and 4 pm and avoided at night because they cause nocturia and nocturnal hypotension respectively. (Book p24)"),

# ---------------------------------------------------------------- Book p25
(25, "numeric", "History Summary & Arterial Pulse: Rate, Rhythm, Volume & Delay",
 "Timing of warfarin and benzathine penicillin prophylaxis",
 "At the top of Book p25, warfarin is scheduled at ____ daily, and prophylactic penicillin injection is given once every ____.",
 ["8 am; 28 days",
  "4 pm; 21 days",
  "9 pm; 14 days",
  "4 pm; 30 days"],
 1,
 "Book p25 completes the drug schedule list: warfarin at 4 pm daily, and benzathine penicillin injection once every 21 days. (Book p25)"),

(25, "fillup", "History Summary & Arterial Pulse: Rate, Rhythm, Volume & Delay",
 "Summary and interpretation template at the end of CVS history",
 "In the history summary template on Book p25: 'The disease is probably ____ (cong/acq). Probably a ____ (recurrent) heart disease involving the ____ (lt/rt/both) side(s), the probable valve(s) involved are ____. The patient shows the signs/symptoms of ____ (LVF/RVF/CCF).'",
 ["Ischaemic or non-ischaemic; acute; systolic or diastolic; coronary artery; NYHA Class I to IV",
  "Infective or autoimmune; chronic; endocardial or pericardial; chamber(s); pulmonary oedema",
  "Congenital or acquired; rheumatic/recurrent; left, right or both; specific valve(s); LVF, RVF or CCF",
  "Valvular or myocardial; progressive; arterial or venous; semilunar valve(s); shock"],
 2,
 "The five blanks in the history summary sentence on Book p25 are: congenital/acquired, recurrent (rheumatic) heart disease, left/right/both sides, probable valve(s) involved, and signs/symptoms of LVF/RVF/CCF. (Book p25)"),

(25, "recall", "History Summary & Arterial Pulse: Rate, Rhythm, Volume & Delay",
 "Definition of the arterial pulse and inappropriate bradycardia",
 "How does Book p25 define the arterial pulse, and what term does it use when a high temperature fails to produce the expected tachycardia?",
 ["Waveform felt by the finger produced by cardiac systole that traverses the arterial tree in a peripheral direction; inappropriate bradycardia",
  "Column of blood ejected per stroke from the left ventricle into the radial artery; pulsus parvus",
  "Difference between systolic and diastolic lateral pressure in a peripheral artery; apex-pulse deficit",
  "Oscillation of the arterial wall during diastolic recoil after aortic valve closure; dicrotic bradycardia"],
 0,
 "With a high temperature one expects tachycardia — if absent, p25 calls it inappropriate bradycardia. The pulse is defined as the waveform felt by the finger that is produced by cardiac systole which traverses the arterial tree in a peripheral direction. (Book p25)"),

(25, "numeric", "History Summary & Arterial Pulse: Rate, Rhythm, Volume & Delay",
 "Normal pulse rate, artery used to assess pulse volume, and normal pulse pressure",
 "Under 'Pulse — What to check' on Book p25, the normal pulse rate is ____, pulse volume is assessed clinically at the ____ artery, and the normal pulse pressure used alongside it is ____.",
 ["50–90/min; radial; 20–40 mmHg",
  "60–100/min; carotid; 30–60 mmHg",
  "60–100/min; brachial; 40–80 mmHg",
  "70–110/min; femoral; 30–50 mmHg"],
 1,
 "Book p25 specifies: Rate = 60–100; Volume is checked at the carotid artery and also using pulse pressure (normal 30–60 mmHg). (Book p25)"),

(25, "match", "History Summary & Arterial Pulse: Rate, Rhythm, Volume & Delay",
 "Classification of pulse rhythm and pulse volume causes",
 "Match each pulse rhythm or volume category on Book p25 to its listed causes — 1) Regularly regular tachycardia 2) Regularly irregular rhythm 3) High-volume pulse 4) Low-volume pulse … A) Bigeminy or trigeminy (while atrial fibrillation is irregularly irregular) B) Sinus tachycardia, ventricular tachycardia, atrial flutter and paroxysmal atrial tachycardia C) Heart failure, shock, mitral stenosis and aortic stenosis D) Fever, anaemia, thyrotoxicosis, mitral regurgitation and VSD",
 ["1-A, 2-B, 3-D, 4-C",
  "1-B, 2-A, 3-D, 4-C",
  "1-B, 2-A, 3-C, 4-D",
  "1-D, 2-A, 3-B, 4-C"],
 1,
 "Book p25 classifies rhythm into regularly regular tachycardia (sinus tachycardia, VT, atrial flutter, PAT), regularly irregular (bigeminy, trigeminy) and irregularly irregular (AF); volume is high in fever, anaemia, thyrotoxicosis, MR and VSD, and low in heart failure, shock, MS and AS. (Book p25)"),

(25, "oddoneout", "History Summary & Arterial Pulse: Rate, Rhythm, Volume & Delay",
 "High-volume vs low-volume pulse causes on Book p25",
 "Which of the following conditions is listed on Book p25 as a cause of a HIGH-volume pulse rather than a low-volume pulse?",
 ["Heart failure",
  "Shock",
  "Mitral stenosis and aortic stenosis",
  "Mitral regurgitation and VSD"],
 3,
 "High-volume pulse causes on Book p25 are fever, anaemia, thyrotoxicosis, MR and VSD; low-volume pulse causes are heart failure, shock, MS and AS. (Book p25)"),

(25, "scenario", "History Summary & Arterial Pulse: Rate, Rhythm, Volume & Delay",
 "Normal femoral-radial timing, radiofemoral delay, and mechanism of apex-pulse deficit",
 "In a patient with atrial fibrillation, the apical heart rate exceeds the radial pulse rate, while in a patient with coarctation, the radial pulse precedes the femoral pulse. Which statement accurately states the physiological timing and mechanism on Book p25?",
 ["Normally the radial and femoral pulses arrive at the exact same millisecond; apex-pulse deficit is caused by retrograde blood flow into the left atrium during systole",
  "Normally the radial pulse precedes the femoral pulse by 50 ms; apex-pulse deficit is caused by intermittent AV nodal block",
  "Normally the femoral pulse precedes the radial pulse by a few milliseconds (reversal is radiofemoral delay); apex-pulse deficit occurs because variable diastolic durations in AF produce weak ventricular contractions that fail to generate a peripheral pulse",
  "Normally the femoral pulse lags behind the radial pulse; apex-pulse deficit occurs only in ventricular bigeminy"],
 2,
 "Normally the femoral pulse precedes the radial pulse by a few milliseconds; if the radial precedes the femoral it is called radiofemoral delay. In AF, variable durations of diastole produce some strong and some weak ventricular contractions — weak contractions cause a cardiac contraction at the apex but are not strong enough to produce a peripheral pulse (apex-pulse deficit). (Book p25)"),
]
