# -*- coding: utf-8 -*-
"""Chapter 2 source data, Part C: Book p26-30 (Pulse Waveforms, Pulsus Paradoxus, Pulsus Alternans, CVS General Survey, RF/IE/AR Signs)."""

# (page, fmt, sec, point, question, options, ans, explanation)
C = [
# ---------------------------------------------------------------- Book p26
(26, "scenario", "History Summary & Arterial Pulse: Rate, Rhythm, Volume & Delay",
 "Differentiating ventricular tachycardia (VT) from paroxysmal atrial tachycardia (PAT)",
 "Two patients present with a regularly regular tachycardia. Patient 1 is unchanged by vagal manoeuvres and has cannon A waves with variable S1 intensity; Patient 2 terminates abruptly after carotid sinus massage and reports a pounding sensation in the neck. According to Book p26:",
 ["Patient 1 has paroxysmal atrial tachycardia; Patient 2 has ventricular tachycardia with retrograde 1:1 conduction",
  "Patient 1 has ventricular tachycardia (AV dissociation produces cannon A waves and variable S1); Patient 2 has paroxysmal atrial tachycardia (simultaneous carotid pulsations and cannon A waves cause neck pounding)",
  "Patient 1 has atrial flutter with fixed 2:1 block; Patient 2 has sinus tachycardia",
  "Both patients have ventricular tachycardia, since cannon A waves never occur in supraventricular arrhythmias"],
 1,
 "Book p26 distinguishes VT from PAT: VT is usually unchanged by vagal manoeuvres and shows signs of AV dissociation (cannon A waves and variable intensity of S1), whereas PAT resolves abruptly after Valsalva or carotid artery massage and is typically associated with a pounding feeling in the neck due to simultaneous carotid pulsations and cannon A waves (followed by checking vessel wall thickening). (Book p26)"),

(26, "recall", "Types of Pulse: Normal, Bisferiens, Bifid, Dicrotic, Anacrotic & Corrigan",
 "Normal arterial pulse waveform and limbs (p26 text and diagram)",
 "In the text and accompanying arterial pulse diagram on Book p26, the normal pulse consists of which components?",
 ["An upstroke (anacrotic limb) in systole and a downstroke (dicrotic limb) separated by a dicrotic notch that corresponds to S2 (closure of the semilunar valves)",
  "A dicrotic upstroke in systole and an anacrotic downstroke in diastole separated by a notch corresponding to S1",
  "Two equal systolic peaks separated by a mid-systolic Bernoulli dip before S2",
  "A systolic wave and a diastolic wave separated by an opening snap of the atrioventricular valves"],
 0,
 "The normal pulse has a systolic wave (ascending anacrotic limb) and diastolic wave (descending dicrotic limb) separated by a dicrotic notch corresponding to S2 (closure of the semilunar valves). (Book p26)"),

(26, "scenario", "Types of Pulse: Normal, Bisferiens, Bifid, Dicrotic, Anacrotic & Corrigan",
 "Pulsus bisferiens: definition and Bernoulli mechanism",
 "A patient has two palpable systolic peaks of equal strength in the carotid pulse (pulsus bisferiens). How does Book p26 explain the mid-systolic dip between the two peaks via the Bernoulli effect?",
 ["Premature closure of the aortic valve in mid-systole halts forward flow until a second atrial contraction reopens the valve",
  "Reflected pressure waves from the femoral bifurcation arrive in early diastole after semilunar valve closure",
  "Ejection of a rapid jet of blood through the aortic valve creates high flow velocity, and since lateral pressure is inversely proportional to flow velocity through a tube, there is a sudden decrease in lateral pressure on the inner wall of the ascending aorta",
  "High peripheral vascular resistance coupled with low cardiac output accentuates the diastolic recoil wave"],
 2,
 "Pulsus bisferiens has two palpable systolic peaks of equal strength. When a rapid jet of blood is ejected through the aortic valve, the Bernoulli effect (lateral pressure is inversely proportional to velocity of flow through a tube) acts on the walls of the ascending aorta, producing a sudden decrease in lateral pressure on the inner aspect of the wall. (Book p26)"),

(26, "match", "Types of Pulse: Normal, Bisferiens, Bifid, Dicrotic, Anacrotic & Corrigan",
 "Causes and auscultatory equivalents of pulsus bisferiens",
 "Match each aspect of pulsus bisferiens on Book p26 to its specific detail — 1) Moderate AS with severe AR 2) HOCM 3) Third listed cause of pulsus bisferiens 4) Auscultatory equivalents of pulsus bisferiens … A) Obstruction occurs later in systole as the mitral valve approximates the hypertrophied septum, causing a sharp pressure drop followed by a secondary rise B) Moderate AS causes a jet with extra velocity to be shot out C) Double Korotkoff sounds and Traube's femoral sounds D) Isolated severe aortic regurgitation",
 ["1-A, 2-B, 3-D, 4-C",
  "1-B, 2-A, 3-D, 4-C",
  "1-B, 2-A, 3-C, 4-D",
  "1-D, 2-A, 3-B, 4-C"],
 1,
 "Book p26 lists three causes of pulsus bisferiens — (i) moderate AS with severe AR (moderate AS shoots out a jet with extra velocity), (ii) HOCM (late-systolic obstruction as the mitral valve approximates the hypertrophied septum -> sharp drop then secondary rise), and (iii) severe AR — and notes that it can also be detected as double Korotkoff sounds and Traube's femoral sounds. (Book p26)"),

(26, "fillup", "Types of Pulse: Normal, Bisferiens, Bifid, Dicrotic, Anacrotic & Corrigan",
 "Auscultatory detection of pulsus bisferiens",
 "On Book p26, pulsus bisferiens can also be detected on auscultation as double Korotkoff sounds and ____ femoral sounds.",
 ["Traube's",
  "Duroziez's",
  "Korotkoff Phase 4",
  "Carvallo's"],
 0,
 "Item 2.c on Book p26 states: 'Can also be detected as double Korotkoff sounds and Traube's femoral sounds.' (Book p26)"),

# ---------------------------------------------------------------- Book p27
(27, "match", "Types of Pulse: Normal, Bisferiens, Bifid, Dicrotic, Anacrotic & Corrigan",
 "Bifid pulse, dicrotic pulse, anacrotic pulse and bounding pulse (text & waveform diagrams on p27)",
 "Match each arterial pulse waveform on Book p27 to its timing, haemodynamic setting and classic cause — 1) Bifid ('spike and dome') pulse 2) Dicrotic pulse 3) Anacrotic pulse 4) Bounding pulse … A) Second peak arises in diastole (after S2); low cardiac output + high PVR; caused by LV failure B) Classic pulse of HOCM: early systolic emptying -> obstruction -> late systolic emptying (both peaks before S2) C) Rapid rise + high-volume pulse (with Corrigan/Waterhammer pulse as its exaggerated form) D) Notch palpable on the upstroke; severe aortic stenosis",
 ["1-B, 2-A, 3-D, 4-C",
  "1-A, 2-B, 3-D, 4-C",
  "1-B, 2-D, 3-A, 4-C",
  "1-B, 2-A, 3-C, 4-D"],
 0,
 "Book p27 text and waveform diagrams contrast: Bifid ('spike and dome') pulse in HOCM (both peaks in systole before S2); Dicrotic pulse in LV failure with low CO + high PVR (second peak in diastole after S2); Anacrotic pulse in severe AS (palpable notch on the upstroke); and Bounding pulse (rapid rise + high volume), whose exaggerated form is the Corrigan/Waterhammer pulse. (Book p27)"),

(27, "scenario", "Types of Pulse: Normal, Bisferiens, Bifid, Dicrotic, Anacrotic & Corrigan",
 "Distinguishing dicrotic pulse from pulsus bisferiens and spike-and-dome on the p27 waveform strip",
 "On the three-panel arterial waveform comparison on Book p27 ('Pulsus Bisferiens', 'Spike and Dome pulse', 'Dicrotic pulse') timed against S1 and S2, what distinguishes the dicrotic pulse from the other two?",
 ["In the dicrotic pulse both peaks precede S1, whereas in pulsus bisferiens the second peak follows S2",
  "In the dicrotic pulse the notch is on the ascending anacrotic limb before the systolic peak",
  "In the dicrotic pulse the peripheral vascular resistance is low and cardiac output is high",
  "In the dicrotic pulse the second peak occurs after S2 in diastole, whereas in both pulsus bisferiens and the spike-and-dome pulse both peaks occur between S1 and S2 in systole"],
 3,
 "As shown in the p27 timing strip against S1 and S2, pulsus bisferiens and the HOCM spike-and-dome pulse are both double-peaked in systole (between S1 and S2), whereas the dicrotic pulse has its second peak after S2 in diastole (low CO + high PVR in LV failure). (Book p27)"),

(27, "fillup", "Types of Pulse: Normal, Bisferiens, Bifid, Dicrotic, Anacrotic & Corrigan",
 "Anacrotic pulse definition and Corrigan/Waterhammer upstroke",
 "An ____ pulse has a notch palpable on its upstroke and is seen in severe aortic stenosis, whereas the Corrigan (Waterhammer) pulse is an exaggerated bounding pulse whose sudden, forceful, jerky rise is due to rapid filling of the ____ artery.",
 ["Anacrotic; radial",
  "Dicrotic; carotid",
  "Bisferiens; brachial",
  "Alternans; femoral"],
 0,
 "On Book p27, an anacrotic pulse is defined by a notch palpable on the upstroke (seen in severe AS), and the Corrigan/Waterhammer pulse is an exaggerated form of bounding pulse whose sudden, forceful, jerky rise is due to rapid filling of the radial artery. (Book p27)"),

# ---------------------------------------------------------------- Book p28
(28, "scenario", "Types of Pulse: Normal, Bisferiens, Bifid, Dicrotic, Anacrotic & Corrigan",
 "Corrigan/Waterhammer pulse: why raising the patient's arm accentuates it and mechanisms of upstroke/downstroke",
 "When demonstrating a Corrigan (Waterhammer) pulse, you raise the patient's hand above the head. According to Book p28, which two mechanisms explain why raising the hand accentuates the sign, and what causes the sudden collapsing downstroke?",
 ["Raising the arm compresses the subclavian artery at the thoracic outlet and induces reflex brachial vasodilation; the downstroke is caused by premature closure of the aortic valve",
  "Gravity empties the radial artery (further raising pulse pressure) and brings the radial artery in line with the aorta (making it sensitive to aortic pressure changes); the collapsing downstroke is due to diastolic regurgitation into the LV plus rapid peripheral runoff from increased blood-stream velocity",
  "Venous pooling in the forearm increases local capillary hydrostatic pressure; the downstroke is caused by a Bernoulli drop during mid-systole",
  "Raising the arm slows heart rate via the baroreceptor reflex; the downstroke is caused by right ventricular interdependence"],
 1,
 "Book p28 gives both reasons for raising the arm (gravity empties the radial artery, raising pulse pressure; radial artery comes into line with the aorta, making it sensitive to aortic pressure changes), explains the jerky upstroke (extra-large stroke volume ejected by a distended LV into a relatively empty vessel) and the collapsing downstroke (sudden fall of aortic BP during diastolic regurgitation + rapid emptying of the arterial system from increased blood velocity). (Book p28)"),

(28, "oddoneout", "Types of Pulse: Normal, Bisferiens, Bifid, Dicrotic, Anacrotic & Corrigan",
 "Causes of Corrigan/Waterhammer pulse on Book p28",
 "Which of the following is NOT listed as a cause of a Corrigan (Waterhammer) pulse on Book p28?",
 ["Aortic regurgitation (AR)",
  "Patent ductus arteriosus (PDA)",
  "Other hyperdynamic circulatory states",
  "Severe calcific aortic stenosis"],
 3,
 "Book p28 lists the causes of Corrigan/Waterhammer pulse under 6.f as AR, PDA and other hyperdynamic circulatory states. Severe aortic stenosis causes the opposite pattern: pulsus parvus et tardus (item 8 on the same page). (Book p28)"),

(28, "fillup", "Parvus et Tardus, Bigeminy, Pulsus Paradoxus & Pulsus Alternans",
 "Pulsus parvus and pulsus parvus et tardus (text and diagram on p28)",
 "In the waveform diagram on Book p28, characteristic of aortic stenosis, 'Parvus' means ____ (low peak) and 'Tardus' means ____ (wide).",
 ["Slow; weak",
  "Narrow; bounding",
  "Weak; slow",
  "Delayed; collapsing"],
 2,
 "Pulsus parvus is a low-amplitude pulse seen in low cardiac output states; in pulsus parvus et tardus (characteristic of AS), the p28 diagram labels 'Parvus = weak (low peak)' and 'Tardus = slow (wide)'. (Book p28)"),

(28, "match", "Parvus et Tardus, Bigeminy, Pulsus Paradoxus & Pulsus Alternans",
 "Bigeminy vs Trigeminy vs Pulsus alternans (p28 text and ECG strips)",
 "Match each pulse/rhythm pattern on Book p28 to its definition and mechanism — 1) Pulsus bigeminy 2) Why bigeminy perpetuates itself 3) Pulsus trigeminy 4) Regular rhythm with alternating strong and weak beats … A) Two sinus beats followed by a PVC, so every third beat is a PVC B) Two beats felt with a pause and an irregular rhythm, where a PVC follows every sinus beat C) The long cycle length (compensatory pause) after the prior PVC tends to precipitate the next PVC after a sinus beat D) Pulsus alternans (not bigeminy, because the rhythm is regular)",
 ["1-B, 2-C, 3-A, 4-D",
  "1-A, 2-C, 3-B, 4-D",
  "1-B, 2-D, 3-A, 4-C",
  "1-D, 2-C, 3-A, 4-B"],
 0,
 "Book p28 contrasts bigeminy (two beats felt with a pause + irregular rhythm when a PVC follows every sinus beat; if regular rhythm, it is called pulsus alternans), the rule of bigeminy (the long cycle length after the prior PVC precipitates the next PVC), and trigeminy (two sinus beats followed by a PVC, so every third beat is a PVC). (Book p28)"),

(28, "numeric", "Parvus et Tardus, Bigeminy, Pulsus Paradoxus & Pulsus Alternans",
 "Pulsus paradoxus: normal inspiratory SBP drop, threshold and two physiological mechanisms",
 "In normal individuals, the maximum drop in systolic BP with deep inspiration is ____ (above which it is an exaggerated pulsus paradoxus), driven by which two normal inspiratory mechanisms on Book p28?",
 ["<20 mmHg; (1) inspiratory vagal withdrawal causes tachycardia, and (2) compression of the thoracic aorta by the inflated lungs",
  "<10 mmHg; (1) negative intrathoracic pressure increases venous return and RV filling, pushing the interventricular septum toward the LV, and (2) increased venous pooling in the lungs reduces LA filling",
  "<5 mmHg; (1) decreased right atrial filling during inspiration, and (2) opening of intrapulmonary arteriovenous shunts",
  "<15 mmHg; (1) shift of blood from the pulmonary veins into the splanchnic bed, and (2) reflex systemic vasodilation"],
 1,
 "Normally the maximum inspiratory drop in SBP is <10 mmHg (>10 mmHg is exaggerated pulsus paradoxus). The two normal mechanisms are: (1) inspiration -> negative intrathoracic pressure -> increased venous return -> increased RV filling -> pushes IV septum toward LV -> decreases LV volume; and (2) increased venous pooling in the lungs reducing LA filling. (Book p28)"),

# ---------------------------------------------------------------- Book p29
(29, "management", "Parvus et Tardus, Bigeminy, Pulsus Paradoxus & Pulsus Alternans",
 "Bedside sphygmomanometric measurement of pulsus paradoxus",
 "When measuring pulsus paradoxus with a sphygmomanometer as described on Book p29, you inflate the cuff above systolic pressure and deflate slowly. Which two pressure readings define the upper and lower limits whose difference equals pulsus paradoxus?",
 ["Upper limit = pressure at which Korotkoff sounds are heard only in expiration; Lower limit = pressure at which Korotkoff sounds are heard in both inspiration and expiration",
  "Upper limit = pressure at which Korotkoff sounds are heard only in inspiration; Lower limit = pressure at which Korotkoff sounds disappear completely in expiration",
  "Upper limit = pressure at which Phase 1 tapping appears; Lower limit = pressure at which Phase 4 muffling appears",
  "Upper limit = systolic pressure in the supine posture; Lower limit = systolic pressure after 3 minutes of standing"],
 0,
 "To measure pulsus paradoxus: inflate the BP cuff above systolic pressure; the pressure at which Korotkoff sounds are heard only in expiration is the upper limit, and the pressure at which Korotkoff sounds are heard in both inspiration and expiration is the lower limit. Their difference is pulsus paradoxus. (Book p29)"),

(29, "match", "Parvus et Tardus, Bigeminy, Pulsus Paradoxus & Pulsus Alternans",
 "Causes and mechanisms of pulsus paradoxus and reversed pulsus paradoxus",
 "Match each condition on Book p29 to its mechanism of pulsus paradoxus (or reversed pulsus paradoxus) — 1) Cardiac tamponade 2) Constrictive pericarditis 3) Asthma, COPD, OSA and obesity 4) Reversed pulsus paradoxus in HOCM … A) Thickened pericardium blocks transmission of inspiratory pleural pressure fall to cardiac chambers, while intrapleural extrapericardial pulmonary veins drop in pressure, diminishing the LA filling gradient B) Expiration markedly raises intrathoracic pressure to overcome airway obstruction, so inspiration lowers systolic pressure excessively C) Pericardial fluid equalises RV and LV diastolic pressures; inspiratory right-heart filling is accommodated only by bowing of the IV septum toward the LV D) Inspiratory rise in arterial systolic and diastolic pressure because of decreased LV volume on expiration",
 ["1-A, 2-C, 3-B, 4-D",
  "1-C, 2-B, 3-A, 4-D",
  "1-C, 2-A, 3-B, 4-D",
  "1-C, 2-A, 3-D, 4-B"],
 2,
 "Book p29 details all four mechanisms: tamponade (equal RV/LV diastolic pressures -> septal bowing into LV on inspiration), constrictive pericarditis (dissociation between intrathoracic/pulmonary venous pressure fall and insulated intracardiac chambers -> reduced LA filling gradient), asthma/COPD/OSA/obesity (wide intrathoracic pressure swings from expiratory obstruction), and reversed pulsus paradoxus in HOCM (inspiratory rise in SBP/DBP due to decreased LV volume on expiration). (Book p29)"),

(29, "scenario", "Parvus et Tardus, Bigeminy, Pulsus Paradoxus & Pulsus Alternans",
 "Why pulmonary venous pressure falls while intracardiac pressure does not in constrictive pericarditis",
 "In the mechanism of pulsus paradoxus in constrictive pericarditis on Book p29, why does the normal pressure gradient for left atrial filling fall during inspiration?",
 ["Because the pulmonary veins are intrapleural but extrapericardial (so their pressure falls with inspiration), whereas the thickened pericardium prevents the inspiratory fall in pleural pressure from being transmitted to the cardiac chambers",
  "Because the pulmonary veins are intrapericardial and extrapleural, so inspiration compresses them directly",
  "Because the left atrium herniates through the pericardial defect during inspiration",
  "Because tricuspid regurgitation reverses pulmonary venous flow during inspiration"],
 0,
 "Book p29 explains this anatomical dissociation clearly: normally pericardial and pleural pressures fall by the same amount during inspiration, but in constrictive pericarditis the thickened pericardium blocks transmission to the cardiac chambers, whereas the pulmonary veins are intrapleural but extrapericardial — so pulmonary venous pressure falls while LA pressure does not, diminishing the gradient for LA filling. (Book p29)"),

(29, "truefalse", "Parvus et Tardus, Bigeminy, Pulsus Paradoxus & Pulsus Alternans",
 "Reversed pulsus paradoxus in HOCM",
 "Which of the following True/False statements accurately describes reversed pulsus paradoxus on Book p29?",
 ["True: Reversed pulsus paradoxus is an expiratory rise in arterial pressure seen in cardiac tamponade",
  "True: Reversed pulsus paradoxus is an inspiratory rise in arterial systolic and diastolic pressure seen in HOCM because of decreased LV volume on expiration",
  "False: Reversed pulsus paradoxus is seen in HOCM",
  "False: In reversed pulsus paradoxus, arterial systolic and diastolic pressures rise during inspiration"],
 1,
 "Reversed pulsus paradoxus is defined on Book p29 as an inspiratory rise in arterial systolic and diastolic pressure, seen in HOCM because of a decrease in LV volume on expiration. (Book p29)"),

(29, "scenario", "Parvus et Tardus, Bigeminy, Pulsus Paradoxus & Pulsus Alternans",
 "Pulsus alternans: definition, cellular mechanism, cuff detection threshold and Harrison Ch 239 pointer",
 "A patient in sinus rhythm with a normal heart rate has alternating strong and weak radial pulses and alternating loud and soft Korotkoff sounds when the cuff is lowered just below peak systolic pressure. According to Book p29, what does this sign indicate, what is its most accepted cellular mechanism, and what pressure difference can be detected?",
 ["Sign of right ventricular infarction; caused by alternating AV nodal conduction through dual pathways; pulsus alternans of >25 mmHg is required for detection",
  "Sign of cardiac tamponade; caused by swinging of the heart within a large pericardial effusion; pulsus alternans of >5 mmHg is diagnostic",
  "Sign of severe aortic regurgitation; caused by Bernoulli suction in the ascending aorta; pulsus alternans is detected only in diastole",
  "Sign of LV dysfunction; caused by intermittent release of Ca2+ ions from the myocardial sarcoplasmic reticulum; pulsus alternans of >10 mmHg can be detected"],
 3,
 "Pulsus alternans is alternating strong and weak pulses despite normal rate and rhythm, a sign of LV dysfunction. Its most accepted theory is intermittent release of Ca2+ ions from the myocardial sarcoplasmic reticulum, and a difference of >10 mmHg can be detected with a BP cuff (followed at the bottom of p29 by the Harrison's 21e Ch 239 cross-reference for volume, contour, timing, radio-femoral delay, Allen's test, parvus et tardus, bisferiens, alternans and paradoxus). (Book p29)"),

# ---------------------------------------------------------------- Book p30
(30, "scenario", "CVS General Examination: PICCLE, Slow vs Fast Oedema, RF, IE & AR Signs",
 "Pallor vs ruddy/suffused conjunctiva in congenital cyanotic heart disease and tongue technique for cyanosis",
 "During the general examination of a patient with suspected congenital cyanotic heart disease (Book p30), why must you look for a ruddy/suffused conjunctiva alongside pallor, and how does the book instruct you to examine the tongue for cyanosis?",
 ["A ruddy/suffused conjunctiva indicates polycythaemia pointing to congenital cyanotic heart disease (while coexisting anaemia can act as a confounding factor); ask the patient to stick out their tongue and leave it out for some time",
  "A ruddy conjunctiva indicates subconjunctival haemorrhage from infective endocarditis; ask the patient to curl the tongue upward to inspect only the frenulum",
  "A ruddy conjunctiva indicates hypercapnic vasodilation; ask the patient to swallow repeatedly while inspecting the soft palate",
  "A ruddy conjunctiva rules out congenital heart disease; cyanosis of the tongue is checked only under fluorescent light"],
 0,
 "On Book p30: check BP in UL and LL plus pulse pressure, RR, and under PICCLE: (1) Pallor — check for ruddy/suffused conjunctiva indicating polycythaemia of congenital cyanotic heart disease (noting anaemia itself can act as a confounding factor); (2) Icterus — 'better to avoid'; (3) Cyanosis — ask the patient to stick out their tongue and leave it out for some time, and also check lips, nail bed, ear lobe, tip of nose, inner surface of lips and palate. (Book p30)"),

(30, "match", "CVS General Examination: PICCLE, Slow vs Fast Oedema, RF, IE & AR Signs",
 "Central vs peripheral cyanosis table and CVS causes of clubbing on Book p30",
 "Match each column from Book p30 to its exact entries — 1) Central cyanosis causes: cardiac, vascular and haemoglobin 2) Central cyanosis cause: V/Q mismatch 3) Peripheral cyanosis causes 4) CVS causes of clubbing … A) Shock/CHF, cold exposure and peripheral vascular disease B) Cyanotic heart disease, pulmonary AV fistulas and Hb anomalies [met-, sulf-, CO-Hb] C) Congenital cyanotic heart disease, infective endocarditis and left atrial myxoma D) Pulmonary oedema, COPD and extensive pneumonia",
 ["1-A, 2-D, 3-B, 4-C",
  "1-B, 2-D, 3-A, 4-C",
  "1-B, 2-A, 3-D, 4-C",
  "1-B, 2-D, 3-C, 4-A"],
 1,
 "Book p30 tabulates Central cyanosis (1. Cyanotic HD, 2. Pulmonary AV fistulas, 3. Hb anomalies [met, sulf, CO], 4. V/Q mismatch [pulmonary oedema, COPD, extensive pneumonia]) vs Peripheral cyanosis (1. Shock/CHF, 2. Cold exposure, 3. PVD), and lists the three CVS causes of clubbing: congenital cyanotic heart disease, infective endocarditis and left atrial myxoma. (Book p30)"),

(30, "fillup", "CVS General Examination: PICCLE, Slow vs Fast Oedema, RF, IE & AR Signs",
 "Bony landmarks for pitting oedema and dependent site in a cardiac patient",
 "On Book p30, pitting oedema is checked on a bony prominence such as the shin of the tibia or just above the ____, and in a bedridden cardiac patient dependent oedema is seen in the ____ region.",
 ["Medial malleolus; presacral",
  "Lateral malleolus; periorbital",
  "Tibial tuberosity; submental",
  "Calcaneal tendon; infraclavicular"],
 0,
 "Under 5. Oedema on Book p30: check for pitting on a bony prominence like the shin of the tibia or just above the medial malleolus, and oedema in a cardiac patient is seen in the presacral region (the dependent part). (Book p30)"),

(30, "numeric", "CVS General Examination: PICCLE, Slow vs Fast Oedema, RF, IE & AR Signs",
 "Slow oedema vs fast oedema (>40 sec vs <40 sec) and treatment",
 "When testing for pitting oedema on Book p30, what time cutoff separates slow oedema from fast oedema, what does each signify, and what is the treatment of slow oedema?",
 ["Slow oedema: pitting lasts >2 minutes (indicates lymphatic obstruction); Fast oedema: pitting lasts <10 seconds (indicates right heart failure); treated with albumin infusion",
  "Slow oedema: pitting lasts >60 seconds (indicates hypoproteinaemia); Fast oedema: pitting lasts <60 seconds (indicates sodium retention); treated with fluid restriction",
  "Slow oedema: pitting lasts >40 seconds (indicates 4 kg sodium and water retention in the extravascular compartment; treatment is salt restriction); Fast oedema: pitting lasts <40 seconds (due to hypoproteinaemia)",
  "Slow oedema: pitting lasts >40 seconds (due to hypoalbuminaemia); Fast oedema: pitting lasts <40 seconds (due to 4 kg salt retention); treated with compression stockings"],
 2,
 "Book p30 defines Slow oedema as pitting lasting >40 seconds (indicating sodium and water — 4 kg — retention in the extravascular compartment; treatment is salt restriction) and Fast oedema as pitting lasting <40 seconds (due to hypoproteinaemia), followed by Ht, wt and BMI. (Book p30)"),

(30, "match", "CVS General Examination: PICCLE, Slow vs Fast Oedema, RF, IE & AR Signs",
 "Signs of rheumatic activity, signs of infective endocarditis, and the Lighthouse sign of AR",
 "Match each peripheral sign on Book p30 to its description — 1) Subcutaneous nodules of rheumatic activity 2) Janeway lesions vs Osler nodes in IE 3) Roth spots and splinter haemorrhages in IE 4) Lighthouse sign of AR … A) Alternate flushing and blanching of the forehead B) Painless, pea-sized nodules over bony prominences / extensor aspects of long bones (alongside joint swelling) C) Janeway = non-tender erythematous macules on palms/soles; Osler = tender subcutaneous violaceous nodules on pads of fingers/toes D) Roth = exudative oedematous haemorrhagic retinal lesions with pale centres; Splinter = non-blanching reddish-brown lesions under the nail bed",
 ["1-B, 2-C, 3-D, 4-A",
  "1-C, 2-B, 3-D, 4-A",
  "1-B, 2-D, 3-C, 4-A",
  "1-B, 2-C, 3-A, 4-D"],
 0,
 "Book p30 details: Signs of rheumatic activity (painless pea-sized SC nodules over bony prominences/extensor aspects of long bones + joint swelling); Signs of IE (Janeway lesions, Osler nodes, Roth spots, splinter haemorrhages); and Signs of AR #1: Lighthouse sign = alternate flushing and blanching of the forehead. (Book p30)"),

(30, "oddoneout", "CVS General Examination: PICCLE, Slow vs Fast Oedema, RF, IE & AR Signs",
 "Immunologic phenomena in infective endocarditis on Book p30",
 "Under 'Signs of IE' on Book p30, item 5 explicitly groups three features as 'Immunologic phenomena in IE'. Which of the following is NOT one of those three?",
 ["Osler nodes",
  "Roth spots",
  "Microscopic haematuria",
  "Janeway lesions"],
 3,
 "Item 5 under Signs of IE on Book p30 states: 'Immunologic phenomena in IE — Osler nodes, Roth spots and microscopic haematuria'. Non-tender Janeway lesions on the palms and soles are microembolic/vascular phenomena, not immunologic. (Book p30)"),
]
