# -*- coding: utf-8 -*-
"""Chapter 3 source data, Part B: Book p34-36 (JVP procedure, ACXVY waves, A/V/X/Y abnormalities, Constrictive pericarditis, Abdominojugular reflux, Kussmaul's sign)."""

# (page, fmt, sec, point, question, options, ans, explanation)
B = [
# ---------------------------------------------------------------- Book p34
(34, "scenario", "JVP Procedure, Non-pulsatile JVP & ACXVY Waveforms",
 "JVP positioning sequence and why inspiratory pulsations become more prominent while mean height falls",
 "When examining the JVP (Book p34), you first inspect the patient in the sitting position (checking other positions if it rises above the clavicle, and preferring 45° over supine where the top of the column may be hard to detect). During inspiration, why does the mean JVP level fall while the JVP pulsations paradoxically become MORE prominent?",
 ["Negative intrathoracic pressure creates a suction effect that lowers the mean JVP column, while the resulting increase in venous return increases right-heart volume and makes the individual pulsations more prominent",
  "Inspiratory contraction of the sternocleidomastoid compresses the lower IJV while dilating the superior jugular bulb",
  "Tricuspid valve closure is delayed during inspiration, abolishing the y descent while doubling the c wave",
  "Inspiration shifts blood from the right atrium into the left atrium across the interatrial septum"],
 0,
 "Item 7 on Book p34 explains both halves of the inspiratory response: the JVP column drops on inspiration because the drop in intrathoracic pressure causes a suction effect, yet the pulsations of the JVP become more prominent on inspiration because the increased venous return increases the volume of the right heart. (Book p34)"),

(34, "match", "JVP Procedure, Non-pulsatile JVP & ACXVY Waveforms",
 "Reduced JVP, bilateral vs unilateral non-pulsatile elevated JVP, and respiratory variation (items 8–11)",
 "Match each JVP column abnormality on Book p34 to its cause — 1) Reduced JVP 2) Bilateral elevated JVP without pulsation 3) Unilateral non-pulsatile elevated JVP 4) Wide respiratory variation of JVP … A) Superior vena cava (SVC) obstruction B) Innominate vein obstruction or thrombosis C) Hypovolaemia D) Bronchial asthma and emphysema (wide variation of intrathoracic pressure with respiration)",
 ["1-A, 2-C, 3-B, 4-D",
  "1-C, 2-A, 3-B, 4-D",
  "1-C, 2-B, 3-A, 4-D",
  "1-C, 2-A, 3-D, 4-B"],
 1,
 "Items 8–11 on Book p34 state: (8) reduced JVP is seen in hypovolaemia; (9) bilateral elevated JVP without pulsation = SVC obstruction; (10) unilateral non-pulsatile elevated JVP = innominate vein obstruction or thrombosis; (11) in bronchial asthma and emphysema, wide intrathoracic pressure swings cause the JVP to vary with respiration. (Book p34)"),

(34, "numeric", "JVP Procedure, Non-pulsatile JVP & ACXVY Waveforms",
 "JVP figure on Book p34: arithmetic example and timing against Phonocardiogram and EKG",
 "In the illustrated JVP figure on Book p34, a venous pulsation top level of 3 cm above the sternal angle added to the 5 cm distance from the right atrium to the sternal angle equals ____, and on the simultaneous Phonocardiogram/EKG strip the 'x' descent falls between ____ and ____ while the 'y' descent follows ____.",
 ["8 cm H2O jugular venous pressure; S1 and S2; S2",
  "5 cm H2O jugular venous pressure; S2 and S1; S1",
  "8 mmHg jugular venous pressure; P wave and QRS; QRS",
  "15 cm H2O jugular venous pressure; T wave and P wave; S1"],
 0,
 "The figure on Book p34 shows: '3 cm (from sternal angle) + 5 cm (from right atrium to sternal angle) = 8 cm H2O jugular venous pressure', and aligns the JVP waves with the phonocardiogram and EKG: 'a' wave with the P wave before S1, 'c' wave at S1/QRS, 'x' descent in systole between S1 and S2, 'v' wave peaking around S2, and 'y' descent in diastole after S2. (Book p34)"),

(34, "match", "JVP Procedure, Non-pulsatile JVP & ACXVY Waveforms",
 "Physiological origin of the ACXVY waves and descents on Book p34",
 "Match each component of the ACXVY jugular venous waveform on Book p34 to its physiological mechanism — 1) 'a' wave 2) 'c' wave 3) 'v' wave and 'y' descent 4) 'x' descent and 'x prime' descent … A) Tricuspid valve bulging into the RA during isovolumetric contraction (plus a small component from adjacent carotid pulsations) B) 'x prime' (between a and c) is due to atrial relaxation; 'x' is due to ventricular systolic contraction pulling the tricuspid valve apparatus toward the apex, increasing RA volume C) Atrial contraction D) 'v' wave = venous return (passive RA filling); 'y' descent = atrial emptying",
 ["1-A, 2-C, 3-D, 4-B",
  "1-C, 2-A, 3-B, 4-D",
  "1-C, 2-A, 3-D, 4-B",
  "1-C, 2-D, 3-A, 4-B"],
 2,
 "Item 12 on Book p34 defines ACXVY: a = Atrial contraction; c = TriCuspid valve bulging into RA in isovolumetric contraction (plus a small carotid pulsation component); v = Venous return; x = Atrial RelaXation (comprising x' between a and c from atrial relaxation, and x from systolic descent of the tricuspid ring toward the apex increasing RA volume); y = atrial emptYing. (Book p34)"),

(34, "fillup", "JVP Procedure, Non-pulsatile JVP & ACXVY Waveforms",
 "Dual mechanism of the x' and x descents on Book p34",
 "On Book p34, the x descent actually comprises the x' descent (between the a and c waves, caused by ____) and the x descent proper (caused during ventricular systole when the ventricles pull the ____ apparatus toward the apex).",
 ["Atrial relaxation; tricuspid valve",
  "Isovolumetric relaxation; mitral valve",
  "Passive venous filling; semilunar valve",
  "Carotid recoil; eustachian valve"],
 0,
 "Item 12.d on Book p34 explains that the x' descent between a and c is due to atrial relaxation, whereas when the ventricles contract in systole they pull the tricuspid valve apparatus toward the apex, increasing right atrial volume and lowering RA pressure (the x descent). (Book p34)"),

# ---------------------------------------------------------------- Book p35
(35, "match", "Abnormalities of JVP Waves & Descents (A, V, X, Y)",
 "Prominent A waves, giant A waves, and the Bernheim effect on Book p35",
 "Match each 'a' wave abnormality on Book p35 to its cause or mechanism — 1) Prominent 'a' waves 2) Classical valvular cause of giant 'a' waves 3) Bernheim effect causing giant 'a' waves 4) Cannon 'a' waves … A) Marked LVH pushes the interventricular septum toward the right, making RV filling more difficult B) Right atrium contracting against a closed tricuspid valve C) Right ventricular hypertrophy causes: pulmonary hypertension, pulmonary embolism causing acute cor pulmonale, and pulmonic stenosis D) Tricuspid stenosis (TS)",
 ["1-C, 2-D, 3-A, 4-B",
  "1-D, 2-C, 3-A, 4-B",
  "1-C, 2-A, 3-D, 4-B",
  "1-B, 2-D, 3-A, 4-C"],
 0,
 "Item 13 on Book p35 separates: prominent 'a' waves (RVH from pulmonary hypertension, PE causing acute cor pulmonale, pulmonic stenosis); giant 'a' waves in tricuspid stenosis (TS) and via the Bernheim effect in marked LVH (septum pushed rightward, impeding RV filling); and cannon 'a' waves (RA contracting against a closed tricuspid valve). (Book p35)"),

(35, "scenario", "Abnormalities of JVP Waves & Descents (A, V, X, Y)",
 "Bernheim effect in marked left ventricular hypertrophy",
 "A patient with severe systemic hypertension and marked left ventricular hypertrophy exhibits giant 'a' waves in the JVP without tricuspid stenosis or pulmonary hypertension. According to Book p35, this phenomenon is called the:",
 ["Bernheim effect — the hypertrophied interventricular septum is pushed toward the right, making right ventricular filling more difficult",
  "Reverse Bernheim effect — right ventricular dilation pushes the interventricular septum into the left ventricle during inspiration",
  "Venturi effect — high-velocity outflow across the aortic valve sucks the anterior mitral leaflet into the outflow tract",
  "Carvallo effect — inspiratory augmentation of right-sided venous return unmasks tricuspid regurgitation"],
 0,
 "Item 13.b.i on Book p35 defines the Bernheim effect: giant 'a' waves can also be seen in marked LVH because the RV septum is pushed toward the right, making RV filling more difficult. (Book p35)"),

(35, "truefalse", "Abnormalities of JVP Waves & Descents (A, V, X, Y)",
 "Intermittent vs regular cannon A waves on Book p35",
 "Which of the following True/False statements accurately states the distinction between intermittent and regular cannon 'a' waves on Book p35?",
 ["True: Regular cannon 'a' waves are characteristic of complete (third-degree) heart block, whereas intermittent cannon 'a' waves are characteristic of junctional tachycardia",
  "True: Intermittent cannon 'a' waves occur in AV dissociation (third-degree heart block), whereas regular cannon 'a' waves occur in junctional tachycardia (where the AV-nodal focus depolarises right and left chambers simultaneously)",
  "False: Cannon 'a' waves represent the right atrium contracting against a closed tricuspid valve",
  "False: In junctional tachycardia the focus is at the AV node"],
 1,
 "Item 13.c on Book p35 distinguishes intermittent cannon waves (AV dissociation / third-degree heart block) from regular cannon 'a' waves (junctional tachycardia, where the focus is at the AV node and depolarisation spreads equally to the chambers at the same time). (Book p35)"),

(35, "scenario", "Abnormalities of JVP Waves & Descents (A, V, X, Y)",
 "VT vs SVT with aberrancy and timing of cannon A wave vs giant A wave relative to S1",
 "You are asked at the bedside to use the JVP to distinguish ventricular tachycardia (VT) from supraventricular tachycardia (SVT) with aberrancy, and to distinguish a cannon 'a' wave from a giant 'a' wave. Which statement matches Book p35?",
 ["SVT with aberrancy produces intermittent cannon 'a' waves while VT produces regular cannon 'a' waves; both cannon and giant 'a' waves peak after S2",
  "Junctional tachycardia produces intermittent cannon 'a' waves while 3rd-degree heart block produces regular cannon 'a' waves; cannon 'a' waves precede S1",
  "VT has complete V-A dissociation and therefore produces cannon 'a' waves, whereas SVT with aberrancy (without 3rd-degree heart block) preserves AV association and has no cannon 'a' waves; a cannon 'a' wave begins JUST AFTER S1, whereas a giant 'a' wave begins JUST BEFORE S1",
  "Neither VT nor junctional tachycardia alters the 'a' wave; cannon 'a' waves occur only in atrial fibrillation"],
 2,
 "Book p35 (13.c.iii & 13.d) stresses that in VT there is complete V-A dissociation (so cannon 'a' waves are present), whereas in SVT with aberrancy (without 3rd-degree heart block) AV association is preserved (no cannon 'a' waves); and a cannon 'a' wave begins just AFTER S1 (atrial contraction against a closed tricuspid valve), whereas a giant 'a' wave begins just BEFORE S1. (Book p35)"),

(35, "scenario", "Abnormalities of JVP Waves & Descents (A, V, X, Y)",
 "Equally prominent A and V waves and 'left atrialization' of the JVP in ASD",
 "In a normal JVP the 'a' wave is taller than the 'v' wave, but in a patient with an atrial septal defect (ASD) the 'a' and 'v' waves have equal amplitude. How does Book p35 explain this 'left atrialization' of the jugular venous waveform?",
 ["Normally the RA 'a' wave (active contraction) exceeds the 'v' wave (passive filling), whereas in the LA the 4 pulmonary vein entry points decrease LA compliance so LA 'a' and 'v' waves have similar amplitude; in ASD, left atrialization of the JVP occurs",
  "In ASD the tricuspid valve is congenitally stenotic, reducing the 'a' wave to match the 'v' wave",
  "The four pulmonary veins drain directly into the superior vena cava in every ostium secundum ASD",
  "High left ventricular end-diastolic pressure obliterates the 'x' descent and fuses the 'a' and 'v' waves into a single systolic wave"],
 0,
 "Item 14 on Book p35 notes that equally prominent 'a' and 'v' waves occur in RV failure and ASD: normally the 'a' wave exceeds the 'v' wave (active contraction vs passive filling), but in the left atrium the 4 pulmonary vein entry points reduce LA compliance so LA 'a' and 'v' waves have similar amplitude; in ASD, left atrialization of the JVP equalises the 'a' and 'v' waves. (Book p35)"),

(35, "match", "Abnormalities of JVP Waves & Descents (A, V, X, Y)",
 "Abnormalities of the x and y descents, TS vs TR, and the PAY TAX mnemonic on Book p35",
 "Match each JVP descent pattern or mnemonic on Book p35 to its clinical correlate — 1) Prominent 'x' descent 2) Diminished or blunted 'x' descent 3) Prominent 'y' descent vs diminished/absent 'y' descent 4) 'PAY TAX' mnemonic … A) Pericarditis [constrictive] = prominent Y descent; Tamponade = prominent X descent [with blunted y descent] B) Vigorous RV contraction / space creation in systole: cardiac tamponade and RV overload C) Atrial fibrillation, cardiomyopathy and tricuspid regurgitation [systolic regurgitant jet into RA prevents pressure fall] D) Prominent y = constrictive pericarditis and restrictive cardiomyopathy; Diminished/absent y = tricuspid stenosis [diastolic RA emptying impaired, with giant a wave]",
 ["1-C, 2-B, 3-D, 4-A",
  "1-B, 2-C, 3-D, 4-A",
  "1-B, 2-D, 3-C, 4-A",
  "1-B, 2-C, 3-A, 4-D"],
 1,
 "Items 15–20 on Book p35 cover all four: (15) prominent x = tamponade, RV overload; (16 & 19b) diminished/blunted x = AF, cardiomyopathy, TR; (17–19a) prominent y = constrictive pericarditis, restrictive cardiomyopathy, while diminished/absent y = TS (a diastolic pathology giving giant a wave + diminished y descent); (19c & 20) PAY TAX = Pericarditis prominent y descent, Tamponade prominent x descent (and blunted y descent). (Book p35)"),

(35, "fillup", "Abnormalities of JVP Waves & Descents (A, V, X, Y)",
 "PAY TAX mnemonic for constrictive pericarditis vs cardiac tamponade",
 "The mnemonic 'PAY TAX' on Book p35 stands for: Constrictive ____ has a prominent ____ descent, whereas Cardiac ____ has a prominent ____ descent.",
 ["Pericarditis; y; Tamponade; x",
  "Pericarditis; x; Tamponade; y",
  "Pulmonary stenosis; a; Tricuspid stenosis; v",
  "Pericarditis; a; Tamponade; y"],
 0,
 "Item 19.c on Book p35 gives the mnemonic: 'PAY TAX — Pericarditis prominent y descent, Tamponade prominent x descent'. (Book p35)"),

# ---------------------------------------------------------------- Book p36
(36, "scenario", "Constrictive Pericarditis, Abdominojugular Reflux & Kussmaul's Sign",
 "Mechanism of rapid y descent and dip-and-square-root sign in constrictive pericarditis",
 "In constrictive pericarditis, the pericardium is stuck like an adhesive to the right ventricle. How does Book p36 link this pathology to both the JVP waveform and the cardiac catheterisation tracing?",
 ["The RV fails to relax in early diastole and contracts twice in systole — producing a prominent 'x' descent on JVP and a 'spike and dome' tracing on cardiac catheterisation",
  "Pericardial fluid compresses the right atrium throughout diastole — obliterating the 'y' descent and producing electrical alternans on catheterisation",
  "The RV relaxes very quickly in early diastole (causing a rapid pressure drop), but its pressure increases and plateaus immediately due to a recoil against the adherent pericardium — producing a rapid 'y' descent on JVP and the 'dip and square root' sign on cardiac catheterisation",
  "The tricuspid valve remains fixed open in systole — producing cv fusion waves and a 'square wave' arterial response"],
 2,
 "Item 21 on Book p36 explains: in constrictive pericarditis, the pericardium is stuck like an adhesive to the RV; the RV relaxes very quickly (rapid pressure drop), but its pressure rises immediately due to a recoil of sorts, causing the rapid 'y' descent on JVP and accounting for the 'dip and square root' sign on cardiac catheterisation. (Book p36)"),

(36, "match", "Constrictive Pericarditis, Abdominojugular Reflux & Kussmaul's Sign",
 "Comparison table on Book p36: Tamponade vs Constrictive Pericarditis vs Restrictive Cardiomyopathy",
 "Match each row or column of the three-way comparison table on Book p36 — 1) Cardiac tamponade 2) Constrictive pericarditis 3) Restrictive cardiomyopathy 4) Feature present in both Tamponade and Constrictive pericarditis but absent in Restrictive cardiomyopathy … A) Kussmaul sign PRESENT, Pulsus paradoxus PRESENT, JVP shows rapid y descent B) Kussmaul sign ABSENT, Pulsus paradoxus PRESENT, JVP shows prominent x descent with blunted y descent C) Pulsus paradoxus D) Kussmaul sign PRESENT, Pulsus paradoxus ABSENT",
 ["1-B, 2-A, 3-D, 4-C",
  "1-A, 2-B, 3-D, 4-C",
  "1-B, 2-D, 3-A, 4-C",
  "1-B, 2-A, 3-C, 4-D"],
 0,
 "The p36 table contrasts the three entities: Tamponade (Kussmaul absent, pulsus paradoxus present, JVP prominent x / blunted y); Constrictive pericarditis (Kussmaul present, pulsus paradoxus present, JVP rapid y descent); Restrictive cardiomyopathy (Kussmaul present, pulsus paradoxus absent). (Book p36)"),

(36, "truefalse", "Constrictive Pericarditis, Abdominojugular Reflux & Kussmaul's Sign",
 "Restrictive cardiomyopathy vs constrictive pericarditis in the Book p36 comparison table",
 "Which of the following True/False statements accurately reflects the three-column comparison table on Book p36?",
 ["True: Both constrictive pericarditis and restrictive cardiomyopathy have Kussmaul's sign present, whereas pulsus paradoxus is present in constrictive pericarditis (and tamponade) but absent in restrictive cardiomyopathy",
  "True: Cardiac tamponade has Kussmaul's sign present and pulsus paradoxus absent",
  "False: Constrictive pericarditis has both Kussmaul's sign and pulsus paradoxus present in the p36 table",
  "False: Tamponade shows a prominent x descent with a blunted y descent on the JVP"],
 0,
 "In the p36 table, Kussmaul's sign is Absent in Tamponade and Present in both Constrictive pericarditis and Restrictive cardiomyopathy; Pulsus paradoxus is Present in Tamponade and Constrictive pericarditis, and Absent in Restrictive cardiomyopathy. (Book p36)"),

(36, "management", "Constrictive Pericarditis, Abdominojugular Reflux & Kussmaul's Sign",
 "Abdominojugular reflux: normal vs RV failure response, clinical purpose, technique and positive cutoff",
 "How is the abdominojugular reflux elicited according to Book p36, what defines a positive test, why does the JVP normally fall with abdominal compression, and what are its two clinical uses?",
 ["Apply the hand over the periumbilical area with fingers widely spread and press gradually, firmly and steadily inward for at least 15 seconds; positive if JVP rises by >3 cm throughout compression; normally abdominal compression obstructs femoral venous return so less blood reaches the RA; used to unmask subclinical RV failure and confirm symptomatic LV failure",
  "Press sharply over the left iliac fossa for 3 seconds while the patient holds breath in expiration; positive if JVP rises by >1 cm transiently; used to diagnose superior vena cava obstruction",
  "Compress the epigastrium for 60 seconds with the patient standing erect; positive if JVP falls by >5 cm; used to differentiate tricuspid stenosis from mitral stenosis",
  "Percuss the right costal margin for 5 seconds; positive if a jugular venous thrill appears; used to confirm cardiac tamponade"],
 0,
 "Item 22 on Book p36 covers every detail of abdominojugular reflux: (a) normally abdominal compression makes JVP fall because it obstructs femoral venous return so less blood reaches the RA; (b) in RV failure, RA/RV already have high pressure, so RUQ/abdominal compression decreases RV output and raises JVP for a sustained duration; (c) used to unmask subclinical RV failure and confirm symptomatic LV failure; (d) hand over periumbilical area with fingers widely spread, gradual firm inward steady pressure for at least 15 seconds — positive if JVP rises by >3 cm throughout the compression. (Book p36)"),

(36, "numeric", "Constrictive Pericarditis, Abdominojugular Reflux & Kussmaul's Sign",
 "Abdominojugular reflux compression duration and sustained JVP rise threshold",
 "In the abdominojugular reflux procedure on Book p36, steady periumbilical pressure is applied for at least ____, and the test is positive if the JVP rises by ____ throughout the compression.",
 ["5 seconds; >1 cm",
  "10 seconds; >2 cm",
  "15 seconds; >3 cm",
  "30 seconds; >4.5 cm"],
 2,
 "Item 22.d on Book p36 specifies applying gradual, firm, inward, steady pressure over the periumbilical area for at least 15 seconds; it is positive if the JVP rises by >3 cm throughout the compression. (Book p36)"),

(36, "numeric", "Constrictive Pericarditis, Abdominojugular Reflux & Kussmaul's Sign",
 "Kussmaul's sign: definition, normal inspiratory JVP fall in mmHg, and the cause to state first",
 "Book p36 defines Kussmaul's sign as a paradoxical rise in JVP with inspiration. What is the normal inspiratory fall of JVP (with the exact unit stressed in the note), and which cause of Kussmaul's sign does the book instruct you to 'tell first'?",
 ["3 cm of water; constrictive pericarditis — tell this first",
  "3 mmHg (explicitly noted: 'not cm of water'); right ventricular myocardial infarction (RVMI) — tell this first",
  "7 mmHg; tricuspid stenosis — tell this first",
  "5 cm of water; cardiac tamponade — tell this first"],
 1,
 "Item 23 on Book p36 states: Kussmaul's sign is a paradoxical rise in JVP with inspiration; the normal fall of JVP on inspiration is 3 mmHg ('not cm of water'); and among the six causes (1. Right ventricular MI — 'tell this first', 2. RV failure, 3. Tricuspid stenosis, 4. Cor pulmonale, 5. Constrictive pericarditis, 6. Restrictive cardiomyopathy), RVMI must be named first. (Book p36)"),

(36, "oddoneout", "Constrictive Pericarditis, Abdominojugular Reflux & Kussmaul's Sign",
 "Six causes of Kussmaul's sign vs cardiac tamponade on Book p36",
 "Which of the following conditions is explicitly noted on Book p36 as NOT causing Kussmaul's sign?",
 ["Right ventricular myocardial infarction and RV failure",
  "Tricuspid stenosis and cor pulmonale",
  "Constrictive pericarditis and restrictive cardiomyopathy",
  "Cardiac tamponade"],
 3,
 "Item 23.d lists the six causes of Kussmaul's sign: right ventricular MI ('tell this first'), RV failure, tricuspid stenosis (backflow from RA), cor pulmonale (RV failure), constrictive pericarditis, and restrictive cardiomyopathy. Item 23.e specifically asks 'Why not in tamponade?' (Book p36)"),

(36, "scenario", "Constrictive Pericarditis, Abdominojugular Reflux & Kussmaul's Sign",
 "Why Kussmaul's sign is absent in cardiac tamponade while pulsus paradoxus is present",
 "Why does cardiac tamponade produce pulsus paradoxus but NOT Kussmaul's sign, whereas constrictive pericarditis produces Kussmaul's sign? (Book p36)",
 ["In tamponade, the RV can still accommodate the inspiratory increase in venous return by pushing the interventricular septum toward the LV (so there is no Kussmaul's sign, but decreased LV volume causes pulsus paradoxus); in constrictive pericarditis, RA pressure increases with inspiration but is not transmitted to the RV",
  "In tamponade, the superior vena cava collapses completely during inspiration, preventing blood from entering the neck veins",
  "In tamponade, the pericardial fluid is confined to the left ventricle and spares the right atrium and right ventricle",
  "In constrictive pericarditis, the interventricular septum is absent, equalising systemic and pulmonary pressures"],
 0,
 "Item 23.d.v and 23.e on Book p36 explain: in constrictive pericarditis, right atrial pressure increases with inspiration because it is not transmitted to the constricted RV; in tamponade, by contrast, the RV can accommodate the increased inspiratory venous return by pushing the IV septum toward the LV — so there is no Kussmaul's sign, but there is pulsus paradoxus because of decreased LV volume. (Book p36)"),
]
