# -*- coding: utf-8 -*-
"""Chapter 3 source data, Part A: Book p31-33 (Peripheral signs of AR, Hill's sign, Precordial inspection, JVP basics & POLICE)."""

# (page, fmt, sec, point, question, options, ans, explanation)
A = [
# ---------------------------------------------------------------- Book p31
(31, "match", "Peripheral Signs of Aortic Regurgitation & Hill's Sign",
 "Head and neck peripheral signs of aortic regurgitation (signs 2–7 on p31)",
 "Match each eponymous sign of aortic regurgitation on Book p31 to its clinical finding — 1) Becker's sign 2) Landolfi's sign 3) Muller's sign 4) De Musset's sign and Corrigan's sign … A) Changes in pupil size with cardiac systole B) Retinal artery pulsations C) Uvula pulsation D) Head bobbing [De Musset's] and dancing carotids [Corrigan's]",
 ["1-B, 2-A, 3-C, 4-D",
  "1-A, 2-B, 3-C, 4-D",
  "1-B, 2-C, 3-A, 4-D",
  "1-C, 2-A, 3-B, 4-D"],
 0,
 "Continuing from p30's Lighthouse sign (1), Book p31 lists: (2) Becker's sign = retinal artery pulsations, (3) Landolfi's sign = changes in pupil size with cardiac systole, (4) Muller's sign = uvula pulsation, (5) De Musset's sign = head bobbing, (6) Corrigan's sign = dancing carotids, and (7) Locomotor brachii = tortuous and highly pulsatile brachial artery. (Book p31)"),

(31, "oddoneout", "Peripheral Signs of Aortic Regurgitation & Hill's Sign",
 "Ocular, oral and cervical signs of AR on Book p31",
 "Which of the following eponymous signs of aortic regurgitation on Book p31 is paired with an INCORRECT anatomical site?",
 ["Becker's sign — retinal artery pulsations",
  "Landolfi's sign — changes in pupil size with cardiac systole",
  "Muller's sign — uvula pulsation",
  "Corrigan's sign — tortuous and highly pulsatile brachial artery"],
 3,
 "On Book p31, Corrigan's sign is dancing carotids (while Corrigan's pulse is the water-hammer/collapsing pulse); a tortuous and highly pulsatile brachial artery is locomotor brachii. (Book p31)"),

(31, "recall", "Peripheral Signs of Aortic Regurgitation & Hill's Sign",
 "Locomotor brachii and cuff/artery landmarks for lower-limb BP in Hill's sign",
 "How does Book p31 define 'locomotor brachii', and what two cuff-and-artery combinations are given for measuring lower-limb systolic BP when testing Hill's sign?",
 ["Tortuous and highly pulsatile brachial artery; (1) popliteal artery with a lower-limb cuff over the thigh, or (2) posterior tibial artery with the cuff tied just above the medial malleolus",
  "Alternate flushing and blanching of the forearm skin; (1) femoral artery with an inguinal cuff, or (2) dorsalis pedis artery with a metatarsal cuff",
  "Visible venous pulsations in the antecubital fossa; (1) popliteal artery with a calf cuff, or (2) anterior tibial artery with a thigh cuff",
  "Systolic thrill over the axillary artery; (1) femoral artery at the mid-inguinal point, or (2) peroneal artery above the lateral malleolus"],
 0,
 "Locomotor brachii is a tortuous and highly pulsatile brachial artery. For Hill's sign (LL SBP >20 mmHg above UL SBP), lower-limb BP can be measured in the popliteal artery with a lower-limb cuff over the thigh, or over the posterior tibial artery with the cuff tied just above the medial malleolus. (Book p31)"),

(31, "numeric", "Peripheral Signs of Aortic Regurgitation & Hill's Sign",
 "Grading the severity of aortic regurgitation by Hill's sign",
 "In Hill's sign on Book p31, what lower-limb minus upper-limb systolic BP thresholds correspond to mild, moderate and severe aortic regurgitation?",
 [">10 mmHg = mild AR; >20 mmHg = moderate AR; >40 mmHg = severe AR",
  ">20 mmHg = mild AR; >40 mmHg = moderate AR; >60 mmHg = severe AR",
  ">15 mmHg = mild AR; >30 mmHg = moderate AR; >45 mmHg = severe AR",
  ">30 mmHg = mild AR; >50 mmHg = moderate AR; >70 mmHg = severe AR"],
 1,
 "Book p31 grades Hill's sign as: >20 mmHg = mild AR, >40 mmHg = moderate AR, and >60 mmHg = severe AR. (Book p31)"),

(31, "scenario", "Peripheral Signs of Aortic Regurgitation & Hill's Sign",
 "Physical mechanism of Hill's sign (Jules Constant) and causes of a falsely low Hill's sign",
 "Direct intra-arterial catheterisation in a patient with severe AR and a +65 mmHg Hill's sign shows identical systolic pressures in the brachial and femoral arteries. How does Book p31 (citing Jules Constant) explain Hill's sign, and which two conditions produce a falsely low Hill's sign?",
 ["Hill's sign reflects true hydrostatic pressure amplification in the supine posture; it is falsely low in patent ductus arteriosus and hyperthyroidism",
  "Hill's sign is a sphygmomanometer artefact caused by summation of reflected waves from the periphery with forward waves of the central arteries; it is falsely low in CHF (decreased stroke volume / myocardial contraction) and severe AS",
  "Hill's sign is caused by Bernoulli suction in the descending thoracic aorta; it is falsely low in mitral regurgitation and atrial fibrillation",
  "Hill's sign is caused by femoral arterial calcification; it is falsely low in coarctation of the aorta above the left subclavian artery"],
 1,
 "Book p31 (citing Jules Constant) notes that Hill's sign is an artefact of the sphygmomanometer (intra-arterial measurements are the same in UL and LL arteries), believed to result from reflected peripheral waves summating with central forward waves. A falsely low Hill's sign occurs in (i) CHF (decreased stroke volume, as Hill's sign depends on myocardial contraction) and (ii) severe AS. (Book p31)"),

(31, "truefalse", "Peripheral Signs of Aortic Regurgitation & Hill's Sign",
 "Dependence of Hill's sign on myocardial contraction",
 "Which of the following True/False statements accurately reflects the note on a 'falsely low Hill's sign' on Book p31?",
 ["True: The presence of Hill's sign depends on myocardial contraction, so congestive heart failure (decreased stroke volume) and severe aortic stenosis produce a falsely low Hill's sign",
  "True: Congestive heart failure and severe aortic stenosis produce a falsely high Hill's sign exceeding 80 mmHg",
  "False: Intra-arterial blood pressure measurements are the same in the upper-limb and lower-limb arteries in Hill's sign",
  "False: Severe aortic stenosis is a cause of a falsely low Hill's sign"],
 0,
 "Item 8.e on Book p31 states that a falsely low Hill's sign (where the BP difference is lower than the actual severity of AR) occurs in CHF — due to decreased stroke volume, as the presence of Hill's sign depends on myocardial contraction — and in severe AS. (Book p31)"),

(31, "match", "Peripheral Signs of Aortic Regurgitation & Hill's Sign",
 "Visceral and femoral peripheral signs of AR (signs 9–16 on p31)",
 "Match each peripheral sign of aortic regurgitation on Book p31 to its description — 1) Quincke's sign 2) Rosenbach's sign vs Gerhardt's sign 3) Duroziez's murmur vs proximal femoral compression murmur 4) Traube's pistol-shot femorals … A) Alternate flushing and pallor when light pressure is applied to the nail bed B) Booming sound produced after pressing the stethoscope over the femoral artery C) Rosenbach's = pulsations in the liver; Gerhardt's = pulsations in an enlarged spleen D) Diastolic murmur on distal femoral artery compression [Duroziez] vs systolic murmur on proximal femoral artery compression",
 ["1-B, 2-C, 3-D, 4-A",
  "1-A, 2-D, 3-C, 4-B",
  "1-A, 2-C, 3-D, 4-B",
  "1-C, 2-A, 3-D, 4-B"],
 2,
 "Signs 9–16 on Book p31: (9) Corrigan's water-hammer/collapsing pulse, (10) Quincke's sign (capillary nail-bed flushing and pallor on light pressure), (11) Suprasternal pulsations, (12) Rosenbach's sign (hepatic pulsations), (13) Gerhardt's sign (pulsations in an enlarged spleen), (14) Duroziez's murmur (diastolic murmur on distal femoral compression), (15) Traube's pistol-shot femorals (booming sound over femoral artery), and (16) systolic murmur on proximal femoral compression. (Book p31)"),

(31, "scenario", "Peripheral Signs of Aortic Regurgitation & Hill's Sign",
 "Distinguishing Rosenbach's sign from Gerhardt's sign in severe AR",
 "In a patient with chronic severe aortic regurgitation and hepatosplenomegaly, you palpate systolic pulsations over both the liver and the enlarged spleen. Which pair of eponyms on Book p31 names these two findings?",
 ["Rosenbach's sign = pulsations in the liver; Gerhardt's sign = pulsations in the enlarged spleen",
  "Gerhardt's sign = pulsations in the liver; Rosenbach's sign = pulsations in the enlarged spleen",
  "Becker's sign = pulsations in the liver; Landolfi's sign = pulsations in the enlarged spleen",
  "Muller's sign = pulsations in the liver; Quincke's sign = pulsations in the enlarged spleen"],
 0,
 "Items 12 and 13 on Book p31 define Rosenbach's sign as pulsations in the liver and Gerhardt's sign as pulsations in an enlarged spleen. (Book p31)"),

(31, "fillup", "Peripheral Signs of Aortic Regurgitation & Hill's Sign",
 "Distal vs proximal compression of the femoral artery in AR (Duroziez's sign)",
 "In aortic regurgitation on Book p31, compressing the femoral artery distally produces a ____ murmur (Duroziez's murmur), whereas compressing the femoral artery proximally produces a ____ murmur.",
 ["Diastolic; systolic",
  "Systolic; diastolic",
  "Continuous; mid-diastolic",
  "Presystolic; pansystolic"],
 0,
 "Items 14 and 16 on Book p31 contrast the two components of femoral compression: distal compression produces a diastolic murmur (Duroziez's murmur, from retrograde diastolic flow), whereas proximal compression produces a systolic murmur (from antegrade systolic flow). (Book p31)"),

(31, "recall", "Cardiac Inspection: Neck, Precordium & Pulsations",
 "Opening sequence of cardiac inspection: JVP, trachea, thyroid",
 "Cardiac examination on Book p31 opens under 'Inspection' with JVP, trachea, and thyroid. If a thyroid swelling is present, what does the note specifically instruct you to look out for?",
 ["Hoarseness from recurrent laryngeal nerve palsy and superior vena caval obstruction",
  "Thyrotoxicosis — look out for palpitations and other eye signs",
  "Myxoedema coma — look out for non-pitting ankle oedema and loss of lateral eyebrows",
  "Medullary thyroid carcinoma — look out for marfanoid habitus and mucosal neuromas"],
 1,
 "Under Cardiac Examination -> Inspection on Book p31, the first three items are (1) JVP, (2) Trachea, and (3) Thyroid: 'If present, thyrotoxicosis — look out for palpitations and other eye signs.' (Book p31)"),

# ---------------------------------------------------------------- Book p32
(32, "match", "Cardiac Inspection: Neck, Precordium & Pulsations",
 "Precordial bulge detection, four cause groups and backward bulge on Book p32",
 "Match each precordial inspection item on Book p32 to its description — 1) Clue to precordial bulge in males 2) Skeletal and pleuropulmonary causes of precordial bulge 3) Cardiac, pericardial and localised causes of precordial bulge 4) Backward bulge of the precordium … A) Ventricular hypertrophy, pericardial effusion, and localised bulging from a post-MI ventricular aneurysm B) Pectus excavatum C) Lateral displacement and elevation of the left nipple D) Scoliosis, kyphoscoliosis, rachitic deformity, bronchial carcinoma and pleural effusion",
 ["1-C, 2-D, 3-A, 4-B",
  "1-D, 2-C, 3-A, 4-B",
  "1-C, 2-A, 3-D, 4-B",
  "1-B, 2-D, 3-A, 4-C"],
 0,
 "On Book p32, a good sign for detecting a precordial bulge in males is lateral displacement and elevation of the left nipple. Its four cause groups are skeletal anomalies (scoliosis, kyphoscoliosis, rachitic deformity), lung/pleural diseases (bronchial carcinoma, pleural effusion), heart/pericardial diseases (ventricular hypertrophy, pericardial effusion), and localised bulging (aneurysm, possibly secondary to MI). Backward bulges are pectus excavatum. (Book p32)"),

(32, "oddoneout", "Cardiac Inspection: Neck, Precordium & Pulsations",
 "Causes of precordial bulge vs backward bulge on Book p32",
 "Which of the following is listed on Book p32 as a 'backward bulge' of the precordium rather than a cause of a precordial bulge?",
 ["Scoliosis, kyphoscoliosis or rachitic deformity",
  "Bronchial carcinoma or pleural effusion",
  "Ventricular hypertrophy, pericardial effusion or post-MI ventricular aneurysm",
  "Pectus excavatum"],
 3,
 "Book p32 groups scoliosis/kyphoscoliosis/rachitic deformity, bronchial carcinoma/pleural effusion, ventricular hypertrophy/pericardial effusion, and post-MI aneurysm under 'Causes of precordial bulge', and lists pectus excavatum under 'Backward bulges'. (Book p32)"),

(32, "scenario", "Cardiac Inspection: Neck, Precordium & Pulsations",
 "Tangential inspection of apex, visible parasternal heave and see-saw precordial movement",
 "While inspecting the precordium tangentially from the left side (Book p32), you observe an inward movement of the apex accompanied by an outward movement of the precordium during systole (see-saw movement). What does this pattern signify, and what causes a visible parasternal heave?",
 ["Left ventricular hypertrophy causes inward apical movement with outward precordial movement; visible parasternal heave is caused only by right atrial myxoma",
  "Right ventricular hypertrophy causes inward movement of the apex with outward movement of the precordium during systole (LV hypertrophy produces the reverse); visible parasternal heave is due to massive RV hypertrophy or sometimes LA enlargement",
  "Cardiac tamponade causes see-saw precordial movement; visible parasternal heave is specific for ascending aortic aneurysm",
  "Pectus excavatum causes see-saw movement; visible parasternal heave occurs only in tricuspid atresia"],
 1,
 "Book p32 notes: look tangentially from the left side for the apical impulse; a visible parasternal heave indicates massive RV hypertrophy (or sometimes LA enlargement); in see-saw movements, RV hypertrophy gives inward movement of the apex with outward movement of the precordium during systole, while LV hypertrophy gives the reverse. (Book p32)"),

(32, "match", "Cardiac Inspection: Neck, Precordium & Pulsations",
 "Regional thoracic and back pulsations on inspection (Book p32)",
 "Match each anatomical site of visible pulsation on Book p32 to its listed causes — 1) High thoracic region: 2nd right intercostal space 2) 2nd or 3rd left intercostal space 3) Suprasternal notch pulsation 4) Back pulsations … A) Coarctation of the aorta [Suzman's sign] B) Ascending aortic aneurysm, aortic regurgitation or dilation of the aorta C) Pulmonary artery dilation, hyperkinetic states or aneurysm of the aorta D) Can be physiological; pathological causes are aortic regurgitation and aortic arch aneurysm",
 ["1-C, 2-B, 3-D, 4-A",
  "1-B, 2-C, 3-A, 4-D",
  "1-B, 2-C, 3-D, 4-A",
  "1-D, 2-C, 3-B, 4-A"],
 2,
 "Book p32 localises visible pulsations: 2nd right ICS = ascending aortic aneurysm, AR, dilation of aorta; 2nd/3rd left ICS = pulmonary artery dilation, hyperkinetic states, aortic aneurysm; suprasternal = physiological or aortic pathology (AR, aortic arch aneurysm); back pulsations = coarctation of aorta (Suzman's sign). (Book p32)"),

(32, "fillup", "Cardiac Inspection: Neck, Precordium & Pulsations",
 "Suzman's sign of coarctation of the aorta",
 "Visible pulsations over the back in coarctation of the aorta are named ____ sign on Book p32.",
 ["Suzman's",
  "Trail's",
  "Oliver's",
  "Broadbent's"],
 0,
 "Item 4.d.vi on Book p32 states: 'Back pulsations — Coarctation of aorta (Suzman sign)'. (Book p32)"),

(32, "scenario", "Cardiac Inspection: Neck, Precordium & Pulsations",
 "Differentiating right ventricular vs abdominal aortic epigastric pulsations on inspection",
 "On inspecting the epigastrium (Book p32), how do you distinguish an epigastric pulsation originating from the right ventricle from one originating from the abdominal aorta?",
 ["Right ventricular pulsation coincides with the apex beat and is located higher up in the epigastrium; abdominal aortic pulsation (seen physiologically in thin people, in AAA, or with a mass on the aorta) occurs after the apex beat and is located lower down in the epigastrium",
  "Right ventricular pulsation occurs after the apex beat in the lower epigastrium; abdominal aortic pulsation precedes the apex beat in the subxiphoid notch",
  "Right ventricular pulsation is expansile in all directions; abdominal aortic pulsation disappears completely during expiration",
  "Both coincide exactly with the apex beat and can only be separated after inspecting for dilated veins, scars and sinuses"],
 0,
 "Book p32 contrasts the two origins of epigastric pulsation: from the RV, it coincides with the apex beat and lies higher up in the epigastrium; from the abdominal aorta (physiological in thin people, AAA, or a mass on the aorta), it occurs after the apex beat and lies lower down in the epigastrium (followed by inspecting for dilated veins, scars and sinuses). (Book p32)"),

# ---------------------------------------------------------------- Book p33
(33, "numeric", "JVP: Definition, RAP Conversion, POLICE & IJV vs EJV",
 "Definition of JVP, normal RAP (Macleod) and sternal angle offset",
 "Book p33 defines the JVP as the vertical height from the sternal angle to the zone of transition of distended and collapsed internal jugular veins. According to Macleod as quoted on p33, normal right atrial pressure (RAP) is ____, and because the sternal angle lies ____ above the right atrium, the normal JVP height is ____.",
 ["<7 mmHg / 9 cm water; 5 cm; <=4 cm",
  "<10 mmHg / 12 cm water; 7 cm; <=5 cm",
  "<5 mmHg / 6 cm water; 3 cm; <=3 cm",
  "<8 mmHg / 10 cm water; 4 cm; <=6 cm"],
 0,
 "On Book p33: normal RAP is <7 mmHg / 9 cm water (Macleod); since the sternal angle is 5 cm above the right atrium, normal JVP should be <=4 cm above the sternal angle. (Book p33)"),

(33, "numeric", "JVP: Definition, RAP Conversion, POLICE & IJV vs EJV",
 "Converting JVP height in cm of water to right atrial pressure in mmHg",
 "A patient's JVP is measured at 5 cm vertically above the sternal angle. Using the two-step conversion formula on Book p33, how do you calculate the right atrial pressure (RAP) in mmHg?",
 ["Add 5 cm (sternal angle to RA distance) to get 10 cm water, then multiply by 0.736 to get 7.36 mmHg",
  "Subtract 5 cm from the JVP height to get 0 cm water, then multiply by 1.36 to get 0 mmHg",
  "Add 3 cm to the JVP height to get 8 cm water, then divide by 0.736 to get 10.87 mmHg",
  "Multiply 5 cm directly by 0.736 without adding the sternal-angle distance to get 3.68 mmHg"],
 0,
 "Step 3a on Book p33: add the height of the JVP from the sternal angle to 5 cm (distance from RA to sternal angle). Step 3b: multiply that total cm H2O height by 0.736 to convert cm H2O into mmHg RAP. (Book p33)"),

(33, "match", "JVP: Definition, RAP Conversion, POLICE & IJV vs EJV",
 "POLICE mnemonic for differentiating JVP from the carotid pulse",
 "Match each letter of the 'POLICE' mnemonic on Book p33 for JVP vs Carotid to its JVP characteristic — 1) P and O: Palpation and Occlusion 2) L: Location 3) I: Inspiration 4) C and E: Contour and Erection … A) Between the heads of the sternocleidomastoid muscle, lateral to the carotid B) Non-palpable and readily occludable C) Biphasic waveform that drops when sitting erect D) Drops with inspiration",
 ["1-A, 2-B, 3-D, 4-C",
  "1-B, 2-A, 3-D, 4-C",
  "1-B, 2-A, 3-C, 4-D",
  "1-D, 2-A, 3-B, 4-C"],
 1,
 "The POLICE mnemonic on Book p33: P = Palpation (non-palpable), O = Occlusion (readily occludable), L = Location (between the heads of SCM, lateral to carotid), I = Inspiration (drops with inspiration), C = Contour (biphasic waveform), E = Erection (drops when sitting erect). (Book p33)"),

(33, "truefalse", "JVP: Definition, RAP Conversion, POLICE & IJV vs EJV",
 "Why the internal jugular vein is preferred over the external jugular vein (and the severe TR exception)",
 "Which of the following True/False statements accurately reflects the comparison between the internal jugular vein (IJV) and external jugular vein (EJV) on Book p33?",
 ["True: The EJV is in direct straight-line communication with the SVC, whereas the IJV makes two 90-degree turns through fascial planes",
  "True: The IJV communicates in a direct straight line with the SVC and RA (while the EJV makes two near-90° turns, can be compressed by fascial planes, and can constrict in shock/HF), and the IJV itself is never visible except in severe TR — only its transmitted skin pulsations are seen",
  "False: In shock or heart failure, sympathetic stimulation can constrict the EJV and render it invisible",
  "False: The IJV is never directly visible except in severe tricuspid regurgitation"],
 1,
 "Book p33 gives four points comparing IJV and EJV: (a) IJV is in a direct straight line with the SVC and RA, while EJV makes two near-90° turns; (b) EJV runs through fascial planes and can be compressed; (c) EJV can constrict and become invisible in shock/HF due to sympathetic stimulation; (d) the IJV itself is never visible (except in severe TR) — its pulsations are transmitted to the skin. (Book p33)"),

(33, "scenario", "JVP: Definition, RAP Conversion, POLICE & IJV vs EJV",
 "Why the right IJV is preferred over the left IJV (innominate vein compression)",
 "In an elderly, severely arteriosclerotic patient, the left jugular venous column appears elevated while the right IJV is normal. According to Book p33, why is the right IJV always preferred over the left IJV?",
 ["Because the thoracic duct drains into the right IJV and obscures its pulsations after a fatty meal",
  "Because the left IJV lacks a superior bulb valve and transmits left atrial pressure directly",
  "Because in severely arteriosclerotic patients the left innominate (brachiocephalic) vein can be compressed between the sternum and arteries arising from the aortic arch, causing a falsely elevated left JVP",
  "Because the right innominate vein crosses behind the oesophagus and is compressed in left atrial enlargement"],
 2,
 "Item 6 on Book p33 states: the right IJV is preferred to the left IJV because in severely arteriosclerotic patients, the left innominate vein can get compressed between the sternum and arteries arising from the aortic arch and cause a falsely elevated JVP. (Book p33)"),

(33, "numeric", "JVP: Definition, RAP Conversion, POLICE & IJV vs EJV",
 "Harrison's 21e Chapter 239 JVP threshold at 30 degrees (bottom reference box on p33)",
 "In the red reference box at the bottom of Book p33 pointing to Harrison's 21e Chapter 239, what JVP height above the sternal angle (angle of Louis) at 30 degrees elevation is cited as abnormal?",
 [">2.5 cm at 30 degrees",
  ">3.0 cm at 30 degrees",
  ">4.5 cm at 30 degrees",
  ">6.0 cm at 30 degrees"],
 2,
 "The Harrison's 21e Chapter 239 summary box at the foot of Book p33 highlights: 'angle of Louis vs clavicle, >4.5 cm at 30 degrees, a/c/v waves and x/y descents, Kussmaul's sign, abdominojugular reflux'. (Book p33)"),
]
