# -*- coding: utf-8 -*-
"""Chapter 4 source data, Part B: Book p42-47 (S1, S2 & Split S2 in ASD, S3 & S4, Added Sounds, Dynamic Manoeuvres, Named Murmurs)."""

# (page, fmt, sec, point, question, options, ans, explanation)
B = [
# ---------------------------------------------------------------- Book p42
(42, "scenario", "Heart Sounds S1, S2, Split S2 in ASD, S3 & S4",
 "Two theories for a loud S1 in mitral stenosis and the LA-LV pressure crossover slope diagram (A vs B) on Book p42",
 "On Book p42, why is S1 loud in mitral stenosis (MS), and what do curves A ('Steep slope at crossover point') and B ('Shallow slope at crossover point') in the LA-LV pressure crossover diagram illustrate?",
 ["(i) dP/dt theory: elevated LA pressure forces the LV to reach a higher pressure to shut the mitral valve, so crossover occurs on a steeper part of the LV dP/dt curve (Curve A vs normal Curve B); and (ii) Wide closing excursion: the high AV pressure gradient at the onset of systole keeps the leaflets maximally separated so they close through a wider excursion",
  "(i) Bernheim theory: the hypertrophied septum strikes the anterior mitral leaflet; and (ii) Curve A represents low LA pressure with a shallow crossover slope",
  "(i) Early diastolic recoil of the aortic root; and (ii) Curve B represents tight mitral stenosis with a steep crossover slope",
  "(i) Premature closure of the mitral valve before the QRS complex; and (ii) Curves A and B compare inspiration and expiration"],
 0,
 "Item 2.a on Book p42 (with the accompanying LV/LA pressure crossover diagram) explains the two theories for a loud S1 in MS: (i) dP/dt theory — elevated LA pressure shifts the LV-LA pressure crossover to a steeper part of the LV pressure curve (Curve A: steep slope at crossover point, vs Curve B: shallow slope); and (ii) wide closing excursion — the high atrioventricular gradient at the onset of systole keeps the leaflets maximally separated. (Book p42)"),

(42, "match", "Heart Sounds S1, S2, Split S2 in ASD, S3 & S4",
 "Other causes of a loud S1 (hyperdynamic states, holosystolic MVP, LA myxoma, short PR, Ebstein's sail sound) vs soft S1 on Book p42",
 "Match each cause of altered S1 intensity on Book p42 to its exact mechanism — 1) Holosystolic MVP with MR and LA myxoma 2) Short PR interval 3) Ebstein's anomaly ['sail sound'] 4) Causes of a Soft S1 … A) Calcific MS, MR, long PR interval, TR and acute AR B) Atrialization of the RV causes the malformed tricuspid valve to close late at a higher RV pressure [producing a loud S1 / 'sail sound'] C) Ventricle contracts before the LA has time to relax -> short x descent -> high LA pressure -> LV crosses LA pressure on a steeper slope of the dP/dt curve D) In holosystolic MVP, prolapse delays leaflet tension until peak ventricular contraction; in LA myxoma, the tumour delays valve closure",
 ["1-D, 2-C, 3-B, 4-A",
  "1-C, 2-D, 3-B, 4-A",
  "1-D, 2-B, 3-C, 4-A",
  "1-D, 2-C, 3-A, 4-B"],
 0,
 "Items 2.b–f and 3.a–e on Book p42 detail all causes of a loud S1 (MS, hyperdynamic states, holosystolic MVP with MR, LA myxoma, short PR interval, and Ebstein's anomaly 'sail sound') and a soft S1 (calcific MS, MR, long PR interval, TR, and acute AR). (Book p42)"),

(42, "fillup", "Heart Sounds S1, S2, Split S2 in ASD, S3 & S4",
 "Ebstein's anomaly 'sail sound' and short PR interval mechanism on Book p42",
 "In Ebstein's anomaly (Book p42), ____ of the right ventricle causes the malformed tricuspid valve to close late at a higher RV pressure, producing a loud S1 called the '____'; in a short PR interval, the ventricle contracts before the LA has time to relax, producing a short ____ descent and high LA pressure at crossover.",
 ["Atrialization; sail sound; x",
  "Ventricularization; pericardial knock; y",
  "Calcification; tumour plop; c",
  "Hypertrophy; seagull sound; v"],
 0,
 "Items 2.e and 2.f on Book p42 state: in a short PR interval, the ventricle contracts before the LA has had time to relax -> short x descent -> high LA pressure -> LV crosses LA pressure on a steeper slope of the dP/dt curve; in Ebstein's anomaly, atrialization of the RV causes the malformed tricuspid valve to close late at a higher RV pressure -> loud S1 ('sail sound'). (Book p42)"),

# ---------------------------------------------------------------- Book p43
(43, "numeric", "Heart Sounds S1, S2, Split S2 in ASD, S3 & S4",
 "Split S1 interval (M1-T1) vs normal inspiratory S2 split duration on Book p43",
 "According to Book p43, normally M1 precedes T1 by just ____ (widening in RBBB, including the RBBB associated with Ebstein's anomaly), whereas a normal inspiratory S2 split has a duration of ____.",
 ["20–30 msec; <0.03 seconds",
  "80–100 msec; >0.10 seconds",
  "5–10 msec; 0.08–0.12 seconds",
  "50–60 msec; <0.12 seconds"],
 0,
 "Book p43 states: under Split S1, normally M1 is just 20–30 msec before T1 (and in RBBB — which is also associated with Ebstein's anomaly — T1 is heard much after M1); under Second Heart Sound (S2), normal split is seen in inspiration and normal duration is <0.03 seconds. (Book p43)"),

(43, "match", "Heart Sounds S1, S2, Split S2 in ASD, S3 & S4",
 "S2 split anomalies (text and diagram on Book p43): wide variable, wide fixed and paradoxical splitting",
 "Match each S2 splitting abnormality on Book p43 (text and 'S2 split and its anomalies' diagram) to its causes and mechanism — 1) Wide variable split due to early A2 2) Wide variable split due to delayed P2 3) Wide fixed split 4) Paradoxical [reversed] split [P2 precedes A2 in expiration and narrows in inspiration] … A) Pulmonary stenosis (PS) B) Conditions that delay LV emptying: aortic stenosis (AS) and left bundle branch block (LBBB) C) VSD and mitral regurgitation (MR) D) ASD, TAPVC and RBBB",
 ["1-A, 2-C, 3-D, 4-B",
  "1-C, 2-A, 3-D, 4-B",
  "1-C, 2-D, 3-A, 4-B",
  "1-C, 2-A, 3-B, 4-D"],
 1,
 "Item 1.c–f and the accompanying diagram on Book p43 classify S2 splitting into: wide variable split from early A2 (VSD, MR) or delayed P2 (PS); wide fixed split (ASD, TAPVC, RBBB); and paradoxical split from delayed LV emptying (AS, LBBB, where P2 occurs before A2 in expiration and merges on inspiration). (Book p43)"),

(43, "scenario", "Heart Sounds S1, S2, Split S2 in ASD, S3 & S4",
 "Perloff's two-part explanation for why S2 is both WIDELY split and FIXED in ASD (Book p43)",
 "Citing Perloff's Physical Examination of the Heart and Circulation, Book p43 separately explains (i) why S2 is WIDELY split in ASD and (ii) why the split is FIXED across respiration. Which statement captures both mechanisms?",
 ["(i) Wide split: increased pulmonary 'hangout interval' (interval between RV-PA pressure crossover and pulmonary valve closure) due to low pulmonary vascular resistance prolonging RV ejection (unlike the high-resistance systemic circuit where the aortic valve has almost no hangout interval); (ii) Fixed split: the inspiratory increase in systemic venous return to the RA is matched by a reciprocal decrease in the left-to-right shunt across the ASD, minimising respiratory variation in RV filling",
  "(i) Wide split: left bundle branch block delays A2 behind P2; (ii) Fixed split: pulmonary hypertension fuses the right and left ventricular ejection times",
  "(i) Wide split: premature closure of the aortic valve into the left atrium; (ii) Fixed split: complete absence of the interatrial septum prevents any pressure gradient in systole",
  "(i) Wide split: tricuspid regurgitation shortens RV systole; (ii) Fixed split: the Valsalva effect of normal inspiration closes the foramen ovale"],
 0,
 "Item 1.g on Book p43 details both parts: (i) Why widely split — increased pulmonary hangout interval (interval between RV-PA pressure crossover and pulmonary valve closure) in the low-resistance pulmonary bed prolongs RV ejection; (ii) Why fixed — inspiratory increase in systemic venous return to the RA is matched by a reciprocal decrease in the left-to-right transatrial shunt, keeping RV filling constant across respiration. (Book p43)"),

# ---------------------------------------------------------------- Book p44
(44, "match", "Heart Sounds S1, S2, Split S2 in ASD, S3 & S4",
 "TAPVC and massive PE in S2 splitting, S3 physiological vs pathological causes, and S4 causes on Book p44",
 "Match each heart sound concept on Book p44 to its listed mechanism and causes — 1) Other causes of wide/fixed S2 split on p44 2) Physiological S3 [initial passive filling of ventricles in diastole] 3) Pathological S3 4) Fourth heart sound (S4) … A) Emptying of atria into a stiff ventricle: systemic HTN, CAD, severe AS, HOCM and restrictive cardiomyopathy (RCM) B) Children, athletes and pregnancy C) TAPVC [one or more pulmonary veins connect to RA, producing an effect similar to ASD] and massive acute pulmonary embolism D) MR/TR [increased atrial volume filling ventricles], high-output states, CHD [ASD, VSD, PDA], HOCM, systolic HF [overly compliant myocardium -> dilated LV], and systemic/pulmonary HTN",
 ["1-C, 2-B, 3-D, 4-A",
  "1-B, 2-C, 3-D, 4-A",
  "1-C, 2-D, 3-B, 4-A",
  "1-C, 2-B, 3-A, 4-D"],
 0,
 "Book p44 covers: other causes of wide/fixed S2 split (TAPVC, massive acute PE), A2/P2 intensity, S3 (initial passive ventricular filling in diastole: physiological in children, athletes, pregnancy; pathological in MR/TR, high-output states, CHD [ASD, VSD, PDA], HOCM, systolic HF with overly compliant myocardium and dilated LV, systemic/pulmonary HTN), and S4 (atrial emptying into a stiff ventricle: systemic HTN, CAD, severe AS, HOCM, RCM). (Book p44)"),

(44, "truefalse", "Heart Sounds S1, S2, Split S2 in ASD, S3 & S4",
 "Ventricular compliance in systolic heart failure (S3) vs stiff ventricle (S4) on Book p44",
 "Which of the following True/False statements accurately reflects the pathophysiology of S3 and S4 on Book p44?",
 ["True: In systolic heart failure producing an S3, the myocardium is overly compliant resulting in a dilated LV during initial passive diastolic filling, whereas an S4 is caused by atrial emptying into a stiff ventricle (systemic HTN, CAD, severe AS, HOCM, RCM)",
  "True: An S4 is physiological in children, athletes and pregnancy, whereas an S3 occurs only in restrictive cardiomyopathy",
  "False: HOCM can be associated with both a pathological S3 and an S4 on Book p44",
  "False: Soft A2 is seen in AS and soft P2 is seen in PS"],
 0,
 "Book p44 explicitly states that in systolic heart failure causing a pathological S3, 'the myocardium is overly compliant, resulting in a dilated LV', whereas S4 is caused by 'emptying of atria into a stiff ventricle' (systemic HTN, CAD, severe AS, HOCM, RCM). Note that HOCM appears in both lists on p44. (Book p44)"),

# ---------------------------------------------------------------- Book p45
(45, "match", "Added Sounds, OS vs S3 Table & Innocent Murmurs",
 "Added sounds phonocardiogram diagram (A–E) on Book p45",
 "Match each trace (A–E) in the 'Added sounds' diagram on Book p45 to the heart sound or prosthetic valve event it depicts — 1) Trace A and Trace B 2) Trace C 3) Trace D [Prosthetic mitral valve] 4) Trace E [Prosthetic aortic valve] … A) Closing click coincides with S1; opening click occurs in early diastole after S2 [at the timing of an opening snap] B) Opening click occurs in early systole after S1 [at the timing of an ejection click]; closing click coincides with S2 C) Trace A = Opening snap in early diastole after S2; Trace B = Ejection click in early systole just after S1 D) Midsystolic click between S1 and S2",
 ["1-C, 2-D, 3-B, 4-A",
  "1-C, 2-D, 3-A, 4-B",
  "1-D, 2-C, 3-A, 4-B",
  "1-C, 2-A, 3-D, 4-B"],
 1,
 "The 'Added sounds' diagram on Book p45 shows: (A) Opening snap after S2; (B) Ejection click shortly after S1; (C) Midsystolic click in mid-systole; (D) Prosthetic mitral valve closing at S1 and opening after S2; and (E) Prosthetic aortic valve opening after S1 and closing at S2. (Book p45)"),

(45, "scenario", "Added Sounds, OS vs S3 Table & Innocent Murmurs",
 "Protodiastolic gallop (S1-S2-S3) and differentiating an Opening Snap from a split S2 on standing (Book p45)",
 "Both S3 and S4 are heard with the bell of the stethoscope, and S1-S2-S3 is called a gallop rhythm ('canter of a galloping horse' / 'protodiastolic gallop'). At the bedside, how does asking the patient to STAND differentiate an opening snap (OS) of mitral stenosis from a split S2 (Book p45)?",
 ["On standing, the S2–OS gap INCREASES, whereas the A2–P2 gap of a split S2 REDUCES because venous return decreases",
  "On standing, the S2–OS gap NARROWS and disappears, whereas the A2–P2 gap WIDENS due to increased systemic vascular resistance",
  "On standing, both the S2–OS gap and the A2–P2 gap remain completely unchanged",
  "On standing, an opening snap transforms into a presystolic murmur whereas a split S2 becomes paradoxical"],
 0,
 "Item 3.c on Book p45 states the bedside rule: 'OS vs S2: S2-OS gap increases on standing; A2-P2 gap reduces on standing because venous return decreases.' Its differential diagnosis (3.d) includes split S2, S3 and pericardial knock. (Book p45)"),

(45, "recall", "Added Sounds, OS vs S3 Table & Innocent Murmurs",
 "Three bedside differential diagnoses of an Opening Snap (OS) on Book p45",
 "Which triad of heart sounds is listed under 'Ddx of OS' (Item 3.d) at the bottom of Book p45?",
 ["Split S2, S3, and Pericardial knock",
  "S4, Aortic ejection click, and Midsystolic click",
  "Split S1, Mammary souffle, and Venous hum",
  "Austin Flint murmur, Carey-Coombs murmur, and Graham Steell's murmur"],
 0,
 "Item 3.d on Book p45 lists the three differential diagnoses of an opening snap: (i) Split S2, (ii) S3, and (iii) Pericardial knock. (Book p45)"),

# ---------------------------------------------------------------- Book p46
(46, "match", "Added Sounds, OS vs S3 Table & Innocent Murmurs",
 "Opening Snap (OS) vs S3 comparison table on Book p46",
 "Match each feature in the 'OS vs S3' comparison table on Book p46 — 1) Cause and character 2) Best heard with and radiation 3) Timing and effect of standing 4) Effect of treating heart failure … A) OS: early part of diastole, S2–OS gap widens on standing; S3: mid-diastole, unchanged on standing B) OS: becomes LOUDER after treating HF; S3: is LOST after treating HF C) OS: bellowing down of closed MV cusp at onset of ventricular diastole [MS], sharp, high-pitched, LOUD; S3: passive ventricular filling [HF/chronic MI], low-pitched D) OS: diaphragm, loudest at left parasternal border especially on standing, radiates [++]; S3: bell, best heard at apex in left lateral position, no radiation [-]",
 ["1-C, 2-D, 3-A, 4-B",
  "1-D, 2-C, 3-A, 4-B",
  "1-C, 2-A, 3-D, 4-B",
  "1-C, 2-D, 3-B, 4-A"],
 0,
 "The OS vs S3 table on Book p46 contrasts every row: Cause (bellowing down of closed MV cusp in MS vs passive ventricular filling in HF/chronic MI), Character (sharp, high-pitched, loud vs low-pitched), Best heard with (diaphragm at LPSB especially on standing vs bell at apex in LLP), Radiation (++ vs -), Timing (early diastole vs mid-diastole), Standing (S2-OS widens vs unchanged), and After treating HF (OS becomes louder vs S3 is lost). (Book p46)"),

(46, "management", "Added Sounds, OS vs S3 Table & Innocent Murmurs",
 "Auscultatory technique and effect of treating heart failure on Opening Snap vs S3 on Book p46",
 "In a patient with decompensated heart failure and an extra diastolic sound, how should you position the patient and apply the stethoscope to distinguish an Opening Snap (OS) from an S3 gallop, and how does medical treatment of heart failure alter each sound (Book p46)?",
 ["Listen for OS with the diaphragm at the left parasternal border (especially on standing, where S2–OS widens) and for S3 with the bell at the apex in the left lateral position; after treating heart failure, the OS becomes LOUDER whereas the S3 is LOST",
  "Listen for OS with the bell at the apex in the left lateral position and for S3 with the diaphragm at the right 2nd ICS; after treating heart failure, the OS disappears whereas the S3 becomes louder",
  "Listen for both sounds with the diaphragm at Erb's point while squatting; treating heart failure abolishes both OS and S3 equally",
  "Listen for OS at the carotid artery and S3 over the xiphisternum; treating heart failure narrows the S2–OS interval to zero"],
 0,
 "The OS vs S3 table on Book p46 specifies: OS is best heard with the diaphragm, loudest at the left parasternal border especially on standing (where S2–OS widens) and becomes louder after treating HF; S3 is best heard with the bell at the apex in the left lateral position (unchanged on standing) and is lost after treating HF. (Book p46)"),

(46, "match", "Added Sounds, OS vs S3 Table & Innocent Murmurs",
 "Ejection clicks (pulmonary vs aortic), pericardial knock, triphasic pericardial rub and tumour plop on Book p46",
 "Match each added sound on Book p46 (items 4–8) to its description — 1) Ejection click [semilunar valve opening] 2) Pericardial knock 3) Pericardial rub 4) Tumour plop and prosthetic sound … A) Friction between the two pericardial layers; classically triphasic — presystolic, mid-systolic and mid-diastolic B) Loud high-frequency diastolic sound due to an abrupt halt to early diastolic filling in constrictive pericarditis C) Pulmonary ejection click varies with respiration [noted on p46 as increasing with inspiration; see also p47 Carvallo exception]; aortic ejection click does NOT change with respiration and is heard all over the precordium D) Mobile left atrial myxoma [tumour plop] and mechanical valve clicks [prosthetic sound]",
 ["1-C, 2-B, 3-A, 4-D",
  "1-B, 2-C, 3-A, 4-D",
  "1-C, 2-A, 3-B, 4-D",
  "1-C, 2-B, 3-D, 4-A"],
 0,
 "Items 4–8 on Book p46 describe: (4) Ejection click from opening of semilunar valves (pulmonary vs aortic, which does not change with respiration and is heard all over the precordium); (5) Pericardial knock in constrictive pericarditis; (6) Triphasic pericardial rub (presystolic, mid-systolic, mid-diastolic); (7) Tumour plop; and (8) Prosthetic sound. (Book p46)"),

(46, "oddoneout", "Added Sounds, OS vs S3 Table & Innocent Murmurs",
 "Innocent / functional murmurs vs pathological murmurs on Book p46",
 "All of the following statements about innocent (functional) murmurs on Book p46 are true EXCEPT:",
 ["They are soft (<3/6 intensity), often position-dependent, and occur in asymptomatic patients with no palpable thrill",
  "They occur only in systole or continuously — any pure diastolic murmur is always pathological",
  "Examples include Still's murmur (musical quality at the inferior aspect of the lower left sternal border), infraclavicular venous hum (continuous, heard with the bell), and mammary souffle",
  "They are typically Grade IV/VI or louder pure mid-diastolic murmurs accompanied by a palpable parasternal thrill"],
 3,
 "Under 'Innocent / functional murmurs' on Book p46, innocent murmurs are soft (<3/6), position-dependent, asymptomatic, systolic or continuous ('Any pure diastolic murmur is pathological'), have no palpable thrill, and include Still's murmur, infraclavicular venous hum (continuous, with bell), and mammary souffle. (Book p46)"),

# ---------------------------------------------------------------- Book p47
(47, "scenario", "Dynamic Auscultation, Systolic Murmur Timing & 10 Named Murmurs",
 "MVP leaflet orientation (/\\ at low volume vs __ __ at high volume) and dynamic manoeuvres on Book p47",
 "Book p47 illustrates the mitral valve in `/\\` orientation at low ventricular volume (conducive to early prolapse) versus `__ __` at higher ventricular volume (taking longer to prolapse). How do (1) Valsalva/standing and (2) sustained handgrip or rapid squatting affect the HOCM murmur and the MVP click/murmur?",
 ["Valsalva and standing (decreased preload/LV volume) INCREASE the intensity of the HOCM murmur and cause an EARLIER onset of the MVP click/murmur; sustained handgrip and rapid squatting DECREASE the intensity of the HOCM murmur and cause a LATER onset of the MVP click/murmur",
  "Valsalva and standing DECREASE the HOCM murmur and delay the MVP click; sustained handgrip and rapid squatting INCREASE the HOCM murmur and advance the MVP click",
  "Sustained handgrip increases both the AS and HOCM murmurs while abolishing MR, AR and VSD murmurs",
  "Rapid squatting decreases MS, AR and VSD murmurs while increasing the HOCM murmur"],
 0,
 "Items 1–4 on Book p47 explain: (1) Inspiration increases all right-sided murmurs except pulmonic ejection (Carvallo's sign); (2) Sustained handgrip (increases afterload) increases MR, AR, VSD, decreases HOCM and AS (due to increased LV volume), and causes later onset of click/murmur in MVP; (3) Valsalva and standing (decreased preload) decrease most murmurs including AS, increase HOCM, and cause earlier onset of click/murmur in MVP; (4) Rapid squatting (increased venous return, preload, afterload) decreases HOCM, increases MS, AR, VSD, and causes later onset of click/murmur in MVP. (Book p47)"),

(47, "fillup", "Dynamic Auscultation, Systolic Murmur Timing & 10 Named Murmurs",
 "Carvallo's sign and exception on Book p47, plus sustained handgrip effect on AS vs MR/AR/VSD",
 "According to Book p47, inspiration increases all right-sided murmurs EXCEPT ____ (Carvallo's sign), whereas sustained handgrip (which increases afterload) increases the intensity of ____ murmurs and decreases the intensity of ____ murmurs.",
 ["Pulmonic ejection; MR, AR and VSD; HOCM and AS",
  "Tricuspid regurgitation; HOCM and AS; MR, AR and VSD",
  "Tricuspid stenosis; ASD and PS; MS and VSD",
  "Pulmonic regurgitation; MVP and HOCM; AR and MR"],
 0,
 "Items 1 and 2 on Book p47 state: (1) Inspiration increases all right-sided murmurs except pulmonic ejection — Carvallo's sign; (2) Sustained handgrip (increases afterload) increases intensity of MR, AR, VSD murmurs and decreases HOCM and AS murmurs (because of increased LV volume). (Book p47)"),

(47, "match", "Dynamic Auscultation, Systolic Murmur Timing & 10 Named Murmurs",
 "Classification of systolic murmurs by timing (pansystolic, early, mid, late) on Book p47",
 "Match each timing class of systolic murmur on Book p47 to its listed causes — 1) Pansystolic 2) Early systolic 3) Mid-systolic 4) Late systolic … A) MVP, acute MI and tricuspid valve prolapse (TVP) B) Acute MR, muscular VSD and acute TR C) MR, TR and VSD D) Supravalvular AS, coarctation of aorta, AS, aortic sclerosis, HOCM, increased flow, PS, supravalvular PS and ASD [flow murmur]",
 ["1-C, 2-B, 3-D, 4-A",
  "1-B, 2-C, 3-D, 4-A",
  "1-C, 2-A, 3-D, 4-B",
  "1-C, 2-B, 3-A, 4-D"],
 0,
 "Under 'Systolic murmurs' on Book p47: (1) Pansystolic = MR, TR, VSD; (2) Early systolic = acute MR, muscular VSD, acute TR; (3) Mid-systolic = supravalvular AS, coarctation of aorta, AS, aortic sclerosis, HOCM, increased flow, PS, supravalvular PS, ASD (flow murmur); (4) Late systolic = MVP, acute MI, TVP. (Book p47)"),

(47, "truefalse", "Dynamic Auscultation, Systolic Murmur Timing & 10 Named Murmurs",
 "Early systolic (acute MR, muscular VSD, acute TR) vs pansystolic and late systolic murmurs on Book p47",
 "Which of the following True/False statements accurately reflects the systolic murmur classification on Book p47?",
 ["True: Acute MR, muscular VSD and acute TR produce early systolic murmurs (unlike chronic MR, TR and VSD, which are pansystolic), whereas MVP, acute MI and TVP produce late systolic murmurs",
  "True: ASD produces a pansystolic murmur across the interatrial defect, whereas muscular VSD produces a late systolic murmur",
  "False: Rapid squatting increases the intensity of MS, AR and VSD murmurs while decreasing the HOCM murmur",
  "False: In MVP, the mitral valve is in the `/\\` orientation at low ventricular volume, which is conducive to early prolapse"],
 0,
 "Book p47 classifies chronic MR, TR and VSD as pansystolic, acute MR, muscular VSD and acute TR as early systolic, ASD flow murmur as mid-systolic, and MVP, acute MI and TVP as late systolic. (Book p47)"),

(47, "match", "Dynamic Auscultation, Systolic Murmur Timing & 10 Named Murmurs",
 "Named murmurs 1–5 on Book p47: Austin Flint, Carey-Coombs, Cole-Cecil, Cruveilhier-Baumgarten and Gibson",
 "Match each named murmur (items 1–5 under 'Named murmurs****' on Book p47) to its classic definition — 1) Austin Flint murmur 2) Carey-Coombs murmur 3) Cole-Cecil murmur 4) Cruveilhier-Baumgarten murmur and Gibson murmur … A) Early diastolic murmur (EDM) of aortic regurgitation heard at the apex or axilla B) Mid-diastolic murmur (MDM) at the apex due to mitral valvulitis in acute rheumatic fever C) Mid-diastolic murmur (MDM) at the apex in severe AR due to vibration of the anterior mitral leaflet caused by the regurgitant jet D) Cruveilhier-Baumgarten = epigastric venous hum from collaterals between the portal system and remnant of the umbilical vein in portal hypertension; Gibson = machinery murmur of PDA",
 ["1-B, 2-C, 3-A, 4-D",
  "1-C, 2-B, 3-A, 4-D",
  "1-C, 2-A, 3-B, 4-D",
  "1-C, 2-B, 3-D, 4-A"],
 1,
 "Items 1–5 under 'Named murmurs****' on Book p47 define: (1) Austin Flint = MDM at apex in severe AR (vibration of AML from regurgitant jet); (2) Carey-Coombs = MDM at apex due to mitral valvulitis in ARF; (3) Cole-Cecil = EDM of AR heard at apex or axilla; (4) Cruveilhier-Baumgarten = epigastric venous hum in portal hypertension (collaterals between portal system and remnant of umbilical vein); (5) Gibson = machinery murmur of PDA. (Book p47)"),

(47, "match", "Dynamic Auscultation, Systolic Murmur Timing & 10 Named Murmurs",
 "Named murmurs 6–10 on Book p47: Graham Steell, Means-Lerman scratch, Roger's, Seagull and Still's",
 "Match each named murmur (items 6–10 under 'Named murmurs****' on Book p47) to its classic definition — 1) Graham Steell's murmur 2) Means-Lerman scratch 3) Roger's murmur 4) Seagull murmur and Still's murmur … A) Ejection systolic murmur (ESM) due to increased flow across the pulmonary valve in thyrotoxicosis B) Pansystolic murmur (PSM) of VSD best heard at the left sternal border C) Early diastolic murmur (EDM) of pulmonary regurgitation D) Seagull = musical murmur occasionally heard in AR or a sign of tight calcific AS in the Gallavardin phenomenon; Still's = innocent/benign/physiological murmur resembling the noise of a twanging string in young children that disappears later",
 ["1-C, 2-A, 3-B, 4-D",
  "1-A, 2-C, 3-B, 4-D",
  "1-C, 2-B, 3-A, 4-D",
  "1-C, 2-A, 3-D, 4-B"],
 0,
 "Items 6–10 under 'Named murmurs****' on Book p47 define: (6) Graham Steell's = EDM of PR; (7) Means-Lerman scratch = ESM from increased flow across the pulmonary valve in thyrotoxicosis; (8) Roger's = PSM of VSD at the left sternal border; (9) Seagull = musical murmur in AR or sign of tight calcific AS in Gallavardin phenomenon; (10) Still's = innocent/benign/physiological murmur resembling a twanging string in young children. (Book p47)"),
]
