# -*- coding: utf-8 -*-
"""Chapter 4 source data, Part A: Book p37-41 (Palpation: Apex beat, Thrills, Heave, Pulsatile liver, Percussion; Auscultation: Areas, Grading, Classical Murmurs)."""

# (page, fmt, sec, point, question, options, ans, explanation)
A = [
# ---------------------------------------------------------------- Book p37
(37, "recall", "Palpation: Apex Beat, DR POPE & Hyperdynamic vs Heaving Impulse",
 "Definition of apex beat, reporting template and patient position for commenting on character",
 "How does Book p37 define the apex beat (marked with ***), how is its location reported, and in which position must its character be commented on?",
 ["Lowermost, outermost definite palpable cardiac impulse; reported as '__ ICS, __ cm medial/lateral to the midclavicular line'; character must be commented on in the left lateral position",
  "Strongest systolic impulse felt anywhere over the precordium; reported relative to the anterior axillary line; character must be commented on in the sitting leaning-forward position",
  "Point of maximal auscultatory intensity of S1; reported relative to the sternal border; character must be commented on in the supine position at end-inspiration",
  "Midpoint of cardiac dullness on percussion; reported in fingerbreadths from the xiphisternum; character must be commented on while standing"],
 0,
 "On Book p37, the apex beat is defined (***) as the lowermost, outermost definite palpable cardiac impulse, reported as 'In the ____ ICS, ___ cm medial/lateral to the midclavicular line', and its character must be commented on in the left lateral position. (Book p37)"),

(37, "scenario", "Palpation: Apex Beat, DR POPE & Hyperdynamic vs Heaving Impulse",
 "Mechanism of the apex beat and palpatory see-saw test for LV vs RV apex",
 "During ventricular systole, what causes the outward palpable apex beat and its subsequent regression in amplitude, and what happens when you place one finger on the apex and one finger on the left parasternal area (Book p37)?",
 ["Isovolumetric contraction causes counterclockwise rotation of the heart (due to the spiral orientation of cardiac muscle fibres) making the apex palpable, and LV ejection causes regression in amplitude; if the LV forms the apex, the apex finger goes up while the parasternal finger goes down like a see-saw, whereas if the RV forms the apex, both fingers move together",
  "Diastolic ventricular filling pushes the apex outward and atrial contraction causes regression; if the LV forms the apex, both fingers move upward simultaneously",
  "Clockwise rotation during rapid ejection lifts the apex and isovolumetric relaxation causes regression; if the RV forms the apex, the two fingers move in opposite directions",
  "Closure of the semilunar valves produces the outward apical thrust; palpatory see-saw movement occurs only in cardiac tamponade"],
 0,
 "Item 3 on Book p37 explains: isovolumetric contraction causes counterclockwise rotation of the heart due to the spiral orientation of cardiac muscle fibres (making the apex palpable), and regression in amplitude is due to LV ejection. With one finger on the apex and one on the left parasternal area, an LV apex makes the apex finger rise while the parasternal finger goes down like a see-saw; an RV apex makes both move together. (Book p37)"),

(37, "oddoneout", "Palpation: Apex Beat, DR POPE & Hyperdynamic vs Heaving Impulse",
 "DR POPE mnemonic for a non-locatable apex beat and the viva rule on dextrocardia",
 "The mnemonic 'DR POPE' on Book p37 lists six causes of a non-locatable apex beat — Dextrocardia, behind the Rib, Pleural effusion, Obesity, Pericardial effusion and Emphysema. Which viva instruction does the book attach to this list?",
 ["Always name dextrocardia first because it is the most specific congenital anomaly",
  "Never say dextrocardia first — and if the apex is non-locatable on the left, check the right side",
  "Never check the right side of the chest unless situs inversus is confirmed on chest X-ray",
  "Always percuss Traube's space before palpating the right hemithorax"],
 1,
 "Item 4 on Book p37 gives DR POPE (Dextrocardia, behind the Rib, Pleural effusion, Obesity, Pericardial effusion, Emphysema) and explicitly warns: '(But never say dextrocardia first). If non locatable, check the Rt side.' (Book p37)"),

(37, "numeric", "Palpation: Apex Beat, DR POPE & Hyperdynamic vs Heaving Impulse",
 "Four characteristics of a normal apical impulse on Book p37",
 "According to Book p37, a normal apical impulse is located in the ____, confined to ____, has an area of around ____, and lasts for ____ of systole.",
 ["Left 5th ICS, 1/2 inch medial to the midclavicular line; one ICS; 2.5 cm² (1.5 finger breadths); <1/3 of systole",
  "Left 4th ICS, at the midclavicular line; two intercostal spaces; 4.5 cm² (3 finger breadths); >2/3 of systole",
  "Left 5th ICS, 1 inch lateral to the midclavicular line; one ICS; 1.0 cm² (0.5 finger breadth); 1/2 of systole",
  "Left 6th ICS, 1/2 inch medial to the anterior axillary line; one ICS; 2.5 cm²; throughout systole"],
 0,
 "Item 5 on Book p37 lists the four characteristics of a normal apical impulse: (a) left 5th ICS, 1/2 inch medial to the midclavicular line, (b) confined to one ICS, (c) area around 2.5 cm² (1.5 finger breadths), and (d) lasts for <1/3 of systole. (Book p37)"),

(37, "match", "Palpation: Apex Beat, DR POPE & Hyperdynamic vs Heaving Impulse",
 "Hyperdynamic vs Heaving LV apical impulse table and RV vs Tapping apex (Dr. Hamide, p37)",
 "Match each apical impulse character on Book p37 to its features in Dr. Hamide's classification — 1) Hyperdynamic LV apex 2) Heaving LV apex 3) RV apex 4) Tapping apical impulse … A) High amplitude, confined to ONE ICS in normal location, lasts >2/3 of systole, sustainable; caused by pressure overload [AS, systemic HTN, coarctation of aorta] B) High amplitude, felt in >1 ICS and shifted downwards and outwards, lasts 1/3–2/3 of systole, non-sustainable; caused by volume overload [MR, AR, high output states, VSD, PDA] C) Palpable first heart sound [S1] — neither an RV nor an LV type D) Diffuse, not easily localisable, no special character",
 ["1-A, 2-B, 3-D, 4-C",
  "1-B, 2-A, 3-D, 4-C",
  "1-B, 2-A, 3-C, 4-D",
  "1-D, 2-A, 3-B, 4-C"],
 1,
 "Item 6 on Book p37 contrasts RV apex (diffuse, not easily localisable, no special character), Hyperdynamic LV apex (high amplitude, >1 ICS, shifted downwards/outwards, 1/3–2/3 systole, non-sustainable, volume overload: MR, AR, high-output states, VSD, PDA), Heaving LV apex (high amplitude, one ICS, normal location, >2/3 systole, sustainable, pressure overload: AS, systemic HTN, coarctation), and Tapping apex (palpable S1; not an RV or LV type). (Book p37)"),

(37, "truefalse", "Palpation: Apex Beat, DR POPE & Hyperdynamic vs Heaving Impulse",
 "Volume overload vs pressure overload examples and tapping apex classification on Book p37",
 "Which of the following True/False statements accurately reflects Dr. Hamide's apical impulse classification on Book p37?",
 ["True: A hyperdynamic LV apex is caused by volume overload (MR, AR, high-output states, VSD, PDA) and is felt in >1 ICS, whereas a tapping apical impulse represents a palpable S1 and is neither an RV nor an LV type",
  "True: A heaving LV apex is shifted downwards and outwards across >1 ICS and lasts <1/3 of systole",
  "False: A heaving LV apex is caused by pressure overload such as aortic stenosis, systemic hypertension, and coarctation of the aorta",
  "False: An RV apex is diffuse, not easily localisable, and has no special character"],
 0,
 "Item 6 on Book p37 specifies that a hyperdynamic LV apex (>1 ICS, shifted downwards and outwards, 1/3–2/3 systole, non-sustainable) is caused by volume overload (MR, AR, high-output states, VSD, PDA); a heaving LV apex (1 ICS, normal location, >2/3 systole, sustainable) is caused by pressure overload (AS, systemic HTN, coarctation); and a tapping apex is a palpable S1 (not an RV or LV type). (Book p37)"),

# ---------------------------------------------------------------- Book p38
(38, "match", "Apex Shift, Abnormal Impulses, Thrills & Parasternal Heave",
 "Direction of apical shift and retracting, hypokinetic and double apical impulses on Book p38",
 "Match each apical impulse abnormality on Book p38 to its cause or mechanism — 1) Shifted downwards and laterally vs shifted only laterally 2) Retracting apical impulse [inward in systole, outward in diastole] 3) Hypokinetic apical impulse 4) Double apical impulse … A) Myocardial infarction B) Constrictive pericarditis and tricuspid regurgitation (TR) C) Downwards and laterally = LV enlargement [volume overload]; Only laterally = RV enlargement D) HOCM ['second LV contraction' as MV and hypertrophied septum approximate], severe AS with AR, and LBBB",
 ["1-C, 2-B, 3-A, 4-D",
  "1-B, 2-C, 3-A, 4-D",
  "1-C, 2-A, 3-B, 4-D",
  "1-C, 2-B, 3-D, 4-A"],
 0,
 "Items 7 and 8 on Book p38 cover: (7) LV enlargement shifts the apex downwards and laterally, whereas RV enlargement shifts it only laterally; (8a) retracting apex (inward in systole, outward in diastole) = constrictive pericarditis and TR; (8b) hypokinetic apex = MI; (8c) double apex = HOCM, severe AS with AR, and LBBB. (Book p38)"),

(38, "scenario", "Apex Shift, Abnormal Impulses, Thrills & Parasternal Heave",
 "Mechanism of the double apical impulse in HOCM vs retracting apical impulse on Book p38",
 "In a patient with hypertrophic obstructive cardiomyopathy (HOCM), palpation of the apex reveals a double apical impulse, whereas a patient with constrictive pericarditis has a retracting apical impulse. How does Book p38 explain the mechanism of each?",
 ["In HOCM, as the LV ejects blood, the mitral valve and hypertrophied interventricular septum nearly approximate, producing a sort of 'second LV contraction' to overcome the obstruction; in a retracting apex (constrictive pericarditis, TR), the impulse moves inwards in systole and outwards in diastole",
  "In HOCM, the right and left ventricles contract asynchronously due to complete AV block; in a retracting apex, the impulse moves outwards in systole and inwards in diastole",
  "In HOCM, the second impulse occurs in late diastole from giant 'a' waves; a retracting apex occurs only in acute myocardial infarction",
  "In HOCM, aortic regurgitation refills the LV in mid-systole; a retracting apex is unique to ostium secundum ASD"],
 0,
 "Item 8 on Book p38 explains that a retracting apical impulse moves inwards in systole and outwards in diastole (constrictive pericarditis, TR), whereas in HOCM when the LV is ejecting blood the mitral valve and hypertrophied IV septum nearly approximate, producing a sort of second LV contraction to overcome the obstruction (other causes of double apical impulse: severe AS with AR, and LBBB). (Book p38)"),

(38, "match", "Apex Shift, Abnormal Impulses, Thrills & Parasternal Heave",
 "Precordial thrills table and carotid shudder on Book p38",
 "Match each auscultatory/palpatory area in the 'Thrills' table on Book p38 (where a thrill is defined as a palpable murmur and carotid thrill is an AS shudder) to its systolic and diastolic thrills — 1) Aortic area [A] 2) Pulmonary area [P] 3) Tricuspid area [T] 4) Mitral area [M] … A) Systolic = PS, ASD; Diastolic/Continuous = PDA B) Systolic = AS; Diastolic = AR C) VSD D) Systolic = MR; Diastolic = MS",
 ["1-A, 2-B, 3-C, 4-D",
  "1-B, 2-A, 3-D, 4-C",
  "1-B, 2-A, 3-C, 4-D",
  "1-D, 2-A, 3-C, 4-B"],
 2,
 "The Thrills table on Book p38 maps: Carotid = AS shudder; A = AS (systolic), AR (diastolic); P = PS, ASD (systolic), PDA (continuous); T = VSD; M = MR (systolic), MS (diastolic). (Book p38)"),

(38, "match", "Apex Shift, Abnormal Impulses, Thrills & Parasternal Heave",
 "Parasternal area boundaries, AIIMS grading of parasternal heave and causes on Book p38",
 "Match each aspect of parasternal heave on Book p38 to its exact specification — 1) Anatomical boundaries of the parasternal area 2) AIIMS Grade I heave 3) AIIMS Grade II heave 4) AIIMS Grade III heave and causes of heave … A) Visible, palpable and obliterable on compression B) 2nd to 5th ICS from midline to the midpoint between midline and midclavicular line [upper = 2nd–3rd ICS; lower = 4th–5th ICS] C) Visible, palpable and non-obliterable; caused by RVH and LA enlargement D) Visible but not palpable",
 ["1-B, 2-D, 3-A, 4-C",
  "1-D, 2-B, 3-A, 4-C",
  "1-B, 2-A, 3-D, 4-C",
  "1-B, 2-D, 3-C, 4-A"],
 0,
 "Under Heave on Book p38: (1) Parasternal area is 2nd–5th ICS from midline to midpoint between midline and MCL (upper = 2nd–3rd ICS, lower = 4th–5th ICS); (2–3) AIIMS grading: Grade I = visible but not palpable, Grade II = visible, palpable, obliterable, Grade III = visible, palpable, non-obliterative; (4) Causes = RVH and LA enlargement. (Book p38)"),

(38, "numeric", "Apex Shift, Abnormal Impulses, Thrills & Parasternal Heave",
 "Upper vs lower parasternal intercostal spaces and AIIMS heave grades on Book p38",
 "On Book p38, the parasternal area extends from the ____ ICS (with the upper parasternal area defined as the ____ ICS and the lower parasternal area as the ____ ICS), and an AIIMS Grade II parasternal heave is defined as ____.",
 ["2nd to 5th; 2nd and 3rd; 4th and 5th; visible, palpable and obliterable",
  "1st to 4th; 1st and 2nd; 3rd and 4th; visible but not palpable",
  "2nd to 6th; 2nd to 4th; 5th and 6th; visible, palpable and non-obliterable",
  "3rd to 6th; 3rd and 4th; 5th and 6th; palpable only in the left lateral decubitus posture"],
 0,
 "Item 1–3 under Heave on Book p38 specifies: parasternal area = 2nd to 5th ICS (upper = 2nd and 3rd ICS; lower = 4th and 5th ICS); AIIMS Grade I = visible but not palpable, Grade II = visible, palpable, obliterable, Grade III = visible, palpable, non-obliterable. (Book p38)"),

# ---------------------------------------------------------------- Book p39
(39, "fillup", "Pulsatile Liver, Epigastric Thumb Sign & Percussion",
 "Epigastric thumb palpation for RVH vs aortic aneurysm",
 "When palpating epigastric pulsations with the thumb placed in the epigastric region pointing towards the shoulder (Book p39), a pulsation felt at the ____ of the thumb indicates right ventricular hypertrophy (RVH), whereas a pulsation felt at the ____ of the thumb indicates an aortic aneurysm.",
 ["Tip; pulp",
  "Pulp; tip",
  "Base; nail bed",
  "Ulnar border; radial border"],
 0,
 "Item 1 on Book p39 states: 'With thumb in epigastric region towards shoulder: a. At tip: RVH; At pulp: Aneurysm.' (Book p39)"),

(39, "scenario", "Pulsatile Liver, Epigastric Thumb Sign & Percussion",
 "Examination of a pulsatile liver: bimanual technique, JVP timing, inspiratory breath-hold, expansile vs transmitted and presystolic vs systolic",
 "While examining for a pulsatile liver (Book p39), you place your right hand on the lower border of the liver and your left hand made into a fist on the right lower intercostal space, asking the patient to hold their breath in deep inspiration. How do you time the pulsation, and how do you distinguish tricuspid regurgitation (TR), tricuspid stenosis (TS) and transmitted pulsations?",
 ["Use the JVP to time systole and diastole (since both hands are on the abdomen); pulsations pushing both hands outwards are expansile (e.g. TR) whereas those felt only by the abdominal hand are transmitted (aortic or RV cause); pulsations coinciding with the JVP 'a' wave are presystolic (e.g. TS) whereas those after the 'a' wave are systolic (e.g. TR)",
  "Use the radial pulse with a third assistant to time systole; pulsations felt only on the posterior fist are expansile (TS) whereas those pushing both hands are transmitted (TR)",
  "Ask the patient to hold breath in full expiration so the diaphragm rises; pulsations coinciding with the 'a' wave indicate TR whereas those after the 'a' wave indicate TS",
  "Use carotid auscultation to time systole; expansile pulsations indicate abdominal aortic aneurysm whereas transmitted pulsations indicate constrictive pericarditis"],
 0,
 "Item 2 on Book p39 details the bimanual liver pulsation test: JVP times the cardiac cycle because both hands are occupied; deep inspiratory breath-hold prevents respiratory interference and lowers the liver; expansile (both hands pushed outwards) = TR vs transmitted (only abdominal hand) = aortic/RV; coinciding with JVP 'a' wave = presystolic (TS) vs after 'a' wave = systolic (TR). (Book p39)"),

(39, "recall", "Pulsatile Liver, Epigastric Thumb Sign & Percussion",
 "Two clinical uses of percussion in cardiac examination on Book p39",
 "Under 'Percussion' at the bottom of Book p39, which two findings are specifically listed?",
 ["Liver span in suspected hepatomegaly, and increased cardiac dullness in pericardial effusion",
  "Dullness in the left 2nd ICS in pulmonary artery dilation, and Traube's space obliteration in splenomegaly",
  "Right-sided cardiac dullness in dextrocardia, and shifting dullness in congestive ascites",
  "Sternal percussion for right ventricular enlargement, and Kronig's isthmus percussion"],
 0,
 "Under Percussion on Book p39, the two listed items are: (1) Liver span in suspected hepatomegaly, and (2) Pericardial effusion: increased cardiac dullness. (Book p39)"),

# ---------------------------------------------------------------- Book p40
(40, "match", "Auscultation: Sequence, Areas, Gallavardin's Phenomenon & Murmur Grading",
 "Dr. Hamide's auscultatory sequence (M -> T -> P -> A) and findings at each area on Book p40",
 "Match each auscultatory area in Dr. Hamide's M -> T -> P -> A sequence on Book p40 to its anatomical landmark and characteristic findings — 1) M: Apex 2) T: Left 5th ICS parasternally 3) P: Left 2nd ICS parasternally 4) AA1 [Right 2nd ICS] and AA2 [Erb's point, Left 3rd ICS] … A) P2 loud/normal/soft, S1 +/-, Murmurs: ESM > EDM B) S1, S2, S3, Opening snap, Murmurs: MDM + PSA and PSM C) AA1: A2, EDM and ESM [radiating to carotids as shudder, or to apex confused with MR = Gallavardin's phenomenon]; AA2 [Erb's point]: EDM of AR heard better D) S1, S2, MDM and PSM [increasing on inspiration = Carvallo's sign]",
 ["1-B, 2-D, 3-A, 4-C",
  "1-D, 2-B, 3-A, 4-C",
  "1-B, 2-A, 3-D, 4-C",
  "1-B, 2-D, 3-C, 4-A"],
 0,
 "Item 1 on Book p40 sets out Dr. Hamide's M -> T -> P -> A sequence, distinguishing AA1 (right 2nd ICS parasternally, where the ESM of AS radiates to the carotids as a shudder or to the apex where it is confused with MR — Gallavardin's phenomenon) and AA2 (Erb's point, left 3rd ICS parasternally, where the EDM of AR is heard better). (Book p40)"),

(40, "scenario", "Auscultation: Sequence, Areas, Gallavardin's Phenomenon & Murmur Grading",
 "Gallavardin's phenomenon at AA1 vs apex and Erb's point (AA2)",
 "In an elderly patient with calcific aortic stenosis, a harsh ejection systolic murmur at the right 2nd ICS (AA1) radiates to the carotids as a shudder, while a high-frequency musical systolic component is heard at the cardiac apex and mistaken for mitral regurgitation. On Book p40 this apical radiation is called:",
 ["Carvallo's sign",
  "Gallavardin's phenomenon",
  "Cole-Cecil murmur",
  "Austin Flint phenomenon"],
 1,
 "Under 1.e (AA1: Rt 2nd ICS parasternally) on Book p40, the ESM of AS is noted as 'radiating to carotids as shudder, to apex often confused with MR: Gallavardin's phenomenon', while AA2 (Erb's point, Lt 3rd ICS parasternally) is where the EDM of AR is heard better. (Book p40)"),

(40, "match", "Auscultation: Sequence, Areas, Gallavardin's Phenomenon & Murmur Grading",
 "Levine and Freeman's six-grade classification of murmurs on Book p40",
 "Match each Levine and Freeman murmur grade on Book p40 to its definition — 1) Grade I/VI and Grade II/VI 2) Grade III/VI 3) Grade IV/VI 4) Grade V/VI and Grade VI/VI … A) Loud murmur WITH a palpable thrill B) Grade I = very soft, heard in optimal conditions; Grade II = faint murmur but clearly audible C) Grade V = louder with thrill, heard away from the affected site; Grade VI = loud with thrill, heard even with the stethoscope lifted from the chest D) Moderately loud murmur with NO thrill",
 ["1-D, 2-B, 3-A, 4-C",
  "1-B, 2-D, 3-A, 4-C",
  "1-B, 2-A, 3-D, 4-C",
  "1-B, 2-D, 3-C, 4-A"],
 1,
 "Item 2 on Book p40 lists Levine and Freeman's grading: Grade I/VI = very soft (optimal conditions); Grade II/VI = faint but clearly audible; Grade III/VI = moderately loud, no thrill; Grade IV/VI = loud with thrill; Grade V/VI = louder with thrill, heard away from the affected site; Grade VI/VI = loud with thrill, heard even with the stethoscope lifted from the chest. (Book p40)"),

(40, "numeric", "Auscultation: Sequence, Areas, Gallavardin's Phenomenon & Murmur Grading",
 "Thrill threshold in Levine and Freeman grading on Book p40",
 "In Levine and Freeman's murmur grading on Book p40, the highest grade WITHOUT a palpable thrill is ____, the lowest grade WITH a palpable thrill is ____, and a murmur audible even with the stethoscope lifted from the chest is ____.",
 ["Grade III/VI; Grade IV/VI; Grade VI/VI",
  "Grade II/VI; Grade III/VI; Grade V/VI",
  "Grade I/VI; Grade II/VI; Grade IV/VI",
  "Grade IV/VI; Grade V/VI; Grade VI/VI"],
 0,
 "Item 2 on Book p40 defines Grade III/VI as a moderately loud murmur with no thrill, Grade IV/VI as a loud murmur with a thrill, and Grade VI/VI as loud with a thrill and heard even with the stethoscope lifted from the chest. (Book p40)"),

# ---------------------------------------------------------------- Book p41
(41, "scenario", "Classical Murmur Descriptions & Heart Sound Intensity Table",
 "Classical bedside description of the mitral stenosis murmur (**** on Book p41)",
 "When asked for the classical description of the mitral stenosis murmur (marked **** on Book p41), which combination of stethoscope piece, patient posture, and respiratory phase is specified for the opening snap versus the mid-diastolic murmur?",
 ["S1 is loud, S2 is normal; a high-pitched opening snap is heard after S2 with the DIAPHRAGM, followed by a low-pitched, rough, rumbling MDM (with or without presystolic accentuation) best heard with the BELL with the patient in the LEFT LATERAL position with breath held in MID-EXPIRATION",
  "S1 is soft, S2 is absent; a low-pitched opening snap is heard with the bell, followed by a high-pitched blowing MDM best heard with the diaphragm in the sitting leaning-forward posture at end-inspiration",
  "S1 and S2 are normal; both the opening snap and the rough rumbling MDM are best heard with the diaphragm in the supine posture during deep inspiration",
  "S1 is loud, S2 is wide fixed split; the MDM is best heard with the bell at Erb's point while the patient performs a Valsalva manoeuvre"],
 0,
 "Item 4.a on Book p41 gives the verbatim classical description of MS: loud S1, normal S2, high-pitched opening snap after S2 heard with the diaphragm, followed by a low-pitched, rough, rumbling MDM with/without presystolic accentuation best heard with the bell in the left lateral position with breath held in mid-expiration. (Book p41)"),

(41, "match", "Classical Murmur Descriptions & Heart Sound Intensity Table",
 "Other causes of a mid-diastolic murmur (MDM) at the apex vs at the tricuspid area on Book p41",
 "Match each category of non-MS mid-diastolic murmur on Book p41 to its listed causes — 1) Intracardiac masses causing apical MDM 2) Regurgitant / valvulitic eponymous apical MDMs 3) Increased flow across a non-stenotic mitral valve 4) Causes of MDM at other areas [tricuspid area] … A) Austin Flint murmur [MDM in AR] and Carey-Coombs murmur [MDM in acute rheumatic fever] B) Left atrial myxoma and ball-valve thrombus in the left atrium C) Tricuspid stenosis, increased flow across a non-stenotic tricuspid valve [ASD, TR, TAPVR], and right atrial myxoma D) MR, VSD, PDA, high-output states and complete heart block",
 ["1-B, 2-A, 3-D, 4-C",
  "1-A, 2-B, 3-D, 4-C",
  "1-B, 2-D, 3-A, 4-C",
  "1-B, 2-A, 3-C, 4-D"],
 0,
 "Book p41 lists five other causes of MDM at the apex (LA myxoma, Austin Flint murmur in AR, Carey-Coombs murmur in ARF, ball-valve LA thrombus, and increased flow across a non-stenotic MV in MR, VSD, PDA, high-output states, complete heart block) and three causes of MDM at other areas (tricuspid stenosis, increased flow across a non-stenotic TV in ASD/TR/TAPVR, and right atrial myxoma). (Book p41)"),

(41, "match", "Classical Murmur Descriptions & Heart Sound Intensity Table",
 "Classical descriptions of AS, MR and AR murmurs and the S1/A2/P2 intensity table on Book p41",
 "Match each murmur or heart-sound row on Book p41 to its classical description — 1) Aortic stenosis vs Aortic regurgitation classical descriptions 2) Mitral regurgitation classical description 3) Loud vs Soft S1 in the p41 table 4) Loud vs Soft A2 and P2 in the p41 table … A) S1 and S2 not audible; high-pitched loud pansystolic murmur of soft blowing quality best heard with the diaphragm, radiating to the axilla B) Loud S1 = MS, hyperdynamic circulations; Soft S1 = MR, calcific MS, TR, acute AR C) AS = S1 and S2 heard, harsh crescendo-decrescendo ESM in aortic area; AR = S1 heard, S2 soft, soft high-pitched blowing decrescendo EDM; both best heard sitting leaning forward in expiration D) Loud A2 = systemic HTN, aortic aneurysm [Soft A2 = AS]; Loud P2 = pulmonary HTN, pulmonary artery dilatation [Soft P2 = PS]",
 ["1-A, 2-C, 3-B, 4-D",
  "1-C, 2-A, 3-B, 4-D",
  "1-C, 2-B, 3-A, 4-D",
  "1-C, 2-A, 3-D, 4-B"],
 1,
 "Items 4.b–d and the bottom table on Book p41 summarise the classical descriptions of AS, MR and AR along with the Loud/Soft causes for S1, A2 and P2. (Book p41)"),
]
