# -*- coding: utf-8 -*-
"""Chapter 6 source data, Part A: Book p49-52 (Mitral Stenosis: Harrison Table 263-1, Anatomy, Congenital & Variants, Etiopathogenesis, Clinical Features, Severity & Pulmonary Hypertension)."""

# (page, fmt, sec, point, question, options, ans, explanation)
A = [
# ---------------------------------------------------------------- Book p49
(49, "match", "Mitral Stenosis: Causes, Anatomy, Congenital Types & Variants",
 "Harrison's Table 263-1 on Book p49: Major causes of Mitral Stenosis and conditions simulating MS",
 "Match each category in Harrison's Table 263-1 [Major Causes of Mitral Valve Disease, Book p49] to the listed causes of Mitral Stenosis — 1) Leading global cause and congenital/shunt combination 2) Metabolic causes in Table 263-1 3) Autoimmune / drug / endocrine-tumour causes 4) Conditions that simulate MS by obstructing left atrial outflow … A) Hurler-Scheie syndrome, Fabry's disease and Whipple's disease B) Cor triatriatum, left atrial myxoma and pulmonary vein obstruction C) Systemic lupus erythematosus [SLE], rheumatoid arthritis [RA], methysergide therapy and carcinoid D) Rheumatic fever [~40% of RHD patients have pure or predominant MS], congenital MS, severe annular calcification and Lutembacher's syndrome",
 ["1-D, 2-A, 3-C, 4-B",
  "1-A, 2-D, 3-C, 4-B",
  "1-D, 2-C, 3-A, 4-B",
  "1-D, 2-A, 3-B, 4-C"],
 0,
 "Harrison's Table 263-1 on Book p49 lists the causes of Mitral Stenosis: Congenital, Rheumatic fever (~40% of RHD patients have pure/predominant MS), Metabolic (Hurler-Scheie syndrome, Fabry's disease, Whipple's disease), SLE, RA, Methysergide therapy, Carcinoid, Lutembacher's syndrome, Severe annular calcification, and conditions simulating MS (cor triatriatum, LA myxoma, pulmonary vein obstruction). (Book p49)"),

(49, "scenario", "Mitral Stenosis: Causes, Anatomy, Congenital Types & Variants",
 "Rheumatic 'fish-mouth' pathology, secondary flow trauma, and sites of thrombus formation on Book p49",
 "According to the Harrison's Pathology text on Book p49, how does the 'fish-mouth' mitral valve develop, what drives the later progression of leaflet thickening after the initial rheumatic insult, and where do thrombi most frequently arise in patients with atrial fibrillation?",
 ["Fibrous tissue and/or calcific deposits thicken the leaflets, mitral commissures fuse, and chordae tendineae fuse and shorten into a rigid funnel-shaped ('fish-mouth') orifice; later changes result from a nonspecific process due to trauma from altered flow patterns; thrombi may arise on the calcific valve itself, but in AF they arise more frequently in the dilated LA, particularly within the LA appendage",
  "Bacterial vegetations perforate the anterior leaflet body while sparing the commissures and chordae; thrombi in AF arise exclusively on the right ventricular moderator band",
  "Myxomatous degeneration elongates and ruptures the chordae tendineae, creating a flail posterior leaflet; calcific deposits prevent any thrombus formation in the LA appendage",
  "Subvalvular muscular hypertrophy obliterates the LV outflow tract while the mitral commissures remain mobile; thrombi arise only in the pulmonary veins"],
 0,
 "The Harrison excerpt on Book p49 explains that fibrous/calcific thickening, commissural fusion, and chordal fusion/shortening create a rigid funnel-shaped ('fish-mouth') valve; while the initial insult is rheumatic, later changes are a nonspecific process from trauma caused by altered flow patterns; and in AF, thrombi arise most frequently from the dilated LA, particularly within the LA appendage. (Book p49)"),

# ---------------------------------------------------------------- Book p50
(50, "recall", "Mitral Stenosis: Causes, Anatomy, Congenital Types & Variants",
 "Mitral valve anatomical components in the Book p50 diagram",
 "In the anatomical diagram of the mitral valve at the top of Book p50, how is the posterior leaflet structured compared with the anterior leaflet, and what are the two commissures and two papillary muscles?",
 ["The posterior leaflet has 3 lobes (scallops) whereas the anterior leaflet is a single curtain; they meet at the anteromedial and posterolateral commissures within the anterior and posterior annulus and attach via chordae tendineae to the lateral and medial papillary muscles",
  "The anterior leaflet has 3 lobes whereas the posterior leaflet is a single cusp; they attach directly to the interventricular septum without papillary muscles",
  "Both leaflets are tri-lobed semilunar cusps anchored by a single posterior commissure and an infundibular muscle",
  "The mitral apparatus consists of septal, anterior, and posterior leaflets attached to three papillary muscles"],
 0,
 "The diagram on Book p50 labels: Anterior annulus, Posterior annulus, Anterior leaflet, Posterior leaflet (3 lobes), Anteromedial commissure, Posterolateral commissure, Chordae tendineae, Lateral papillary muscle, and Medial papillary muscle. (Book p50)"),

(50, "match", "Mitral Stenosis: Causes, Anatomy, Congenital Types & Variants",
 "Causes of MS (1.a–d) and classification of Congenital MS (2.a–c: Supravalvular, Valvular, Subvalvular) on Book p50",
 "Match each congenital or acquired category of Mitral Stenosis on Book p50 to its specific lesions — 1) Storage and connective-tissue causes listed under 1.c–d 2) Supravalvular and Valvular congenital MS [2.a–b] 3) Parachute mitral valve [2.c.i] 4) Hammock valve [2.c.ii] and 2.c.iii … A) Subvalvular MS with a single papillary muscle B) Subvalvular MS with abnormally large or numerous papillary muscles [Hammock valve], or absent papillary muscle C) SLE, Rheumatoid Arthritis, Hunter's syndrome and Hurler's syndrome [plus RHD, congenital MS, severe MAC] D) Supravalvular = fibrous ring; Valvular = fusion of commissure and papillary muscle, excessive valvular tissue, annular hypoplasia",
 ["1-C, 2-D, 3-A, 4-B",
  "1-D, 2-C, 3-A, 4-B",
  "1-C, 2-D, 3-B, 4-A",
  "1-A, 2-D, 3-C, 4-B"],
 0,
 "Items 1 and 2 on Book p50 classify MS causes (RHD, congenital MS, severe MAC, SLE/RA, Hunter's/Hurler's syndromes) and Congenital MS into Supravalvular (fibrous ring), Valvular (fusion of commissure and papillary muscle, excessive valvular tissue, annular hypoplasia), and Subvalvular (single papillary muscle = parachute valve; abnormally large or numerous papillary muscles = hammock valve; absent papillary muscle). (Book p50)"),

(50, "match", "Mitral Stenosis: Causes, Anatomy, Congenital Types & Variants",
 "Three variants of MS (Lutembacher, Damped/Silent MS for Dr. Hamide, and Juvenile MS) on Book p50",
 "Match each variant of Mitral Stenosis on Book p50 [Item 3] to its defining characteristics — 1) Lutembacher syndrome 2) Damped MS [= Silent MS, for Dr. Hamide] 3) Juvenile MS — age, etiology and haemodynamics 4) Juvenile MS — rhythm and management … A) Less prone to atrial fibrillation; immediate surgery should be done in symptomatic cases B) Rheumatic in aetiology, age of onset <20 years, severe MS is common and highly prone to develop pulmonary hypertension C) In severe pulmonary hypertension, the right ventricle forms the apex, so the mid-diastolic murmur [MDM] is no longer heard over the apex D) Mitral stenosis plus atrial septal defect [ASD]",
 ["1-D, 2-C, 3-B, 4-A",
  "1-C, 2-D, 3-B, 4-A",
  "1-D, 2-B, 3-C, 4-A",
  "1-D, 2-C, 3-A, 4-B"],
 0,
 "Item 3 on Book p50 defines the three variants: (a) Lutembacher syndrome = MS + ASD; (b) Damped MS = Silent MS (for Dr. Hamide): in severe PAH, the RV forms the apex so the MDM is no longer heard over the apex; (c) Juvenile MS: rheumatic in aetiology, onset <20 years, severe MS common and highly prone to pulmonary HTN, less prone to AF, and immediate surgery should be done in symptomatic cases. (Book p50)"),

(50, "fillup", "Mitral Stenosis: Causes, Anatomy, Congenital Types & Variants",
 "Parachute vs Hammock subvalvular congenital MS and Damped MS mechanism on Book p50",
 "In subvalvular congenital MS on Book p50, a single papillary muscle is called a ____ valve whereas abnormally large or numerous papillary muscles form a ____ valve; in Damped (Silent) MS (for Dr. Hamide), severe pulmonary hypertension causes the ____ to form the apex so the MDM is no longer heard over the apex.",
 ["Parachute; Hammock; right ventricle",
  "Hammock; Parachute; left atrium",
  "Sail; Ebstein; left ventricle",
  "Funnel; Fish-mouth; infundibulum"],
 0,
 "Items 2.c and 3.b on Book p50 state: single papillary muscle = parachute valve; abnormally large or numerous papillary muscles = hammock valve; and in Damped MS (Silent MS, for Dr. Hamide), in severe pulmonary hypertension the right ventricle forms the apex, so the MDM is no longer heard over the apex. (Book p50)"),

(50, "truefalse", "Mitral Stenosis: Causes, Anatomy, Congenital Types & Variants",
 "Juvenile MS characteristics on Book p50",
 "Which of the following True/False statements accurately describes Juvenile Mitral Stenosis on Book p50 (Item 3.c)?",
 ["True: Juvenile MS is rheumatic in aetiology with onset <20 years, is highly prone to severe MS and pulmonary hypertension, is LESS prone to atrial fibrillation, and requires immediate surgery in symptomatic cases",
  "True: Juvenile MS is congenital in aetiology with onset >40 years and almost universally presents with chronic atrial fibrillation",
  "False: In Juvenile MS, severe MS and pulmonary hypertension are common",
  "False: Immediate surgery should be performed in symptomatic cases of Juvenile MS"],
 0,
 "Item 3.c on Book p50 lists the five hallmarks of Juvenile MS: (i) rheumatic in aetiology, (ii) age of onset <20 years, (iii) severe MS is common and highly prone to pulmonary HTN, (iv) less prone to AF, and (v) immediate surgery should be done in symptomatic cases. (Book p50)"),

(50, "scenario", "Mitral Stenosis: Causes, Anatomy, Congenital Types & Variants",
 "Gradual vs sudden rise in LA pressure in MS etiopathogenesis (Item 4.a–b on Book p50)",
 "Why does a patient with chronic progressive MS and a gradual rise in LA pressure avoid acute pulmonary oedema, whereas a patient with MS who develops sudden-onset atrial fibrillation rapidly develops frank pulmonary oedema (Book p50)?",
 ["A gradual rise in LA pressure causes an increase in pulmonary vascular resistance leading to pulmonary hypertension that protects against pulmonary oedema; a sudden rise in LA pressure (as in AF due to loss of atrial contraction) causes pulmonary oedema",
  "A gradual rise in LA pressure dilates the aortic root and decompresses the lungs; a sudden rise in LA pressure closes the foramen ovale",
  "A gradual rise in LA pressure abolishes right ventricular output completely; AF protects against pulmonary oedema by slowing the ventricular rate",
  "Both gradual and sudden rises in LA pressure decrease pulmonary vascular resistance equally"],
 0,
 "Items 4.a and 4.b on Book p50 contrast: (a) a gradual rise in LA pressure tends to cause an increase in pulmonary vascular resistance which leads to pulmonary hypertension that protects against pulmonary oedema; (b) a sudden rise in LA pressure, like in AF (due to decreased atrial contraction), causes pulmonary oedema. (Book p50)"),

# ---------------------------------------------------------------- Book p51
(51, "scenario", "Etiopathogenesis, Clinical Features & Haemoptysis in MS",
 "Cardiac output and EF in MS, loss of atrial kick with tachycardia, and 7 precipitants of acute dyspnoea/cough (Item 4.c–d, Book p51)",
 "Up to severe MS, cardiac output (CO) and ejection fraction (EF) remain normal at rest because the elevated LA pressure maintains flow across the valve. What happens when conditions increase the heart rate, and what seven precipitants can trigger marked LA pressure elevation, dyspnoea and cough in mild-to-moderate MS (Book p51)?",
 ["With tachycardia, the atrial kick is not possible (and diastole shortens) so CO decreases; marked LA pressure elevation with dyspnoea and cough is precipitated by fever, excitement, severe exertion, severe anaemia, paroxysmal AF, pregnancy, and thyrotoxicosis",
  "With tachycardia, EF rises to >85% and LA pressure falls to zero; dyspnoea is precipitated only by hypothyroidism and hypothermia",
  "Even in mild MS, resting EF is <25% due to primary LV myocardial necrosis; beta-blockade precipitates pulmonary oedema by prolonging diastole",
  "Tachycardia opens the mitral commissures wider, increasing CO; only bacterial endocarditis precipitates dyspnoea"],
 0,
 "Items 4.c and 4.d on Book p51 explain: up to severe MS, elevated LA pressure maintains normal CO and EF, but when HR increases the atrial kick is lost so CO falls; sudden changes in HR, volume status or CO — fever, excitement, severe exertion, severe anaemia, paroxysmal AF, pregnancy, thyrotoxicosis — precipitate marked LA pressure rise, dyspnoea and cough. (Book p51)"),

(51, "fillup", "Etiopathogenesis, Clinical Features & Haemoptysis in MS",
 "Two mechanisms of PAH ('second stenosis') and mechanism of presystolic accentuation (Item 4.e–f, Book p51)",
 "On Book p51, pulmonary arterial hypertension (PAH) in MS is caused by (i) passive backward transmission of elevated LA pressure and (ii) pulmonary arteriolar constriction — called '____' (reactive pulmonary hypertension); presystolic accentuation occurs because ____ occurs before ventricular systole (S1), increasing force and turbulence through the stenotic valve.",
 ["Second stenosis; atrial systole",
  "Bernheim constriction; rapid passive filling",
  "Eisenmenger reaction; isovolumetric relaxation",
  "Post-capillary shunt; papillary muscle contraction"],
 0,
 "Items 4.e and 4.f on Book p51 state: PAH is caused by (i) passive backward transmission of elevated LA pressure and (ii) pulmonary arteriolar constriction ('second stenosis') due to LA and pulmonary venous hypertension (reactive PAH); presystolic accentuation occurs because atrial systole precedes ventricular systole (S1), increasing force and turbulence through the stenotic valve. (Book p51)"),

(51, "match", "Etiopathogenesis, Clinical Features & Haemoptysis in MS",
 "Clinical features of MS: latent period, J-receptor dyspnoea, pulmonary-vein stretch AF, and signs including mitral facies (Item 5, Book p51)",
 "Match each clinical feature or sign of Mitral Stenosis on Book p51 to its stated mechanism — 1) Latent period between rheumatic carditis and MS symptoms 2) Dyspnoea in MS 3) Palpitations [atrial fibrillation] in MS 4) Mitral facies and other clinical signs [5.l] … A) Pulmonary congestion stimulates interstitial J receptors; initial exertional dyspnoea is due to elevated pulmonary vascular pressures decreasing pulmonary compliance B) About two decades [~20 years] C) Stretching of the pulmonary veins triggers atrial fibrillation; fatigue is from decreased CO, chest pain from PAH, and oedema/ascites from RHF D) Malar flush with pinched and blue facies; AF gives absent 'a' wave and variable S1, whereas PAH gives prominent JVP 'a' waves, parasternal heave and loud P2",
 ["1-B, 2-A, 3-C, 4-D",
  "1-A, 2-B, 3-C, 4-D",
  "1-B, 2-C, 3-A, 4-D",
  "1-B, 2-A, 3-D, 4-C"],
 0,
 "Item 5 on Book p51 covers: (a) latent period ~2 decades; (b) dyspnoea via interstitial J-receptor stimulation and decreased pulmonary compliance; (c–e, g–k) fatigue (low CO), oedema/ascites (RHF), palpitations/AF (stretching of pulmonary veins), cough, chest pain (PAH), emboli (stroke, limb ischaemia, recurrent PE), winter pulmonary infections; and (l) signs including mitral facies (malar flush with pinched and blue facies). (Book p51)"),

(51, "oddoneout", "Etiopathogenesis, Clinical Features & Haemoptysis in MS",
 "Five causes of haemoptysis in MS on Book p51 (pulmonary apoplexy, winter bronchitis, acute pulmonary oedema, pulmonary infarction, warfarin overdose)",
 "Item 5.f on Book p51 lists five causes of haemoptysis in Mitral Stenosis (with #1 highlighted in bold as the most classic). Which of the following is NOT one of the five causes of haemoptysis in MS on Book p51, or misstates #1?",
 ["1. Rupture of pulmonary-bronchial venous connections (pulmonary apoplexy) due to a sudden rise in LA pressure",
  "2. Winter bronchitis or chronic bronchitis, and 3. Acute pulmonary oedema",
  "4. Pulmonary infarction, and 5. Warfarin overdose (rare)",
  "Rupture of a congenital bronchial artery Rasmussen aneurysm secondary to cavitating left ventricular tuberculosis"],
 3,
 "Item 5.f on Book p51 lists the five causes of haemoptysis in MS: (i) Rupture of pulmonary-bronchial venous connections (pulmonary apoplexy) due to sudden rise in LA pressure [bolded], (ii) Winter bronchitis or chronic bronchitis, (iii) Acute pulmonary oedema, (iv) Pulmonary infarction, and (v) Warfarin overdose (rare). (Book p51)"),

(51, "recall", "Etiopathogenesis, Clinical Features & Haemoptysis in MS",
 "Mitral facies description and mechanism of palpitations/AF and winter infections on Book p51",
 "How does Book p51 (Item 5.e, k, l.ii) describe 'Mitral facies', why do palpitations/atrial fibrillation develop in MS, and which infections complicate untreated MS especially in winter months?",
 ["Mitral facies = malar flush with pinched and blue facies; palpitations/AF occur because of stretching of the pulmonary veins; bronchitis, bronchopneumonia, and lobar pneumonia complicate untreated MS especially in winter months",
  "Mitral facies = periorbital xanthelasma with leonine forehead; palpitations occur from sinoatrial nodal ischaemia; fungal aspergillomas complicate MS in summer months",
  "Mitral facies = heliotrope rash with malar sparing; palpitations occur from accessory Kent bundles; viral myocarditis complicates MS",
  "Mitral facies = plethora with moon facies; palpitations occur from carotid body denervation; miliary tuberculosis complicates MS"],
 0,
 "Item 5 on Book p51 notes: (e) palpitations — AF because of stretching of pulmonary veins; (k) pulmonary infections — bronchitis, bronchopneumonia, lobar pneumonia complicate untreated MS, especially in winter months; and (l.ii) Mitral facies — malar flush with pinched and blue facies. (Book p51)"),

# ---------------------------------------------------------------- Book p52
(52, "scenario", "Clinical Severity, Complications & Pulmonary Hypertension Signs",
 "Clinical assessment of severity of MS: S2–OS gap, MDM duration and PAH features (Item 6, Book p52)",
 "How does Book p52 assess the clinical severity of Mitral Stenosis at the bedside using the S2–OS interval, the mid-diastolic murmur (MDM), and right-sided findings?",
 ["In severe MS, very high LA pressure forces the mitral valve open early after S2, making the S2–OS gap shorter ('less'); because OS occurs early, the duration of the MDM is longer ('more'); and features of pulmonary hypertension are present",
  "In severe MS, the S2–OS gap becomes wider (>0.16 sec) and the duration of the MDM becomes shorter while its intensity always increases to Grade VI/VI",
  "The loudness of S1 and the amplitude of the tapping apex beat are the two most reliable quantitative correlates of MS severity",
  "Severe MS is characterised by a wide fixed split S2 and an early systolic click at the apex"],
 0,
 "Item 6 on Book p52 lists the three clinical markers of MS severity: (a) S2–OS gap is less (high LA pressure forces the MV open early after S2); (b) duration of MDM is more (because OS occurs early, MDM lasts longer); and (c) features of pulmonary hypertension. (Book p52)"),

(52, "match", "Clinical Severity, Complications & Pulmonary Hypertension Signs",
 "Complications of MS, most common thrombus site in AF, Ortner's syndrome and the IE viva warning (Item 7, Book p52)",
 "Match each complication entry under Item 7 ['Complications of MS'] on Book p52 to its exact note — 1) Atrial fibrillation and thrombus location [7.a] 2) Systemic embolic complications [7.c–e] 3) Ortner's syndrome and esophageal compression [7.g.i] 4) Infective endocarditis [7.g.ii] … A) Embolic stroke, acute limb ischaemia and mesenteric ischaemia B) Most common location of the thrombus is in the left atrial appendage [left auricle] C) Very, very rare — 'don't say it' [also noted as rare in ASD] D) Very rare complication: LA enlargement causing left recurrent laryngeal nerve [RLN] compression leading to hoarseness, and dysphagia due to oesophageal compression",
 ["1-B, 2-A, 3-D, 4-C",
  "1-A, 2-B, 3-D, 4-C",
  "1-B, 2-D, 3-A, 4-C",
  "1-B, 2-A, 3-C, 4-D"],
 0,
 "Item 7 on Book p52 lists: (a) AF (most common location of thrombus is in the left atrial appendage / left auricle), (b) pulmonary HTN, RV failure, cor pulmonale, (c) embolic stroke, (d) acute limb ischaemia, (e) mesenteric ischaemia, (f) haemoptysis, and (g) very rare complications: (i) Ortner's syndrome (LA enlargement -> RLN compression -> hoarseness; esophageal compression -> dysphagia) and (ii) IE — 'very very rare (don't say it). Also rare in ASD'. (Book p52)"),

(52, "numeric", "Clinical Severity, Complications & Pulmonary Hypertension Signs",
 "Normal pulmonary arterial pressure and resting vs post-exercise mean PAP cutoffs for Pulmonary Hypertension (Item 8.a–b, Book p52)",
 "On Book p52, normal pulmonary arterial pressure is ____, pulmonary hypertension is defined as a mean pulmonary artery pressure of ____ at rest or ____ after exercise, and severe pulmonary hypertension is ____ after exercise.",
 ["15–25/10 mmHg; >25 mmHg; >30 mmHg; >60 mmHg",
  "120/80 mmHg; >40 mmHg; >50 mmHg; >80 mmHg",
  "8–12/4 mmHg; >15 mmHg; >20 mmHg; >35 mmHg",
  "30–40/20 mmHg; >35 mmHg; >45 mmHg; >100 mmHg"],
 0,
 "Items 8.a and 8.b on Book p52 state: normal pulmonary arterial pressure is 15–25/10 mmHg; pulmonary hypertension is defined as mean pulmonary pressure >25 mmHg at rest or >30 mmHg after exercise, and severe >60 mmHg (after exercise). (Book p52)"),

(52, "match", "Clinical Severity, Complications & Pulmonary Hypertension Signs",
 "Symptoms and Signs*** of Pulmonary Hypertension including the 6-part classical auscultatory sequence (Item 8.c–d, Book p52)",
 "Match each component of the clinical examination in Pulmonary Hypertension ['Signs***', Item 8.d on Book p52] to its findings — 1) Symptoms [8.c], Pulse and JVP [8.d.i–ii] 2) Inspection and Percussion [8.d.iii, v] 3) Palpation [8.d.iv] 4) Auscultation — classical sequence of 6 events [8.d.vi] … A) Apex goes outwards, palpable P2 [diastolic shock], left parasternal heave, palpable P2 B) 1. Audible S1 -> 2. Pulmonary ejection click -> 3. Pulmonary ESM due to relative PS -> 4. Loud P2 with narrow S2 split -> 5. Graham Steell murmur -> 6. Right-sided S3 C) Symptoms: exertional breathlessness, easy fatigability, dizziness, syncope; Pulse: low volume due to decreased CO; JVP: prominent 'a' wave D) Inspection: visible pulmonary arterial pulsation in 2nd ICS and epigastric pulsation; Percussion: left 2nd ICS is dull",
 ["1-C, 2-D, 3-A, 4-B",
  "1-D, 2-C, 3-A, 4-B",
  "1-C, 2-A, 3-D, 4-B",
  "1-C, 2-D, 3-B, 4-A"],
 0,
 "Item 8.c–d on Book p52 details the symptoms and Signs*** of pulmonary hypertension, culminating in the classical 6-event auscultatory sequence: (1) Audible S1, (2) Pulmonary ejection click, (3) Pulmonary ESM due to relative PS, (4) Loud P2 with narrow S2 split, (5) Graham Steell murmur, and (6) Right-sided S3. (Book p52)"),

(52, "recall", "Clinical Severity, Complications & Pulmonary Hypertension Signs",
 "Classical 6-event auscultatory sequence of Pulmonary Hypertension (Item 8.d.vi, Book p52)",
 "What is the exact 6-step 'classical sequence of events' on auscultation of Pulmonary Hypertension listed under Signs*** (Item 8.d.vi) at the bottom of Book p52?",
 ["1. Audible S1 -> 2. Pulmonary ejection click -> 3. Pulmonary ESM due to relative PS -> 4. Loud P2 with narrow S2 split -> 5. Graham Steell murmur -> 6. Right-sided S3",
  "1. Soft S1 -> 2. Aortic ejection click -> 3. Harsh carotid ESM -> 4. Soft P2 with wide fixed split -> 5. Austin Flint murmur -> 6. Left-sided S4",
  "1. Split S1 -> 2. Midsystolic click -> 3. Late systolic murmur -> 4. Paradoxical S2 split -> 5. Carey-Coombs murmur -> 6. Pericardial knock",
  "1. Loud S1 -> 2. Opening snap -> 3. Rough rumbling MDM -> 4. Presystolic accentuation -> 5. Roger's murmur -> 6. Tumour plop"],
 0,
 "Item 8.d.vi on Book p52 enumerates the 6 auscultatory events in order: (1) Audible S1, (2) Pulmonary ejection click, (3) Pulmonary ESM due to relative PS, (4) Loud P2 with narrow S2 split, (5) Graham Steell murmur, and (6) Right-sided S3. (Book p52)"),
]
