# -*- coding: utf-8 -*-
"""Chapter 6 source data, Part B: Book p53-55 (Opening Snap/PSA/Soft S1 Significance, Differential Diagnoses, ECG/CXR/Echo/Wilkins, Medical & Surgical Management, Mechanical vs Bioprosthetic Valves)."""

# (page, fmt, sec, point, question, options, ans, explanation)
B = [
# ---------------------------------------------------------------- Book p53
(53, "match", "Opening Snap, Absent PSA, Soft S1 & Differential Diagnoses of MS",
 "Significance of an Opening Snap (9.a), Absent Presystolic Accentuation (9.b) and Soft S1 in MS (9.c) on Book p53",
 "Match each auscultatory finding in Mitral Stenosis on Book p53 [Item 9] to its clinical significance or causes — 1) Six clinical meanings of an audible Opening Snap [9.a.i–vi] 2) Three causes of absent presystolic accentuation in MS [9.b.i–iii] 3) Valvular and rhythm causes of a Soft S1 in MS [9.c.i–ii, v] 4) PR-interval and RV-apex causes of a Soft S1 in MS [9.c.iii–iv, vi] … A) Atrial fibrillation, Left heart failure, and Massive LA thrombus B) Indicates organic MS, valve is pliable with no calcification, S2–OS interval judges severity, MS is amenable to surgery, significant MS, and high LA pressure C) Digitalis overdose [prolonged PR interval], acute rheumatic carditis [prolonged PR interval], and Damped MS [PAH causing RVH so an RV apex replaces the LV apex] D) Co-existent MR, mitral valve calcification, and atrial fibrillation",
 ["1-B, 2-A, 3-D, 4-C",
  "1-A, 2-B, 3-D, 4-C",
  "1-B, 2-D, 3-A, 4-C",
  "1-B, 2-A, 3-C, 4-D"],
 0,
 "Item 9 on Book p53 lists: (a) 6 meanings of an opening snap (organic MS, pliable non-calcified valve, S2–OS judges severity, amenable to surgery, significant MS, high LA pressure); (b) 3 causes of absent presystolic accentuation (AF, left heart failure, massive LA thrombus); and (c) 6 causes of soft S1 in MS (co-existent MR, MV calcification, digitalis overdose [prolonged PR], acute rheumatic carditis [prolonged PR], AF, and damped MS from PAH/RVH/RV apex). (Book p53)"),

(53, "match", "Opening Snap, Absent PSA, Soft S1 & Differential Diagnoses of MS",
 "Four Differential Diagnoses of MS (10.a–d: ASD, LA Myxoma, Significant MR, Severe AR / Austin Flint) on Book p53",
 "Match each condition in the Differential Diagnosis of Mitral Stenosis [Item 10 on Book p53] to the bedside clues that distinguish it from true MS — 1) Atrial Septal Defect [10.a] 2) Left Atrial Myxoma [10.b] 3) Significant Mitral Regurgitation [10.c] 4) Severe Aortic Regurgitation with Austin Flint murmur [10.d] … A) Prominent apical diastolic murmur from increased anterograde flow, but OS and loud P2 are ABSENT, S1 is soft/absent, and a loud PSM is heard B) RV enlargement and PAH occur in both, but fixed split of S2 and mid-systolic murmur at the left sternal border favour ASD [large L-to-R shunts can cause a functional TS diastolic murmur] C) Not intensified in presystole and becomes SOFTER with the administration of vasodilators D) Systemic features [weight loss, fever, anaemia, systemic emboli, elevated IgG and IL-6] and auscultatory findings that change markedly with body position",
 ["1-B, 2-D, 3-A, 4-C",
  "1-D, 2-B, 3-A, 4-C",
  "1-B, 2-A, 3-D, 4-C",
  "1-B, 2-D, 3-C, 4-A"],
 0,
 "Item 10 on Book p53 contrasts the four key differential diagnoses of MS: (a) ASD (fixed split S2, LSM mid-systolic murmur, functional TS from enhanced diastolic flow); (b) LA myxoma (weight loss, fever, anaemia, systemic emboli, elevated IgG & IL-6, positional murmur change); (c) Significant MR (anterograde flow MDM, absent OS and loud P2, soft/absent S1, loud PSM); and (d) Severe AR (Austin Flint murmur is not intensified in presystole and softens with vasodilators). (Book p53)"),

(53, "scenario", "Opening Snap, Absent PSA, Soft S1 & Differential Diagnoses of MS",
 "Distinguishing Left Atrial Myxoma and Austin Flint murmur from true MS on Book p53",
 "Two patients present with an apical diastolic murmur mimicking Mitral Stenosis: Patient 1 has fever, weight loss, anaemia, systemic emboli, and a murmur that changes markedly with body position; Patient 2 has severe aortic regurgitation and an apical diastolic murmur. According to Book p53 (Item 10.b & 10.d), what laboratory elevations characterise Patient 1, and how does Patient 2's murmur behave in presystole and after vasodilators?",
 ["Patient 1 (LA myxoma) has elevated IgG and IL-6; Patient 2's Austin Flint murmur is NOT intensified in presystole and becomes SOFTER with the administration of vasodilators",
  "Patient 1 (LA myxoma) has elevated IgM and TNF-beta; Patient 2's Austin Flint murmur shows marked presystolic accentuation and becomes louder with vasodilators",
  "Patient 1 (ASD) has low complement C3; Patient 2's murmur is accompanied by a loud opening snap and fixed split S2",
  "Patient 1 (Damped MS) has elevated calcitonin; Patient 2's murmur is unaffected by vasodilators"],
 0,
 "Items 10.b and 10.d on Book p53 state: LA myxoma presents with systemic features (weight loss, fever, anaemia, systemic emboli, elevated IgG and IL-6) and auscultatory findings that change markedly with body position; in severe AR, the Austin Flint murmur is not intensified in presystole and becomes softer with the administration of vasodilators. (Book p53)"),

(53, "fillup", "Opening Snap, Absent PSA, Soft S1 & Differential Diagnoses of MS",
 "ECG findings in MS including the P mitrale tracing (Item 11.a, Book p53)",
 "Under Investigations (Item 11.a on Book p53, illustrated by the ECG tracing), the ECG in Mitral Stenosis shows atrial fibrillation or bifid P waves called ____ (associated with left atrial hypertrophy), alongside right ventricular hypertrophy manifested by ____ in leads V1–V2 and a deep S wave in ____.",
 ["P mitrale; tall R waves; V6",
  "P pulmonale; deep Q waves; aVR",
  "Epsilon waves; QS complexes; V1",
  "Osborn waves; tall T waves; aVL"],
 0,
 "Item 11.a on Book p53 (with the 'P mitrale' ECG strip) states: 'ECG — A fib / bifid P waves (P mitrale) associated with LA hypertrophy / RV hypertrophy — tall R waves in V1, V2 and deep S in V6.' (Book p53)"),

# ---------------------------------------------------------------- Book p54
(54, "match", "Investigations (CXR, Doppler Echo, Wilkins Score) & Medical Management",
 "Chest X-ray findings in MS including pressure thresholds for Kerley B vs Kerley A lines (Item 11.b, Book p54)",
 "Match each Chest X-ray sign of Mitral Stenosis on Book p54 [Item 11.b] to its anatomical basis or pulmonary venous pressure threshold — 1) Earliest CXR sign of MS [11.b.i] 2) Double shadow / 'shadow within a shadow' [11.b.ii] 3) Kerley B lines [11.b.iii] 4) Kerley A lines [11.b.iv] … A) Dense, short, horizontal lines in the costophrenic angle [from distention of interlobular septae and lymphatics with fluid] when pulmonary venous pressure is between 20 and 30 mmHg B) Straight, dense lines running towards the hilum when pulmonary venous pressure is >30 mmHg C) Straightening of the left heart border due to a prominent pulmonary artery and left atrial appendage D) Left atrial enlargement seen behind the heart inside the right heart border",
 ["1-C, 2-D, 3-A, 4-B",
  "1-D, 2-C, 3-A, 4-B",
  "1-C, 2-D, 3-B, 4-A",
  "1-A, 2-D, 3-C, 4-B"],
 0,
 "Item 11.b on Book p54 lists: (i) Straightening of left heart border from prominent PA and LA appendage (Earliest); (ii) LA enlargement causing a double shadow behind the heart in the right heart border ('shadow within a shadow'); (iii) Kerley B lines (interlobular septae/lymphatics distended with fluid, short horizontal costophrenic lines) at pulmonary venous pressure 20–30 mmHg; and (iv) Kerley A lines (straight dense lines running towards the hilum) at pulmonary venous pressure >30 mmHg. (Book p54)"),

(54, "numeric", "Investigations (CXR, Doppler Echo, Wilkins Score) & Medical Management",
 "Pulmonary venous pressure thresholds for Kerley B lines vs Kerley A lines on Book p54",
 "On a Chest X-ray in Mitral Stenosis (Item 11.b.iii–iv, Book p54), Kerley B lines (dense, short, horizontal lines in the costophrenic angle due to distention of interlobular septae and lymphatics with fluid) appear when pulmonary venous pressure is ____, whereas Kerley A lines (straight, dense lines running towards the hilum) appear when pulmonary venous pressure is ____.",
 ["Between 20–30 mmHg; more than 30 mmHg",
  "Between 8–12 mmHg; between 12–18 mmHg",
  "More than 45 mmHg; less than 15 mmHg",
  "Between 5–10 mmHg; more than 60 mmHg"],
 0,
 "Items 11.b.iii and 11.b.iv on Book p54 specify that Kerley B lines appear when pulmonary venous pressure is between 20–30 mmHg, and Kerley A lines appear when pulmonary venous pressure is more than 30 mmHg. (Book p54)"),

(54, "numeric", "Investigations (CXR, Doppler Echo, Wilkins Score) & Medical Management",
 "Doppler Echo MVA severity classification and enlarged LA cutoff on Book p54",
 "In the Doppler Echo Severity Classification on Book p54 (Item 11.c.i), normal mitral valve area (MVA) is ____, progressive MS is ____, severe MS is ____, very severe / tight / critical MS is ____, and an enlarged left atrium is defined as a largest dimension of ____.",
 ["4–6 cm²; >1.5 cm²; 1–1.5 cm²; <1 cm²; >5.5 cm",
  "2–3 cm²; >2.0 cm²; 1.5–2.0 cm²; <1.5 cm²; >4.0 cm",
  "4–6 cm²; >2.5 cm²; 1.5–2.5 cm²; <0.5 cm²; >3.5 cm",
  "6–8 cm²; >3.0 cm²; 2.0–3.0 cm²; <1.5 cm²; >7.0 cm"],
 0,
 "Item 11.c.i on Book p54 specifies: Normal MVA = 4–6 cm²; <1 cm² = very severe MS / tight MS / critical MS; 1–1.5 cm² = severe MS; >1.5 cm² = progressive MS; and enlarged LA = largest dimension >5.5 cm (along with thickened immobile cusps, reduced rate of LV diastolic filling, and vegetation/thrombus). (Book p54)"),

(54, "scenario", "Investigations (CXR, Doppler Echo, Wilkins Score) & Medical Management",
 "Abascal or Wilkins Echocardiography Score: 4 components, point value, and BMV cutoff (<8/16) on Book p54",
 "Before planning a percutaneous balloon mitral valvotomy (BMV), you calculate the Abascal or Wilkins Echocardiography score (Item 11.c.ii–iii on Book p54). What are its four parameters, how many points does each carry, and what total score indicates that the valve is amenable to BMV?",
 ["1. Leaflet mobility, 2. Valve thickness, 3. Subvalvular thickening, 4. Valvular calcification — each carries 4 points (total 16); a Wilkins score of <8/16 means the valve is amenable to BMV (otherwise surgery is advised)",
  "1. LA diameter, 2. PASP, 3. LV ejection fraction, 4. Regurgitant jet area — each carries 5 points (total 20); a score >15 indicates BMV",
  "1. S2–OS gap, 2. MDM grade, 3. QRS axis, 4. Kerley B count — each carries 2 points (total 8); a score of 8/8 indicates BMV",
  "1. Annular diameter, 2. Papillary muscle number, 3. Chordal length, 4. Aortic root size — each carries 3 points (total 12); a score <4/12 indicates BMV"],
 0,
 "Item 11.c.ii–iii on Book p54 lists the four components of the Abascal/Wilkins score — (1) Leaflet mobility, (2) Valve thickness, (3) Subvalvular thickening, (4) Valvular calcification — each carrying 4 points (out of 16), where <8/16 indicates amenability to BMV and otherwise surgery is advised. Item 11.d notes cardiac catheterisation checks for CAD, pulmonary artery pressure, MS and MR. (Book p54)"),

(54, "management", "Investigations (CXR, Doppler Echo, Wilkins Score) & Medical Management",
 "Medical management of MS: Penicillin V dosing, Digoxin 5-days-a-week regimen, Diltiazem/Atenolol, and Warfarin INR target on Book p54",
 "Which medical management regimen for Mitral Stenosis matches Item 12.a (i–vi) on Book p54?",
 ["Penicillin V 250 mg BD (250 mg QID if acute rheumatic fever; lifelong if established heart disease); for AF, Digoxin 0.25 mg 5 days a week OD (adding oral Diltiazem or Atenolol if rate is not controlled); Warfarin targeted to INR 2–3 indefinitely in MS with AF or history of thromboembolism; plus Diuretics",
  "Penicillin V 1000 mg TDS for 7 days only; Amiodarone monotherapy for all sinus-rhythm MS patients; Aspirin 75 mg OD instead of Warfarin in AF; and high-dose IV fluids",
  "Oral Gentamicin 80 mg BD for 6 months; Digoxin 2 mg IV QID daily without holiday; Warfarin targeted to INR 4.5–6.0 in all mild MS patients",
  "No antibiotic prophylaxis once MS is diagnosed; Nifedipine sublingually for rate control; and Dabigatran in all mechanical valve patients"],
 0,
 "Item 12.a (i–vi) on Book p54 specifies: (i) Penicillin V 250 mg BD; (ii) if rheumatic fever, 250 mg QID; (iii) if established heart disease, lifelong; (iv) AF: Digoxin 0.25 mg 5 days a week OD (to avoid digoxin toxicity), and if rate is not controlled by digoxin, oral Diltiazem/Atenolol; (v) Warfarin targeted to INR 2–3 indefinitely for MS with AF or history of thromboembolism; (vi) Diuretics. (Book p54)"),

# ---------------------------------------------------------------- Book p55
(55, "management", "Surgical & Interventional Management: Emergency AF, BMV & Prosthetic Valves",
 "Emergency AF rapid digitalisation protocol and Closed Mitral Valvotomy (TUBBS dilator) on Book p55",
 "According to Book p55 (Item 12.a.vii & 12.b.i), how is emergency atrial fibrillation in MS managed with rapid digitalisation, and how is closed mitral valvotomy/commissurotomy performed?",
 ["Emergency AF: Digoxin 0.25 mg IV bolus, wait 2 hours; if no improvement, repeat 0.25 mg IV until a maximum of 1 mg, and if it still does not work, give beta-blockers. Closed mitral valvotomy (preferred in pliable valves without associated MR) is done with the aid of a TUBBS transventricular dilator",
  "Emergency AF: Digoxin 2.0 mg IM stat followed by immediate atropine. Closed mitral valvotomy is preferred in heavily calcified valves with severe MR using an Amplatzer device",
  "Emergency AF: Adenosine 6 mg IV infusion over 24 hours. Closed mitral valvotomy is performed via the femoral vein using a Fogarty catheter",
  "Emergency AF: Oral verapamil once weekly. Closed mitral valvotomy requires cardiopulmonary bypass and excision of both papillary muscles"],
 0,
 "Book p55 (top) states: (vii) Emergency AF — rapid digitalisation 0.25 mg IV bolus, wait for 2 hours; if no improvement, 0.25 mg again until max 1 mg; if it does not work, beta-blockers. Under Sx (b.i): Closed mitral valvotomy/commissurotomy is preferred in patients with pliable valves without associated MR, done with the aid of a TUBBS transventricular dilator. (Book p55)"),

(55, "match", "Surgical & Interventional Management: Emergency AF, BMV & Prosthetic Valves",
 "Balloon Mitral Valvotomy (BMV): 5 selection criteria, 4 complications, and 2 criteria for success on Book p55",
 "Match each aspect of Balloon Mitral Valvotomy [BMV, Item 12.b.ii on Book p55] to its listed criteria or complications — 1) Five selection criteria for BMV [ii.1.a–e] 2) Four complications of BMV [ii.2.a–d] 3) Two haemodynamic criteria for a successful BMV [ii.3.a–b] 4) Indication for Mitral Valve Replacement instead of valvotomy [iii.1] … A) Embolic events, cardiac perforation, mitral regurgitation [MR], and iatrogenic ASD B) [a] 50% reduction in the mean mitral valve gradient, and [b] doubling of the mitral valve area C) Significant symptoms, isolated MS, no MR, mobile non-calcified valve, and no LA thrombus D) When associated MR is present or the valve is rigid and calcified",
 ["1-C, 2-A, 3-B, 4-D",
  "1-A, 2-C, 3-B, 4-D",
  "1-C, 2-B, 3-A, 4-D",
  "1-C, 2-A, 3-D, 4-B"],
 0,
 "Item 12.b.ii–iii on Book p55 lists: (1) BMV criteria = significant symptoms, isolated MS, no MR, mobile non-calcified valve, no LA thrombus; (2) BMV complications = embolic events, cardiac perforation, MR, iatrogenic ASD; (3) Criteria for successful BMV = 50% reduction in mean MV gradient and doubling of MVA; and (iii.1) Valve replacement when associated MR is present or valve is rigid and calcified. (Book p55)"),

(55, "match", "Surgical & Interventional Management: Emergency AF, BMV & Prosthetic Valves",
 "Mechanical vs Bioprosthetic valves and the MECHANICAL VALVES figure on Book p55",
 "Match each prosthetic valve category on Book p55 [Item 12.b.iii.2–3 and the 'MECHANICAL VALVES' figure] to its examples, target INR, and advantages/limitations — 1) Caged-ball vs Tilting-disc / Bileaflet mechanical valves [text & figure] 2) Target INR for mechanical mitral prostheses and 3 reasons tilting-disc is preferred to caged-ball 3) Bioprosthetic valves — advantage and examples 4) Bioprosthetic valves — age limitation … A) Desired INR 2.5–3.5; tilting-disc is preferred to caged-ball because it [i] occupies less space, [ii] has less incidence of haemolysis, and [iii] has less incidence of strut fractures B) Caged-ball = Starr-Edwards Silastic ball valve; Tilting-disc / bileaflet = St. Jude Medical bileaflet valve, Bjork-Shiley valve, and Chitra TTK tilting disc valve [Indian] C) Not useful in patients <65 years of age due to rapid deterioration D) Lower incidence of thromboembolism; examples include Porcine, Pericardial xenograft, and Cadaveric valve",
 ["1-B, 2-A, 3-D, 4-C",
  "1-A, 2-B, 3-D, 4-C",
  "1-B, 2-D, 3-A, 4-C",
  "1-B, 2-A, 3-C, 4-D"],
 0,
 "Item 12.b.iii.2–3 and the 'MECHANICAL VALVES' figure on Book p55 cover: desired INR 2.5–3.5 for mechanical prostheses; Caged-ball = Starr-Edwards Silastic ball valve; Tilting-disc/bileaflet = St. Jude, Bjork-Shiley, and Chitra TTK tilting disc valve (Indian); 3 reasons tilting-disc is preferred over caged-ball (occupies less space, less haemolysis, less strut fractures); and Bioprosthesis (lower thromboembolism, not useful in patients <65 years due to rapid deterioration; e.g. porcine, pericardial xenograft, cadaveric valve). (Book p55)"),

(55, "truefalse", "Surgical & Interventional Management: Emergency AF, BMV & Prosthetic Valves",
 "Target INR in MS with AF (2–3) vs Mechanical Valve (2.5–3.5) and Bioprosthesis <65 years cutoff on Book p55",
 "Which of the following True/False statements accurately compares the prosthetic valve rules on Book p55?",
 ["True: Mechanical mitral prostheses require a desired INR of 2.5–3.5 (higher than the INR 2–3 used for native MS with AF on p54), and bioprosthetic valves are not useful in patients <65 years of age due to rapid deterioration",
  "True: Caged-ball Starr-Edwards valves are preferred over tilting-disc valves because they occupy less space and cause less haemolysis",
  "False: The Chitra TTK valve shown on Book p55 is an Indian tilting-disc mechanical valve",
  "False: Successful balloon mitral valvotomy is defined by a 50% reduction in mean mitral valve gradient and doubling of the mitral valve area"],
 0,
 "Book p54–55 contrasts the Warfarin target INR of 2–3 for native MS with AF/thromboembolism (p54) against the desired INR of 2.5–3.5 for mechanical prostheses (p55), notes that tilting-disc valves (St. Jude, Bjork-Shiley, Indian Chitra TTK) are preferred to caged-ball (Starr-Edwards) because they occupy less space and have less haemolysis and strut fractures, and states that bioprostheses are not useful in patients <65 years due to rapid deterioration. (Book p55)"),

(55, "oddoneout", "Surgical & Interventional Management: Emergency AF, BMV & Prosthetic Valves",
 "Reasons tilting-disc valves are preferred over caged-ball valves and BMV success criteria on Book p55",
 "All of the following statements about surgical and interventional management of Mitral Stenosis on Book p55 are true EXCEPT:",
 ["Tilting-disc valves (e.g. St. Jude, Bjork-Shiley, Indian Chitra TTK) are preferred to caged-ball (Starr-Edwards) valves because they occupy less space, have a lower incidence of haemolysis, and have a lower incidence of strut fractures",
  "Criteria for a successful Balloon Mitral Valvotomy (BMV) are a 50% reduction in the mean mitral valve gradient and a doubling of the mitral valve area",
  "Complications of BMV include embolic events, cardiac perforation, mitral regurgitation, and iatrogenic atrial septal defect (ASD)",
  "Bioprosthetic valves (porcine, pericardial xenograft, cadaveric) are the prosthesis of choice in patients <30 years of age because they never deteriorate"],
 3,
 "Item 12.b.iii.3.b on Book p55 explicitly states that bioprosthetic valves (porcine, pericardial xenograft, cadaveric valve) are 'Not useful in patients <65 years of age due to rapid deterioration.' (Book p55)"),
]
