# -*- coding: utf-8 -*-
"""Chapter 7 source data: Book p56-57 (Mitral Regurgitation)."""

# (page, fmt, sec, point, question, options, ans, explanation)
DATA = [
# ---------------------------------------------------------------- Book p56 (Harrison's Table 264-1)
(56, "recall", "Harrison's Table 264-1: Major Causes of Mitral Regurgitation",
 "Acute row of Table 264-1: IE, papillary muscle rupture (post-MI), chordal rupture/leaflet flail (MVP, IE), blunt trauma",
 "In Harrison's Table 264-1 'Major Causes of Mitral Regurgitation (MR)' (Book p56), which of these is listed under the ACUTE etiologies?",
 ["Blunt trauma",
  "HOCM with systolic anterior motion",
  "Myxomatous disease — Barlow's",
  "Mitral annular calcification"],
 0,
 "The Acute row of Table 264-1 on Book p56 lists exactly four: IE, papillary muscle rupture (post-MI), chordal rupture/leaflet flail (MVP, IE) and blunt trauma. HOCM with SAM and mitral annular calcification sit under Chronic, and Barlow's is Chronic Primary (myxomatous). (Book p56)"),

(56, "match", "Harrison's Table 264-1: Major Causes of Mitral Regurgitation",
 "Four rows of Table 264-1 (Acute / Chronic Primary / Chronic Secondary / Mitral annular calcification) mapped to their defining feature",
 "Match each category of the Major Causes of MR table on Book p56 to its defining feature — 1) Acute causes 2) Chronic — Primary (affecting leaflets, chordae) 3) Chronic — Secondary (leaflet and chordal disease absent) 4) Mitral annular calcification … A) Leaflets and chordae are 'innocent bystanders' B) Includes myxomatous, rheumatic, healed IE, congenital and radiation C) Includes papillary muscle rupture (post-MI) and chordal rupture/leaflet flail D) May be 'mixed' — disease encroaches on leaflets and impairs sphincteric function of the annulus",
 ["1-C, 2-B, 3-D, 4-A",
  "1-C, 2-B, 3-A, 4-D",
  "1-B, 2-C, 3-A, 4-D",
  "1-C, 2-A, 3-B, 4-D"],
 1,
 "Table 264-1 on Book p56: Acute = IE, papillary muscle rupture (post-MI), chordal rupture/leaflet flail (MVP, IE), blunt trauma; Chronic Primary (affecting leaflets, chordae) = myxomatous, rheumatic fever, IE (healed), congenital (cleft, AV canal), radiation; Chronic Secondary (leaflets, chordae 'innocent bystanders') = ischemic CM, dilated CM, HOCM with SAM, AF with LA enlargement and annular dilation; Mitral annular calcification carries the 'mixed' footnote. (Book p56)"),

(56, "recall", "Harrison's Table 264-1: Major Causes of Mitral Regurgitation",
 "Chronic Primary (affecting leaflets, chordae) list: Myxomatous, Rheumatic fever, IE (healed), Congenital (cleft, AV canal), Radiation",
 "Which of the following is classified in Table 264-1 (Book p56) as a CHRONIC PRIMARY cause of MR — a disease affecting the leaflets and chordae themselves?",
 ["Ischemic cardiomyopathy",
  "AF with LA enlargement and annular dilation (atrial functional MR)",
  "Radiation",
  "HOCM with SAM"],
 2,
 "The Chronic Primary list on Book p56 (affecting leaflets, chordae) is: Myxomatous (MVP, Barlow's, forme fruste), Rheumatic fever, IE (healed), Congenital (cleft, AV canal) and Radiation. Ischemic cardiomyopathy, AF-related atrial functional MR and HOCM with SAM are all Chronic Secondary, where leaflets and chordae are 'innocent bystanders'. (Book p56)"),

(56, "fillup", "Harrison's Table 264-1: Major Causes of Mitral Regurgitation",
 "The three entities under 'Myxomatous' in the Chronic Primary list (MVP, Barlow's, forme fruste)",
 "In the Chronic Primary list of Table 264-1 (Book p56), the entry 'Myxomatous' expands to ____, ____ and ____.",
 ["MVP, Barlow's, forme fruste",
  "cleft, AV canal, rheumatic leaflet fusion",
  "papillary muscle rupture, chordal rupture, blunt trauma",
  "annular dilation, leaflet flail, healed endocarditis"],
 0,
 "Book p56 lists under Chronic Primary: 'Myxomatous (MVP, Barlow's, forme fruste)', followed by Rheumatic fever, IE (healed), Congenital (cleft, AV canal) and Radiation. (Book p56)"),

(56, "recall", "Harrison's Table 264-1: Major Causes of Mitral Regurgitation",
 "Chronic Secondary (leaflets, chordae 'innocent bystanders') list: Ischemic CM, Dilated CM, HOCM (with SAM), AF with LA enlargement and annular dilation (atrial functional MR)",
 "Which of the following is listed under Chronic Secondary MR — where the leaflets and chordae are 'innocent bystanders' — in Table 264-1 (Book p56)?",
 ["Congenital cleft and AV canal",
  "IE (healed)",
  "Barlow's",
  "AF with LA enlargement and annular dilation (atrial functional MR)"],
 3,
 "The Chronic Secondary block on Book p56 (leaflets, chordae 'innocent bystanders') lists Ischemic cardiomyopathy, Dilated cardiomyopathy, HOCM (with SAM) and AF with LA enlargement and annular dilation (atrial functional MR). Congenital cleft/AV canal and healed IE are Chronic Primary; Barlow's is Myxomatous (Primary). (Book p56)"),

(56, "oddoneout", "Harrison's Table 264-1: Major Causes of Mitral Regurgitation",
 "Odd-one-out within the Chronic Secondary 'innocent bystanders' group",
 "All of the following belong to the Chronic Secondary group of Table 264-1 (Book p56) — leaflets and chordae as 'innocent bystanders' — EXCEPT:",
 ["Ischemic cardiomyopathy",
  "Dilated cardiomyopathy",
  "Congenital AV canal defect",
  "HOCM with SAM"],
 2,
 "Congenital (cleft, AV canal) is a Chronic PRIMARY cause (disease of leaflets/chordae), not a Secondary 'innocent bystander' cause. Ischemic CM, Dilated CM and HOCM with SAM are the table's Secondary etiologies (along with AF-related atrial functional MR). (Book p56)"),

(56, "truefalse", "Harrison's Table 264-1: Major Causes of Mitral Regurgitation",
 "Footnote a to Mitral annular calcification: mixed primary+secondary elements, sphincteric function, MVP + ischemic CM example",
 "Which of the following True/False statements correctly reflects footnote 'a' attached to Mitral annular calcification in Table 264-1 (Book p56)?",
 ["False: the sphincteric function of the mitral annulus may be impaired by the calcific process",
  "True: mitral annular calcification may include elements of both primary and secondary MR (mixed), because the disease process may encroach on the leaflets, impair the normal sphincteric function of the annulus, or both",
  "True: mitral annular calcification is classified purely as a primary leaflet disease",
  "False: 'mixed' secondary MR exists, such as coexistence of MVP with an ischemic cardiomyopathy"],
 1,
 "Footnote a on Book p56: mitral annular calcification may include elements of both primary and secondary MR (mixed) as the disease process may encroach on the leaflets, impair the normal sphincteric function of the annulus, or both — and it gives coexistence of MVP with an ischemic cardiomyopathy as an example of 'mixed' secondary MR. (Book p56)"),

(56, "match", "Harrison's Table 264-1: Major Causes of Mitral Regurgitation",
 "Abbreviation key at the foot of Table 264-1: SAM, HOCM, AV, MVP",
 "Match the abbreviations from the abbreviation key of Table 264-1 (Book p56) to their full forms — 1) SAM 2) HOCM 3) AV 4) MVP … A) Atrioventricular B) Systolic anterior motion C) Hypertrophic obstructive cardiomyopathy D) Mitral valve prolapse",
 ["1-B, 2-C, 3-A, 4-D",
  "1-B, 2-A, 3-C, 4-D",
  "1-C, 2-B, 3-A, 4-D",
  "1-B, 2-C, 3-D, 4-A"],
 0,
 "The key at the foot of Table 264-1 on Book p56: AF = atrial fibrillation; AV = atrioventricular; HOCM = hypertrophic obstructive cardiomyopathy; IE = infective endocarditis; LA = left atrial; LV = left ventricular; MI = myocardial infarction; MVP = mitral valve prolapse; SAM = systolic anterior motion. (Book p56)"),

# ---------------------------------------------------------------- Book p57 (Mitral Regurgitation note)
(57, "recall", "MR Causes: Acute vs Chronic",
 "Acute MR list on p57: Endocarditis, Post-MI papillary muscle rupture (posteromedial), Chordal rupture/leaflet flail due to MVP and IE, Trauma",
 "Which of the following is named in the acute MR cause list on Book p57?",
 ["Anterolateral papillary muscle rupture after MI",
  "Congenital cleft of the anterior leaflet",
  "Posteromedial papillary muscle rupture post-MI",
  "Aortic root dissection"],
 2,
 "Book p57's acute MR list: Endocarditis, Post-MI papillary muscle rupture (posteromedial), Chordal rupture/leaflet flail due to MVP and IE, and Trauma. The note specifies the POSTEROMEDIAL papillary muscle, not the anterolateral. (Book p57)"),

(57, "fillup", "MR Causes: Acute vs Chronic",
 "Posteromedial papillary muscle rupture in post-MI acute MR; MVP and IE as chordal rupture/leaflet flail causes",
 "Per Book p57, post-MI acute MR classically results from rupture of the ____ papillary muscle, while chordal rupture/leaflet flail in acute MR arises from ____ and ____.",
 ["posteromedial; MVP; infective endocarditis",
  "anterolateral; rheumatic fever; atrial fibrillation",
  "posteromedial; HOCM; mitral annular calcification",
  "anterolateral; radiation; trauma"],
 0,
 "Book p57: 'Acute MR: Endocarditis, Post MI papillary muscle rupture (posteromedial), Chordal rupture/leaflet fall due to MVP and IE, Trauma'. (Book p57)"),

(57, "recall", "MR Causes: Acute vs Chronic",
 "Chronic MR list on p57: MVP, Rheumatic Fever, healed endocarditis, mitral annular calcification, congenital cleft, HOCM with SAM, Dilated cardiomyopathy",
 "Which of the following belongs to the CHRONIC MR cause list on Book p57?",
 ["Post-MI papillary muscle rupture",
  "HOCM with SAM",
  "Blunt trauma",
  "Acute endocarditis with leaflet perforation"],
 1,
 "Book p57's chronic MR list: MVP, Rheumatic Fever, healed endocarditis, mitral annular calcification, congenital cleft, HOCM with SAM, Dilated cardiomyopathy. Post-MI papillary muscle rupture, blunt trauma and acute endocarditis are acute causes. (Book p57)"),

(57, "scenario", "MR Haemodynamics: Chronic vs Acute",
 "Chronic MR haemodynamics: gradual LA dilation with little pressure rise (few symptoms); slow LV dilation; gradual LA and LV pressure rise from chronic volume overload",
 "A 45-year-old woman with long-standing mitral regurgitation is asymptomatic. Which haemodynamic course on Book p57 explains chronic MR?",
 ["Gradual LA dilation with little rise in LA pressure (hence very few symptoms), slow LV dilation, and gradual rise in LA and LV pressures from chronic volume overload",
  "A rapid rise in LA pressure because the LA compliance is reduced",
  "Rapid LV pressure overload with preserved LV volume and high LA pressures from the start",
  "Immediate right atrial dilation with spared left-sided pressures"],
 0,
 "Book p57: chronic MR causes gradual dilation of the LA with little increase in pressures and therefore causes very few symptoms; the LV dilates slowly and the LA and LV pressures gradually increase due to chronic volume overload. (Book p57)"),

(57, "truefalse", "MR Haemodynamics: Chronic vs Acute",
 "Chronic MR: increased LV volume often with reduced cardiac output (verify note); acute MR: rapid LA pressure rise due to normal LA compliance with marked deterioration",
 "Which of the following True/False statements accurately reflects the MR haemodynamics on Book p57?",
 ["False: acute MR causes a rapid rise in LA pressure because of normal LA compliance, producing marked symptomatic deterioration",
  "True: chronic MR causes gradual LA dilation with little increase in pressure, and therefore very few symptoms",
  "True: increased LV volume in chronic MR is often accompanied by an increased cardiac output",
  "False: chronic volume overload gradually increases both LA and LV pressures in chronic MR"],
 1,
 "Book p57: chronic MR — gradual LA dilation, little pressure rise, very few symptoms; 'increased LV volume is often accompanied by a reduced cardiac output (verify this)'; LA and LV pressures rise gradually with chronic volume overload. Acute MR — rapid LA pressure rise (normal LA compliance) with marked symptomatic deterioration. (Book p57)"),

(57, "scenario", "MR Haemodynamics: Chronic vs Acute",
 "Acute MR haemodynamics: normal LA compliance prevents buffering, so LA pressure rises rapidly with marked symptomatic deterioration",
 "A 60-year-old man, 4 days after an anterior MI, develops sudden dyspnoea, hypotension and bilateral pulmonary oedema with a new systolic murmur. Per Book p57, why does acute MR cause such marked symptomatic deterioration?",
 ["The LV becomes acutely pressure-overloaded, raising systolic LV pressure against a stenotic outflow",
  "The non-compliant, undilated LA cannot buffer the regurgitant volume, so LA pressure rises rapidly",
  "The right atrium fails to accept the regurgitant volume, isolating the pulmonary circuit",
  "Atrial fibrillation shortens ventricular systole and prolongs the regurgitant orifice"],
 1,
 "Book p57: acute MR causes a rapid rise in LA pressure because of normal LA compliance (the undilated LA cannot dilate to accommodate the regurgitant stroke volume), producing marked symptomatic deterioration. (Book p57)"),

(57, "match", "MR Symptoms",
 "Four MR symptoms on p57 matched to their stated mechanisms: Dyspnoea (early, with palpitations), Fatigue (decreased CO), Palpitations (A fib, increased stroke volume), late Right heart failure",
 "Match the MR symptoms on Book p57 to their stated mechanism — 1) Dyspnoea 2) Fatigue 3) Palpitations 4) Right heart failure … A) Decreased cardiac output B) Early, along with palpitations C) Atrial fibrillation and increased stroke volume D) Occurs in the late stages",
 ["1-B, 2-C, 3-A, 4-D",
  "1-A, 2-B, 3-C, 4-D",
  "1-B, 2-A, 3-D, 4-C",
  "1-B, 2-A, 3-C, 4-D"],
 3,
 "Book p57 symptoms: Dyspnoea (early, along with palpitations); Fatigue — decreased cardiac output; Palpitations — A fib, increased stroke volume; Right heart failure in late stages. (Book p57)"),

(57, "oddoneout", "MR Symptoms",
 "Odd-one-out among the MR symptoms listed on p57",
 "All of the following are listed as symptoms of MR on Book p57 EXCEPT:",
 ["Dyspnoea, early with palpitations",
  "Fatigue from decreased cardiac output",
  "Palpitations from A fib and increased stroke volume",
  "Exertional angina from subendocardial ischaemia"],
 3,
 "Book p57 lists exactly: Dyspnoea (early, with palpitations), Fatigue (decreased cardiac output), Palpitations (A fib, increased stroke volume) and Right heart failure in late stages. Exertional angina is not on the list. (Book p57)"),

(57, "recall", "MR Signs",
 "MR sign list on p57: A fib; cardiomegaly with displaced hyperdynamic apex; apical PSM +/- thrill; soft S1, S3; pulmonary venous congestion (crepts, oedema, effusions); pulmonary hypertension and right heart failure",
 "Which of the following is a listed sign of MR on Book p57?",
 ["Loud S1 with an S4 gallop",
  "Apical mid-diastolic rumble with an opening snap",
  "Soft S1 with an S3",
  "Mid-diastolic apical thrill"],
 2,
 "Book p57 signs of MR: A fib; cardiomegaly with a displaced hyperdynamic apex; apical PSM ± thrill; soft S1, S3; signs of pulmonary venous congestion (crepts, oedema, effusions); signs of pulmonary hypertension and right heart failure. Soft (not loud) S1 with S3 is the auscultatory entry. (Book p57)"),

(57, "match", "MR Signs",
 "The six sign entries on p57 matched to their book description",
 "Match the six sign entries of the MR list on Book p57 to their description — 1) A fib 2) Cardiomegaly 3) Apical PSM 4) S1 and S3 5) Pulmonary venous congestion 6) Late stage … A) Listed first in the MR sign list (arrhythmic) B) With a displaced hyperdynamic apex C) ± thrill D) Soft S1 with an S3 gallop E) Crepts, oedema, effusions F) Signs of pulmonary hypertension and right heart failure",
 ["1-A, 2-C, 3-B, 4-D, 5-E, 6-F",
  "1-B, 2-A, 3-C, 4-D, 5-E, 6-F",
  "1-A, 2-B, 3-C, 4-E, 5-D, 6-F",
  "1-A, 2-B, 3-C, 4-D, 5-E, 6-F"],
 3,
 "Book p57's MR sign list in order: a. A fib; b. Cardiomegaly with a displaced hyperdynamic apex; c. Apical PSM ± thrill; d. Soft S1, S3; e. Signs of pulmonary venous congestion — crepts, oedema, effusions; f. Signs of pulmonary hypertension and right heart failure. (Book p57)"),

(57, "oddoneout", "MR Signs",
 "Odd-one-out: a TR-specific sign among MR signs",
 "Which of the following is NOT among the listed signs of MR on Book p57?",
 ["Giant V waves in the JVP with deep Y descents",
  "Cardiomegaly with a displaced hyperdynamic apex",
  "Apical PSM ± thrill",
  "Signs of pulmonary hypertension and right heart failure"],
 0,
 "Giant V waves with deep Y descents (Lancisi sign) belong to the TR side of the TR-vs-MR comparison on Book p57; the MR sign list contains A fib, cardiomegaly with displaced hyperdynamic apex, apical PSM ± thrill, soft S1/S3, pulmonary venous congestion, and pulmonary hypertension/right heart failure. (Book p57)"),

(57, "match", "MR Investigations",
 "MR investigations on p57: ECG (LAH, LVH/A fib), CXR (inverted moustache, enlarged LA/LV, pulm venous congestion, pulm oedema if acute), Echo (dilated LA, LV), Doppler, cardiac cath",
 "Match the MR investigations on Book p57 to the findings the note lists for them — 1) ECG 2) CXR 3) Echo 4) Doppler; cardiac catheterisation … A) Inverted moustache, enlarged LA and LV, pulmonary venous congestion, pulmonary oedema if acute B) Dilated LA and LV C) Left atrial hypertrophy, left ventricular hypertrophy or A fib D) Listed as further investigations without elaborated findings",
 ["1-C, 2-A, 3-D, 4-B",
  "1-C, 2-A, 3-B, 4-D",
  "1-A, 2-C, 3-B, 4-D",
  "1-C, 2-B, 3-A, 4-D"],
 1,
 "Book p57 investigations: ECG — left atrial hypertrophy, left ventricular hypertrophy / A fib; CXR — inverted moustache, enlarged LA, LV, pulmonary venous congestion, pulmonary oedema if acute; Echo — dilated LA, LV; Doppler; cardiac cath (listed without further elaboration). (Book p57)"),

(57, "fillup", "MR Investigations",
 "CXR 'inverted moustache' of MR and pulmonary oedema in acute MR",
 "The characteristic CXR sign of mitral regurgitation on Book p57 is the inverted ____ silhouette, and in acute MR the film may additionally show ____.",
 ["moustache; pulmonary oedema",
  "snowman; cardiomegaly with a clear lung field",
  "egg-on-a-string; pulmonary oligemia",
  "straight border; pleural effusion only"],
 0,
 "Book p57 CXR entry for MR: i. Inverted moustache; ii. Enlarged LA, LV, Pulm venous congestion, Pulm oedema if acute. (Book p57)"),

(57, "match", "TR vs MR: Differentiating Features",
 "The six TR features in the TR-vs-MR list on p57: tricuspid-area murmur, positive Carvallo's, hepatic pulsation, A-JR response (Vitam sign), giant V waves with deep Y descents (Lancisi sign), earlobe pulsation",
 "Match the six TR features of the TR-vs-MR list on Book p57 to their description — 1) Murmur site 2) Carvallo's sign 3) Hepatic pulsation 4) Response to abdominojugular reflux 5) Giant V waves with deep Y descents 6) Earlobe pulsation … A) Best heard in the tricuspid area B) Positive with inspiration C) Pulsation of the liver D) The 'Vitam sign' E) The 'Lancisi sign' F) Visible pulsation of the earlobe",
 ["1-A, 2-C, 3-B, 4-D, 5-E, 6-F",
  "1-A, 2-B, 3-C, 4-E, 5-D, 6-F",
  "1-A, 2-B, 3-C, 4-D, 5-E, 6-F",
  "1-B, 2-A, 3-C, 4-D, 5-E, 6-F"],
 2,
 "Book p57 'TR has': i. Murmur best heard in tricuspid area; ii. Positive Carvallo's; iii. Hepatic pulsation; iv. Response to abdominojugular reflux — Vitum sign; v. Giant V waves with deep Y descents — Lancisi sign; vi. Earlobe pulsation. (Book p57)"),

(57, "scenario", "TR vs MR: Differentiating Features",
 "Why acute MR produces an early systolic murmur: undilated LA means LV-LA pressure equalises in early systole",
 "A 55-year-old with acute MR from chordal rupture has a pansystolic murmur that begins very early in systole. According to Book p57, why is the murmur early systolic in acute MR?",
 ["The regurgitant orifice is small, so the jet is low-velocity and late in systole",
  "Pulmonary artery pressure falls, delaying aortic valve closure",
  "A dilated LA must first be present for a PSM to occur; in early MR the LA cannot dilate, so LV and LA pressures equalise in early systole itself",
  "Atrial fibrillation shortens ventricular systole so the murmur ends early"],
 2,
 "Book p57: 'Acute MR causes an early systolic murmur. This is because a dilated LA needs to be present for a PSM to occur and in early MR the LA is not capable of dilation, so the LV and LA pressure equalises in early systole itself.' (Book p57)"),

(57, "truefalse", "TR vs MR: Differentiating Features",
 "TR feature statements: tricuspid-area murmur, Carvallo's, Vitam sign (A-JR), Lancisi sign (giant V waves), earlobe pulsation",
 "Which of the following True/False statements is consistent with the TR-vs-MR section on Book p57?",
 ["False: giant V waves with deep Y descents in TR are called Lancisi's sign",
  "True: earlobe pulsation is a listed sign of MR, not of TR",
  "True: TR shows a response to abdominojugular reflux — the 'Vitam sign'",
  "False: in TR the murmur becomes louder with inspiration — positive Carvallo's"],
 2,
 "Book p57's TR list: murmur best heard in the tricuspid area, positive Carvallo's, hepatic pulsation, response to abdominojugular reflux (Vitam sign), giant V waves with deep Y descents (Lancisi sign) and earlobe pulsation — all features of TR, not MR. (Book p57)"),
]
