# -*- coding: utf-8 -*-
"""Chapter 9 source data: Book p62-63 (Aortic Regurgitation)."""

# (page, fmt, sec, point, question, options, ans, explanation)
DATA = [
# ---------------------------------------------------------------- Book p62 (Harrison's Table 262-1)
(62, "recall", "Harrison's Table 262-1: Major Causes of Aortic Regurgitation",
 "Valvular column of Table 262-1: Congenital (bicuspid), Endocarditis, Rheumatic fever, Myxomatous (prolapse), Radiation, Trauma, Syphilis, Ankylosing spondylitis",
 "Which of the following is listed under the VALVULAR column of Table 262-1 'Major Causes of Aortic Regurgitation' (Book p62)?",
 ["Aortic dissection",
  "Hypertension",
  "Radiation",
  "Nonsyndromic familial aneurysm"],
 2,
 "Table 262-1 on Book p62 (Valve lesion: Aortic regurgitation) — Valvular column: Congenital (bicuspid), Endocarditis, Rheumatic fever, Myxomatous (prolapse), Radiation, Trauma, Syphilis, Ankylosing spondylitis. Aortic dissection, Hypertension and Nonsyndromic familial aneurysm sit in the Aortic root disease column. (Book p62)"),

(62, "match", "Harrison's Table 262-1: Major Causes of Aortic Regurgitation",
 "The two etiology columns of Table 262-1 (Valvular vs Aortic root disease) applied to four entries",
 "Match the four AR etiologies of Table 262-1 (Book p62) to their table placement — 1) Radiation 2) Hypertension 3) Ankylosing spondylitis 4) Nonsyndromic familial aneurysm … A) Valvular-column entry — the radiation-induced etiology B) The one root-disease-column entry that is not a structural aortic-root disorder C) Valvular-column entry — the inflammatory spondyloarthropathy D) Root-disease-column entry — the familial aneurysm without a named syndrome",
 ["1-A, 2-C, 3-B, 4-D",
  "1-A, 2-B, 3-C, 4-D",
  "1-C, 2-B, 3-A, 4-D",
  "1-A, 2-B, 3-D, 4-C"],
 1,
 "Table 262-1 on Book p62: Valvular = Congenital (bicuspid), Endocarditis, Rheumatic fever, Myxomatous (prolapse), Radiation, Trauma, Syphilis, Ankylosing spondylitis; Aortic root disease = Aortic dissection, Medial degeneration, Marfan syndrome, Bicuspid aortic valve, Nonsyndromic familial aneurysm, Aortitis, Hypertension. Hypertension is the only root-disease entry that is not a structural aortic-root disorder. (Book p62)"),

(62, "oddoneout", "Harrison's Table 262-1: Major Causes of Aortic Regurgitation",
 "Table entry reads 'Medial degeneration' (the 'Cystic' prefix appears only in the p63 note)",
 "Which of the following is NOT an etiology exactly as listed in Table 262-1 (Book p62)?",
 ["Ankylosing spondylitis",
  "Cystic medial degeneration",
  "Marfan syndrome",
  "Hypertension"],
 1,
 "The Aortic root disease column of Table 262-1 on Book p62 reads 'Medial degeneration' — the 'Cystic' prefix appears only in the p63 note ('Cystic medial degeneration'). The other three entries are verbatim table entries. (Book p62)"),

(62, "recall", "Harrison's Table 262-1: Major Causes of Aortic Regurgitation",
 "Aortic root disease column: Aortic dissection, Medial degeneration, Marfan syndrome, Bicuspid aortic valve, Nonsyndromic familial aneurysm, Aortitis, Hypertension",
 "Which of the following is listed under AORTIC ROOT DISEASE in Table 262-1 (Book p62)?",
 ["Syphilis",
  "Radiation",
  "Endocarditis",
  "Hypertension"],
 3,
 "The Aortic root disease column on Book p62 lists Aortic dissection, Medial degeneration, Marfan syndrome, Bicuspid aortic valve, Nonsyndromic familial aneurysm, Aortitis and Hypertension. Syphilis, Radiation and Endocarditis are Valvular-column entries. (Book p62)"),

(62, "match", "Harrison's Table 262-1: Major Causes of Aortic Regurgitation",
 "Table-only etiologies (Hypertension, Nonsyndromic familial aneurysm, Radiation) vs Aortitis which the p63 note also lists",
 "Match the four AR etiologies of Table 262-1 (Book p62) to how the p63 cause list handles them — 1) Hypertension 2) Nonsyndromic familial aneurysm 3) Radiation 4) Aortitis … A) Appears only in the Harrison's table, not in the p63 list B) Appears only in the Harrison's table, not in the p63 list C) Appears only in the Harrison's table, not in the p63 list D) Also listed as a p63 cause (entry c)",
 ["1-A, 2-D, 3-C, 4-B",
  "1-D, 2-B, 3-A, 4-A",
  "1-A, 2-C, 3-B, 4-D",
  "1-A, 2-B, 3-C, 4-D"],
 3,
 "Book p63's AR causes are: valvular (congenital bicuspid, rheumatic, endocarditis, myxomatous, syphilis/Luetic aortitis, ankylosing spondylitis, trauma), root disease (dissection, cystic medial degeneration, Marfan's, bicuspid) and c. Aortitis. Hypertension, Nonsyndromic familial aneurysm and Radiation appear only in Table 262-1 on Book p62. (Book p62)"),

# ---------------------------------------------------------------- Book p63 (AR note)
(63, "fillup", "AR Causes: Valvular, Root, Aortitis",
 "Valvular list parentheticals: Syphilis (Luetic Aortitis); Myxomatous (prolapse)",
 "In the valvular cause list on Book p63, Syphilis is annotated in parentheses as ____, and Myxomatous as ____.",
 ["Tertiary syphilis; mitral prolapse",
  "Luetic Aortitis; prolapse",
  "Tabes dorsalis; chordal shortening",
  "Cardio-renal syphilis; leaflet thickening"],
 1,
 "Book p63 valvular causes: i. Congenital — bicuspid aortic valve; ii. Rheumatic heart disease; iii. Endocarditis; iv. Myxomatous (prolapse); v. Syphilis (Luetic Aortitis); vi. Ankylosing spondylitis; vii. Trauma. (Book p63)"),

(63, "match", "AR Causes: Valvular, Root, Aortitis",
 "Root disease list: dissection (displacement of the valves), cystic medial degeneration, Marfan's, bicuspid (also a valvular cause)",
 "Match the root-disease causes of AR on Book p63 to their detail — 1) Aortic dissection 2) Cystic medial degeneration 3) Marfan's 4) Bicuspid aortic valve … A) Listed with the note that dissection causes AR due to displacement of the valves B) Listed as root cause ii C) Listed as root cause iii D) Also appears in the valvular cause list",
 ["1-D, 2-B, 3-C, 4-A",
  "1-A, 2-C, 3-B, 4-D",
  "1-A, 2-B, 3-D, 4-C",
  "1-A, 2-B, 3-C, 4-D"],
 3,
 "Book p63 root disease: i. Aortic dissection (Dissection causes AR due to displacement of the valves); ii. Cystic medial degeneration; iii. Marfan's; iv. Bicuspid aortic valve — the bicuspid valve is the one cause listed under BOTH the valvular and the root-disease headings. (Book p63)"),

(63, "oddoneout", "AR Causes: Valvular, Root, Aortitis",
 "Odd-one-out against the full p63 AR cause list",
 "All of the following are listed causes of aortic regurgitation on Book p63 EXCEPT:",
 ["Cystic medial degeneration",
  "Traumatic rupture of mitral chordae",
  "Ankylosing spondylitis",
  "Aortitis"],
 1,
 "Book p63 AR causes: valvular (congenital bicuspid, rheumatic, endocarditis, myxomatous, syphilis, ankylosing spondylitis, trauma), root disease (dissection, cystic medial degeneration, Marfan's, bicuspid), aortitis. Traumatic rupture of MITRAL chordae causes MR, not AR. (Book p63)"),

(63, "fillup", "AR Causes: Valvular, Root, Aortitis",
 "p63 'Cystic medial degeneration' vs the p62 table's bare 'Medial degeneration'",
 "The root-disease cause the Book p63 note calls 'Cystic ____ degeneration' appears in the Book p62 table simply as '____ degeneration'.",
 ["intimal; intimal",
  "medial; medial",
  "medial; adventitial",
  "adventitial; medial"],
 1,
 "Book p63 root disease ii reads 'Cystic medial degeneration', while Table 262-1 on Book p62 lists the root-disease entry simply as 'Medial degeneration'. (Book p63)"),

(63, "fillup", "AR Haemodynamics: Acute vs Chronic",
 "Cascade: increased total stroke volume -> increased LVEDV (preload) -> dilation and eccentric hypertrophy -> LV failure",
 "The AR haemodynamic cascade on Book p63: total stroke volume increases, so ____ (increased preload) occurs, and volume overload results in dilation and ____, until ultimately the LV fails.",
 ["LVEDP rises; concentric hypertrophy develops",
  "LVEDV increases; eccentric hypertrophy develops",
  "LVEDV falls; eccentric hypertrophy develops",
  "LVEDV increases; concentric hypertrophy develops"],
 1,
 "Book p63 haemodynamics a: 'Total stroke volume increases -> Increase in LVEDV occurs (increased preload) -> Volume overload results in dilation and eccentric hypertrophy -> Ultimately, the LV fails'. (Book p63)"),

(63, "scenario", "AR Haemodynamics: Acute vs Chronic",
 "Acute severe AR (as in endocarditis): LV cannot compensate rapidly -> pulmonary oedema",
 "A 50-year-old with infective endocarditis develops acute severe aortic regurgitation and pulmonary oedema. Per Book p63, why does acute severe AR decompensate this fast?",
 ["His chronically dilated LV has already failed by the time he presents",
  "The mitral valve is secondarily stenosed, raising left atrial pressure",
  "In acute severe AR, as in endocarditis, the LV cannot compensate rapidly, so pulmonary oedema occurs",
  "Right ventricular failure reduces LV preload, backing fluid into the lungs"],
 2,
 "Book p63 haemodynamics b: 'In acute severe AR, as in endocarditis, LV cannot compensate rapidly so pulmonary oedema occurs.' (Book p63)"),

(63, "numeric", "AR Haemodynamics: Acute vs Chronic",
 "Chronic severe AR: asymptomatic for up to 10-15 years",
 "Per Book p63, a patient with chronic severe aortic regurgitation can remain asymptomatic for up to ____ years.",
 ["10–15",
  "3–5",
  "20–25",
  "5–8"],
 0,
 "Book p63 haemodynamics c: 'In chronic severe AR, the patients can be asymptomatic for up to 10–15 years.' (Book p63)"),

(63, "fillup", "AR Symptoms",
 "Palpitations as an early complaint for years before exertional dyspnoea; angina; then dyspnoea, PND, orthopnoea",
 "Per the AR symptom list on Book p63, palpitations can be an early complaint seen ____ before the exertional dyspnoea, and after angina the patient develops exertional dyspnoea, ____ and ____.",
 ["for weeks; paroxysmal cough; syncope",
  "for months; orthopnoea; angina",
  "for years; orthopnoea; PND",
  "for years; PND; orthopnoea"],
 3,
 "Book p63 symptoms: a. Palpitations can be an early complaint — can be seen for years before the exertional dyspnoea; b. Angina can occur; c. Then exertional dyspnoea, PND, orthopnoea. (Book p63)"),

(63, "recall", "AR Signs: Head to Toe",
 "First sign entry: peripheral signs (from head to toe)",
 "The FIRST sign entry of the AR sign list on Book p63 is:",
 ["Peripheral signs (from head to toe)",
  "A giant v wave in the JVP",
  "Tache cerebrale over the chest",
  "A laterally displaced apical impulse"],
 0,
 "Book p63 sign a (the list is even marked '***Signs' in the note): 'Peripheral signs (from head to toe)' — the first entry, before any specific impulse or murmur. (Book p63)"),

(63, "recall", "AR Signs: Head to Toe",
 "Heaving apical impulse, displaced down and out (annotated '????' in the note)",
 "Which apical-impulse finding is listed as a sign of AR on Book p63?",
 ["A soft, non-displaced apical impulse",
  "Pulsus alternans recorded at the apex",
  "Heaving apical impulse, displaced down and out — annotated '????' in the note",
  "An apical impulse that vanishes on inspiration"],
 2,
 "Book p63 sign b: 'Heaving apical impulse???? Displaced down and out' — the note itself flags this line with question marks. (Book p63)"),

(63, "truefalse", "AR Signs: Head to Toe",
 "Pulsus bisferiens; diastolic thrill over aortic area; systolic thrill over carotids/SSN need not mean AS; A2 usually absent in severe AR",
 "Which of the following True/False statements correctly reflects the AR signs on Book p63?",
 ["False: in severe AR, A2 is usually absent",
  "True: a systolic thrill may be felt over the carotids and suprasternal notch and need not mean there is an accompanying AS",
  "True: pulsus bisferiens is not a listed sign of AR",
  "False: a diastolic thrill over the aortic area is a listed sign of AR"],
 1,
 "Book p63 signs c–f: c. Pulsus bisferiens; d. Diastolic thrill over aortic area; e. Systolic thrill may be felt over the carotids and suprasternal notch and need not mean there is an accompanying AS; f. In severe AR, A2 is usually absent. (Book p63)"),

(63, "match", "AR Murmur & Auscultatory Discrimination",
 "Murmur detail: high pitched blowing decrescendo diastolic; early diastolic at Erb's point (neo aortic area); sitting, breath held in expiration; aortic-orientation reason",
 "Match the AR murmur details on Book p63 to their statement — 1) Quality 2) Characteristic timing and site 3) Position for auscultation 4) Why it is best heard at Erb's point … A) High pitched, blowing, decrescendo diastolic B) An early diastolic murmur best heard over Erb's point (neo Aortic area) C) Sitting position with the breath held in expiration D) Because of the orientation of the aorta",
 ["1-A, 2-B, 3-C, 4-D",
  "1-A, 2-C, 3-B, 4-D",
  "1-B, 2-A, 3-C, 4-D",
  "1-A, 2-B, 3-D, 4-C"],
 0,
 "Book p63 signs g–h: g. High pitched, blowing, decrescendo diastolic murmur, best heard in the 3rd ICS along the left sternal border in the sitting position with breath held in expiration; h. Characteristically an early diastolic murmur best heard over Erb's point (neo Aortic area) because of the orientation of the aorta. (Book p63)"),

(63, "scenario", "AR Murmur & Auscultatory Discrimination",
 "AR murmur better heard in the aortic area suggests an aortic aneurysm causing AR",
 "A patient's aortic regurgitation murmur is better heard in the aortic area than at Erb's point. According to Book p63, what does that site discrimination suggest?",
 ["An accompanying aortic stenosis",
  "A bicuspid aortic valve",
  "Eccentric LV dilation",
  "An aortic aneurysm causing the AR"],
 3,
 "Book p63 sign h: the AR murmur is characteristically best heard over Erb's point (neo Aortic area) because of the orientation of the aorta — 'However, if the AR murmur is better heard in the Aortic area, it suggests an aortic aneurysm causing AR'. (Book p63)"),

(63, "oddoneout", "AR Murmur & Auscultatory Discrimination",
 "Odd-one-out: an AS sign among AR signs",
 "All of the following are listed signs of AR on Book p63 EXCEPT:",
 ["Pulsus bisferiens",
  "Diastolic thrill over the aortic area",
  "Pulsus parvus et tardus",
  "Peripheral signs from head to toe"],
 2,
 "Pulsus parvus et tardus is the CAROTID pulse of aortic STENOSIS (Book p58); the p63 AR list instead includes pulsus bisferiens, diastolic thrill over the aortic area and peripheral signs from head to toe. (Book p63)"),
]
