# -*- coding: utf-8 -*-
"""Chapter 10 source data: Book p64 (Congenital Heart Disease — with the AR note tail at the top of the page)."""

# (page, fmt, sec, point, question, options, ans, explanation)
DATA = [
# ---------------------------------------------------------------- Book p64 (top: AR signs i-l, investigations, management)
(64, "scenario", "AR Signs i-l (top of Book p64)",
 "Sign i: murmur best heard over the right sternal border suggests regurgitation due to aneurysmal dilation",
 "A patient's aortic regurgitation murmur is best heard over the right sternal border rather than at Erb's point. According to Book p64, what does that suggest?",
 ["An accompanying aortic stenosis",
  "A bicuspid aortic valve",
  "That the regurgitation is due to aneurysmal dilation",
  "Severe left ventricular dilation"],
 2,
 "Book p64 sign i: 'When the murmur is best heard over the right sternal border, it suggests that the regurgitation is due to aneurysmal dilation.' (Book p64)"),

(64, "recall", "AR Signs i-l (top of Book p64)",
 "Sign j: a mid systolic ejection murmur can also be heard best in the aortic area and transmitted to the carotids",
 "Per Book p64, which additional systolic finding can be present with aortic regurgitation?",
 ["A mid systolic ejection murmur best heard in the aortic area and transmitted to the carotids",
  "A pansystolic murmur at the apex radiating to the axilla",
  "A mid diastolic rumble at the apex with an opening snap",
  "A continuous machinery murmur below the left clavicle"],
 0,
 "Book p64 sign j: 'A mid systolic ejection murmur can also be heard best in the aortic area and transmitted to the carotids'. (Book p64)"),

(64, "fillup", "AR Signs i-l (top of Book p64)",
 "Signs k and l: the two eponymous murmurs named (without elaboration) under the AR signs",
 "Book p64 names two eponymous murmurs as signs k and l of aortic regurgitation, without elaborating them: the ____ murmur and the ____ murmur.",
 ["Austin Flint; Cole Cecil",
  "Graham Steell; Carey Coombs",
  "Traube; Duroziez",
  "Duroziez; Müller"],
 0,
 "Book p64 signs k–l: 'k. Austin Flint murmur-  l. Cole Cecil murmur-' — the note lists the eponyms only, with nothing after the dashes. (Book p64)"),

(64, "fillup", "AR Investigations (p64)",
 "Doppler Echo sub-item: color doppler most sensitive for mild cases",
 "In the AR investigation list on Book p64, the only sub-item elaborated is under Doppler Echo: color doppler is the ____ for ____.",
 ["most sensitive; mild cases",
  "most specific; severe cases",
  "gold standard; prosthetic valves",
  "most specific; mild cases"],
 0,
 "Book p64 investigations: b. Doppler Echo — i. 'color doppler : most sensitive for mild cases'. (Book p64)"),

(64, "match", "AR Investigations (p64)",
 "The three CXR findings of AR: cardiomegaly -> cor bovinum; aortic root dilation -> prominent aortic knuckle; aortic valve calcification -> sus concomitant AS",
 "Match the three CXR findings of AR on Book p64 to their sign — 1) Cardiomegaly 2) Aortic root dilation 3) Aortic valve calcification … A) Cor bovinum / bovine heart B) Prominent aortic knuckle C) Sus for concomitant AS",
 ["1-A, 2-C, 3-B",
  "1-B, 2-A, 3-C",
  "1-A, 2-B, 3-C",
  "1-C, 2-B, 3-A"],
 2,
 "Book p64 CXR findings: i. cardiomegaly -> cor bovinum / bovine heart; ii. aortic root dilation -> prominent aortic knuckle; iii. Aortic valve calcification -> sus for concomitant AS. (Book p64)"),

(64, "oddoneout", "AR Investigations (p64)",
 "Odd-one-out against the p64 AR investigation list (ECG-LVH, Doppler Echo, CXR, cardiac cath)",
 "All of the following are listed investigations for AR on Book p64 EXCEPT:",
 ["ECG — LVH",
  "Chest X ray",
  "Color doppler for mild cases",
  "24-hour ambulatory blood pressure monitoring"],
 3,
 "Book p64 AR investigations: a. ECG — LVH; b. Doppler Echo (color doppler most sensitive for mild cases); c. CXR (three findings); d. Cardiac cath. Holter/ambulatory BP monitoring is not listed. (Book p64)"),

(64, "match", "AR Management (p64)",
 "Management: as in MS (IE or syphilitic aortitis needs Rx); chronic + significant vol overload -> vasodilator (hydralazine, nifedipine, ACE inh); Sx AVR, ideal time after LVD evidence but before significant symptoms",
 "Match the AR management entries on Book p64 to their detail — 1) Baseline medical 2) Chronic + significant volume overload 3) Surgical treatment 4) Ideal time for surgery … A) As in MS (IE or syphilitic aortitis needs Rx) B) Requires a vasodilator (hydralazine, nifedipine, or ACE inhibitor) C) AVR D) After haemodynamic / echogenic evidence of LVdys but before significant symptoms",
 ["1-A, 2-C, 3-B, 4-D",
  "1-B, 2-A, 3-C, 4-D",
  "1-A, 2-B, 3-D, 4-C",
  "1-A, 2-B, 3-C, 4-D"],
 3,
 "Book p64 AR management: a. as in MS (IE or syphilitic aortitis needs Rx); b. chronic + significant vol overload: requires vasodilator (hydralazine, nifedipine, or ACE inh); c. Sx: AVR; ideal time: after haemodynamic / echogenic evidence of LVdys but before significant symptoms. (Book p64)"),

(64, "scenario", "AR Management (p64)",
 "IE or syphilitic aortitis needs Rx (parenthetical in the 'as in MS' line)",
 "A patient with chronic aortic regurgitation is found to have active infective endocarditis. What does the Book p64 AR management line ('as in MS …') say must happen here?",
 ["The MS-style medical regimen proceeds, but IE or syphilitic aortitis needs Rx",
  "Vasodilators are withheld until the endocarditis is cured",
  "Immediate AVR regardless of haemodynamic status",
  "No medical therapy — surgical AVR alone"],
 0,
 "Book p64 management a: 'as in MS ( IE or syphilitic aortitis needs Rx )' — the parenthetical singles out IE and syphilitic aortitis as conditions that require treatment. (Book p64)"),

(64, "fillup", "AR Management (p64)",
 "Vasodilator trio for chronic AR with significant volume overload: hydralazine, nifedipine, or ACE inhibitor",
 "For chronic AR with significant volume overload, Book p64 requires a vasodilator — listing ____, ____, or ____.",
 ["digoxin; furosemide; spironolactone",
  "nifedipine; carvedilol; warfarin",
  "hydralazine; nifedipine; ACE inhibitor",
  "hydralazine; isosorbide dinitrate; spironolactone"],
 2,
 "Book p64 management b: 'chronic + significant vol overload : requires vasodilator ( hydralazine , nifedipine , or ACE inh )'. (Book p64)"),

# ---------------------------------------------------------------- Book p64 (Congenital HD)
(64, "numeric", "Congenital HD — ASD: Types",
 "Ostium secundum ASD 90%; ostium primum ASD 5%",
 "In the ASD types on Book p64, ostium secundum ASD accounts for ____% and ostium primum ASD for ____%.",
 ["90; 5",
  "80; 10",
  "70; 15",
  "95; 2"],
 0,
 "Book p64 ASD types: a. Ostium secundum ASD — 90%; b. Ostium primum ASD 5%. (Book p64)"),

(64, "recall", "Congenital HD — ASD: Types",
 "Ostium primum ASD commonly associated with Down syndrome or endocardial cushion defects",
 "Ostium primum ASD on Book p64 is commonly associated with:",
 ["Marfan syndrome or a bicuspid aortic valve",
  "Down syndrome or endocardial cushion defects",
  "Turner syndrome or coarctation of the aorta",
  "Klinefelter syndrome or mitral valve prolapse"],
 1,
 "Book p64: 'Ostium primum ASD 5% — commonly associated with Down syndrome or endocardial cushion defects'. (Book p64)"),

(64, "match", "Congenital HD — ASD: Syndromic Associations",
 "The five syndromic ASD associations matched to their listed detail",
 "Match the five syndromic ASD associations on Book p64 to their listed detail — 1) Holt-Oram syndrome 2) Patau syndrome 3) Edward syndrome 4) Ellis van Creveld syndrome 5) Lutembacher syndrome … A) Triphalangeal (fingerised) thumb, sometimes abrachia or phocomelia B) Trisomy 13 C) Trisomy 18 D) Polydactyly, nail dysplasia, dwarfism E) MS + ASD",
 ["1-A, 2-B, 3-C, 4-D, 5-E",
  "1-A, 2-C, 3-B, 4-D, 5-E",
  "1-D, 2-B, 3-C, 4-A, 5-E",
  "1-A, 2-B, 3-E, 4-D, 5-C"],
 0,
 "Book p64 syndromic associations: a. Holt-Oram (triphalangeal fingerised thumb, sometimes abrachia or phocomelia); b. Patau (trisomy 13); c. Edward (trisomy 18); d. Ellis van Creveld (polydactyly, nail dysplasia, dwarfism); e. Lutembacher — MS + ASD. (Book p64)"),

(64, "match", "Congenital HD — ASD: Syndromic Associations",
 "Patau syndrome: trisomy 13; polydactyly, flexion deformity of fingers, simian crease, cleft lip and palate, microcephaly; ASD, VSD, PDA",
 "Match the three Patau syndrome entries on Book p64 to their detail — 1) Chromosomal basis 2) Phenotype 3) Cardiac lesions … A) Trisomy 13 B) Polydactyly, flexion deformity of fingers, simian crease, cleft lip and palate, microcephaly C) ASD, VSD, PDA",
 ["1-A, 2-C, 3-B",
  "1-B, 2-A, 3-C",
  "1-A, 2-B, 3-C",
  "1-C, 2-B, 3-A"],
 2,
 "Book p64 Patau syndrome: i. Trisomy 13; ii. Polydactyly, flexion deformity of fingers, simian crease, cleft lip and palate, microcephaly; iii. ASD, VSD, PDA. (Book p64)"),

(64, "match", "Congenital HD — ASD: Syndromic Associations",
 "Edward syndrome: trisomy 18; prominent occiput, low set malformed ears, rocker bottom feet, micrognathia, clenched fists; ASD, VSD, PDA",
 "Match the three Edward syndrome entries on Book p64 to their detail — 1) Chromosomal basis 2) Phenotype 3) Cardiac lesions … A) Trisomy 18 B) Prominent occiput, low set malformed ears, rocker bottom feet, micrognathia, clenched fists C) ASD, VSD, PDA",
 ["1-A, 2-B, 3-C",
  "1-B, 2-A, 3-C",
  "1-A, 2-C, 3-B",
  "1-C, 2-B, 3-A"],
 0,
 "Book p64 Edward syndrome: i. Trisomy 18; ii. Prominent occiput, low set malformed ears, rocker bottom feet, micrognathia, clenched fists; iii. ASD, VSD, PDA. (Book p64)"),

(64, "oddoneout", "Congenital HD — ASD: Syndromic Associations",
 "Odd-one-out against the Edward syndrome phenotype list",
 "All of the following are listed features of Edward syndrome on Book p64 EXCEPT:",
 ["Rocker bottom feet",
  "Polydactyly",
  "Clenched fists",
  "Low set malformed ears"],
 1,
 "Edward syndrome (Book p64): prominent occiput, low set malformed ears, rocker bottom feet, micrognathia, clenched fists. Polydactyly belongs to Patau syndrome (and Ellis van Creveld), not Edward. (Book p64)"),

(64, "oddoneout", "Congenital HD — ASD: Syndromic Associations",
 "Odd-one-out against the five syndromic ASD associations",
 "All of the following are listed under the syndromic associations of ASD on Book p64 EXCEPT:",
 ["Holt-Oram syndrome",
  "Patau syndrome",
  "Williams syndrome",
  "Ellis van Creveld syndrome"],
 2,
 "The five listed syndromic associations (Book p64) are Holt-Oram, Patau, Edward, Ellis van Creveld and Lutembacher (MS + ASD). Williams syndrome is not listed here — the elfin-facies/hypercalcaemia phenotype appears on p61 beside supravalvular AS. (Book p64)"),

(64, "fillup", "Congenital HD — ASD: Syndromic Associations",
 "Holt-Oram: triphalangeal (fingerised) thumb, sometimes abrachia or phocomelia",
 "The skeletal entry of Holt-Oram syndrome on Book p64: a triphalangeal (fingerised) thumb, sometimes ____ or ____.",
 ["abrachia; phocomelia",
  "arachnodactyly; pectus excavatum",
  "polydactyly; clinodactyly",
  "scoliosis; kyphosis"],
 0,
 "Book p64 Holt-Oram syndrome: 'Triphalangeal (fingerised) thumb, sometimes abrachia or phocomelia'. (Book p64)"),

(64, "recall", "Congenital HD — ASD: Atrial Fibrillation",
 "Final ASD point: atrial fibrillation is common in ASD",
 "The third and final point under ASD on Book p64 states:",
 ["Atrial fibrillation is common in ASD",
  "Complete heart block is common in ASD",
  "Supraventricular tachycardia is common in ASD",
  "Ventricular ectopy is common in ASD"],
 0,
 "Book p64, ASD point 3: 'Atrial fibrillation is common in ASD'. (Book p64)"),
]
