# -*- coding: utf-8 -*-
"""Chapter 12 source data: Book p69-72 (Infective Endocarditis & 2023 Duke-ISCVID)."""

# (page, fmt, sec, point, question, options, ans, explanation)
DATA = [
# ---------------------------------------------------------------- Book p69 (IE diagnosis + classic Duke table)
(69, "fillup", "IE Diagnosis: Definite vs Possible",
 "Definite IE: pathological criteria, 2 major + 1 minor, 1 major + 2 minor, 5 minor",
 "Definite IE on Book p69 is diagnosed by the pathological criteria, or 2 major + ____, or 1 major + ____, or ____ minor.",
 ["1 minor; 2 minor; 5",
  "2 minor; 1 minor; 3",
  "1 minor; 3 minor; 4",
  "2 minor; 3 minor; 5"],
 0,
 "Book p69 IE diagnosis, definitive: i. pathological criteria; ii. 2 major + 1 minor; iii. 1 major + 2 minor; iv. 5 minor. (Book p69)"),

(69, "recall", "IE Diagnosis: Definite vs Possible",
 "Possible IE: 1 major + 1 minor or 3 minor",
 "Possible IE on Book p69 is:",
 ["2 major + 1 minor",
  "1 major + 2 minor",
  "1 major + 1 minor, or 3 minor",
  "5 minor"],
 2,
 "Book p69 IE diagnosis b: 'possible : 1 major + 1 minor or 3 minor'. (Book p69)"),

(69, "oddoneout", "IE Diagnosis: Definite vs Possible",
 "Odd-one-out against the definitive-IE combinations",
 "All of the following are combinations for DEFINITE IE on Book p69 EXCEPT:",
 ["Pathological criteria",
  "2 major + 1 minor",
  "1 major + 1 minor",
  "5 minor"],
 2,
 "Definite IE (Book p69): pathological criteria, 2 major + 1 minor, 1 major + 2 minor, or 5 minor. '1 major + 1 minor' is only the first possible-IE combination (alongside 3 minor). (Book p69)"),

(69, "match", "Duke Criteria: Major — Blood Cultures",
 "The four blood-culture major entries: typical organisms (two cultures), community-acquired S. aureus/enterococci, other organisms persistently positive, single Coxiella culture/serology",
 "Match the four blood-culture major-criteria entries on Book p69 to their detail — 1) Typical organisms from two blood cultures 2) The 'or' entry within typical organisms 3) Other organisms from persistently positive cultures 4) Single positive culture / serology … A) Viridans streptococci, Streptococcus bovis, HACEK group (Haemophilus, Actinobacillus, Cardiobacterium, Eikenella, Kingella) B) Community-acquired Staphylococcus aureus or enterococci in the absence of a primary focus C) Two positive cultures of samples drawn >12 hours apart, or all of three or a majority of four separate cultures (first and last sample drawn 1 hour apart) D) Single positive culture for Coxiella burnetii, or positive serology for Q fever, Bartonella species and Chlamydia psittaci",
 ["1-A, 2-C, 3-B, 4-D",
  "1-B, 2-A, 3-C, 4-D",
  "1-A, 2-B, 3-C, 4-D",
  "1-A, 2-B, 3-D, 4-C"],
 2,
 "Book p69 major criteria, blood cultures positive: typical microorganisms from two blood cultures (Viridans streptococci, Streptococcus bovis, HACEK group — Haemophilus, Actinobacillus, Cardiobacterium, Eikenella, Kingella), OR community-acquired S. aureus or enterococci without a primary focus; OR other organisms from persistently positive cultures (two positive cultures >12 h apart, or all of three / majority of four, first and last 1 h apart); OR single positive culture for Coxiella burnetii or positive serology for Q fever, Bartonella species and Chlamydia psittaci. (Book p69)"),

(69, "fillup", "Duke Criteria: Major — Blood Cultures",
 "The five HACEK organisms",
 "The HACEK group in the Book p69 major criteria comprises ____, ____, ____, ____ and ____.",
 ["Haemophilus; Acinetobacter; Cardiobacterium; Edwardsiella; Kingella",
  "Haemophilus; Actinobacillus; Cardiobacterium; Eikenella; Kingella",
  "Helicobacter; Actinobacillus; Cardiobacterium; Eikenella; Klebsiella",
  "Haemophilus; Actinomyces; Corynebacterium; Eikenella; Kingella"],
 1,
 "Book p69: HACEK group = (Haemophilus, Actinobacillus, Cardiobacterium, Eikenella, Kingella). (Book p69)"),

(69, "scenario", "Duke Criteria: Major — Blood Cultures",
 "Definition of 'persistently positive' cultures for other microorganisms",
 "A patient grows an organism that is not on the typical list, in cultures from draws 14 hours apart. Per the Book p69 major criteria, what defines 'persistently positive' blood cultures for other microorganisms?",
 ["A single positive culture from any draw",
  "Two positive cultures drawn within 6 hours of each other",
  "Two positive cultures of blood samples drawn >12 hours apart, or all of three or a majority of four separate cultures with the first and last sample drawn 1 hour apart",
  "One positive culture from two separate venipunctures on the same day"],
 2,
 "Book p69: other microorganisms consistent with IE from persistently positive blood cultures defined as — two positive cultures of blood samples drawn >12 hours apart, or all of three or a majority of four separate cultures of blood (with first and last sample drawn 1 hour apart). (Book p69)"),

(69, "match", "Duke Criteria: Major — Endocardial Involvement",
 "The four echocardiographic entries under 'Echo positive for IE'",
 "Match the four echocardiographic entries that make the echo 'positive for IE' on Book p69 to their detail — 1) Oscillating mass 2) Abscess 3) Prosthetic valve 4) Valvular regurgitation … A) Oscillating intracardiac mass without alternative explanation B) The second listed echocardiographic entry C) New partial dehiscence of prosthetic valve D) New valvular regurgitation (worsening or changing of preexisting murmur not sufficient)",
 ["1-A, 2-B, 3-C, 4-D",
  "1-C, 2-B, 3-A, 4-D",
  "1-A, 2-B, 3-D, 4-C",
  "1-A, 2-D, 3-C, 4-B"],
 0,
 "Book p69 major criteria: evidence of endocardial involvement — echocardiogram positive for IE: oscillating intracardiac mass without alternative explanation, or abscess, or new partial dehiscence of prosthetic valve, or new valvular regurgitation (worsening or changing of preexisting murmur not sufficient). (Book p69)"),

(69, "recall", "Duke Criteria: Major — Endocardial Involvement",
 "Why a worsening/changing preexisting murmur is not sufficient",
 "Per the Book p69 major criteria, why is a 'worsening or changing of preexisting murmur' explicitly not sufficient?",
 ["Murmur changes cannot be recorded on echocardiography",
  "Only a NEW valvular regurgitation satisfies the echocardiographic major criterion",
  "It implies the murmur is rheumatic in origin",
  "A preexisting murmur excludes infective endocarditis"],
 1,
 "Book p69: the echocardiographic entry requires NEW valvular regurgitation — 'worsening or changing of preexisting murmur not sufficient'. (Book p69)"),

(69, "fillup", "Duke Criteria: Major — Endocardial Involvement",
 "The four echo entries, with the middle two blanked",
 "A positive echocardiogram for IE on Book p69 shows an oscillating intracardiac mass without alternative explanation, or ____, or a new partial dehiscence of prosthetic valve, or ____.",
 ["pericardial effusion; new valvular stenosis",
  "intracardiac thrombus; worsened preexisting murmur",
  "new valvular stenosis; new atrial septal defect",
  "abscess; new valvular regurgitation"],
 3,
 "Book p69 echo entries: oscillating intracardiac mass without alternative explanation, or abscess, or new partial dehiscence of prosthetic valve, or new valvular regurgitation. (Book p69)"),

(69, "match", "Duke Criteria: Minor & Pathological",
 "The four minor-criteria bullets: predisposition, fever, vascular phenomena, immunologic phenomena",
 "Match the four minor-criteria bullets on Book p69 to their content — 1) Predisposition 2) Fever 3) Vascular phenomena 4) Immunologic phenomena … A) Predisposing heart condition, injection drug use, previous infective endocarditis, or prosthetic valve or material B) Temperature >38°C C) Major arterial emboli, septic pulmonary infarcts, mycotic aneurysm, intracranial haemorrhages, subconjunctival petechiae, Janeway lesions D) Glomerulonephritis, Osler's nodes, Roth's spots, positive rheumatoid factor",
 ["1-A, 2-B, 3-D, 4-C",
  "1-C, 2-B, 3-A, 4-D",
  "1-A, 2-B, 3-C, 4-D",
  "1-A, 2-C, 3-B, 4-D"],
 2,
 "Book p69 minor criteria: predisposition (heart condition, injection drug use, previous IE, prosthetic valve or material); fever >38°C; vascular phenomena (major arterial emboli, septic pulmonary infarcts, mycotic aneurysm, intracranial haemorrhages, subconjunctival petechiae, Janeway lesions); immunologic phenomena (glomerulonephritis, Osler's nodes, Roth's spots, positive rheumatoid factor). (Book p69)"),

(69, "match", "Duke Criteria: Minor & Pathological",
 "Janeway lesions (vascular) vs Osler's nodes, Roth's spots, glomerulonephritis (immunologic)",
 "Match the five physical findings on Book p69 to the minor-criteria list they belong to — 1) Janeway lesions 2) Osler's nodes 3) Roth's spots 4) Subconjunctival petechiae 5) Glomerulonephritis … A) Vascular phenomena list B) Immunologic phenomena list C) Immunologic phenomena list D) Vascular phenomena list E) Immunologic phenomena list",
 ["1-A, 2-B, 3-C, 4-D, 5-E",
  "1-B, 2-A, 3-C, 4-D, 5-E",
  "1-A, 2-C, 3-B, 4-D, 5-E",
  "1-A, 2-B, 3-E, 4-D, 5-C"],
 1,
 "Book p69: vascular phenomena include major arterial emboli, septic pulmonary infarcts, mycotic aneurysm, intracranial haemorrhages, subconjunctival petechiae and Janeway lesions; immunologic phenomena include glomerulonephritis, Osler's nodes, Roth's spots and positive rheumatoid factor. (Book p69)"),

(69, "fillup", "Duke Criteria: Minor & Pathological",
 "Microbiological minor: positive culture not meeting major, or serological evidence",
 "The 'microbiological evidence' minor criterion on Book p69: a positive blood culture that does not meet a major criterion, or ____ evidence of active infection with organisms consistent with infective endocarditis.",
 ["histological",
  "radiological",
  "serological",
  "immunological"],
 2,
 "Book p69 minor criteria: 'Microbiological evidence: Positive blood culture but does not meet a major criterion or serological evidence of active infection with organisms consistent with infective endocarditis'. (Book p69)"),

(69, "recall", "Duke Criteria: Minor & Pathological",
 "Pathological criteria: positive microbiology or histology of pathologic tissue at surgery or autopsy",
 "The pathological criterion on Book p69 is:",
 ["Two positive blood cultures from separate venipunctures",
  "Positive microbiology or histology of pathologic tissue material attained at surgery or autopsy (vegetations, valve tissue, embolic fragments or tissue/pus from intracardiac abscesses)",
  "An echocardiographic abscess without surgery",
  "A vegetation seen only on cardiac CT"],
 1,
 "Book p69: 'Pathological criteria — Positive microbiology or histology of pathologic tissue material attained at surgery or autopsy (vegetations, valve tissue, embolic fragments or tissue/pus from intracardiac abscesses)'. (Book p69)"),

# ---------------------------------------------------------------- Book p70 (old prophylaxis, superseded)
(70, "match", "IE Prophylaxis — Old Regimens (p70, superseded)",
 "Oral-procedures table: amoxicillin (oral) vs ampicillin + ceftriaxone (IV); allergy row clindamycin + azithro (oral) vs clindamycin + ceftriaxone (IV)",
 "Match the four cells of the 'for oral procedures' prophylaxis table on Book p70 to its regimen — 1) Can take oral (no allergy) 2) Cannot take oral (no allergy) 3) Can take oral + penicillin allergy 4) Cannot take oral + penicillin allergy … A) Amoxicillin B) Ampicillin ; ceftriaxone C) Clindamycin ; azithro D) Clindamycin ; ceftriaxone",
 ["1-A, 2-B, 3-D, 4-C",
  "1-B, 2-A, 3-C, 4-D",
  "1-A, 2-B, 3-C, 4-D",
  "1-A, 2-C, 3-B, 4-D"],
 2,
 "Book p70 oral-procedures table: penicillin row — can take oral: amoxicillin; cannot take oral: ampicillin; ceftriaxone. Penicillin-allergy row — can take oral: clindamycin; azithro; cannot take oral: clindamycin; ceftriaxone. (Book p70)"),

(70, "fillup", "IE Prophylaxis — Old Regimens (p70, superseded)",
 "RESP prophylaxis: same as oral; abscess/empyema drainage include below; strep viridans; staph : Vanco",
 "For RESP procedure prophylaxis on Book p70, abscess/empyema drainage requires adding coverage for ____, and staph is covered with ____.",
 ["staphylococci; cloxacillin",
  "enterococci; penicillin",
  "strep viridans; vancomycin",
  "MRSA; daptomycin"],
 2,
 "Book p70 prophylaxis — RESP: i. same as oral; ii. abscess/empyema drainage include below; iii. strep viridans; iv. staph : Vanco. (Book p70)"),

(70, "truefalse", "IE Prophylaxis — Old Regimens (p70, superseded)",
 "GU/GIT: not recommended (except established infx/abx cover — enterococci: penicillin); SSTI: not for routine sx; infected tissue — penicillin, allergic/MRSA — Vance",
 "Which of the following True/False statements correctly reflects the old prophylaxis page (Book p70)?",
 ["True: GU or GIT prophylaxis is not recommended, but in patients with established infection or under antibiotic cover, enterococci are covered with penicillin",
  "False: SSTI prophylaxis is not recommended for routine surgery",
  "True: clindamycin; azithro is the first-line non-allergic oral regimen",
  "False: if SSTI surgery involves infected skin or musculoskeletal tissue and the patient is allergic or MRSA, Vance is used"],
 0,
 "Book p70: GU or GIT — not recommended; pts with established infx or under abx cover to prevent sepsis during procedure: enterococci — penicillin. SSTI — not recommended for routine sx; if sx involves infected skin or musculoskeletal: anti strep or staph — penicillin; if allergic or MRSA — Vance. (Book p70)"),

(70, "recall", "IE Prophylaxis — Old Regimens (p70, superseded)",
 "The supersession note: 2023 ESC guideline and 2023 Duke-ISCVID criteria supersede the above (including prophylaxis)",
 "The highlighted note at the foot of Book p70 states:",
 ["The 2023 ESC guideline and 2023 Duke-ISCVID criteria have superseded the above — see the UPDATE pages that follow, including prophylaxis",
  "The 2023 Duke-ISCVID criteria replace only the diagnosis table, not prophylaxis",
  "The p70 prophylaxis regimens remain current for RESP procedures",
  "The 2015 ESC guidelines supersede this page"],
 0,
 "Book p70, foot note: '* IE — 2023 ESC guideline and 2023 Duke-ISCVID criteria have superseded the above. See the UPDATE pages that follow, including prophylaxis.' (Book p70)"),

# ---------------------------------------------------------------- Book p71 (2023 update)
(71, "truefalse", "2023 Update: What Duke-ISCVID Changed",
 "Definite IE structure unchanged (2 major / 1 major + 3 minor / 5 minor); possible IE 1 major + 1 minor or 3 minor",
 "Which of the following True/False statements correctly reflects what Duke-ISCVID changed (Book p71)?",
 ["False: the separate-venipuncture / defined-time-interval blood-culture requirement has been removed",
  "True: definite IE is unchanged in structure — 2 major, or 1 major + 3 minor, or 5 minor",
  "True: cardiac CT and 18F-FDG PET/CT became major imaging criteria only for prosthetic valves",
  "False: previous IE is now a predisposing condition"],
 1,
 "Book p71: definite IE unchanged in structure — 2 major, or 1 major + 3 minor, or 5 minor; possible IE 1 major + 1 minor, or 3 minor. Cardiac CT and 18F-FDG PET/CT are now major imaging criteria — no longer restricted to prosthetic valves; intraoperative inspection by the surgeon is a NEW major clinical criterion. (Book p71)"),

(71, "match", "2023 Update: What Duke-ISCVID Changed",
 "The six Duke-ISCVID changes: blood-culture rules, organism tiers, new microbiology, imaging majors, intraoperative inspection, new minors",
 "Match the six Duke-ISCVID changes on Book p71 to their detail — 1) Blood-culture rules 2) Typical organism list 3) New microbiological methods 4) Imaging major criteria 5) Intraoperative inspection 6) New minor criteria … A) Relaxed — the separate-venipuncture / defined-time-interval requirement has been removed B) Expanded, with a second tier that counts as typical only if intracardiac prosthetic material is present (e.g. coagulase-negative staphylococci, Cutibacterium acnes, corynebacteria) C) PCR, amplicon and metagenomic sequencing, in-situ hybridisation, and enzyme immunoassay for Bartonella D) Cardiac CT and 18F-FDG PET/CT are now major imaging criteria — no longer restricted to prosthetic valves E) A new major clinical criterion by the surgeon F) Previous IE is now a predisposing condition; predisposing lesions broadened (transcatheter valves, CIEDs)",
 ["1-A, 2-B, 3-C, 4-D, 5-E, 6-F",
  "1-F, 2-B, 3-C, 4-D, 5-A, 6-E",
  "1-A, 2-D, 3-C, 4-B, 5-E, 6-F",
  "1-A, 2-B, 3-E, 4-D, 5-C, 6-F"],
 1,
 "Book p71 'DIAGNOSIS — WHAT DUKE-ISCVID CHANGED': blood-culture rules relaxed (separate venipunctures at defined time intervals removed); typical organism list expanded with a prosthetic-material second tier; new microbiological methods (PCR, amplicon/metagenomic sequencing, in-situ hybridisation, enzyme immunoassay for Bartonella); imaging majors widened (cardiac CT, 18F-FDG PET/CT, no longer prosthetic-valve-only); intraoperative inspection a new major clinical criterion; new minors (previous IE a predisposing condition; transcatheter valves, CIEDs added). (Book p71)"),

(71, "recall", "2023 Update: What Duke-ISCVID Changed",
 "Second-tier typical organisms (require intracardiac prosthetic material): coagulase-negative staphylococci, Cutibacterium acnes, corynebacteria",
 "Which organisms count as typical ONLY if intracardiac prosthetic material is present (the Duke-ISCVID second tier, Book p71)?",
 ["HACEK organisms, Brucella, Tropheryma",
  "Viridans streptococci, Streptococcus bovis",
  "Coagulase-negative staphylococci, Cutibacterium acnes, corynebacteria",
  "Staphylococcus aureus, enterococci"],
 2,
 "Book p71: a second tier was added of organisms that count as typical only if intracardiac prosthetic material is present (e.g. coagulase-negative staphylococci, Cutibacterium acnes, corynebacteria). (Book p71)"),

(71, "fillup", "2023 Update: What Duke-ISCVID Changed",
 "New microbiological methods: PCR, amplicon and metagenomic sequencing, in-situ hybridisation, enzyme immunoassay for Bartonella",
 "The new microbiological methods accepted by Duke-ISCVID (Book p71): ____, ____ and metagenomic sequencing, in-situ hybridisation, and enzyme immunoassay for ____.",
 ["ELISA; FISH; Brucella",
  "PCR; amplicon; Bartonella",
  "PCR; culture; Coxiella",
  "LPA; culture; Bartonella"],
 1,
 "Book p71: 'New microbiological methods accepted: PCR, amplicon and metagenomic sequencing, in-situ hybridisation, and enzyme immunoassay for Bartonella.' (Book p71)"),

(71, "match", "2023 Update: Management by Type",
 "The six rows of the 'five buckets' table: native valve community-acquired; prosthetic EARLY; prosthetic LATE; right-sided/PWID; CIED-related; culture-negative",
 "Match the six rows of the management-by-type table in the 'FIVE BUCKETS' section (Book p71) to their regimen — 1) Native valve, community-acquired 2) Prosthetic valve, EARLY (<12 months) 3) Prosthetic valve, LATE (>12 months) 4) Right-sided / PWID 5) CIED-related 6) Culture-negative … A) Ampicillin + (flu)cloxacillin + gentamicin; penicillin allergy: vancomycin + gentamicin — 4–6 weeks B) Vancomycin + gentamicin + rifampicin; ≥6 weeks; usually nosocomial staphylococci — assume MRSA; rifampicin added 3–5 days after starting the other two, once bacteraemia is clearing C) As for native valve, plus rifampicin if staphylococcal — ≥6 weeks D) Cover S. aureus — (flu)cloxacillin, or vancomycin/daptomycin if MRSA risk — 2 weeks may suffice for uncomplicated tricuspid MSSA IE E) As for staphylococcal IE — complete hardware extraction is mandatory; new device at a different site once cultures are clear F) Cover HACEK, Coxiella, Bartonella, Brucella, Tropheryma — serology + PCR",
 ["1-A, 2-B, 3-C, 4-D, 5-E, 6-F",
  "1-B, 2-A, 3-C, 4-D, 5-E, 6-F",
  "1-A, 2-C, 3-B, 4-D, 5-E, 6-F",
  "1-A, 2-B, 3-F, 4-D, 5-E, 6-C"],
 0,
 "Book p71 table: Native valve community-acquired — ampicillin + (flu)cloxacillin + gentamicin (allergy: vancomycin + gentamicin), 4–6 weeks; Prosthetic EARLY — vancomycin + gentamicin + rifampicin, ≥6 weeks, assume MRSA, rifampicin 3–5 days later; Prosthetic LATE — as native + rifampicin if staphylococcal, ≥6 weeks; Right-sided/PWID — (flu)cloxacillin or vancomycin/daptomycin, 2 weeks may suffice for uncomplicated tricuspid MSSA; CIED — as staphylococcal IE, hardware extraction mandatory; Culture-negative — cover HACEK, Coxiella, Bartonella, Brucella, Tropheryma, serology + PCR. (Book p71)"),

(71, "fillup", "2023 Update: Management by Type",
 "Streptococcal fully sensitive: penicillin or ceftriaxone 4 weeks (2 weeks with gentamicin)",
 "For streptococcal, fully sensitive native-valve IE (Book p71), penicillin or ceftriaxone runs for ____ weeks — or ____ weeks if combined with gentamicin.",
 ["6; 2",
  "2; 4",
  "4; 2",
  "4; 6"],
 2,
 "Book p71: 'Streptococcal, fully sensitive: penicillin or ceftriaxone 4 weeks (2 weeks if combined with gentamicin)'. (Book p71)"),

(71, "scenario", "2023 Update: Management by Type",
 "EARLY prosthetic-valve IE: vancomycin + gentamicin + rifampicin, rifampicin timing",
 "A patient 3 months after prosthetic aortic valve implantation presents with IE. Per the 2023 table (Book p71), the empirical regimen is:",
 ["(Flu)cloxacillin alone for 2 weeks",
  "Ampicillin + (flu)cloxacillin + gentamicin for 4 weeks",
  "Vancomycin + gentamicin + rifampicin for ≥6 weeks — assume MRSA — with rifampicin added 3–5 days after starting the other two, once bacteraemia is clearing",
  "Ceftriaxone for 4 weeks without rifampicin"],
 2,
 "Book p71 Prosthetic valve, EARLY (<12 months): Vancomycin + gentamicin + rifampicin; ≥6 weeks; usually nosocomial staphylococci — assume MRSA; rifampicin added 3–5 days after starting the other two, once bacteraemia is clearing. (Book p71)"),

(71, "recall", "2023 Update: Management by Type",
 "Right-sided / PWID notes: 2 weeks may suffice for uncomplicated tricuspid MSSA; look for septic pulmonary emboli",
 "The right-sided / PWID row of the 2023 table (Book p71) states:",
 ["A minimum of 6 weeks is mandatory for all right-sided IE",
  "2 weeks may suffice for uncomplicated tricuspid MSSA IE, and septic pulmonary emboli must be looked for",
  "Rifampicin is mandatory for all PWID IE",
  "Hardware extraction is mandatory in PWID IE"],
 1,
 "Book p71: Right-sided / PWID — cover S. aureus ((flu)cloxacillin, or vancomycin/daptomycin if MRSA risk); '2 weeks may suffice for uncomplicated tricuspid MSSA IE. Look for septic pulmonary emboli'. (Book p71)"),

(71, "fillup", "2023 Update: Management by Type",
 "Culture-negative row: prior antibiotics = commonest cause of culture negativity",
 "In the culture-negative row of the 2023 table (Book p71), examiners should ask about prior ____, because that is the commonest cause of culture negativity.",
 ["surgery",
  "steroids",
  "anticoagulation",
  "antibiotics"],
 3,
 "Book p71 Culture-negative row: 'Serology + PCR. Ask about prior antibiotics — the commonest cause of culture negativity'. (Book p71)"),

(71, "oddoneout", "2023 Update: Management by Type",
 "Culture-negative coverage list: HACEK, Coxiella, Bartonella, Brucella, Tropheryma",
 "All of the following are on the culture-negative coverage list in the 2023 table (Book p71) EXCEPT:",
 ["HACEK",
  "Coxiella",
  "Nocardia",
  "Brucella"],
 2,
 "Book p71 Culture-negative: 'Cover HACEK, Coxiella, Bartonella, Brucella, Tropheryma'. Nocardia is not on the list. (Book p71)"),

(71, "match", "2023 Update: Team, Surgery, Stroke, POET",
 "The three H's of surgery indications: Heart failure, uncontrolled Infection, prevention of Embolism",
 "Match the three H's of surgery indications on Book p71 to their detail — 1) Heart failure 2) Uncontrolled Infection 3) Prevention of Embolism … A) From valve destruction — the commonest and most urgent B) Abscess, false aneurysm, fistula, enlarging vegetation, persistent positive cultures >7 days, fungal or resistant organism C) Vegetation >10 mm with an embolic event, or >10 mm with severe valve stenosis/regurgitation, or isolated vegetation >15 mm",
 ["1-A, 2-C, 3-B",
  "1-B, 2-A, 3-C",
  "1-A, 2-B, 3-C",
  "1-C, 2-B, 3-A"],
 2,
 "Book p71 'Surgery indications (the three H's)': Heart failure from valve destruction — the commonest and most urgent; uncontrolled Infection (abscess, false aneurysm, fistula, enlarging vegetation, persistent positive cultures >7 days, fungal or resistant organism); prevention of Embolism (vegetation >10 mm with an embolic event, or >10 mm with severe valve stenosis/regurgitation, or isolated vegetation >15 mm). (Book p71)"),

(71, "truefalse", "2023 Update: Team, Surgery, Stroke, POET",
 "Stroke is no longer an automatic bar; ischaemic without haemorrhage — no delay; intracranial haemorrhage — defer about a month",
 "Which of the following True/False statements correctly reflects the 2023 stroke-and-surgery guidance (Book p71)?",
 ["True: after an ischaemic stroke without haemorrhage, surgery need not be delayed if otherwise indicated",
  "False: after intracranial haemorrhage, surgery should be deferred about a month",
  "True: stroke remains an automatic bar to surgery",
  "False: heart failure from valve destruction is the commonest and most urgent surgery indication"],
 0,
 "Book p71: 'Stroke is no longer an automatic bar to surgery. After an ischaemic stroke without haemorrhage, surgery need not be delayed if otherwise indicated. After intracranial haemorrhage, defer about a month.' (Book p71)"),

(71, "fillup", "2023 Update: Team, Surgery, Stroke, POET",
 "POET trial: stabilised left-sided IE, oral switch non-inferior; OPAT not in first 10 days, not with complications",
 "The POET trial on Book p71: in stabilised left-sided IE, switching to oral antibiotics to complete the course is ____; OPAT is endorsed for selected stable patients — not in the first ____ days, not in the presence of ____.",
 ["inferior; 7; complications",
  "non-inferior; 14; stroke",
  "non-inferior; 10; complications",
  "equivalent; 10; MRSA"],
 2,
 "Book p71: 'Partial oral therapy (POET trial): in stabilised left-sided IE, switching to oral antibiotics to complete the course is non-inferior. OPAT is endorsed for selected stable patients — not in the first 10 days, not in the presence of complications.' (Book p71)"),

(71, "recall", "2023 Update: Team, Surgery, Stroke, POET",
 "Endocarditis Team and Heart Valve Centre: every case discussed by cardiology, cardiac surgery, microbiology and imaging",
 "The 2023 ESC recommendation on the Endocarditis Team and Heart Valve Centre (Book p71) states:",
 ["Every case is discussed by cardiology, cardiac surgery, microbiology and imaging",
  "Only prosthetic-valve cases require team discussion",
  "Discussion is limited to cardiology and microbiology",
  "Surgery is consulted only after a negative echocardiogram"],
 0,
 "Book p71: 'Endocarditis Team and Heart Valve Centre — a formal 2023 ESC recommendation. Every case discussed by cardiology, cardiac surgery, microbiology and imaging.' (Book p71)"),

(71, "recall", "2023 Prophylaxis: The Principle (bottom of Book p71)",
 "The principle since 2007: high-risk patients undergoing high-risk procedures only; moderate-risk no longer qualify",
 "The prophylaxis principle stated in section 3 at the foot of Book p71 is:",
 ["Since 2007: prophylaxis for every cardiac lesion undergoing a dental procedure",
  "Since 2007: prophylaxis is confined to high-risk patients undergoing high-risk procedures — moderate-risk cardiac lesions no longer qualify",
  "New in 2023: moderate-risk lesions now qualify",
  "Prophylaxis for all oral-mucosa procedures in every patient"],
 1,
 "Book p71, section 3 'PROPHYLAXIS — WHO, WHEN, WHAT': 'The principle since 2007 is unchanged: prophylaxis is confined to high-risk patients undergoing high-risk procedures. Moderate-risk cardiac lesions no longer qualify.' (Book p71)"),

# ---------------------------------------------------------------- Book p72 (2023 prophylaxis table)
(72, "match", "2023 Prophylaxis: Who, When, What",
 "The four high-risk patient categories 1-4 (including the NEW 2023 category)",
 "Match the four high-risk patient categories on Book p72 to their description — 1) Category 1 2) Category 2 3) Category 3 4) Category 4 … A) Prosthetic valve — surgical or transcatheter — or any prosthetic material used for valve repair B) Previous infective endocarditis C) Untreated cyanotic congenital heart disease, or CHD repaired with prosthetic material — for 6 months after the procedure, or lifelong if a residual shunt or regurgitation persists D) NEW in 2023 — recipients of a ventricular assist device or a heart transplant with valvulopathy",
 ["1-A, 2-B, 3-C, 4-D",
  "1-C, 2-B, 3-A, 4-D",
  "1-A, 2-D, 3-C, 4-B",
  "1-A, 2-B, 3-D, 4-C"],
 0,
 "Book p72 WHICH PATIENTS (high risk only): 1. Prosthetic valve (surgical or transcatheter) or any prosthetic material used for valve repair; 2. Previous infective endocarditis; 3. Untreated cyanotic CHD, or CHD repaired with prosthetic material — 6 months after the procedure, or lifelong if a residual shunt or regurgitation persists; 4. NEW in 2023: recipients of a ventricular assist device or a heart transplant with valvulopathy. (Book p72)"),

(72, "match", "2023 Prophylaxis: Who, When, What",
 "Procedures (dental only) vs not-recommended procedures; regimen single dose 30-60 min before; penicillin-allergy regimen",
 "Match the 2023 prophylaxis procedure and regimen details on Book p72 — 1) WHICH PROCEDURES 2) NOT recommended 3) REGIMEN (single dose, 30–60 min before) 4) Penicillin-allergy regimen … A) Dental only — manipulation of the gingiva or the periapical region of the teeth, or perforation of the oral mucosa B) Respiratory, gastrointestinal, genitourinary, dermatological or musculoskeletal procedures in the absence of established infection — the point examiners test C) Amoxicillin or ampicillin 2 g PO/IV (children 50 mg/kg) D) Doxycycline 100 mg, or clindamycin 600 mg where still used; azithromycin/clarithromycin 500 mg are alternatives",
 ["1-A, 2-B, 3-C, 4-D",
  "1-C, 2-B, 3-A, 4-D",
  "1-A, 2-D, 3-C, 4-B",
  "1-A, 2-B, 3-D, 4-C"],
 0,
 "Book p72: WHICH PROCEDURES — dental only (gingiva/periapical region or perforation of oral mucosa); NOT recommended for respiratory, GI, GU, dermatological or musculoskeletal procedures without established infection ('this is the point examiners test'); REGIMEN — amoxicillin or ampicillin 2 g PO/IV (children 50 mg/kg); penicillin allergy — doxycycline 100 mg, or clindamycin 600 mg where still used; azithromycin/clarithromycin 500 mg alternatives. (Book p72)"),

(72, "truefalse", "2023 Prophylaxis: Who, When, What",
 "Cephalosporins must not be used with penicillin anaphylaxis; doxycycline/clindamycin/azithro-regimens",
 "Which of the following True/False statements correctly reflects the 2023 prophylaxis regimen (Book p72)?",
 ["True: cephalosporins can be used safely in patients with anaphylaxis to penicillin",
  "True: cephalosporins must not be used in patients with anaphylaxis to penicillin",
  "False: doxycycline 100 mg is an alternative in penicillin allergy",
  "False: amoxicillin or ampicillin 2 g PO/IV (children 50 mg/kg) is the single-dose regimen"],
 1,
 "Book p72: 'Cephalosporins must not be used in patients with anaphylaxis to penicillin'; the single dose is amoxicillin or ampicillin 2 g PO/IV (children 50 mg/kg), with doxycycline 100 mg or clindamycin 600 mg (where still used) and azithromycin/clarithromycin 500 mg as allergy alternatives. (Book p72)"),

(72, "recall", "2023 Prophylaxis: Who, When, What",
 "'ALWAYS, FOR EVERYONE': oral hygiene and dental review outweigh prophylaxis; aseptic technique; discourage piercing/tattooing",
 "The 'ALWAYS, FOR EVERYONE' column on Book p72 states:",
 ["Antibiotic prophylaxis matters more than oral hygiene",
  "Good oral hygiene and regular dental review matter more than antibiotic prophylaxis — the cumulative bacteraemia of daily chewing and brushing far exceeds that of a single dental visit; aseptic technique for all vascular access and invasive procedures; discourage piercing and tattooing",
  "Tattooing is safe for high-risk cardiac patients",
  "Vascular access requires no special technique in IE patients"],
 1,
 "Book p72 ALWAYS, FOR EVERYONE: 'Good oral hygiene and regular dental review matter more than antibiotic prophylaxis — the cumulative bacteraemia of daily chewing and brushing far exceeds that of a single dental visit. Aseptic technique for all vascular access and invasive procedures. Discourage piercing and tattooing.' (Book p72)"),

(72, "numeric", "2023 Prophylaxis: Who, When, What",
 "Single dose given 30-60 minutes before the procedure",
 "The single 2023 prophylaxis dose is given ____–60 minutes before the procedure, per Book p72.",
 ["15",
  "60",
  "30",
  "120"],
 2,
 "Book p72 REGIMEN header: '(single dose, 30–60 min before)'. (Book p72)"),

(72, "oddoneout", "2023 Prophylaxis: Who, When, What",
 "Odd-one-out against the four high-risk categories",
 "All of the following are 2023 HIGH-RISK patient categories for IE prophylaxis on Book p72 EXCEPT:",
 ["A prosthetic valve (surgical or transcatheter)",
  "Previous infective endocarditis",
  "A moderate-risk cardiac lesion without previous IE",
  "Untreated cyanotic congenital heart disease"],
 2,
 "Book p72 high-risk categories: prosthetic valve/material, previous IE, untreated cyanotic CHD (or prosthetic-repair CHD for 6 months/lifelong), and the 2023 addition of VAD/heart-transplant recipients with valvulopathy. Moderate-risk cardiac lesions no longer qualify (Book p71). (Book p72)"),

(72, "fillup", "2023 Prophylaxis: Who, When, What",
 "CHD repaired with prosthetic material: 6 months after the procedure, or lifelong if a residual shunt/regurgitation persists",
 "For CHD repaired with prosthetic material (Book p72), prophylaxis lasts for ____ months after the procedure, or lifelong if a residual shunt or regurgitation persists.",
 ["3",
  "12",
  "6",
  "24"],
 2,
 "Book p72 category 3: 'Untreated cyanotic congenital heart disease, or CHD repaired with prosthetic material — for 6 months after the procedure, or lifelong if a residual shunt or regurgitation persists'. (Book p72)"),
]
