# -*- coding: utf-8 -*-
"""Chapter 13 source data: Book p75-79 (RS - History, Symptomatology & Breathlessness Tables)."""

# (page, fmt, sec, point, question, options, ans, explanation)
DATA = [
# ---------------------------------------------------------------- Book p75 (History proforma; chest pain; dyspnoea; cough)
(75, "match", "History Proforma & Chest Pain",
 "The nine bullet points of the respiratory history proforma",
 "Match the nine entries of the respiratory history proforma on Book p75 to their detail — 1) Cough with expectoration 2) Haemoptysis 3) Dyspnoea 4) Chest pain 5) Constitutional features 6) Cor pulmonale 7) Bronchiectasis 8) Past history 9) Occupational history … A) First bullet of the proforma B) Second bullet C) MRC grading is preferred in RS D) Unilateral pain usually points towards RS causes E) Fever, evening rise of temperature, weight loss, night sweats F) Features suggestive of right heart failure (cor pulmonale) G) If suspecting bronchiectasis, its complications H) Past history of TB? I) The double-asterisked entry",
 ["1-A, 2-B, 3-C, 4-D, 5-E, 6-F, 7-G, 8-H, 9-I",
  "1-B, 2-A, 3-C, 4-D, 5-E, 6-F, 7-G, 8-H, 9-I",
  "1-A, 2-B, 3-C, 4-G, 5-E, 6-F, 7-D, 8-H, 9-I",
  "1-A, 2-B, 3-D, 4-C, 5-E, 6-F, 7-G, 8-H, 9-I"],
 0,
 "Book p75 proforma: cough with expectoration; haemoptysis; dyspnoea (rule out CVS causes of breathlessness); chest pain; fever/evening rise/weight loss/night sweats; features suggestive of right heart failure (cor pulmonale); if suspecting bronchiectasis, its complications; oedema; past history of TB?; occupational history**. (Book p75)"),

(75, "fillup", "History Proforma & Chest Pain",
 "Pleuritic chest pain characteristically increases on inspiration (coughing)",
 "Pleuritic chest pain on Book p75 characteristically increases on ____ (coughing).",
 ["expiration only",
  "inspiration",
  "deep inspiration only, never with coughing",
  "sneezing"],
 1,
 "Book p75: 'Pleuritic chest pain characteristically increases on inspiration (coughing). Pleural disease can be associated with dry cough and stabbing type of chest pain.' (Book p75)"),

(75, "scenario", "History Proforma & Chest Pain",
 "Minimal pleural effusion: layers of pleura more in contact -> more irritation -> more pain",
 "A patient with a MINIMAL pleural effusion has intense pleuritic chest pain. Per Book p75, why is the pain greater when the effusion is minimal?",
 ["A minimal effusion compresses the bronchus",
  "A minimal effusion is usually infected",
  "With minimal effusion the layers of the pleura are more in contact, causing more irritation",
  "Pain is independent of effusion volume"],
 2,
 "Book p75: 'If the pleural effusion is minimal, the layers of the pleura are more in contact which causes more irritation leading to more pain.' (Book p75)"),

(75, "fillup", "Dyspnoea & Acute Onset",
 "MRC grading preferred in RS; advantages: distance checked, peer comparison, slope vs level ground",
 "For dyspnoea, Book p75 prefers the ____ grading in RS, whose advantages are that distance is checked, peer comparison, and ____ vs level ground.",
 ["NYHA; peak flow",
  "Borg; heart rate",
  "MRC; slope",
  "MRC; oxygen saturation"],
 2,
 "Book p75: 'Dyspnoea — MRC grading is preferred in RS. The advantages are: distance is checked, peer comparison and slope vs. level ground'. (Book p75)"),

(75, "fillup", "Dyspnoea & Acute Onset",
 "Acute onset dyspnoea: pulmonary oedema, PE, acute COPD exacerbation, acute severe asthma, status asthmaticus, one more asthma",
 "The acute-onset dyspnoea list on Book p75: pulmonary oedema, pulmonary embolism, acute exacerbation of COPD, acute severe asthma, ____, one more asthma.",
 ["atelectasis",
  "pneumothorax",
  "cor pulmonale",
  "status asthmaticus"],
 3,
 "Book p75: 'Acute onset dyspnoea — pulmonary oedema, pulmonary embolism, acute exacerbation of COPD, acute severe asthma, status asthmaticus, one more asthma'. (Book p75)"),

(75, "match", "Cough & Expectoration History",
 "The seven cough/expectoration history points with their cause lists",
 "Match the seven cough-and-expectoration history points on Book p75 to their cause lists — 1) Onset, duration 2) Postural variation 3) Diurnal variation — nocturnal cough 4) Mucopurulent to purulent colour 5) Bronchorrhoea >100 ml/day 6) Foul smell 7) Blood … A) TB, chronic bronchitis B) Post nasal drip, bronchiectasis, left heart failure (orthopnoea equalii), mass on trachea C) Post nasal drip, PND, bronchial asthma, cough variant asthma (no wheeze), GERD, tropical pulmonary eosinophilia D) Bronchial/pneumonia infection E) Bronchiectasis, lung abscess, empyema rupturing into a bronchus, necrotising pneumonia F) Lung abscess, bronchiectasis G) Frank haemoptysis vs blood stained sputum",
 ["1-A, 2-C, 3-B, 4-D, 5-E, 6-F, 7-G",
  "1-B, 2-A, 3-C, 4-D, 5-E, 6-F, 7-G",
  "1-A, 2-B, 3-C, 4-D, 5-E, 6-F, 7-G",
  "1-A, 2-B, 3-E, 4-D, 5-C, 6-F, 7-G"],
 2,
 "Book p75: onset/duration — TB, chronic bronchitis; postural variation — post nasal drip, bronchiectasis, left heart failure (orthopnoea equalii), mass on trachea; nocturnal cough — post nasal drip, PND, bronchial asthma, cough variant asthma (no wheeze), GERD, tropical pulmonary eosinophilia; mucopurulent-purulent — bronchial/pneumonia infection; quantity — bronchorrhoea >100 ml/day (bronchiectasis, lung abscess, empyema rupturing into a bronchus, necrotising pneumonia); smell — foul in lung abscess, bronchiectasis; blood — frank haemoptysis vs blood stained sputum. (Book p75)"),

(75, "fillup", "Cough & Expectoration History",
 "Bronchorrhoea >100 ml/day; 1 tumbler approx 150-200 ml",
 "Bronchorrhoea on Book p75 is defined as expectoration of more than ____ ml/day, with one tumbler approximating ____–200 ml.",
 ["50; 100",
  "100; 150",
  "200; 300",
  "100; 250"],
 1,
 "Book p75: 'Quantity — bronchorrhea >100 ml/day (1 tumbler approx. 150–200 ml)'. (Book p75)"),

(75, "oddoneout", "Cough & Expectoration History",
 "Odd-one-out against the four bronchorrhoea causes",
 "All of the following are listed causes of bronchorrhoea (>100 ml/day) on Book p75 EXCEPT:",
 ["Bronchiectasis",
  "Lung abscess",
  "Simple chronic bronchitis",
  "Empyema rupturing into a bronchus"],
 2,
 "Book p75 bronchorrhoea causes: bronchiectasis, lung abscess, empyema rupturing into a bronchus, necrotising pneumonia. Simple chronic bronchitis is not on that list. (Book p75)"),

# ---------------------------------------------------------------- Book p76 (haemoptysis)
(76, "match", "Haemoptysis: Types & Severity",
 "Frank / spurious / pseudo / endemic haemoptysis with their definitions",
 "Match the four special haemoptysis types on Book p76 to their definition — 1) Frank haemoptysis 2) Spurious haemoptysis 3) Pseudohemoptysis 4) Endemic haemoptysis … A) Expectoration of blood only B) Secondary to URTI C) Serratia marcescens D) Paragonimus westermani",
 ["1-B, 2-A, 3-C, 4-D",
  "1-A, 2-B, 3-C, 4-D",
  "1-A, 2-C, 3-B, 4-D",
  "1-A, 2-B, 3-D, 4-C"],
 1,
 "Book p76: Frank haemoptysis — expectoration of blood only; Spurious — secondary to URTI; Pseudohemoptysis — Serratia marcescens; Endemic — Paragonimus westermani. (Book p76)"),

(76, "numeric", "Haemoptysis: Types & Severity",
 "Severity: Mild <100 ml/day; Moderate 100-150 ml; Severe up to 200 ml",
 "Haemoptysis severity on Book p76: mild is below ____ ml of blood loss per day, moderate is 100–150 ml, and severe is up to ____ ml.",
 ["50; 100",
  "100; 150",
  "100; 200",
  "150; 200"],
 2,
 "Book p76 severity: Mild <100 ml/day; Moderate 100–150 ml; Severe up to 200 ml. (Book p76)"),

(76, "fillup", "Haemoptysis: Types & Severity",
 "Massive: >500 ml/day OR rate >150 ml/hr OR 100 ml/day for >3 days",
 "Massive haemoptysis on Book p76: more than ____ ml/day, or a rate above 150 ml/hr, or 100 ml loss per day for more than ____ days.",
 ["200; 5",
  "500; 7",
  "300; 3",
  "500; 3"],
 3,
 "Book p76: Massive — '>500 ml/day or Rate >150 ml/hr or 100 ml loss per day for more than 3 days.' (Book p76)"),

(76, "fillup", "Haemoptysis: Causes",
 "Airway causes: Bronchitis (Ac & Chr), Bronchogenic Ca, Bronchiectasis, Body (Foreign body)",
 "The airway causes of haemoptysis on Book p76: Bronchitis (acute and chronic), ____, bronchiectasis and ____.",
 ["lung abscess; aspergilloma",
  "bronchogenic carcinoma; body (foreign body)",
  "tuberculosis; endobronchial TB",
  "carcinoid; foreign body"],
 1,
 "Book p76 (Dr. Vivekanandan's list), Airway: Bronchitis (Ac & Chr), Bronchogenic Ca, Bronchiectasis and Body (Foreign body). (Book p76)"),

(76, "recall", "Haemoptysis: Causes",
 "Bronchial bleed more dangerous than pulmonary artery bleed: bronchial arteries = systemic circulation at higher pressure",
 "Per the note on Book p76, why is a bronchial bleed more dangerous than a pulmonary artery bleed?",
 ["The pulmonary artery carries more blood volume",
  "Bronchial arteries are smaller and spasm more",
  "The bronchial arteries are part of the systemic circulation at a much higher pressure than the pulmonary circulation",
  "Bronchial bleeding triggers more coagulopathy"],
 2,
 "Book p76 note: 'Bronchial bleed is more dangerous than a pulmonary artery bleed because the bronchial arteries are a part of the systemic circulation which are at a much higher pressure than the pulmonary circulation.' (Book p76)"),

(76, "recall", "Haemoptysis: Causes",
 "h/o repeated small haemoptysis / blood-streaked sputum highly suggestive of carcinoma",
 "A history of repeated small haemoptysis / blood-streaked sputum is highly suggestive of (Book p76):",
 ["Bronchiectasis",
  "Tuberculosis",
  "Carcinoma",
  "Pulmonary embolism"],
 2,
 "Book p76 note: 'h/o repeated small haemoptysis/ blood streaked sputum is highly s/o carcinoma.' (Book p76)"),

(76, "fillup", "Haemoptysis: Causes",
 "Alveolar: TB — fibrocavitary TB (rupture of Rasmussen aneurysms); acute pulmonary oedema — pink frothy sputum",
 "Among the alveolar causes on Book p76, TB is specified as fibrocavitary TB due to rupture of ____ aneurysms (dilated pulmonary arteries surrounding the cavity), and acute pulmonary oedema presents with ____ sputum.",
 ["mycotic; brown sticky",
  "Rasmussen; blood-stained",
  "pulmonary; white frothy",
  "Rasmussen; pink frothy"],
 3,
 "Book p76 Alveolar: pneumonia; TB — 'Fibrocavitary TB (don't just say TB) due to rupture of Rasmussen Aneurysms (dilated pulmonary arteries surrounding the cavity)'; lung abscess; acute pulmonary oedema (pink frothy sputum). (Book p76)"),

(76, "match", "Haemoptysis: Causes",
 "Interstitial, Vascular, CVS and Collagen vascular cause groups",
 "Match the four remaining cause groups on Book p76 to their members — 1) Interstitial 2) Vascular 3) CVS 4) Collagen vascular disorders … A) ILD (rare) B) Pulmonary HTN, pulmonary embolism, pulmonary AV fistula C) Mitral stenosis, pulmonary embolism, pulmonary hypertension, AV malformation D) Wegener's, Goodpasture syndrome, other vasculitis",
 ["1-B, 2-A, 3-C, 4-D",
  "1-A, 2-D, 3-C, 4-B",
  "1-A, 2-B, 3-C, 4-D",
  "1-A, 2-B, 3-D, 4-C"],
 2,
 "Book p76: Interstitial — ILD (rare); Vascular — Pulmonary HTN, pulmonary embolism, pulmonary AV fistula; CVS — Mitral stenosis, pulmonary embolism, pulmonary hypertension, AV malformation; Collagen vascular disorders — Wegener's, Goodpasture syndrome, other vasculitis. (Book p76)"),

(76, "oddoneout", "Haemoptysis: Causes",
 "Odd-one-out against the infective causes list",
 "All of the following are listed infective causes of haemoptysis on Book p76 EXCEPT:",
 ["Weil's disease (severe Leptospirosis)",
  "Invasive Aspergillosis",
  "Goodpasture syndrome",
  "Paragonimiasis"],
 2,
 "Book p76 infective causes: Weil's disease (severe Leptospirosis), Fibrocavitary TB, Invasive Aspergillosis, Paragonimiasis. Goodpasture syndrome is under collagen vascular disorders, not infective causes. (Book p76)"),

(76, "recall", "Massive Haemoptysis: Causes & Management",
 "Causes: Bronchiectasis, Fibrocavitary TB, Aspergillosis, Paragonimiasis",
 "The four causes of massive haemoptysis on Book p76 are:",
 ["Mitral stenosis, pulmonary embolism, pulmonary hypertension, AV malformation",
  "Bronchiectasis, fibrocavitary TB, aspergillosis, paragonimiasis",
  "Pneumonia, lung abscess, TB, aspergillosis",
  "Bronchogenic carcinoma, Wegener's, Goodpasture, leptospirosis"],
 1,
 "Book p76 Massive haemoptysis causes: Bronchiectasis, Fibrocavitary TB, Aspergillosis, Paragonimiasis. (Book p76)"),

(76, "match", "Massive Haemoptysis: Causes & Management",
 "Management steps: Intubate, Volume resuscitation, Blood transfusion, Bronchoscopy with balloon tamponade/topical epinephrine or vasopressin",
 "Match the four management steps for massive haemoptysis on Book p76 to their detail — 1) Airway 2) Circulation 3) Transfusion 4) Bronchoscopy … A) Intubate B) Volume resuscitation C) Blood transfusion D) Balloon tamponade / topical epinephrine or vasopressin",
 ["1-B, 2-A, 3-C, 4-D",
  "1-A, 2-C, 3-B, 4-D",
  "1-A, 2-B, 3-D, 4-C",
  "1-A, 2-B, 3-C, 4-D"],
 3,
 "Book p76 management: Intubate; Volume resuscitation; Blood transfusion; Bronchoscopy with balloon tamponade/topical epinephrine or vasopressin. (Book p76)"),

# ---------------------------------------------------------------- Book p77 (recurrent, vs haematemesis, dry cough, special coughs)
(77, "fillup", "Recurrent Haemoptysis & Differential Diagnosis",
 "Recurrent haemoptysis causes: bronchiectasis, chronic bronchitis, bronchogenic carcinoma",
 "The causes of recurrent haemoptysis on Book p77: bronchiectasis, chronic bronchitis and ____.",
 ["pulmonary embolism",
  "mitral stenosis",
  "Wegener's",
  "bronchogenic carcinoma"],
 3,
 "Book p77: 'Recurrent haemoptysis causes — bronchiectasis, chronic bronchitis, bronchogenic carcinoma'. (Book p77)"),

(77, "fillup", "Recurrent Haemoptysis & Differential Diagnosis",
 "Pseudohemoptysis: bleeding from upper respiratory tract or oral cavity",
 "Pseudohemoptysis on Book p77: bleeding from the ____ or oral cavity.",
 ["alveoli",
  "upper respiratory tract",
  "bronchial arteries",
  "lower GIT"],
 1,
 "Book p77: 'Pseudohemoptysis — bleeding from upper respiratory tract or oral cavity'. (Book p77)"),

(77, "match", "Recurrent Haemoptysis & Differential Diagnosis",
 "Haemoptysis vs haematemesis: cough/frothing, alkaline pH, food particles/melaena",
 "Match the three discriminators between haemoptysis and haematemesis on Book p77 to their detail — 1) Associated features 2) pH 3) Food particles / melaena … A) Associated with cough, not with nausea and vomiting; frothing present B) Alkaline — haematemesis is acidic C) Food particles may be present in haematemesis, which may be associated with melaena",
 ["1-B, 2-A, 3-C",
  "1-A, 2-C, 3-B",
  "1-A, 2-B, 3-C",
  "1-C, 2-B, 3-A"],
 2,
 "Book p77: associated with cough, not with nausea and vomiting, frothing present; pH alkaline (haematemesis acidic); food particles may be present in haematemesis, which may be associated with melaena. (Book p77)"),

(77, "recall", "Recurrent Haemoptysis & Differential Diagnosis",
 "Cause of death in haemoptysis: asphyxia due to blood in bronchial tree",
 "The cause of death in haemoptysis on Book p77 is:",
 ["Exsanguination",
  "Pulmonary embolism from the clot",
  "Severe anaemia",
  "Asphyxia due to blood in the bronchial tree"],
 3,
 "Book p77: 'Cause of death in Hemoptysis: Asphyxia as d/t blood in bronchial tree.' (Book p77)"),

(77, "fillup", "Recurrent Haemoptysis & Differential Diagnosis",
 "Cor pulmonale history: puffiness/swelling d/t PA hypertension causing RV failure, or protein loss from expectoration; also amyloidosis",
 "Puffiness and swelling in a patient with cor pulmonale on Book p77 results from pulmonary artery hypertension causing ____ failure, or from protein loss in the expectoration — and can also be due to ____.",
 ["LV; sarcoidosis",
  "RV; silicosis",
  "LV; amyloidosis",
  "RV; amyloidosis"],
 3,
 "Book p77: 'h/s/o cor pulmonale — puffiness and swelling d/t pulmonary artery hypertension causing RV failure or even due to protein loss from the expectoration. Can also be due to amyloidosis.' (Book p77)"),

(77, "match", "Causes of Dry Cough & Special Coughs",
 "The eight dry-cough causes in book order (first three, next three, last two)",
 "Match the eight causes of dry cough on Book p77 to their position — 1) First three 2) Next three 3) Last two … A) Pleural pathologies, interstitial lung disease (ILD), cough-variant asthma B) Tropical pulmonary eosinophilia, atypical pneumonia, GERD C) ACE inhibitors, recurrent laryngeal nerve palsy",
 ["1-B, 2-A, 3-C",
  "1-A, 2-C, 3-B",
  "1-A, 2-B, 3-C",
  "1-C, 2-B, 3-A"],
 2,
 "Book p77 dry-cough causes in order: pleural pathologies, interstitial lung disease (ILD), cough-variant asthma, tropical pulmonary eosinophilia, atypical pneumonia, GERD, ACE inhibitors, recurrent laryngeal nerve palsy. (Book p77)"),

(77, "fillup", "Causes of Dry Cough & Special Coughs",
 "Brassy cough (metallic sound, tracheal compression); Bovine cough (without explosive nature) — RLN palsy",
 "On Book p77, the brassy cough is a cough with a metallic sound from compression over the trachea, while the bovine cough — cough without its explosive nature — points to ____ palsy.",
 ["vagus nerve",
  "phrenic nerve",
  "hypoglossal nerve",
  "recurrent laryngeal nerve"],
 3,
 "Book p77: 'Brassy cough — cough with metallic sound — compression over trachea; Bovine cough — cough without its explosive nature — RLN palsy'. (Book p77)"),

(77, "fillup", "Causes of Dry Cough & Special Coughs",
 "Post-tussive syncope: high intrathoracic pressure -> decreased venous return -> decreased cardiac output",
 "Post-tussive syncope on Book p77: high intrathoracic pressure -> decreased ____ -> decreased cardiac output.",
 ["arterial return",
  "venous return",
  "cerebral perfusion",
  "pulmonary flow"],
 1,
 "Book p77: 'Post-tussive syncope: High intraThoracic pressure -> decreases venous return -> decreased cardiac output'. (Book p77)"),

# ---------------------------------------------------------------- Book p78 (TB past history, MRC, receptors, CVS vs RS breathlessness)
(78, "fillup", "Past History of TB",
 "TB past history: Category; treatment taken? treatment completed? compliance?; side effects experienced?",
 "The past-history-of-TB items on Book p78: category, treatment taken?, ____, ____, and side effects experienced?",
 ["sputum conversion?; adherence?",
  "duration?; dose?",
  "relapse?; reinfection?",
  "treatment completed?; compliance?"],
 3,
 "Book p78 Past history of TB: Category; Treatment taken? Treatment completed? Compliance?; Side effects experienced? (Book p78)"),

(78, "match", "Breathlessness: MRC Scale & Receptors",
 "The five Modified MRC grades 0-4 verbatim",
 "Match the five Modified MRC grades on Book p78 to their description — 1) Grade 0 2) Grade 1 3) Grade 2 4) Grade 3 5) Grade 4 … A) No breathlessness, except with strenuous exercise B) Breathlessness when hurrying on level ground / walking up a slight hill C) Walks slower than peers on level ground / has to stop for breath while walking at own pace D) Stops for breath after walking about 100 m or after a few minutes on level ground E) Too breathless to leave the house / breathless when dressing and undressing",
 ["1-B, 2-A, 3-C, 4-D, 5-E",
  "1-A, 2-B, 3-C, 4-D, 5-E",
  "1-A, 2-C, 3-B, 4-D, 5-E",
  "1-A, 2-B, 3-E, 4-D, 5-C"],
 1,
 "Book p78 Modified MRC: 0 — no breathlessness except with strenuous exercise; 1 — breathlessness when hurrying on level ground/walking up a slight hill; 2 — walks slower than peers on level ground / has to stop for breath while walking at own pace; 3 — stops for breath after walking about 100 m or after a few minutes on level ground; 4 — too breathless to leave the house / breathless when dressing and undressing. (Book p78)"),

(78, "recall", "Breathlessness: MRC Scale & Receptors",
 "Note: No 'Breathlessness at rest' on the MRC scale",
 "According to the note under the MRC scale on Book p78, which of these is NOT on the scale?",
 ["Stops for breath after walking about 100 m",
  "Too breathless to leave the house",
  "Walks slower than peers on level ground",
  "Breathlessness at rest"],
 3,
 "Book p78 MRC note: 'No \"Breathlessness at rest\"'. (Book p78)"),

(78, "fillup", "Breathlessness: MRC Scale & Receptors",
 "MRC advantages vs NYHA: slope vs level ground, peer comparison, distance checked; other classification Sherwood Jones",
 "Per Book p78, the MRC advantages over NYHA are that ____ vs level ground is checked, peer comparison, and distance is checked; the other named classification is the ____ classification.",
 ["hill; WHO",
  "stairs; Borg",
  "slope; Sherwood Jones",
  "slope; NYHA class"],
 2,
 "Book p78: 'The advantages vs NYHA are: slope vs. level ground, peer comparison and Distance is checked. Other classification — Sherwood Jones classification'. (Book p78)"),

(78, "recall", "Breathlessness: MRC Scale & Receptors",
 "Other classification: Sherwood Jones classification",
 "The other breathlessness classification named on Book p78 is:",
 ["The WHO classification",
  "The Borg scale",
  "The NYHA class 4 extension",
  "The Sherwood Jones classification"],
 3,
 "Book p78: 'Other classification — Sherwood Jones classification'. (Book p78)"),

(78, "match", "Breathlessness: Receptors (JSCR) & CVS vs RS",
 "The four JSCR receptor groups and their locations",
 "Match the receptors involved in dyspnoea (JSCR) on Book p78 to their location — 1) J receptors 2) Stretch receptors 3) Chemoreceptors 4) Respiratory muscle receptors … A) Alveolar capillary junction B) Thoracic cage and lungs C) Carotid artery, aorta, medulla D) The fourth of the four listed receptor groups",
 ["1-B, 2-A, 3-C, 4-D",
  "1-A, 2-C, 3-B, 4-D",
  "1-C, 2-B, 3-A, 4-D",
  "1-A, 2-B, 3-C, 4-D"],
 3,
 "Book p78 JSCR: J receptors — alveolar capillary junction; stretch receptors — thoracic cage and lungs; chemoreceptors — carotid artery, aorta, medulla; respiratory muscle receptors. (Book p78)"),

(78, "match", "Breathlessness: Receptors (JSCR) & CVS vs RS",
 "CVS vs RS breathlessness: CVS cardinal symptoms, orthopnoea/PND vs PND specific to CVS",
 "Match the two columns of the breathlessness table on Book p78 to their content — 1) CVS breathlessness 2) RS breathlessness … A) Associated CVS cardinal symptom(s); orthopnoea, PND B) No associated CVS symptoms; orthopnoea may be present (asthma, COPD), but PND is specific to CVS",
 ["1-B, 2-A",
  "1-A, 2-B",
  "1-A, 2-A",
  "1-B, 2-B"],
 1,
 "Book p78 table: CVS breathlessness — associated CVS cardinal symptom(s); orthopnoea, PND. RS breathlessness — no associated CVS symptoms; orthopnoea may be present (asthma, COPD), but PND is specific to CVS. (Book p78)"),

# ---------------------------------------------------------------- Book p79 (Box 19.8: differential diagnosis of acute breathlessness)
(79, "match", "Box 19.8: Differential Diagnosis of Acute Breathlessness",
 "The seven conditions and their history-column entries",
 "Match the seven conditions of Box 19.8 on Book p79 to their History column — 1) Pulmonary oedema 2) Massive pulmonary embolus 3) Acute severe asthma 4) Acute exacerbation of COPD 5) Pneumonia 6) Metabolic acidosis 7) Psychogenic … A) Chest pain, palpitations, orthopnoea, cardiac history B) Risk factors, chest pain, pleurisy, syncope, dizziness C) History of asthma, asthma medications, wheeze D) Previous episodes, smoker — in type II respiratory failure may be drowsy E) Prodromal illness, fever, rigors, pleurisy F) Evidence of diabetes mellitus or renal disease, aspirin or ethylene glycol overdose G) Previous episodes, digital or perioral dyssaesthesia",
 ["1-A, 2-B, 3-C, 4-D, 5-E, 6-F, 7-G",
  "1-B, 2-A, 3-C, 4-D, 5-E, 6-F, 7-G",
  "1-A, 2-G, 3-C, 4-D, 5-E, 6-F, 7-B",
  "1-A, 2-B, 3-D, 4-C, 5-E, 6-F, 7-G"],
 0,
 "Box 19.8 (Book p79) History column: Pulmonary oedema — chest pain, palpitations, orthopnoea, cardiac history; Massive PE — risk factors, chest pain, pleurisy, syncope, dizziness; Acute severe asthma — history of asthma, asthma medications, wheeze; Acute COPD exacerbation — previous episodes, smoker, drowsy in type II failure; Pneumonia — prodromal illness, fever, rigors, pleurisy; Metabolic acidosis — diabetes mellitus or renal disease, aspirin or ethylene glycol overdose; Psychogenic — previous episodes, digital or perioral dyssaesthesia. (Book p79)"),

(79, "match", "Box 19.8: Differential Diagnosis of Acute Breathlessness",
 "ABG patterns of the five most distinguishable rows",
 "Match the ABG patterns in Box 19.8 on Book p79 to their condition — 1) Acute severe asthma 2) Acute exacerbation of COPD 3) Metabolic acidosis 4) Psychogenic 5) Pulmonary oedema … A) Down-PaO2, down-PaCO2 — with up-PaCO2 in extremis B) Down or down-down-PaO2, up-PaCO2 (type II failure ± up-H+; up-HCO3 in chronic type II failure) C) PaO2 normal, down-PaCO2, up-H+ D) PaO2 normal, down-down-PaCO2, up-H+ E) Down-PaO2, down-PaCO2",
 ["1-A, 2-D, 3-C, 4-B, 5-E",
  "1-E, 2-B, 3-C, 4-D, 5-A",
  "1-A, 2-B, 3-C, 4-D, 5-E",
  "1-A, 2-B, 3-D, 4-C, 5-E"],
 2,
 "Box 19.8 ABG (Book p79): Acute severe asthma — down-PaO2, down-PaCO2 (up-PaCO2 in extremis); Acute COPD exacerbation — down or down-down-PaO2, up-PaCO2 (type II failure ± up-H+; up-HCO3 in chronic type II failure); Metabolic acidosis — PaO2 normal, down-PaCO2, up-H+; Psychogenic — PaO2 normal, down-down-PaCO2, up-H+; Pulmonary oedema — down-PaO2, down-PaCO2. (Book p79)"),

(79, "match", "Box 19.8: Differential Diagnosis of Acute Breathlessness",
 "ECG rows: sinus tachy + ischaemia/arrhythmia; PE pattern S1Q3T3/RBBB/T(V1-V4); bradycardia in extremis; RV strain; tachycardia; two blank rows",
 "Match the ECG rows of Box 19.8 on Book p79 to their condition — 1) Pulmonary oedema 2) Massive pulmonary embolus 3) Acute severe asthma 4) Acute exacerbation of COPD 5) Pneumonia 6) Metabolic acidosis 7) Psychogenic … A) Sinus tachycardia, ischaemia, arrhythmia B) Sinus tachycardia, RBBB, S1Q3T3 pattern, T-wave inversion (V1–V4) C) Sinus tachycardia (bradycardia in extremis) D) Normal, or signs of right ventricular strain E) Tachycardia F) Left blank in the table G) Left blank in the table",
 ["1-A, 2-D, 3-C, 4-B, 5-E, 6-F, 7-G",
  "1-C, 2-B, 3-A, 4-D, 5-E, 6-F, 7-G",
  "1-A, 2-B, 3-C, 4-D, 5-E, 6-G, 7-F",
  "1-A, 2-B, 3-C, 4-D, 5-E, 6-F, 7-G"],
 3,
 "Box 19.8 ECG (Book p79): Pulmonary oedema — sinus tachycardia, ischaemia, arrhythmia; Massive PE — sinus tachycardia, RBBB, S1Q3T3 pattern, T(V1–V4) inversion; Acute severe asthma — sinus tachycardia (bradycardia in extremis); Acute COPD exacerbation — normal or signs of right ventricular strain; Pneumonia — tachycardia; Metabolic acidosis and Psychogenic — blank. (Book p79)"),

(79, "scenario", "Box 19.8: Differential Diagnosis of Acute Breathlessness",
 "Massive PE signs: central cyanosis, up-JVP, absence of signs in the lung, shock (tachycardia, hypotension) -> ECG S1Q3T3/RBBB/T(V1-V4) inversion",
 "A patient presents with acute breathlessness, central cyanosis and raised JVP, but NO signs in the lungs, with shock (tachycardia, hypotension). Per Box 19.8 (Book p79), the ECG pattern expected in this condition is:",
 ["Sinus tachycardia with bradycardia in extremis",
  "Sinus tachycardia, ischaemia, arrhythmia",
  "Normal, or signs of right ventricular strain",
  "Sinus tachycardia, RBBB, S1Q3T3 pattern, T-wave inversion (V1–V4)"],
 3,
 "Box 19.8 Massive pulmonary embolus (Book p79): signs — central cyanosis, up-JVP, absence of signs in the lung, shock (tachycardia, hypotension); ECG — sinus tachycardia, RBBB, S1Q3T3 pattern, T(V1–V4) inversion. (Book p79)"),

(79, "recall", "Box 19.8: Differential Diagnosis of Acute Breathlessness",
 "Pneumonia row: fever, confusion, pleural rub, consolidation, cyanosis if severe; pneumonic consolidation; tachycardia",
 "The pneumonia row of Box 19.8 (Book p79) includes:",
 ["Flapping tremor, bounding pulses; hyperinflation with bullae",
  "Fever, confusion, pleural rub, consolidation, cyanosis (if severe); pneumonic consolidation on CXR; tachycardia",
  "Fetor (ketones), air hunger; normal CXR",
  "Carpopedal spasm; no cyanosis"],
 1,
 "Box 19.8 Pneumonia (Book p79): Signs — fever, confusion, pleural rub, consolidation, cyanosis (if severe); CXR — pneumonic consolidation; ECG — tachycardia. (Book p79)"),

(79, "fillup", "Box 19.8: Differential Diagnosis of Acute Breathlessness",
 "COPD row: signs of CO2 retention — flapping tremor, bounding pulses",
 "In the acute COPD exacerbation row of Box 19.8 (Book p79), signs of CO2 retention include a ____ tremor and ____ pulses.",
 ["choreiform; thready",
  "flapping; bounding",
  "flapping; collapsing",
  "asterixis-like; alternating"],
 1,
 "Box 19.8 Acute exacerbation of COPD (Book p79): 'cyanosis, hyperinflation, signs of CO2 retention (flapping tremor, bounding pulses)'. (Book p79)"),

(79, "truefalse", "Box 19.8: Differential Diagnosis of Acute Breathlessness",
 "Asthma CXR hyperinflation only (unless pneumothorax), up-PaCO2 in extremis; PE CXR often normal; metabolic acidosis without heart/lung signs; psychogenic ABG",
 "Which of the following True/False statements correctly reflects Box 19.8 (Book p79)?",
 ["False: the CXR in massive pulmonary embolus is often normal, with prominent hilar vessels and oligemic lung fields",
  "True: metabolic acidosis presents with hyperventilation accompanied by heart or lung signs",
  "True: in acute severe asthma the CXR shows hyperinflation only (unless complicated by pneumothorax), and PaCO2 rises in extremis",
  "False: in psychogenic breathlessness the ABG shows PaO2 normal, down-down-PaCO2, up-H+"],
 2,
 "Box 19.8 (Book p79): Massive PE CXR — often normal, prominent hilar vessels, oligemic lung fields; Metabolic acidosis — hyperventilation WITHOUT heart or lung signs; Acute severe asthma CXR — hyperinflation only (unless complicated by pneumothorax), up-PaCO2 in extremis; Psychogenic ABG — PaO2 normal, down-down-PaCO2, up-H+. (Book p79)"),
]
