# -*- coding: utf-8 -*-
"""Chapter 14 source data: Book p80-92 (RS - General Examination & Chest Wall)."""

# (page, fmt, sec, point, question, options, ans, explanation)
DATA = [
# ---------------------------------------------------------------- Book p80
(80, "recall", "Chest Pain: Origins & Character Table",
 "Chest pain origins: parietal pleura, chest wall, mediastinal structures — NOT lung (autonomic innervation only)",
 "Chest pain can originate from the parietal pleura, chest wall and mediastinal structures — but NOT the lung. Per Book p80, why not the lung?",
 ["The lung has only autonomic innervation, so it does not cause chest pain",
  "The lung is supplied only by the sympathetic trunk",
  "Chest pain always originates from the heart",
  "The parietal pleura lacks innervation"],
 0,
 "Book p80: 'Chest pain — can originate from the parietal pleura, chest wall and mediastinal structures. NOT LUNG because the lung has only autonomic innervation, it does not cause chest pain.' (Book p80)"),

(80, "match", "Chest Pain: Origins & Character Table",
 "The three-column chest pain table: parietal pleura / chest wall / mediastinal structures (character + causes)",
 "Match the three origins of chest pain in the Book p80 table to their character and causes — 1) Parietal pleura 2) Chest wall 3) Mediastinal structures … A) Sharp, stabbing, intensified by inspiration or coughing — pulmonary embolism, pneumonia, pneumothorax, fractured ribs B) Dull, aching, unrelated to respiration, progressively worsens and hinders sleep — invasion, trauma, compression C) Central, retrosternal, no relation to respiration — lung cancer, lymphoma, thymoma, mets",
 ["1-B, 2-A, 3-C",
  "1-A, 2-C, 3-B",
  "1-A, 2-B, 3-C",
  "1-C, 2-B, 3-A"],
 2,
 "Book p80 table: Parietal pleura — sharp, stabbing, intensified by inspiration or coughing (causes: PE, pneumonia, pneumothorax, fractured ribs); Chest wall — dull, aching, unrelated to respiration, progressively worsens and hinders sleep (invasion, trauma, compression); Mediastinal structures — central, retrosternal, no relation to respiration (lung cancer, lymphoma, thymoma, mets). (Book p80)"),

(80, "fillup", "Chest Pain: Origins & Character Table",
 "Parietal pleura radiation rules: upper 6 ribs localised; lower ribs -> upper abdomen; diaphragmatic -> shoulder tip/neck",
 "In the parietal pleura column of Book p80: upper 6 ribs irritation causes ____ pain, lower rib pleural irritation can radiate to the ____, and diaphragmatic pleural irritation is referred to the ____.",
 ["radiating; back; knee",
  "diffuse; upper abdomen; shoulder tip",
  "localised; shoulder; upper abdomen",
  "localised; upper abdomen; shoulder tip/neck"],
 3,
 "Book p80 parietal pleura cell: 'Upper 6 ribs irritation -> localised pain. Lower rib pleural irritation can radiate to the upper abdomen. Diaphragmatic pleural irritation is referred to the shoulder tip/neck.' (Book p80)"),

(80, "match", "Specific TB History Points",
 "The three specific history points in a suspected case of TB: husband's occupation (HIV risk), evening temperature rise (TNF alpha), contact history",
 "Match the three specific history points in a suspected case of tuberculosis on Book p80 to their detail — 1) Occupation of husband 2) Evening rise of temperature 3) Contact history … A) High risk group for HIV B) Due to TNFa C) The third listed TB history point",
 ["1-B, 2-A, 3-C",
  "1-A, 2-B, 3-C",
  "1-A, 2-C, 3-B",
  "1-C, 2-B, 3-A"],
 1,
 "Book p80 'Specific history points in a suspected case of Tuberculosis': occupation of husband — high risk group for HIV; evening rise of temperature — due to TNFa; contact history of tuberculosis. (Book p80)"),

# ---------------------------------------------------------------- Book p81
(81, "numeric", "Examination: Pulse, Pallor, Cyanosis, Clubbing",
 "Pulsus paradoxus: >10 mmHg significant; reduces on treatment",
 "On Book p81, pulsus paradoxus above ____ mmHg is significant, and it reduces on treatment.",
 ["10",
  "5",
  "15",
  "20"],
 0,
 "Book p81: 'Pulse: Comment on pulsus paradoxus. >10 mmHg is significant. It reduces on treatment.' (Book p81)"),

(81, "match", "Examination: Pulse, Pallor, Cyanosis, Clubbing",
 "The three RS pallor causes in book order",
 "Match the three causes of pallor in RS on Book p81 to their position — 1) First listed 2) Second listed 3) Third listed … A) Recurrent haemoptysis B) Bronchial ca C) TB",
 ["1-B, 2-A, 3-C",
  "1-A, 2-C, 3-B",
  "1-C, 2-B, 3-A",
  "1-A, 2-B, 3-C"],
 3,
 "Book p81 pallor in RS: recurrent haemoptysis; bronchial ca; TB. (Book p81)"),

(81, "numeric", "Examination: Pulse, Pallor, Cyanosis, Clubbing",
 "Cyanosis threshold: SpO2 <85%",
 "The cyanosis threshold on Book p81 is SpO2 below ____%.",
 ["90",
  "80",
  "85",
  "75"],
 2,
 "Book p81: 'Cyanosis — SpO2 <85%'. (Book p81)"),

(81, "fillup", "Examination: Pulse, Pallor, Cyanosis, Clubbing",
 "Clubbing in TB: post TB bronchiectasis, scar carcinoma (adenocarcinoma), empyema, endobronchial TB",
 "The four clubbing-in-TB causes on Book p81: post-TB bronchiectasis, ____ (it's an adenocarcinoma), empyema and ____.",
 ["carcinoid; endobronchial TB",
  "scar carcinoma; TB lymphadenitis",
  "bronchocele; endobronchial TB",
  "scar carcinoma; endobronchial TB"],
 3,
 "Book p81: 'Clubbing in TB — post TB bronchiectasis, scar carcinoma (it's an Adenocarcinoma), empyema, endobronchial TB'. (Book p81)"),

(81, "fillup", "Lymphadenopathy: Epitrochlear & Scalene",
 "Epitrochlear nodes always pathologic: NHL, secondary syphilis, sarcoidosis, forearm/hand infections, tularaemia — but not in TB (Dr. Hamide)",
 "A palpable epitrochlear node is always pathologic (Book p81) — causes: NHL, secondary syphilis, sarcoidosis, infections of forearm/hand, tularaemia (rare) — but NOT in ____, per Dr. Hamide.",
 ["TB",
  "sarcoidosis",
  "syphilis",
  "lymphoma"],
 0,
 "Book p81: 'Palpable epitrochlear nodes are always pathologic — NHL, secondary syphilis, sarcoidosis, infections of forearm, hand, tularaemia (rare) but not in TB (Dr. Hamide)'. (Book p81)"),

(81, "oddoneout", "Lymphadenopathy: Epitrochlear & Scalene",
 "Odd-one-out against the epitrochlear node causes",
 "All of the following are listed causes of a palpable epitrochlear node on Book p81 EXCEPT:",
 ["NHL",
  "Tularaemia",
  "Secondary syphilis",
  "Tuberculosis"],
 3,
 "Book p81 lists NHL, secondary syphilis, sarcoidosis, forearm/hand infections and tularaemia (rare) — and explicitly says 'not in TB (Dr. Hamide)'. (Book p81)"),

(81, "fillup", "Lymphadenopathy: Epitrochlear & Scalene",
 "Scalene node technique: index finger between SCM and clavicle; head tilted same side; press down towards first rib",
 "To palpate the scalene node on Book p81: place the index finger between the ____ and the ____, ask the patient to tilt the head to the same side and press firmly down towards the first rib.",
 ["trapezius; scapula",
  "SCM; first rib",
  "SCM; clavicle",
  "sternocleidomastoid; manubrium"],
 2,
 "Book p81: 'Scalene node — Place index finger between SCM and clavicle. Ask the patient to tilt his head to the same side and press firmly down towards the first rib'. (Book p81)"),

# ---------------------------------------------------------------- Book p82
(82, "fillup", "Lymphadenopathy: Generalised & Mediastinal; Oedema",
 "Generalised lymphadenopathy: HIV, IM, sarcoidosis",
 "The three causes of generalised lymphadenopathy on Book p82: ____, ____, and sarcoidosis.",
 ["TB; malaria",
  "HIV; IM",
  "HIV; TB",
  "IM; sarcoidosis"],
 1,
 "Book p82: 'Generalised lymphadenopathy — HIV, IM, sarcoidosis'. (Book p82)"),

(82, "scenario", "Lymphadenopathy: Generalised & Mediastinal; Oedema",
 "d'Espine sign: dull percussion on manubrium sterni, bronchial breathing below T4 spine — subcarinal lymphadenopathy",
 "Dull percussion over the manubrium sterni with bronchial breathing heard below the spine of T4 (d'Espine sign) on Book p82 points to:",
 ["Apical TB",
  "Subcarinal lymphadenopathy — the normally air-containing region at the tracheal bifurcation (T4) now conducts sound better, like consolidation",
  "Aortic arch aneurysm",
  "Pneumothorax"],
 1,
 "Book p82: 'Mediastinal lymphadenopathy — dull percussion on manubrium sterni, bronchial breathing heard below the spine of T4 (d'Espine sign); normally tracheal bifurcation @ T4 -> if sub carinal lymphadenopathy -> conducts sound better (consolidation like) -> bronchial breath'. (Book p82)"),

(82, "match", "Lymphadenopathy: Generalised & Mediastinal; Oedema",
 "The three RS oedema causes in book order",
 "Match the three causes of oedema in RS on Book p82 to their position — 1) First listed 2) Second listed 3) Third listed … A) Cor pulmonale B) Protein loss in the sputum, esp in bronchiectasis C) Amyloidosis due to long standing bronchiectasis",
 ["1-B, 2-A, 3-C",
  "1-A, 2-C, 3-B",
  "1-A, 2-B, 3-C",
  "1-C, 2-B, 3-A"],
 2,
 "Book p82: 'Oedema — in RS, can be due to cor pulmonale; protein loss in the sputum, esp in bronchiectasis; amyloidosis due to long standing bronchiectasis'. (Book p82)"),

(82, "fillup", "Respiration: Rate, Distress & Muscles",
 "Normal rate 12-18/min; Women thoraco-abdominal, Men abdomino thoracic",
 "The normal respiratory rate on Book p82 is ____–18/min; women breathe ____, men breathe ____.",
 ["12; thoraco-abdominal; abdomino thoracic",
  "10; abdomino thoracic; thoraco-abdominal",
  "12; abdomino thoracic; thoraco-abdominal",
  "16; thoraco-abdominal; thoraco-abdominal"],
 0,
 "Book p82: 'Respiration: Normal rate — 12 to 18/min. Women — thoraco-abdominal; Men — abdomino thoracic.' (Book p82)"),

(82, "match", "Respiration: Rate, Distress & Muscles",
 "The five respiratory distress signs: alar nasii, pursed lip (PEEP), tracheal indrawing, accessory muscles, intercostal retraction",
 "Match the five signs of respiratory distress on Book p82 to their detail — 1) Alar nasii 2) Pursed lip breathing 3) Indrawing 4) Accessory muscles 5) Intercostal retraction … A) Enlargement B) Helps like PEEP C) Of the trachea D) Like sternocleidomastoid and recti E) Listed last in the distress list",
 ["1-C, 2-B, 3-A, 4-D, 5-E",
  "1-A, 2-C, 3-B, 4-D, 5-E",
  "1-A, 2-B, 3-E, 4-D, 5-C",
  "1-A, 2-B, 3-C, 4-D, 5-E"],
 3,
 "Book p82 distress signs: alar nasii enlargement; pursed lip breathing — help like PEEP; indrawing of trachea; use of accessory muscles like sternocleidomastoid and recti; intercostal retraction. (Book p82)"),

(82, "match", "Respiration: Rate, Distress & Muscles",
 "Muscles of respiration: inspiration principal/accessory; expiration quiet/active",
 "Match the four muscle-of-respiration entries on Book p82 to their detail — 1) Inspiration — principal 2) Inspiration — accessory 3) Expiration — quiet breathing 4) Expiration — active … A) External intercostal muscles, diaphragm B) Sternocleidomastoid (elevates sternum), scalenes (elevate upper ribs), pectoralis minor, trapezius C) Passive D) Internal intercostals (pulls ribs down), abdominal muscles (pull ribs down, compress abdominal contents pushing diaphragm up), quadratus lumborum (pull ribs down)",
 ["1-D, 2-B, 3-C, 4-A",
  "1-A, 2-B, 3-C, 4-D",
  "1-A, 2-D, 3-B, 4-C",
  "1-A, 2-B, 3-D, 4-C"],
 1,
 "Book p82: Inspiration — principal: external intercostals, diaphragm; accessory: SCM (elevates sternum), scalenes (elevate upper ribs), pectoralis minor, trapezius. Expiration — quiet: passive; active: internal intercostals, abdominal muscles, quadratus lumborum. (Book p82)"),

(82, "recall", "Respiration: Rate, Distress & Muscles",
 "Mnemonic: 'I always with E' — inspiration -> external; vice versa",
 "The 'I always with E' mnemonic on Book p82 means:",
 ["Inspiration -> external (intercostals); vice versa for expiration",
  "Inspiration -> internal; expiration -> external",
  "Inhalation -> abdominal; exhalation -> thoracic",
  "Inspiration -> accessory; expiration -> principal"],
 0,
 "Book p82: '**Muscles of respiration — I always with E (insp -> external; vice versa)'. (Book p82)"),

(82, "match", "External Markers of Tuberculosis",
 "TB external markers 1-4: phlycten, choroid tubercles, scars/sinuses, scrofula",
 "Match the first four external markers of tuberculosis on Book p82 to their detail — 1) Phlycten 2) Choroid tubercles 3) Scars/sinuses 4) Scrofula … A) Small pinkish yellow nodule near the limbus B) Not visible to naked eye C) The third listed marker D) Tuberculous lymphadenitis (painless) in cervical region usually, can be non-TB",
 ["1-B, 2-A, 3-C, 4-D",
  "1-A, 2-B, 3-C, 4-D",
  "1-A, 2-D, 3-C, 4-B",
  "1-A, 2-B, 3-D, 4-C"],
 1,
 "Book p82 TB markers: 1. phlycten — small pinkish yellow nodule near the limbus; 2. choroid tubercles — not visible to naked eye; 3. scars/sinuses; 4. scrofula — tuberculous lymphadenitis (painless) in cervical region usually, can be non-TB. (Book p82)"),

(82, "match", "External Markers of Tuberculosis",
 "TB skin forms 5a-d: lupus vulgaris (apple jelly), erythema nodosum, verrucous cutis, scrofuloderma",
 "Match the four cutaneous TB forms on Book p82 to their detail — 1) Lupus vulgaris 2) Erythema nodosum 3) Tuberculous verrucous cutis 4) Scrofuloderma … A) Painful cutaneous granuloma with apple-jelly nodules — nose, eyelids, cheek, ear, neck B) The second listed skin form C) Direct inoculation of TB over skin -> solitary plaque with central involution and atrophic scar D) Direct skin extension from TB of LN, bones and joints",
 ["1-C, 2-B, 3-A, 4-D",
  "1-A, 2-C, 3-B, 4-D",
  "1-A, 2-B, 3-C, 4-D",
  "1-A, 2-B, 3-D, 4-C"],
 2,
 "Book p82 skin: a. lupus vulgaris — painful cutaneous granuloma with nodular appearance (brown jelly/apple jelly nodules): nose, eyelids, cheek, ear, neck; b. erythema nodosum; c. tuberculous verrucous cutis — direct inoculation -> solitary plaque with central involution and atrophic scar; d. scrofuloderma — direct skin extensions from TB of LN, bones and joints. (Book p82)"),

(82, "fillup", "External Markers of Tuberculosis",
 "TB markers 6 and 7: cold abscess/collar stud abscess; epididymo-orchitis",
 "External TB markers 6 and 7 on Book p82: the ____/collar stud abscess, and ____.",
 ["warm abscess; orchitis",
  "cold abscess; parotitis",
  "collar stud abscess; prostatitis",
  "cold abscess; epididymo-orchitis"],
 3,
 "Book p82 TB markers: 6. cold abscess/collar stud abscess; 7. epididymo-orchitis. (Book p82)"),

(82, "recall", "Other in General Examination",
 "Other G/E items: Horner's syndrome in lung malignancies; wasting of small muscles of hands (neurovascular compression)",
 "The 'other things in G/E' on Book p82: Horner's syndrome in lung malignancies, and signs of neurovascular compression — wasting of the ____.",
 ["small muscles of hands",
  "muscles of mastication",
  "foot muscles",
  "abdominal muscles"],
 0,
 "Book p82: 'Other things in G/E: 1. Horner's syndrome in lung malignancies; 2. Signs of neurovascular compression: wasting of small muscles of hands'. (Book p82)"),

# ---------------------------------------------------------------- Book p83
(83, "fillup", "Dahl's Sign",
 "Dahl's sign = Thinker's sign = Target sign",
 "Dahl's sign on Book p83 is also known as the ____ sign or the ____ sign.",
 ["sitting; square",
  "thinker's; circle",
  "thinker's; target",
  "target; tripod"],
 2,
 "Book p83: 'Dahl's sign (also Thinker's sign or Target sign)'. (Book p83)"),

(83, "recall", "Dahl's Sign",
 "Dahl's sign appearance: darkened (hyperpigmented) and thickened (hyperkeratotic) skin on lower thighs and elbows",
 "In Dahl's sign, the skin over the lower thighs and elbows is:",
 ["pale and atrophic",
  "darkened (hyperpigmented) and thickened (hyperkeratotic)",
  "erythematous and vesicular",
  "purpuric and scaly"],
 1,
 "Book p83 Dahl's sign a: 'areas of darkened (hyperpigmentation) and thickened (hyperkeratotic) skin are seen on the lower thighs and elbows.' (Book p83)"),

(83, "scenario", "Dahl's Sign",
 "Dahl's sign mechanism: flattened diaphragm, sitting forwards improves it, hemosiderin -> brown discoloration",
 "A long-standing COPD patient has brown patches over the lower thighs and elbows while sitting forwards with arms on the thighs. Per the Book p83 mechanism of Dahl's sign, the brown discolouration comes from:",
 ["Hemosiderin released from red blood cells trapped in the skin at the contact points",
  "Yellow jaundice depositing biliverdin",
  "White depigmentation of the dermis",
  "Red telangiectasia of the epidermis"],
 0,
 "Book p83: air trapping flattens the diaphragm (sitting forwards improves its effectiveness); long-standing COPD pts sit forwards with arms on thighs -> chronic erythema at contact points -> 'hemosiderin released from red blood cells trapped in the skin is released causing a brown discolouration of the skin'. (Book p83)"),

(83, "match", "Inspection: Upper Respiratory Tract",
 "URT inspection: oral cavity (thrush, tonsils, halitosis -> lung abscess), nose (DNS, polyps), pharynx (post nasal drip)",
 "Match the three URT inspection entries on Book p83 to their detail — 1) Oral cavity 2) Nose 3) Pharynx … A) Thrush (immunocompromised state), tonsils; poor oral hygiene, halitosis -> lung abscess B) DNS, polyps C) Post nasal drip — even these can cause respiratory symptoms and breathing difficulty",
 ["1-B, 2-A, 3-C",
  "1-C, 2-B, 3-A",
  "1-A, 2-B, 3-C",
  "1-A, 2-C, 3-B"],
 2,
 "Book p83: oral cavity — thrush (immunocompromised state), tonsils; poor oral hygiene, halitosis -> lung abscess; nose — DNS, polyps; pharynx — post nasal drip, 'cause even these can cause respiratory symptoms and breathing difficulty'. (Book p83)"),

(83, "recall", "Tracheal Position & Trail's Sign",
 "Tracheal position affected mainly by upper lobes",
 "The tracheal position is affected mainly by the ____ lobes, per Book p83.",
 ["lower",
  "upper",
  "middle",
  "apical"],
 1,
 "Book p83: 'Tracheal position: affected mainly by upper lobes'. (Book p83)"),

(83, "fillup", "Tracheal Position & Trail's Sign",
 "Trail's sign: pretracheal fascia encloses clavicular head of SCM; tracheal shift -> fascia relaxes -> prominence",
 "Trail's sign (Book p83): the pretracheal fascia encloses the clavicular head of SCM on both sides; when the trachea shifts to one side, the fascia on that side ____, making the clavicular head more prominent.",
 ["tightens",
  "tears",
  "relaxes",
  "calcifies"],
 2,
 "Book p83: 'Trail's sign — undue prominence of the clavicular head of SCM on the side to which the trachea is deviated. The pretracheal fascia encloses the clavicular head of SCM on both sides. When the trachea is shifted to one side, the fascia on that side relaxes, making the clavicular head more prominent.' (Book p83)"),

(83, "fillup", "Chest Wall Inspection: Volume Loss, Symmetry, Shapes",
 "Signs of lung volume loss: shoulder droop, prominence of medial scapular border (don't call it winging), crowding of ribs",
 "The signs of lung volume loss on Book p83: shoulder droop, prominence of the medial border of the scapula (don't call it ____) and crowding of ribs.",
 ["fracture",
  "deformity",
  "frailty",
  "winging"],
 3,
 "Book p83: 'Signs of lung volume loss — shoulder droop, prominence of medial border of scapula (don't call it winging), crowding of ribs.' (Book p83)"),

(83, "numeric", "Chest Wall Inspection: Volume Loss, Symmetry, Shapes",
 "AP:transverse ratios: normal 5:7; flat chest 1:2; barrel chest 1:1",
 "The AP-to-transverse diameter ratios on Book p83: normal chest ____, flat chest ____, barrel chest ____.",
 ["5:7; 1:2; 1:1",
  "4:6; 1:2; 1:1",
  "5:7; 1:1; 1:2",
  "5:7; 2:1; 1:1"],
 0,
 "Book p83: normal chest symmetrical and elliptical, AP:transverse 5:7; flat chest 1:2 (pulmonary TB, fibrothorax); barrel chest 1:1 (infancy, old age, emphysema, acromegaly). (Book p83)"),

(83, "match", "Chest Wall Inspection: Volume Loss, Symmetry, Shapes",
 "The four chest shape abnormalities: flat, barrel, pectus carinatum, pectus excavatum",
 "Match the four chest shape abnormalities on Book p83 to their detail — 1) Flat chest 2) Barrel chest 3) Pectus carinatum 4) Pectus excavatum … A) AP:transverse 1:2 — seen in pulmonary TB, fibrothorax B) 1:1 — infancy, old age, emphysema, acromegaly C) Pigeon chest — associated with rickets; forward protrusion of sternum with depression on either side D) Funnel chest, cobbler's chest — sunken appearance of sternum, most commonly a cup-shaped concavity",
 ["1-B, 2-A, 3-C, 4-D",
  "1-A, 2-B, 3-C, 4-D",
  "1-A, 2-B, 3-D, 4-C",
  "1-A, 2-C, 3-B, 4-D"],
 1,
 "Book p83: flat chest 1:2 (pulmonary TB, fibrothorax); barrel chest 1:1 (infancy, old age, emphysema, acromegaly); pectus carinatum (pigeon chest) — associated with rickets, forward protrusion of sternum, depression on either side; pectus excavatum (funnel chest, cobbler's chest) — sunken sternum, cup-shaped concavity. (Book p83)"),

# ---------------------------------------------------------------- Book p84
(84, "match", "Chest Wall Inspection: Volume Loss, Symmetry, Shapes",
 "Harrison's sulcus (chronic respi disease in child, rickets) vs rachitic rosary (bead-like costochondral junction)",
 "Match the two rib-margin findings on Book p84 to their detail — 1) Harrison's sulcus 2) Rachitic rosary … A) Chronic respi disease in child; rickets — symmetrical horizontal grooves above the costal margin along the line of diaphragm attachment, d/t lung hyperinflation and repeated strong diaphragmatic contraction B) Bead-like enlargement of the costochondral junction",
 ["1-B, 2-A",
  "1-A, 2-B",
  "1-A, 2-A",
  "1-B, 2-B"],
 1,
 "Book p84: Harrison's sulcus — chronic respi disease in child; rickets — symmetrical horizontal grooves above the costal margin along the line of attachment of diaphragm, d/t lung hyperinflation and repeated strong diaphragmatic contraction in chronic respiratory disease in childhood. Rachitic rosary — bead-like enlargement of costochondral junction. (Book p84)"),

(84, "fillup", "Chest Wall Inspection: Volume Loss, Symmetry, Shapes",
 "Harrison's sulcus mechanism: lung hyperinflation + repeated strong diaphragmatic contraction in chronic childhood respiratory disease",
 "Harrison's sulcus on Book p84 results from lung hyperinflation and repeated strong diaphragmatic contraction, as in ____.",
 ["acute asthma attacks in adults",
  "COPD in the elderly",
  "chronic respiratory disease in childhood",
  "neonatal jaundice"],
 2,
 "Book p84: 'd/t lung hyperinflation and repeated strong diaphragmatic contraction like in chronic respiratory disease in childhood.' (Book p84)"),

# ---------------------------------------------------------------- Book p85
(85, "recall", "Back Inspection & Palpation: Movements",
 "Flail chest: multiple rib fractures; paradoxical thoracic movement",
 "Flail chest on Book p85: secondary to multiple rib fractures, depression of the diaphragm causes the injured area to cave inward, producing ____ in breathing.",
 ["hyperdynamic movement",
  "absent movement",
  "paradoxical thoracic movement",
  "synchronous movement"],
 2,
 "Book p85: 'Flail Chest: secondary to multiple rib fractures, depression of diaphragm causes the injured area to cave inward producing a \"paradoxical thoracic movement\" in breathing.' (Book p85)"),

(85, "fillup", "Back Inspection & Palpation: Movements",
 "Kyphosis = forward curvature; scoliosis = lateral curvature",
 "Kyphosis is ____ curvature and scoliosis is ____ curvature, per Book p85.",
 ["lateral; forward",
  "forward; anteroposterior",
  "lateral; rotational",
  "forward; lateral"],
 3,
 "Book p85: 'Kyphosis — forward curvature; Scoliosis — lateral curvature'. (Book p85)"),

(85, "scenario", "Back Inspection & Palpation: Movements",
 "Scoliosis in fibrosis: convexity towards the OPPOSITE side (fibrosed lung pulls both ends towards the fibrosed side)",
 "In a patient with unilateral lung fibrosis, the convexity of the scoliotic curvature (Book p85) points to:",
 ["The opposite side — because the fibrosed lung pulls both ends of the vertebral column towards the fibrosed side",
  "The fibrosed side",
  "Always the right side",
  "Always the left side"],
 0,
 "Book p85: 'In fibrosis, the fibrosed lung pulls both ends of the vertebral column towards the fibrosed side, so the convexity of the curvature is towards the opposite side'. (Book p85)"),

(85, "numeric", "Back Inspection & Palpation: Movements",
 "Chest expansion: normal 5-8 cm; emphysema, ILD, ankylosing spondylitis <1 cm",
 "Normal chest expansion on Book p85 is 5–8 cm; in emphysema, ILD and ankylosing spondylitis it falls below ____ cm.",
 ["2",
  "3",
  "1",
  "0.5"],
 2,
 "Book p85: 'Chest expansion — Normal = 5 to 8 cm. Emphysema, ILD, Ank Spon — <1 cm'. (Book p85)"),

(85, "match", "Back Inspection & Palpation: Movements",
 "Expansion techniques: apical (supraclavicular fossae), anterior (thumbs in front), posterior lower (same as anterior), posterior upper (TRAPS)",
 "Match the chest-movement examination items on Book p85 to their technique — 1) Apical chest expansion 2) Anterior thoracic movement 3) Posterior thoracic movement — lower lobes 4) Posterior thoracic movement — upper lobes … A) Put hands over the supraclavicular fossae B) Hand placed on side of chest with thumbs in front; separation of thumbs with respiration observed C) Same as anterior D) Place hand over the TRAPS and compare movements",
 ["1-B, 2-A, 3-C, 4-D",
  "1-A, 2-D, 3-C, 4-B",
  "1-A, 2-B, 3-D, 4-C",
  "1-A, 2-B, 3-C, 4-D"],
 3,
 "Book p85: apical — hands over supraclavicular fossae; anterior — hand on side of chest, thumbs in front, separation of thumbs observed; posterior — same as anterior for lower lobes, upper lobes: hand over the TRAPS, compare movements. (Book p85)"),

(85, "fillup", "Back Inspection & Palpation: Movements",
 "Tape notes: metal end in front (circumference), on the spines (hemithoracic, fixed point), measure in full expiration first",
 "The measurement notes on Book p85: the metal end of the tape is kept in ____ while measuring chest circumference, kept on the ____ while measuring hemithoracic (the fixed point), and the measurement is taken first in full ____.",
 ["back; sternum; inspiration",
  "front; spines; expiration",
  "front; xiphisternum; inspiration",
  "back; spine; expiration"],
 1,
 "Book p85 notes: metal end in front for chest circumference; on the spines for hemithoracic (the fixed point); measure in full expiration first. (Book p85)"),

# ---------------------------------------------------------------- Book p86
(86, "match", "Significant URT Findings & Syndromes",
 "The five URT syndromes: Kartagener's, Wegener's, Samter's triad, Young's, Churg-Strauss",
 "Match the five syndromes of significant URT findings on Book p86 to their feature lists — 1) Kartagener's syndrome 2) Wegener's granulomatosis 3) Samter's triad 4) Young's syndrome 5) Churg-Strauss syndrome … A) Recurrent sinusitis with ciliary dyskinesia, bronchiectasis, situs inversus, male infertility B) Necrotizing granuloma C) Aspirin sensitivity, bronchial asthma, ethmoidal polyps D) Sinopulmonary disease, azoospermia E) Asthma/allergic rhinitis, eosinophilia, vasculitis, granuloma",
 ["1-D, 2-B, 3-C, 4-A, 5-E",
  "1-A, 2-E, 3-C, 4-D, 5-B",
  "1-A, 2-B, 3-C, 4-D, 5-E",
  "1-A, 2-B, 3-E, 4-D, 5-C"],
 2,
 "Book p86: Kartagener's — recurrent sinusitis with ciliary dyskinesia, bronchiectasis, situs inversus, male infertility; Wegener's — necrotizing granuloma; Samter's triad — aspirin sensitivity, bronchial asthma, ethmoidal polyps; Young's — sinopulmonary disease, azoospermia; Churg-Strauss — asthma/allergic rhinitis, eosinophilia, vasculitis, granuloma. (Book p86)"),

(86, "recall", "Significant URT Findings & Syndromes",
 "First two significant URT findings: turbinate hypertrophy/polyps obstructing airway; sinus tenderness = sinusitis",
 "The first two significant upper respiratory tract findings on Book p86 are:",
 ["Deviated nasal septum; post nasal drip",
  "Rhinitis medicamentosa; nasal obstruction",
  "Nasal turbinate hypertrophy or polyps causing airway obstruction; sinus tenderness suggestive of sinusitis",
  "Nasal polyps with anosmia; laryngeal stridor"],
 2,
 "Book p86: 'Significant findings in the upper respiratory tract: nasal turbinate hypertrophy or polyps causing airway obstruction; sinus tenderness suggestive of sinusitis'. (Book p86)"),

(86, "fillup", "Surface Marking of Lungs & Lower Borders",
 "Right 3 lobes; left 2 lobes",
 "In the surface marking of the lung on Book p86, the right side has ____ lobes and the left side ____ lobes.",
 ["2; 3",
  "3; 3",
  "2; 2",
  "3; 2"],
 3,
 "Book p86: 'Surface marking of lung — Right side 3 lobes; Left side 2 lobes'. (Book p86)"),

(86, "match", "Surface Marking of Lungs & Lower Borders",
 "The four points of the major (oblique) interlobar fissure: T2/T3 spinous process, medial scapular border, 5th rib MAL, 6th rib MCL",
 "Match the course of the major interlobar (oblique) fissure on Book p86 to its points — 1) Starting point 2) Along 3) Crossing 4) Reaching … A) The T2/T3 spinous process B) The medial border of scapula C) The 5th rib in the mid axillary line D) The 6th rib in mid clavicular line",
 ["1-D, 2-B, 3-C, 4-A",
  "1-A, 2-C, 3-B, 4-D",
  "1-A, 2-B, 3-C, 4-D",
  "1-A, 2-B, 3-D, 4-C"],
 2,
 "Book p86: the oblique fissure joins 3 bony points — starting from T2/T3 spinous process, curvilinear line along the medial border of scapula, crossing the 5th rib in the mid axillary line, reaching the 6th rib in mid clavicular line; lung below this line is the lower lobe. (Book p86)"),

(86, "fillup", "Surface Marking of Lungs & Lower Borders",
 "RML marking: horizontal fissure from 4th rib at right sternal border to midaxillary line, cutting the oblique fissure at 5th rib; triangular area = RML",
 "The right middle lobe is marked by a straight line (minor/horizontal fissure) from the ____ at the right sternal border towards the midaxillary line, cutting the major fissure at the ____; the triangular area represents the RML.",
 ["3rd rib; 4th rib",
  "4th rib; 6th rib",
  "4th rib; 5th rib",
  "5th rib; 6th rib"],
 2,
 "Book p86: 'Draw a straight line (minor interlobar fissure/horizontal fissure) from the 4th rib at right sternal border towards the midaxillary line cutting the major interlobar fissure at 5th rib. The triangular area represents RML.' (Book p86)"),

(87, "recall", "Surface Marking of Lungs & Lower Borders",
 "Boloor p142 reference: anterior, posterior and right lateral views of lung surface marking",
 "The inserted Boloor p.142 reference on Book p87 shows the surface marking of lung fissures and lobes in which views?",
 ["Anterior, posterior, right lateral",
  "Anterior, left lateral, axial",
  "Posterior, right lateral, left lateral",
  "Anterior, posterior, left lateral"],
 0,
 "Book p87 (Boloor p.142): Fig 3D.2 anterior view, Fig 3D.3 posterior view, Fig 3D.4 right lateral view of the chest showing the interlobar fissures and lobes. (Book p87)"),

# ---------------------------------------------------------------- Book p88
(88, "fillup", "Surface Marking of Lungs & Lower Borders",
 "Fig 3D.5: left lateral view showing left major interlobar fissure",
 "Fig 3D.5 on Book p88 shows the ____ lateral view of the chest, displaying the left major interlobar fissure.",
 ["right",
  "left",
  "medial",
  "axillary"],
 1,
 "Book p88: 'Fig. 3D.5: Left lateral view of chest showing left major interlobar fissure.' (Book p88)"),

(88, "numeric", "Surface Marking of Lungs & Lower Borders",
 "Lower border: lung 6/8/10 vs pleura 8/10/12 (midclavicular/midaxillary/scapular)",
 "The lower border of the LUNG on Book p88 is the 6th/8th/10th rib in the midclavicular/midaxillary/scapular lines, while the PLEURA reaches the ____, ____ and ____ ribs in the same lines.",
 ["7th; 9th; 11th",
  "8th; 9th; 12th",
  "8th; 10th; 12th",
  "9th; 11th; 12th"],
 2,
 "Book p88 (Boloor p.143, the 6/8/10 vs 8/10/12 rule): Lung — 6th (midclavicular), 8th (midaxillary), 10th (scapular); Pleura — 8th, 10th, 12th. (Book p88)"),

(88, "match", "Surface Marking of Lungs & Lower Borders",
 "Front vs back vs axillary examination: which lobes are predominantly assessed",
 "Match the three examination positions on Book p88 to what is predominantly assessed — 1) Front examination 2) Back examination 3) Axillary examination … A) Upper and middle lobes B) Lower lobe pathology C) All three lobes",
 ["1-B, 2-A, 3-C",
  "1-A, 2-C, 3-B",
  "1-C, 2-B, 3-A",
  "1-A, 2-B, 3-C"],
 3,
 "Book p88 table: front examination — predominantly upper and middle lobe; back examination — predominantly lower lobe pathology; axillary examination — all three lobes can be assessed. (Book p88)"),

# ---------------------------------------------------------------- Book p89
(89, "truefalse", "Tracheal Position: Pushed/Pulled, CricoSternal Distance",
 "Slight right deviation normal; pushed opposite (effusion, pneumothorax, apical tumour); pulled same (fibrosis, collapse); same-side in effusion = fibrosis/collapse or mesothelioma",
 "Which of the following True/False statements correctly reflects the tracheal position rules on Book p89?",
 ["False: slight tracheal deviation to the right is normal",
  "True: slight tracheal deviation to the right is normal",
  "True: an apical tumour pulls the trachea to the same side",
  "False: in effusion, a shift to the same side suggests co-existent fibrosis/collapse or mesothelioma"],
 1,
 "Book p89: slight tracheal deviation to the right is normal; pushed to the opposite side — pleural effusion, pneumothorax, apical tumour; pulled to the same side — fibrosis, collapse; shifted to the same side in effusion — co-existent fibrosis/collapse, mesothelioma. (Book p89)"),

(89, "match", "Tracheal Position: Pushed/Pulled, CricoSternal Distance",
 "The three tracheal deviation categories with their causes",
 "Match the three tracheal deviation categories on Book p89 to their causes — 1) Pushed to the opposite side 2) Pulled to the same side 3) Shifted to the same side in effusion … A) Pleural effusion, pneumothorax, apical tumour B) Fibrosis, collapse C) Co-existent fibrosis/collapse, mesothelioma",
 ["1-A, 2-B, 3-C",
  "1-B, 2-A, 3-C",
  "1-A, 2-C, 3-B",
  "1-C, 2-B, 3-A"],
 0,
 "Book p89: pushed to the opposite side — pleural effusion, pneumothorax, apical tumour; pulled to the same side — fibrosis, collapse; shifted to the same side in effusion — co-existent fibrosis/collapse, mesothelioma. (Book p89)"),

(89, "fillup", "Tracheal Position: Pushed/Pulled, CricoSternal Distance",
 "CricoSternal distance: number of fingers insinuated; reduced in COPD (mediastinum pulled down, cricoid downward)",
 "The crico-sternal distance on Book p89 is measured as the number of ____ that can be insinuated; it is reduced in COPD because the mediastinum is pulled down, pulling the ____ downward.",
 ["toes; thyroid",
  "fingertips; larynx",
  "fingers; cricoid",
  "fingers; thyroid"],
 2,
 "Book p89: 'CricoSternal distance: Measured as number of fingers that can be insinuated. Reduced in COPD bc the mediastinum is pulled down pulling the cricoid also downward.' (Book p89)"),

# ---------------------------------------------------------------- Book p90
(90, "fillup", "Inspiratory Tracheal Descent & Tracheal Tug (p90)",
 "Inspiratory tracheal descent in COPD = Campbell's sign",
 "Inspiratory tracheal descent in COPD on Book p90 is called ____'s sign.",
 ["Oliver's",
  "Trail's",
  "Dahl's",
  "Campbell's"],
 3,
 "Book p90: 'Inspiratory tracheal descent — COPD — Campbell's sign'. (Book p90)"),

(90, "match", "Inspiratory Tracheal Descent & Tracheal Tug (p90)",
 "Oliver's sign entries: chin raised, cricoid held up on deglutition, positive = downward tug (aortic arch aneurysm), false positives/negatives",
 "Match the five entries of Oliver's sign on Book p90 to their detail — 1) Technique a 2) Technique b 3) Positive 4) False positive 5) False negative … A) Patient's chin is raised B) Cricoid cartilage held up on deglutition on either side with fingers of both hands C) Downward tug felt — aortic arch aneurysm D) Mediastinal tumour attached to the arch E) Non pulsatile thrombosed aortic aneurysm",
 ["1-A, 2-B, 3-C, 4-D, 5-E",
  "1-B, 2-A, 3-C, 4-D, 5-E",
  "1-A, 2-B, 3-E, 4-D, 5-C",
  "1-A, 2-C, 3-B, 4-D, 5-E"],
 0,
 "Book p90 Oliver's sign: patient's chin is raised; cricoid cartilage held up on deglutition on either side with fingers of both hands; positive — downward tug felt — aortic arch aneurysm; false positive — mediastinal tumour attached to the arch; false negative — non pulsatile thrombosed aortic aneurysm. (Book p90)"),

# ---------------------------------------------------------------- Book p91
(91, "recall", "Trachea: Normal Position & Trail's Sign (p91)",
 "Trachea normally central or slightly deviated to right",
 "Per Book p91, the trachea is normally:",
 ["always central",
  "central or slightly deviated to the left",
  "slightly deviated to the right on expiration",
  "central or slightly deviated to right"],
 3,
 "Book p91: 'Trachea: Normally central or slightly deviated to right.' (Book p91)"),

(91, "fillup", "Trachea: Normal Position & Trail's Sign (p91)",
 "Trail's sign mechanism: investing fascia splits to enclose SCM, continues as pretracheal fascia; ipsilateral fascia relaxes; SCM contracts",
 "In the Trail's sign mechanism on Book p91, the investing layer of cervical fascia splits to enclose the sternocleidomastoid and continues as the pretracheal fascia; on tracheal shift, the fascia over the ipsilateral SCM ____, the SCM goes into a state of ____, and the clavicular head becomes prominent.",
 ["tightens; relaxation",
  "tears; contraction",
  "relaxes; contraction",
  "relaxes; relaxation"],
 2,
 "Book p91: 'When there is tracheal shift to one side, the fascia covering the ipsilateral sternocleidomastoid relaxes. The sternocleidomastoid goes into a state of contraction making the clavicular head prominent.' (Book p91)"),

(91, "recall", "Trachea: Normal Position & Trail's Sign (p91)",
 "Clinical implication of tracheal shift: upper mediastinal shift; indicates upper lobe fibrosis or collapse",
 "The clinical implication of tracheal shift on Book p91: it suggests a ____ shift and indicates ____.",
 ["upper mediastinal; upper lobe fibrosis or collapse",
  "lower mediastinal; lower lobe fibrosis or collapse",
  "upper mediastinal; apical tumour",
  "lower mediastinal; pneumonia"],
 0,
 "Book p91: 'Clinical implication of tracheal shift: It suggests upper mediastinal shift. Indicates upper lobe fibrosis or collapse.' (Book p91)"),

# ---------------------------------------------------------------- Book p92
(92, "fillup", "Tracheal Palpation: Oliver's & Campbell's (p92)",
 "Oliver's sign technique (p92): stand behind patient, hold cricoid, slight upward thrust",
 "The Oliver's sign technique on Book p92: stand ____ the patient, hold the cricoid cartilage and give a slight ____ thrust.",
 ["in front of; downward",
  "behind; upward",
  "behind; downward",
  "in front of; upward"],
 1,
 "Book p92: 'Stand behind patient and hold cricoid cartilage give a slight upward thrust.' (Book p92)"),

(92, "match", "Tracheal Palpation: Oliver's & Campbell's (p92)",
 "Oliver's sign entries (p92): positive (downward pull each heartbeat, aortic aneurysm), negative, false positive (abdominal aorta), false negative (thrombosed)",
 "Match the four entries of Oliver's sign on Book p92 to their detail — 1) Positive test 2) Negative test 3) False positive 4) False negative … A) Downward pull with each heart beat suggestive of aortic aneurysm B) Normal C) Mediastinal tumor attached to abdominal aorta D) Thrombosed aortic aneurysm",
 ["1-D, 2-B, 3-C, 4-A",
  "1-A, 2-C, 3-B, 4-D",
  "1-A, 2-B, 3-C, 4-D",
  "1-A, 2-B, 3-D, 4-C"],
 2,
 "Book p92 Oliver's sign: positive — downward pull with each heart beat suggestive of aortic aneurysm; negative — normal; false positive — mediastinal tumor attached to abdominal aorta; false negative — thrombosed aortic aneurysm. (Book p92)"),

(92, "scenario", "Tracheal Palpation: Oliver's & Campbell's (p92)",
 "p90 vs p92 false-positive nuance: attached to the arch (p90) vs attached to the abdominal aorta (p92)",
 "Comparing the two Oliver's sign pages: the false positive on Book p90 is a mediastinal tumour attached to the ____, while on Book p92 it is attached to the ____.",
 ["abdominal aorta; arch",
  "thoracic aorta; abdominal aorta",
  "arch; thoracic aorta",
  "arch; abdominal aorta"],
 3,
 "Book p90: 'False positive — mediastinal tumour attached to the arch'; Book p92: 'False positive — mediastinal tumor attached to abdominal aorta'. (Book p92)"),

(92, "fillup", "Tracheal Palpation: Oliver's & Campbell's (p92)",
 "Campbell sign (p92): downward pull of the depressed diaphragm in long standing hyperinflation of lung",
 "Tracheal descent on inspiration (Campbell sign) on Book p92 is due to the downward pull of the depressed diaphragm in long standing ____ of lung.",
 ["fibrosis",
  "hyperinflation",
  "consolidation",
  "hyperplasia"],
 1,
 "Book p92: 'Tracheal descent on inspiration (Campbell sign): Due to downward pull of the depressed diaphragm in long standing hyperinflation of lung.' (Book p92)"),

(92, "recall", "Tracheal Palpation: Oliver's & Campbell's (p92)",
 "Figs 3D.14/3D.15: tracing the trachea with the middle finger; insinuating the finger between trachea and sternal head of SCM to feel resistance",
 "Figs 3D.14 and 3D.15 on Book p92 show:",
 ["Oliver's sign from behind; tracheal tug from the front",
  "Chest expansion measurement; apical impulse palpation",
  "Clavicular head prominence; tracheal shift to the left",
  "Tracing the trachea down with the middle finger; insinuating the middle finger between the trachea and sternal head of sternocleidomastoid and feeling for resistance"],
 3,
 "Book p92: Fig 3D.14 — tracing the trachea down with the middle finger; Fig 3D.15 — insinuate the middle finger between the trachea and sternal head of sternocleidomastoid, and feel for resistance. (Book p92)"),
]
