# -*- coding: utf-8 -*-
"""Chapter 15 source data: Book p93-97 (RS - Percussion & Auscultation)."""

# (page, fmt, sec, point, question, options, ans, explanation)
DATA = [
# ---------------------------------------------------------------- Book p93
(93, "recall", "Chest Wall Tenderness, Subcutaneous Emphysema & Fremitus",
 "Chest wall tenderness: empyema, pleuritis, infiltration of chest wall",
 "Chest wall tenderness in the respiratory system (Book p93) is seen in:",
 ["Empyema, pleuritis, infiltration of chest wall",
  "Asthma, pneumonia, pulmonary oedema",
  "TB, bronchiectasis, lung cancer",
  "Pulmonary embolism, fibrosis, collapse"],
 0,
 "Book p93: 'Chest wall tenderness — Empyema, pleuritis, infiltration of chest wall'. (Book p93)"),

(93, "recall", "Chest Wall Tenderness, Subcutaneous Emphysema & Fremitus",
 "Subcutaneous emphysema listed right after chest wall tenderness",
 "The finding listed on Book p93 immediately after chest wall tenderness is:",
 ["cyanosis",
  "subcutaneous emphysema",
  "clubbing",
  "pulsus paradoxus"],
 1,
 "Book p93: the line 'Subcutaneous emphysema' follows 'Chest wall tenderness — Empyema, pleuritis, infiltration of chest wall'. (Book p93)"),

(93, "match", "Chest Wall Tenderness, Subcutaneous Emphysema & Fremitus",
 "The three fremitus types: vocal (consolidation up, effusion down), tactile (crackles, rhonchi), friction (pleural rub)",
 "Match the three fremitus types on Book p93 to their detail — 1) Vocal 2) Tactile 3) Friction … A) Increased in consolidation, decreased in effusion B) Palpable added sounds — crackles, rhonchi C) Palpable pleural rub",
 ["1-B, 2-A, 3-C",
  "1-A, 2-C, 3-B",
  "1-A, 2-B, 3-C",
  "1-C, 2-B, 3-A"],
 2,
 "Book p93 fremitus: vocal — increased in consolidation, decreased in effusion; tactile — palpable added sounds: crackles, rhonchi; friction — palpable pleural rub. (Book p93)"),

(93, "match", "VR/VF & Percussion: Physics",
 "Transmission speed (solid > liquid > air) vs ability to vibrate (air > liquid > solid); VR/VF = transmission, percussion = vibration",
 "Match the four physics entries on Book p93 to their detail — 1) Transmission (speed) of sound 2) Ability to vibrate 3) VR/VF measures 4) Percussion measures … A) Solid > liquid > air B) Air > liquid > solid C) The medium's ability to transmit sound (from vocal cords) D) The medium's ability to vibrate",
 ["1-B, 2-A, 3-C, 4-D",
  "1-A, 2-B, 3-D, 4-C",
  "1-A, 2-B, 3-C, 4-D",
  "1-A, 2-C, 3-B, 4-D"],
 2,
 "Book p93: transmission (speed) of sound — solid > liquid > air; ability to vibrate — air > liquid > solid; VR/VF measure the medium's ability to transmit sound (from vocal cords); percussion measures the medium's ability to vibrate. (Book p93)"),

(93, "fillup", "VR/VF & Percussion: Physics",
 "Lung-to-skin distance altered: more attenuation of VF/VR/breath sound; nature of vibration remains the same",
 "For lesions where the lung-to-skin distance is altered (Book p93): as distance increases, ____ of the sound produced (VF/VR/breath sound) increases, while the nature of vibration of the medium ____.",
 ["attenuation; remains the same",
  "amplification; changes",
  "attenuation; disappears",
  "amplification; remains the same"],
 0,
 "Book p93: 'Lesions where LUNG to SKIN distance is altered — as distance increase — more attenuation of sound produced (VF/VR/BREATH SOUND) while nature of vibration of medium remain same'. (Book p93)"),

# ---------------------------------------------------------------- Book p94
(94, "match", "Pathology Table: VR/VF & Percussion",
 "The five-row pathology table: consolidation, hyperinflation, pleural effusion, pneumothorax, collapse",
 "Match the five pathologies in the Book p94 table to their VR/VF and percussion — 1) Consolidation 2) Hyperinflation 3) Pleural effusion 4) Pneumothorax 5) Collapse … A) Increased (fluid sound faster) — DULL (fluid vibrate less) B) Reduced (air sound slower) — RESONANT (air vibrate more) C) Reduced (lung-chest distance more) — STONY DULL D) Reduced — Resonant (air vibrate more) E) Reduced — Dull (collapse forms solid like area)",
 ["1-A, 2-C, 3-B, 4-D, 5-E",
  "1-A, 2-B, 3-C, 4-D, 5-E",
  "1-B, 2-A, 3-C, 4-D, 5-E",
  "1-A, 2-B, 3-D, 4-C, 5-E"],
 1,
 "Book p94 table: Consolidation — fluid in parenchyma — increased — DULL; Hyperinflation — more air in parenchyma — reduced — RESONANT; Pleural effusion — fluid around lung, lung far from chest wall — reduced — STONY DULL; Pneumothorax — air around lung, lung far from chest — reduced — Resonant; Collapse — lung far from chest — reduced — Dull (collapse forms solid like area). (Book p94)"),

(94, "fillup", "Pathology Table: VR/VF & Percussion",
 "Consolidation = fluid in parenchyma; hyperinflation = more air replaced in parenchyma",
 "In the Book p94 table, consolidation is described as ____ in the parenchyma, while hyperinflation is described as ____ in the parenchyma.",
 ["more air replaced; fluid",
  "air; fluid",
  "fluid; air",
  "fluid; more air replaced"],
 3,
 "Book p94: consolidation — 'fluid in parenchyma'; hyperinflation — 'more air replaced in parenchyma'. (Book p94)"),

(94, "scenario", "Pathology Table: VR/VF & Percussion",
 "Stony dull percussion + reduced fremitus = pleural effusion",
 "A patient shows STONY DULL percussion with reduced vocal/tactile fremitus because the lung is far from the chest wall. Per the Book p94 table, the pathology is:",
 ["consolidation",
  "pneumothorax",
  "collapse",
  "pleural effusion"],
 3,
 "Book p94: pleural effusion — fluid around lung + lung far from chest wall — VR/VF reduced — percussion STONY DULL. (Book p94)"),

(94, "truefalse", "Pathology Table: VR/VF & Percussion",
 "Pneumothorax: reduced VR/VF but resonant percussion (air vibrates more); hyperinflation reduced; collapse dull",
 "Which of the following True/False statements is consistent with the Book p94 table?",
 ["False: pneumothorax percussion is resonant because air vibrates more",
  "True: pneumothorax percussion is resonant because air vibrates more",
  "True: hyperinflation increases VR/VF because air conducts sound slower",
  "False: collapse gives a dull note because collapse forms a solid like area"],
 1,
 "Book p94: pneumothorax — reduced VR/VF, percussion resonant (air vibrate more); hyperinflation — reduced VR/VF (air sound slower); collapse — dull (collapse forms solid like area). (Book p94)"),

(94, "oddoneout", "Pathology Table: VR/VF & Percussion",
 "All four non-consolidation pathologies in the table reduce VR/VF; consolidation increases it",
 "In the Book p94 table, all of the following pathologies REDUCE VR/VF EXCEPT:",
 ["hyperinflation",
  "consolidation",
  "pleural effusion",
  "collapse"],
 1,
 "Book p94: consolidation — INCREASED VR/VF (fluid conducts sound faster); hyperinflation, pleural effusion, pneumothorax and collapse — all reduced. (Book p94)"),

# ---------------------------------------------------------------- Book p95
(95, "match", "Percussion Technique & Areas",
 "The three percussion techniques: anterior (hand by side), posterior (head bent forward, hands on opposite shoulder), lateral (hands over head)",
 "Match the three percussion techniques on Book p95 to their hand position — 1) Anterior percussion 2) Posterior percussion 3) Lateral percussion … A) Hand by the side B) Head bent forward, hands on opposite shoulder C) Hands held over head",
 ["1-A, 2-B, 3-C",
  "1-B, 2-A, 3-C",
  "1-A, 2-C, 3-B",
  "1-C, 2-B, 3-A"],
 0,
 "Book p95: anterior percussion — hand by the side; posterior percussion — head bent forward, hands on opposite shoulder; lateral percussion — hands held over head. (Book p95)"),

(95, "match", "Percussion Technique & Areas",
 "The nine percussion areas: anterior (supraclavicular, clavicular, infraclavicular up to 2nd ICS, mammary 2nd-6th ICS, axillary up to 4th ICS, infra-axillary 4th-7th ICS) and posterior (suprascapular, interscapular, infrascapular)",
 "Match the nine percussion areas in the Book p95 table to their row/limit — 1) Supraclavicular 2) Clavicular 3) Infraclavicular 4) Mammary 5) Axillary 6) Infra-axillary 7) Suprascapular 8) Interscapular 9) Infrascapular … A) 2nd row of the anterior column B) 3rd row — up to 2nd ICS C) 4th row — 2nd to 6th ICS D) 5th row — up to 4th ICS E) 6th row — 4th to 7th ICS F) 1st row of the posterior column G) 2nd row of the posterior column H) 3rd row of the posterior column I) 1st row of the anterior column",
 ["1-I, 2-A, 3-B, 4-C, 5-D, 6-E, 7-F, 8-G, 9-H",
  "1-A, 2-I, 3-B, 4-C, 5-D, 6-E, 7-F, 8-G, 9-H",
  "1-I, 2-A, 3-E, 4-C, 5-D, 6-B, 7-F, 8-G, 9-H",
  "1-I, 2-A, 3-B, 4-C, 5-D, 6-E, 7-H, 8-G, 9-F"],
 0,
 "Book p95 areas table — Anteriorly: supraclavicular, clavicular, infraclavicular (up to 2nd ICS), mammary (2nd to 6th ICS), axillary (up to 4th ICS), infra-axillary (4th to 7th ICS); Posteriorly: suprascapular, interscapular, infrascapular. (Book p95)"),

(95, "fillup", "Percussion Technique & Areas",
 "Liver dullness: normal upper level 5th ICS; pushed down suggests emphysema (primary or compensatory)",
 "The normal upper level of liver dullness on Book p95 is the ____ ICS; if pushed down, it suggests emphysema (primary or ____).",
 ["4th; compensatory",
  "5th; restrictive",
  "5th; compensatory",
  "6th; obstructive"],
 2,
 "Book p95: 'Normal upper level of liver dullness is the 5th ICS. If pushed down, it suggests emphysema (Primary or compensatory)'. (Book p95)"),

(95, "recall", "Liver Dullness, Traube's & Grocco's Triangle",
 "In left sided pathologies, percuss over Traube's space also",
 "In left sided pathologies, per Book p95 you should also percuss over:",
 ["Kronig's isthmus",
  "Traube's space",
  "Grocco's triangle",
  "Garland's triangle"],
 1,
 "Book p95: 'In left sided pathologies, percuss over Traube's space also'. (Book p95)"),

(95, "scenario", "Liver Dullness, Traube's & Grocco's Triangle",
 "Grocco's triangle: area of dullness against the spine on the base of the opposite lung; posterior mediastinal pleura bulges into contralateral hemithorax; pathognomonic of pleural effusion",
 "A triangular area of dullness on percussion against the spine at the base of the OPPOSITE lung (Book p95) — its reason and significance are:",
 ["The scapula overlying the base; pathognomonic of TB",
  "The posterior mediastinal pleura may bulge into the contralateral hemithorax in the presence of a pleural effusion — pathognomonic of pleural effusion",
  "Lateral displacement of the heart; suggestive of pneumothorax",
  "Depression of the diaphragm; suggests hyperinflation"],
 1,
 "Book p95: Grocco's triangle — area of dullness on percussion against the spine on the base of the opposite lung (possibly due to posterior mediastinal shift); in pleural effusion the posterior mediastinal pleura may bulge into the contralateral hemithorax; pathognomonic of pleural effusion. (Book p95)"),

(95, "fillup", "Liver Dullness, Traube's & Grocco's Triangle",
 "p95 figure labels: Garland's triangle of hyperresonance; compression atelectasis above massive effusion; massive effusion with stony dullness",
 "The figure labels on Book p95: the ____ triangle of hyperresonance; area of compression atelectasis above ____ effusion; and massive effusion with ____ dullness.",
 ["Grocco's; small; resonant",
  "Garland's; moderate; dull",
  "Ellis's; massive; stony",
  "Garland's; massive; stony"],
 3,
 "Book p95 figure labels: 'Garland's triangle of hyperresonance', 'Area of compression atelectasis above massive effusion', 'Massive effusion with stony dullness' (also scapula, Grocco's triangle of dullness). (Book p95)"),

# ---------------------------------------------------------------- Book p96
(96, "match", "Grocco's Triangle: The Red Box & Kronig's Isthmus",
 "Red box: triangular dullness at back of chest on healthy side; base 12th rib; apex at upper margin of fluid on diseased side; internally vertebral line; externally apex-to-lateral-base line",
 "Match the five entries of the Book p96 red box (Grocco's triangle detail) to their detail — 1) Position 2) Base 3) Apex 4) Internally 5) Externally … A) Triangular area of dullness at the back of chest on the healthy side B) Horizontally along the 12th rib C) At the level of upper margin of fluid on diseased side D) Vertebral line E) Line joining the apex and lateral base",
 ["1-A, 2-B, 3-C, 4-D, 5-E",
  "1-A, 2-C, 3-B, 4-D, 5-E",
  "1-B, 2-A, 3-C, 4-D, 5-E",
  "1-A, 2-B, 3-E, 4-D, 5-C"],
 0,
 "Book p96 red box: triangular area of dullness at the back of chest on the healthy side; base — horizontally along the 12th rib; apex — at the level of upper margin of fluid on diseased side; internally — vertebral line; externally — line joining the apex and lateral base. (Book p96)"),

(96, "numeric", "Grocco's Triangle: The Red Box & Kronig's Isthmus",
 "Kronig's isthmus: band of resonance 5-7 cm over the supraclavicular fossa",
 "Kronig's isthmus on Book p96 is a band of resonance of ____ cm over the supraclavicular fossa.",
 ["5-7",
  "3-5",
  "7-9",
  "1-3"],
 0,
 "Book p96: 'Kronig's isthmus — Band of resonance 5-7 cm over the supraclavicular fossa.' (Book p96)"),

(96, "match", "Grocco's Triangle: The Red Box & Kronig's Isthmus",
 "Kronig's isthmus borders: scalenus medius, acromion process laterally, anteriorly clavicle, posteriorly trapezius",
 "Match the four borders of Kronig's isthmus on Book p96 to their detail — 1) The first listed border 2) Laterally 3) Anteriorly 4) Posteriorly … A) Scalenus medius B) Acromion process C) Clavicle D) Trapezius",
 ["1-B, 2-A, 3-C, 4-D",
  "1-A, 2-B, 3-C, 4-D",
  "1-A, 2-C, 3-B, 4-D",
  "1-A, 2-B, 3-D, 4-C"],
 1,
 "Book p96 Kronig's isthmus borders: scalenus medius; acromion process laterally; anteriorly clavicle; posteriorly trapezius. (Book p96)"),

(96, "fillup", "Grocco's Triangle: The Red Box & Kronig's Isthmus",
 "Kronig's technique: standing behind, lateral to medial, clavicle not touched; increase = emphysema, decrease = TB/apical lung tumour",
 "Kronig's isthmus percussion on Book p96 is done by standing ____ the patient, from ____ to medial, without touching the ____. An increase in size suggests emphysema; a decreased size suggests TB/apical lung tumour.",
 ["in front of; medial; scapula",
  "behind; medial; trapezius",
  "behind; lateral; clavicle",
  "in front of; lateral; clavicle"],
 2,
 "Book p96: 'This percussion is done by standing behind the patient, from lateral to medial; clavicle not touched. It indicates the condition of the lung apex. Increase — emphysema; decreased size — TB/apical lung tumour.' (Book p96)"),

(96, "recall", "Grocco's Triangle: The Red Box & Kronig's Isthmus",
 "Tidal percussion: infradiaphragmatic vs supradiaphragmatic pathologies",
 "Tidal percussion on Book p96 is used to differentiate ____ pathologies.",
 ["upper lobe vs lower lobe",
  "infradiaphragmatic vs supradiaphragmatic",
  "right sided vs left sided",
  "pleural vs parenchymal"],
 1,
 "Book p96: 'Tidal percussion — infradiaphragmatic vs. supradiaphragmatic pathologies.' (Book p96)"),

(96, "match", "Traube's Space",
 "Traube's space borders: 6th rib superiorly, left midaxillary line laterally, left costal margin inferiorly; content — fundus of stomach",
 "Match the four borders/content of Traube's space on Book p96 to their detail — 1) Superiorly 2) Laterally 3) Inferiorly 4) Content … A) 6th rib B) Left midaxillary line C) Left costal margin D) Fundus of the stomach",
 ["1-B, 2-A, 3-C, 4-D",
  "1-A, 2-C, 3-B, 4-D",
  "1-A, 2-B, 3-C, 4-D",
  "1-C, 2-B, 3-A, 4-D"],
 2,
 "Book p96: Traube's space — 6th rib superiorly, left midaxillary line laterally, left costal margin inferiorly; content — fundus of the stomach. (Book p96)"),

(96, "match", "Traube's Space",
 "Traube's relations: right side — left lobe of liver; left side — spleen; superiorly — left lung resonance; inferiorly — left costal margin",
 "Match the five relation entries of Traube's space on Book p96 to their detail — 1) Right side 2) Left side 3) Superiorly 4) Inferiorly 5) One obliteration cause … A) Left lobe of the liver B) Spleen C) Left lung resonance D) Left costal margin E) Left pleural effusion",
 ["1-B, 2-A, 3-C, 4-D, 5-E",
  "1-A, 2-B, 3-D, 4-C, 5-E",
  "1-A, 2-C, 3-B, 4-D, 5-E",
  "1-A, 2-B, 3-C, 4-D, 5-E"],
 3,
 "Book p96: right side — left lobe of the liver; left side — spleen; superiorly — left lung resonance; inferiorly — left costal margin; obliterated in — left pleural effusion (among others). (Book p96)"),

(96, "fillup", "Traube's Space",
 "Obliterated in: left pleural effusion, massive splenomegaly, enlarged left lobe of liver, full stomach, massive pericardial effusion",
 "Traube's space is obliterated in left pleural effusion, massive splenomegaly, enlarged left lobe of liver, full stomach, and ____, per Book p96.",
 ["massive pericardial effusion",
  "massive pleural thickening",
  "left apical fibrosis",
  "enlarged right lobe of liver"],
 0,
 "Book p96: obliterated in — left pleural effusion, massive splenomegaly, enlarged left lobe of liver, full stomach, massive pericardial effusion. (Book p96)"),

(96, "fillup", "Traube's Space",
 "Shifted upwards in: left diaphragmatic paralysis, left lower lobe collapse, fibrosis of left lung",
 "Traube's space is shifted upwards in left diaphragmatic paralysis, left lower lobe collapse, and ____, per Book p96.",
 ["fibrosis of the right lung",
  "fibrosis of the left lung",
  "left upper lobe pneumonia",
  "right diaphragmatic paralysis"],
 1,
 "Book p96: shifted upwards in — left diaphragmatic paralysis, left lower lobe collapse, fibrosis of left lung. (Book p96)"),

(96, "recall", "Traube's Space",
 "p96 figure label: area to percuss for Castell's sign",
 "The label on the Book p96 Traube's space figure points to the 'area to percuss for ____ sign'.",
 ["Grocco's",
  "Kronig's",
  "Castell's",
  "Traube's"],
 2,
 "Book p96 figure (Marisa Bonofiglio): labels include sternum, (L) ANT axillary line, 6th rib, costal margin, Traube's space, and 'Area to percuss for Castell's sign'. (Book p96)"),

# ---------------------------------------------------------------- Book p97
(97, "fillup", "Clavicular Percussion & Hydropneumothorax Signs",
 "Clavicular percussion: stretch the skin below; medial 1/3 with middle finger (less muscle attachments); dull note = secondary TB",
 "In clavicular percussion on Book p97, you ____ the skin below, percuss the ____ 1/3 with the middle finger (fewer muscle attachments there), and a dull note over it represents ____ TB.",
 ["relaxed; lateral; primary",
  "stretch; medial; secondary",
  "stretch; lateral; secondary",
  "relaxed; medial; reactivation"],
 1,
 "Book p97: 'Percuss the clavicle — stretch the skin below. Percuss the medial 1/3 with your middle finger because there are less muscle attachments on the medial 1/3. Purpose — near the apex of the lung. So a dull note over here would represent a secondary TB.' (Book p97)"),

(97, "scenario", "Clavicular Percussion & Hydropneumothorax Signs",
 "Shifting dullness: find upper border of posterior dullness, lean forward; immediate = hydropneumothorax; effusion also shifts but takes time",
 "You find the upper border of posterior dullness and ask the patient to lean forward (Book p97). If the dullness is seen IMMEDIATELY, it is suggestive of:",
 ["hydropneumothorax — even effusion has shifting dullness, but it will take time",
  "simple pleural effusion — it shifts immediately",
  "pneumothorax — the dullness disappears",
  "consolidation — the dullness becomes fixed"],
 0,
 "Book p97: 'Shifting dullness — find the upper border of posterior dullness, then ask the patient to lean forward. If the dullness is immediately seen then it is suggestive of hydropneumothorax. Even effusion will have shifting dullness, but it will take time.' (Book p97)"),

(97, "match", "Clavicular Percussion & Hydropneumothorax Signs",
 "The four hydropneumothorax signs: straight line dullness, succussion splash, silver coin sounds, shifting dullness",
 "Match the four hydropneumothorax findings on Book p97 to their detail — 1) Straight line dullness 2) Succussion splash 3) Silver coin sounds 4) Shifting dullness … A) Listed as a hydropneumothorax sign B) Percuss the upper limit of dullness, hug the patient and shake him — a splash like over a stomach containing air and fluid C) Hit one coin with the other, stethoscope on the back — clinking sounds audible D) Find the upper border of posterior dullness, lean forward — immediate dullness",
 ["1-B, 2-A, 3-C, 4-D",
  "1-A, 2-C, 3-B, 4-D",
  "1-A, 2-B, 3-D, 4-C",
  "1-A, 2-B, 3-C, 4-D"],
 3,
 "Book p97: straight line dullness — hydropneumothorax; succussion splash — percuss the upper limit of dullness, stethoscope just above it, hug and shake the patient, splash like stomach with air and fluid; silver coin sounds — hit one coin with the other, steth on the back, clinking audible in hydropneumothorax; shifting dullness — immediate on leaning forward. (Book p97)"),

(97, "scenario", "S shaped Curve of Ellis & the 20-Second Rule",
 "S shaped curve of Ellis: moderate pleural effusion; highest dullness in axilla, lowest near spine/sternum; reason — capillary suction between two pleura layers",
 "The S shaped curve of Ellis on Book p97 (moderate pleural effusion, uppermost dullness highest in the axilla, lowest near the spine posteriorly and sternum anteriorly) is attributed to:",
 ["negative intrapleural pressure",
  "capillary suction between two layers of pleura",
  "surface tension of the pleural fluid",
  "mediastinal pull by the heart"],
 1,
 "Book p97: 'S shaped curve of Ellis — seen in moderate pleural effusion. Uppermost dullness is highest in the axilla. Lowest in spine posteriorly and near sternum anteriorly. Reason — capillary suction between two layers of pleura.' (Book p97)"),

(97, "recall", "S shaped Curve of Ellis & the 20-Second Rule",
 "Ellis curve also seen radiologically, believed due to scattering of X rays by the fluid",
 "The S shaped curve of Ellis is also seen radiologically, per Book p97 believed to be due to:",
 ["scattering of X rays by the fluid",
  "absorption by the mediastinum",
  "reflection from the diaphragm",
  "diffraction at the rib margins"],
 0,
 "Book p97: 'Also seen radiologically, believed to be due to scattering of X rays by the fluid'. (Book p97)"),

(97, "fillup", "S shaped Curve of Ellis & the 20-Second Rule",
 "No 20-second wait in hydropneumothorax shifting dullness (same compartment) vs ascites (different compartments, bowel loops need time)",
 "In shifting dullness due to hydropneumothorax, per Book p97 you don't wait ____ seconds like in ascites — in the abdomen air and fluid are in different compartments so time is needed for bowel loops to move, whereas in the lung air and fluid are in the same compartment.",
 ["10",
  "30",
  "20",
  "5"],
 2,
 "Book p97: 'we don't wait for 20 seconds like ascites because in the abdomen the air and fluid are in different compartments... Whereas in the lung, the air and fluid are in the same compartment so there is no need to give time for movement.' (Book p97)"),

(97, "match", "Vesicular Breath Sounds",
 "VBS: low pitched rustling; I:E = 3:1; no pause; diminished in asthma (silent chest), tumour, small effusion, pleural thickening",
 "Match the four vesicular breath sound entries on Book p97 to their detail — 1) Pitch/nature 2) Inspiration : Expiration 3) Pause 4) Diminished VBS in … A) Low pitched, rustling in nature B) 3:1 C) No pause between end of inspiration and beginning of expiration D) Bronchial asthma (silent chest), tumour, small effusion, pleural thickening",
 ["1-B, 2-A, 3-C, 4-D",
  "1-A, 2-C, 3-B, 4-D",
  "1-A, 2-B, 3-D, 4-C",
  "1-A, 2-B, 3-C, 4-D"],
 3,
 "Book p97 vesicular breath sounds: low pitched, rustling in nature; inspiration: expiration is 3:1; no pause between end of inspiration and beginning of expiration; diminished VBS — bronchial asthma (silent chest), tumour, small effusion, pleural thickening. (Book p97)"),

(97, "match", "Causes of Diminished Vesicular Breathing (Box)",
 "Box: reduced conduction — obesity/thick chest wall, pleural effusion or thickening, pneumothorax; reduced airflow — generalised (COPD), localised (collapsed lung from occluding lung cancer)",
 "Match the five causes of diminished vesicular breathing in the Book p97 box to their category row — 1) Obesity/thick chest wall 2) Pleural effusion or thickening 3) Pneumothorax 4) Generalised, e.g. COPD 5) Localised, e.g. collapsed lung due to occluding lung cancer … A) Reduced conduction — 1st listed B) Reduced conduction — 2nd listed C) Reduced conduction — 3rd listed D) Reduced airflow — generalised E) Reduced airflow — localised",
 ["1-A, 2-B, 3-C, 4-D, 5-E",
  "1-A, 2-C, 3-B, 4-D, 5-E",
  "1-B, 2-A, 3-C, 4-D, 5-E",
  "1-A, 2-B, 3-E, 4-D, 5-C"],
 0,
 "Book p97 box 'Causes of diminished vesicular breathing': Reduced conduction — obesity/thick chest wall, pleural effusion or thickening, pneumothorax; Reduced airflow — generalised, e.g. COPD; localised, e.g. collapsed lung due to occluding lung cancer. (Book p97)"),
]
